### PR TITLE
Update repo URLs for ros2_tracing & tracetools_analysis

### PR DESCRIPTION
**Pull request by christophebedard**
See https://github.com/ros2/ros2/pull/1045

### CODE REVIEW

**Review by jacobperron — COMMENTED** [review]
Since the same release repo is being used for `tracetools_analysis` in rolling, we should also update the URLs in the [tracks.yaml](https://github.com/ros2-gbp/tracetools_analysis-release/blob/master/tracks.yaml).

**Comment by christophebedard** [comment]
oops, I forgot about that one. I created a new release and changed the release repo back to the one on gitlab.com (with the current gitlab link for now): https://github.com/ros/rosdistro/pull/26927

I'll then rebase this branch on that one and update the repo URL.

**Comment by christophebedard** [comment]
The repos have been moved, so this should be ready.

**Review by clalancette — APPROVED** [review]
All right, this looks like everything got moved, so I'm merging.

**Pull request merged**
