### PR TITLE
update rule for libfltk-dev

### PR DESCRIPTION
**Pull request by wjwwood**
See:

- http://packages.ubuntu.com/yakkety/libfltk1.3-dev
- http://packages.ubuntu.com/zesty/libfltk1.3-dev

### CODE REVIEW

**Review by tfoote — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
given that all distros we target for kinetic and lunar do provide fltk1.3. Should we add a [stretch](https://packages.debian.org/testing/libfltk1.3-dev) and [jessie](https://packages.debian.org/stable/libfltk1.3-dev) rule for libfltk-1.3-dev so that we target the same version for all supported platforms?

**Comment by wjwwood** [comment]
I guess so. I'm not sure how much it matters, IIRC the reason for the split in ubuntu rules was that 1.1 caused a dependency conflict of some sort that 1.3 addressed. 1.1 is still in ubuntu too:

- http://packages.ubuntu.com/yakkety/libfltk1.1-dev
- http://packages.ubuntu.com/zesty/libfltk1.1-dev

**Comment by wjwwood** [comment]
Ok, I updated it so that Jessie and Stretch uses `libfltk3.3-dev`, though I'm concerned about updating the Jessie rule after it might be in use. I do think this is "better", but we are risking breaking it I think.

**Comment by wjwwood** [comment]
Ok, this should be good to go with 6cf3796.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks for iterating on this

**Pull request merged**
