### PR TITLE
Adding racecar for documentation index for distro

### PR DESCRIPTION
**Pull request by tianb03**
I'd like racecar to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by clalancette** [comment]
It looks like CI is failing because the release repository hasn't been properly setup.  Did you follow the instructions on blooming a package for the first time [here](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)?  That should setup the release repository correctly.

Additionally, I'd suggest calling the package something other than `racecar`, which is really quite generic.  Something like `tianbot_racecar` might be a better idea.

**Comment by tianb03** [comment]
Thanks @clalancette ! First time commit to rosdistro I just didn't release...

I will change the name to tianbot_racecar. Does it matter that I keep the packages name unchanged just like racecar_bringup or better change it to tianbot_racecar_bringup also?

**Comment by clalancette** [comment]
> I will change the name to tianbot_racecar. Does it matter that I keep the packages name unchanged just like racecar_bringup or better change it to tianbot_racecar_bringup also?

I think it is better to rename the packages to `tianbot_racecar_bringup`; otherwise, it is unclear for end users what they are getting when they `apt-get install ros-kinetic-racecar-bringup`.

**Comment by tfoote** [comment]
+1 for prefixing all the packages with tianbot. It's much clearer.

**Pull request closed without merging**
