### PR TITLE
Revert naoqi packages new versions which are breaking compilation

### PR DESCRIPTION
**Pull request by suryaambrose**

### CODE REVIEW

**Comment by tfoote** [comment]
This is failing the rosdistro cache building. I note that you're changing the version number of naoqi_libqi in indigo but naoqi_libqicore in jade. 

https://travis-ci.org/ros/rosdistro/builds/118389467
```
======================================================================
ERROR: test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ros/rosdistro/test/test_build_caches.py", line 14, in test_build_caches
    generate_distribution_caches(INDEX_YAML)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/rosdistro/distribution_cache_generator.py", line 66, in generate_distribution_caches
    raise RuntimeError('\n'.join(errors))
RuntimeError: jade: missing package.xml file for package "naoqi_libqicore"
```

Did you mean to roll back naoqi_libqi in jade?

**Comment by suryaambrose** [comment]
No this was intended. 
naoqi_libqi was changed to 2.5 but this breaks linkage with boost on Trusty, which is why I wanted to revert. On Jade, naoqi_libqi was not switched to 2.5 so I let it in 2.3. 
naoqi_libqicore has an upgrade to handle naoqi_libqi 2.5. I bumped the version just in case we would want naoqi_libqi 2.5 on jade later but it is not mandatory with this PR.

**Comment by suryaambrose** [comment]
The buildfarm log is quite huge and I am a newbie at this. Any hint on what's the problem and/or how to solve it ?
Thanks a lot :)

**Comment by suryaambrose** [comment]
Ok this should be fixed now

**Comment by tfoote** [comment]
@suryaambrose that looks to have fixed the regressions. Thanks

**Pull request merged**
