### PR TITLE
add ament_virtualenv

### PR DESCRIPTION
**Pull request by max-krichenbauer**
_The bloom release process failed trying to create an oauth token, so this PR was created manually.
I hope it is acceptable. Please let me know if there are anything I should do differently._

`ament_virtualenv` provides a mechanism to export python library requirements in a `requirements.txt` file.
It is a port of [`catkin_virtualenv`](https://github.com/locusrobotics/catkin_virtualenv) for `ament`.

Included packages:
* `ament_virtualenv` : Python package for creating the virtual environment (for `ament_python`)
* `ament_cmake_virtualenv` : Cmake package to use `ament_virtualenv` with `ament_cmake` as build tool.
* `test_ament_virtualenv` : Package using `ament_virtualenv`. Used as a test and usage example.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
You can always create a bloom token manually: https://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization

This PR has build failures which need to be addressed. You're welcome to either edit this PR or set up a bloom token and use the `--pull-request-only` option to create a pull request for an existing release.

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
CI failures must be addressed.

**Comment by max-krichenbauer** [comment]
@nuclearsandwich  Thank you for your comments!
I looked at the CI failures but must admit I'm puzzled and not sure how to address them.
From looking at the code, it seems like the CI job is checking the cache (as referenced in [index.yaml](https://github.com/ros/rosdistro/blob/master/index.yaml), so it's out of my reach) for the `package.xml` files.
Since this is the first release (adding new packages) there are no entries in the cache, which causes the CI test to fail.

Or at least that's how I understand the source code - there are no comments or documentation on it, and I could not find anything related to this in the tutorials either.

Am I missing something?

Here is the error from the CI log for reference:

```
ERROR: test.test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ros/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
    raise RuntimeError('\n'.join(errors))
RuntimeError: crystal: missing package.xml file for package "ament_cmake_virtualenv"
crystal: missing package.xml file for package "ament_virtualenv"
crystal: missing package.xml file for package "test_ament_virtualenv"
dashing: missing package.xml file for package "ament_cmake_virtualenv"
dashing: missing package.xml file for package "ament_virtualenv"
dashing: missing package.xml file for package "test_ament_virtualenv"
```

And here is the section in [`rosdistro/distribution_cache_generator.py`](https://github.com/ros-infrastructure/rosdistro/blob/838099d161b15940eb102c0c13d99675f6752562/src/rosdistro/distribution_cache_generator.py#L101) where the error occurs.

```
dist, cache = _get_cached_distribution(
        index, dist_name, preclean=preclean, ignore_local=ignore_local,
        include_source=include_source)
[...]
package_xml = dist.get_release_package_xml(pkg_name)
if not package_xml:
    errors.append('%s: missing package.xml file for package "%s"' % (dist_name, pkg_name))
    continue
```

**Comment by nuclearsandwich** [comment]
Your current travis failures are due to the fact that the release version is 0.0.2-1 and your PR is specifying 0.0.2-0.

**Comment by max-krichenbauer** [comment]
> Your current travis failures are due to the fact that the release version is 0.0.2-1 and your PR is specifying 0.0.2-0.

Thank you @nuclearsandwich for the input.
I have changed the PR version number but the CI check still fails.
Any more ideas?

**Comment by nuclearsandwich** [comment]
> Any more ideas?

The current failure is due to your package list not being properly alphabetized.
It would be a big help if you checked the CI logs yourself for subsequent changes. You can do so by clicking the "Details" link and selecting either the Python 3 or Python 2 output (the same tests are run with both major python versions). Reading the output does take a bit of getting used to but the information you need is in the logs. For example: https://travis-ci.org/ros/rosdistro/jobs/619386554#L488

```
--- file:///home/travis/build/ros/rosdistro/crystal/distribution.yaml
+++ loaded-and-saved
@@ -138,4 +138,4 @@
       packages:
+      - ament_cmake_virtualenv
       - ament_virtualenv
-      - ament_cmake_virtualenv
       tags:
--- file:///home/travis/build/ros/rosdistro/dashing/distribution.yaml
+++ loaded-and-saved

@@ -210,4 +210,4 @@
       packages:
+      - ament_cmake_virtualenv
       - ament_virtualenv
-      - ament_cmake_virtualenv
       tags:
```

**Comment by max-krichenbauer** [comment]
@nuclearsandwich Thanks so much!
I did look at the log but I would never have guessed this was the issue.

**Comment by nuclearsandwich** [comment]
> I did look at the log but I would never have guessed this was the issue.

Yeah. To be honest I find the hints rather opaque myself. All "AssertionError: see folded block 'block10' above for details" means to me is expand collapsed blocks in the log until one of them shows an error. And I can augment that a little with past experience of which tests can produce which failure.

Thanks for iterating.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
