### PR TITLE
exotica: 5.1.3-3 in 'melodic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by wxmerkt**
Increasing version of package(s) in repository `exotica` to `5.1.3-3`:

- upstream repository: https://github.com/ipab-slmc/exotica.git
- release repository: https://github.com/ipab-slmc/exotica-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.1`
- previous version for package: `5.1.2-1`

## exotica

- No changes

## exotica_aico_solver

- No changes

## exotica_cartpole_dynamics_solver

- No changes

## exotica_collision_scene_fcl

```
* Refactor CollisionScene, add faster distance checks, speedup SmoothCollisionDistance (#688 <https://github.com/ipab-slmc/exotica/issues/688>)
* Contributors: Wolfgang Merkt
```

## exotica_collision_scene_fcl_latest

```
* Refactor CollisionScene, add faster distance checks, speedup SmoothCollisionDistance (#688 <https://github.com/ipab-slmc/exotica/issues/688>)
* Contributors: Wolfgang Merkt
```

## exotica_core

```
* Refactor CollisionScene, add faster distance checks, speedup SmoothCollisionDistance (#688 <https://github.com/ipab-slmc/exotica/issues/688>)
* Expose full KinematicTree to Python; expose mesh collision shape information (#686 <https://github.com/ipab-slmc/exotica/issues/686>)
* Contributors: Wolfgang Merkt
```

## exotica_core_task_maps

```
* Refactor CollisionScene, add faster distance checks, speedup SmoothCollisionDistance (#688 <https://github.com/ipab-slmc/exotica/issues/688>)
* Contributors: Wolfgang Merkt
```

## exotica_ddp_solver

- No changes

## exotica_double_integrator_dynamics_solver

- No changes

## exotica_dynamics_solvers

- No changes

## exotica_examples

- No changes

## exotica_ik_solver

- No changes

## exotica_ilqg_solver

- No changes

## exotica_ilqr_solver

- No changes

## exotica_levenberg_marquardt_solver

- No changes

## exotica_ompl_control_solver

```
* [exotica_ompl_control_solver] Fix ROS buildfarm failure
* Contributors: Wolfgang Merkt
```

## exotica_ompl_solver

- No changes

## exotica_pendulum_dynamics_solver

- No changes

## exotica_pinocchio_dynamics_solver

- No changes

## exotica_python

```
* Refactor CollisionScene, add faster distance checks, speedup SmoothCollisionDistance (#688 <https://github.com/ipab-slmc/exotica/issues/688>)
* Expose full KinematicTree to Python; expose mesh collision shape information (#686 <https://github.com/ipab-slmc/exotica/issues/686>)
* Allow labels/legend in plot()
* Contributors: Wolfgang Merkt
```

## exotica_quadrotor_dynamics_solver

- No changes

## exotica_scipy_solver

- No changes

## exotica_time_indexed_rrt_connect_solver

```
* [exotica_time_indexed_rrt_connect_solver] Fix runtime std::bad_cast exception
* Contributors: Wolfgang Merkt
```

### CODE REVIEW

**Comment by clalancette** [comment]
@wxmerkt FYI, this update is failing to build on Ubuntu 18.04 armhf (32-bit arm): http://repositories.ros.org/status_page/ros_melodic_ubhf.html?q=REGRESSION .  In turn, that is happening because pinocchio is failing to build on armhf: http://build.ros.org/view/Mbin_ubhf_uBhf/job/Mbin_ubhf_uBhf__pinocchio__ubuntu_bionic_armhf__binary/39/console 

I'm going to to do a Melodic sync soon (see https://discourse.ros.org/t/preparing-for-melodic-sync-2020-03-12/13207).  If you'd like to fix it on armhf, please feel free to send PRs during the freeze period.  Otherwise, I'll do the sync with that regression on armhf.

Thanks!

**Comment by wxmerkt** [comment]
HI @clalancette, is it possible to do the sync without the `exotica_pinocchio_dynamics_solver` on ARM 32-bit only? I have no idea how to fix the issue on arm pending https://github.com/ros-infrastructure/buildfarm_deployment/issues/232 ...

**Comment by clalancette** [comment]
> HI @clalancette, is it possible to do the sync without the `exotica_pinocchio_dynamics_solver` on ARM 32-bit only? I have no idea how to fix the issue on arm pending [ros-infrastructure/buildfarm_deployment#232](https://github.com/ros-infrastructure/buildfarm_deployment/issues/232) ...

Yes, that's fine.  It just won't be available any longer on 32-bit arm.  If that's OK with you, it's fine by me.

**Comment by wxmerkt** [comment]
That's okay with us. We do not have users on 32-bit ARM that I am aware of.

**Pull request merged**
