### PR TITLE
apriltag_ros: 3.1.0-1 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by wxmerkt**
Increasing version of package(s) in repository `apriltag_ros` to `3.1.0-1`:

- upstream repository: https://github.com/AprilRobotics/apriltag_ros.git
- release repository: https://github.com/AprilRobotics/apriltag_ros-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.8.0`
- previous version for package: `null`

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
There's an issue with the apriltags release building, this won't be able to build until that's resolved. 

https://github.com/ros/rosdistro/pull/21437

**Comment by wxmerkt** [comment]
Fix is in #21554

**Comment by clalancette** [comment]
> Fix is in #21554

Excellent, thanks.  Would you mind rebasing this now?

**Comment by wxmerkt** [comment]
I've resolved the merge conflict, however, I'd like to wait with this PR to see that apriltag builds on the kinetic buildfarm (it's fine on melodic, but appears to be failing without a clear error on kinetic)

**Comment by clalancette** [comment]
> I've resolved the merge conflict, however, I'd like to wait with this PR to see that apriltag builds on the kinetic buildfarm (it's fine on melodic, but appears to be failing without a clear error on kinetic)

That's fine.  Just comment here again when you'd like to have it merged.

**Comment by wxmerkt** [comment]
@tfoote: The apriltag build on kinetic is failing, whereas the builds on melodic and dashing pass. We use `GNUInstallDirs` internally to install to `CMAKE_INSTALL_LIBDIR`. However, on kinetic this uses the architecture-specific lib directories

image

I saw bloom and catkin PRs related to this - but wonder what the final word is. It appears that other libraries such as octomap set the install lib dir themselves:
https://github.com/OctoMap/octomap/blob/a13407d856715ab3583534c70fbe27f925f2d61e/octomap/CMakeLists.txt#L39

Final word - is GNUInstallDirs broken for Kinetic or did I miss a necessary step in the CMakeLists?

**Review by tfoote — COMMENTED** [review]
I'm not exactly familiar with it, but yes there have been some issues with GNUInstallDirs in the past that I think have been resolved at some point. Kinetic might be the final one where it's not resolved.

**Comment by wxmerkt** [comment]
I am closing this for now. Do you happen to have a resource/link to the issue with GNUInstallDirs and a workaround?

**Comment by tfoote** [comment]
I don't have one off the top of my head. @j-rivero might be more familiar.

**Comment by j-rivero** [comment]
Hello Wolfgang:

> Final word - is GNUInstallDirs broken for Kinetic or did I miss a necessary step in the CMakeLists?

We implemented `GNUInstallDirs` support for catkin long ago. Which is the particular problem you have with lib arch paths in ROS/bloom? If we need to get rid of them, `CMAKE_INSTALL_LIBDIR` (and the rest of GNUInstallDirs paths) can be set from the cmake call:

```
cmake .. -DCMAKE_INSTALL_LIBDIR=/foo
```
That call at package build time is done by the debian packaging tools, more precisely in the `rules` file of `debian/` directory. In the case of ROS packages that call can be customized using bloom templates (*.em files). You can find them in your -release repository branch debian/kinetic/<pkg_name>. This would be the place to inject those values in cmake for gazebo_ros_pkgs: https://github.com/ros-gbp/gazebo_ros_pkgs-release/blob/debian/kinetic/gazebo_ros/debian/rules.em#L29

**Comment by wxmerkt** [comment]
Thank you, Jose for the detailed explanation and references! My problem is best described in https://github.com/ros/rosdistro/pull/21348#issuecomment-504960643 - it's installing into the architecture-prefixed-lib-directory (and I am just doing a release of a third-party package with no patches or manual modifications).

**Comment by j-rivero** [comment]
> My problem is best described in [#21348 (comment)](https://github.com/ros/rosdistro/pull/21348#issuecomment-504960643) - it's installing into the architecture-prefixed-lib-directory

For me, is the [expected behavior](https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L50) when using `GNUInstallDirs`. Is that prefix a problem somehow?

**Comment by wxmerkt** [comment]
Isn't it breaking the packaging on the buildfarm?

**Comment by j-rivero** [comment]
> Isn't it breaking the packaging on the buildfarm?

No idea, looking into https://github.com/ros/rosdistro/pull/21437, I'm pretty sure that dpkg-shlibdeps has no problem with the arch paths.

**Pull request closed without merging**
