### PR TITLE
Adding ucl_drone to documentation index for Indigo

### PR DESCRIPTION
**Pull request by Felicien93**
Hello,

We would like our package ucl_drone to be indexed and documented on ros.org.

It implements ARdrones 2.0 in order to make them search a place and follow a moving target.

### CODE REVIEW

**Comment by tfoote** [comment]
There's no `indigo-devel` branch on that repository. Did you mean master?

**Comment by Felicien93** [comment]
Hi.

Yes indeed.

Sorry for the inconvenience.



2016-06-26 1:02 GMT+02:00 Tully Foote <notifications@github.com>:

**Comment by dirk-thomas** [comment]
You can edit the file on the branch and push the changes to update this pull request.

**Comment by Felicien93** [comment]
It should be updated.

Thank you.

**Pull request merged**
