### PR TITLE
add pyside to Wily/Xenial

### PR DESCRIPTION
**Pull request by vrabaud**
Sources:
http://packages.ubuntu.com/xenial/python-pyside
http://packages.ubuntu.com/xenial/python3-pyside

### CODE REVIEW

**Comment by dirk-thomas** [comment]
What are you using this for? Kinetic aims to use Qt 5 instead and therefore packages should use PySide 2.

**Comment by vrabaud** [comment]
Ecto. Sure, what is the Wily/Xenial package for pyside2 ?

**Comment by dirk-thomas** [comment]
The rosdep key `python-qt5-bindings` contains the PySide 2 packages (beside PyQt). You can look up the Debian keys there.

**Comment by vrabaud** [comment]
I'll complete the pyside2 keys if I need it. Thx

**Pull request closed without merging**
