### PR TITLE
Add postgresql and postgresql-client rosdeps

### PR DESCRIPTION
**Pull request by paulbovbel**

### CODE REVIEW

**Comment by wjwwood** [comment]
Seems that it disagrees with you about the alphabetical ordering.

**Comment by paulbovbel** [comment]
@wjwwood , fixed the ordering, but something unknown is causing an error.

**Comment by wjwwood** [comment]
Hmm, looks like someone may have removed the groovy tags from one of their release repositories? @dirk-thomas what do you think?

**Comment by dirk-thomas** [comment]
Travis failed to fetch the cache and is trying to build it from scratch. This fails then since e.g. the repo containing `beliefstate` was moved. Close / reopen should retrigger travis...

**Pull request merged**
