### PR TITLE
Add entries for clang, multistrap, and g++ libs

### PR DESCRIPTION
**Pull request by codavide**
Added to base.yaml the entry for [clang](https://clang.llvm.org/)

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please link to the upstream packages for contributed rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by codavide** [comment]
The package added is this

https://packages.ubuntu.com/eoan/clang

Clang is considered to be a production quality C, Objective-C, C++ and Objective-C++ compiler when targeting X86-32, X86-64, and ARM.

**Comment by codavide** [comment]
Added rules for:

multistrap:
https://packages.ubuntu.com/xenial/multistrap

Support automated creation of complete, bootable, root filesystems


g++-5-arm-linux-gnueabihf
https://packages.ubuntu.com/xenial/g++-5-arm-linux-gnueabihf

GNU C++ cross-compiler

g++-5-multilib
https://packages.ubuntu.com/xenial/g++-5-multilib

GNU C++ compiler (multilib support)

**Comment by codavide** [comment]
@tfoote can you please check if the pull request is ok now?

**Comment by tfoote** [comment]
Thanks for the links to the ubuntu packages. You've added debian, fedora, and gentoo rules as well that are not linked. And are there not equivalents for Fedora and gentoo for the additional packages that you added?

Note that you might find it more expedient to keep your PRs individually scoped so that reviews of additional submissions don't hold back previous entries.

**Comment by codavide** [comment]
For clang

Debian: https://packages.debian.org/stretch/clang
Fedora; https://fedora.pkgs.org/31/fedora-x86_64/clang-9.0.0-1.fc31.x86_64.rpm.html
https://packages.gentoo.org/packages/sys-devel/clang

I have checked better the other packages that I have added:

multistrap is available also for debian, here the missing link (not avaialble in other distro):

mutlistrap:
https://packages.debian.org/stretch/multistrap

Instead 

g++-5-arm-linux-gnueabihf
g++-5-multilib

are available only for Ubuntu, so I have removed the debian rules.


Thanks for the suggestion to keep the PR separated, you are right, but actually in this case, I need to have all the packages added to successfully build the ROS package, so it is ok to have all approved in the same PR.

**Review by tfoote — APPROVED** [review]
This looks good now. Thanks for digging up the dependencies.

But there's a merge conflict. Could you resolve that and I think we'll be good to go.

**Comment by codavide** [comment]
@tfoote OK, thanks,  conflict solved

**Review by tfoote — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]
Thanks for iterating @codavide. I'll echo @tfoote's suggestion that for future contributions to rosdep please consider using one pull request per package or per group of closely related packages.

**Pull request merged**
