### PR TITLE
Update python.yaml

### PR DESCRIPTION
**Pull request by reinzor**
Added rosbag_pandas via pip

### CODE REVIEW

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
releasing the package only via pip will prevent people from releasing packages depending on it.
Any reason for not releasing it as a ROS package ?

We require at least debian and ubuntu rules to accept a new key. So if the pip route is the final one Debian needs to be added as well

**Comment by tfoote** [comment]
This should definitely be a ROS package. It's importing `rospy` and `rosbag` which means that it can't satisfy it's dependencies via pip and is potentially rosdistro specific.

I'd suggest talking @aktaylor08 about releasing this as a ROS package? If he's not interested maybe you could help.

**Comment by Rayman** [comment]
Added a PR to convert this package to ROS here: https://github.com/aktaylor08/RosbagPandas/pull/9

**Comment by tfoote** [comment]
Since that PR was accepted and it can be released as a ROS package now I'm going to close this.

**Pull request closed without merging**
