### PR TITLE
add ROS Agents to rosdistro

### PR DESCRIPTION
**Pull request by mkabtoul**
# Please add agents to be indexed in the rosdistro

## Package name:

`agents`

## Package Upstream Source:

https://github.com/automatika-robotics/ros-agents.git

## Purpose of using this:

`agents` is  a fully-loaded framework for creating interactive embodied agents that can understand, remember, and act upon contextual information from their environment

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by sloretz** [comment]
[Iron Irwini is already in its final sync hold](https://discourse.ros.org/t/preparing-for-final-iron-irwini-patch-release-and-sync-2024-11-18/)

**Comment by mkabtoul** [comment]
Package removes from Iron @sloretz

**Review by clalancette — CHANGES_REQUESTED** [review]
This name is far too generic for ROS distro, and thus violates [REP-144](https://ros.org/reps/rep-0144.html).

I'm going to suggest that you rename the package to something like "automatika_embodied_agents", which both prefixes with the organization name and describes more of what it does.

**Comment by mjcarroll** [comment]
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-2024-11-21/40682)

**Comment by clalancette** [comment]
There's been no response here in 2 weeks, and the package needs a rename.  So I'm going to close this one out for now, please feel free to resubmit when it has been renamed.

**Pull request closed without merging**
