### PR TITLE
bump linux-headers version for debian stretch

### PR DESCRIPTION
**Pull request by mathias-luedtke**
https://packages.debian.org/stretch/linux-headers-4.9.0-3-all

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]
Does Debian not have a package like "latest" to avoid the continuous updates?

**Comment by ipa-mdl** [comment]
> Does Debian not have a package like "latest" to avoid the continuous updates?

I haven't found any.. But I am no debian user.
I just want to silence the build farm errors ;)
There are architecture-specific ones, like https://packages.debian.org/stretch/linux-headers-amd64

**Comment by ipa-mdl** [comment]
For my use case `linux-libc-dev` (ubuntu & debian) would work as well.

**Comment by mikaelarguedas** [comment]
It looks like both `linux-headers-generic` and `linux-headers` are considered obsolete and cannot be installed (tested on Jessie and Stretch): 
```
Package linux-headers-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
So I don't see any other "generic" package candidate that would prevent us from having to update them manually..

**Comment by ipa-mdl** [comment]
> Edit: we could create another key for the C development version (linux-libc-dev) as suggested by 

Please merge this for now to fix the version problem on debian stretch.
I will open a new PR for `linux-kernel-headers` (virtual package for `linux-libc-dev`)

**Comment by dirk-thomas** [comment]
I already approved this patch. It needs a second maintainer to merge.

**Pull request merged**
