### PR TITLE
librealsense2: 2.25.0-3 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by doronhi**
Increasing version of package(s) in repository `librealsense2` to `2.25.0-3`:

- upstream repository: https://github.com/doronhi/librealsense.git
- release repository: https://github.com/IntelRealSense/librealsense2-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.8.0`
- previous version for package: `2.23.0-1`

### CODE REVIEW

**Comment by sloretz** [comment]
Continuing from https://github.com/ros/rosdistro/pull/21522#issuecomment-512163615

> I failed to find out why I'm not getting the e-mails

Double checking, is the email address used [in by this job](http://build.ros.org/job/Kbin_uX64__librealsense2__ubuntu_xenial_amd64__binary/32/console) correct?

```
23:28:22 Sending e-mails to: ros-buildfarm-kinetic@googlegroups.com tfoote+buildfarm@osrfoundation.org sergey.dorodnicov@intel.com
```

> how do I know the results of the build of the new PR?

I think you can run a prerelease test locally to get the same results. There are instructions on [this page](http://wiki.ros.org/bloom/Tutorials/PrereleaseTest).

If I understand correctly, the `bin` jobs are only run after one of these rosdistro PRs is merged, but there is a `dev` job (jobs that test pull requests on the source repo) that also failed with the same error: http://build.ros.org/job/Kdev__librealsense2__ubuntu_xenial_amd64/ . See [this page](http://wiki.ros.org/buildfarm/Pull%20request%20testing) for instructions on re-enabling dev jobs.

**Comment by doronhi** [comment]
Thanks, I added the webhooks to https://github.com/doronhi/rosdistro and the test_pull_requests flag to the distribution.yaml file. And now we wait...
my e-mail is not on the mailing list of the jobs. Do you know where can I change that? or how can I otherwise check the build results?
I tried building using the script generated by http://prerelease.ros.org but it eventually failed on the installation part of the build, where it copied the .so file from build to devel. I wait to see if it happens on the build farm as well...

**Comment by tfoote** [comment]
Your rosdistro is not where you need/want webhooks for PR builds. They need to go on your source repository. 

All jobs are run on build.ros.org. You can search there for any of the jobs: http://build.ros.org/search/?q=librealsense Or browse by the tabs on the home page. 

If it's failing in the devel and in the prerelease it's not going to pass in the binary deb job. The binary build is generally the most strict of any of the jobs.

Every time you commit to your master branch this job will get run: http://build.ros.org/job/Kdev__librealsense2__ubuntu_xenial_amd64/ I suggest that you get that building before trying to do another prerelease. And once the prerelease is working then you can try to make an actual release.

If you'd like to add the pull request testing you'll need to add the webhooks and I'd suggest reducing this PR to just be that. And then you can rerun bloom to open a new PR with a version that's more likely to build.

**Review by tfoote — CHANGES_REQUESTED** [review]
The dev jobs and prereleases aren't passing. This is not expected to build.

**Comment by doronhi** [comment]
Replaced with #21996

**Pull request closed without merging**
