### PR TITLE
remove old distros and sid

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
removed all
```
sid
lenny
woody
squeeze
karmick
lucid
maverick
natty
beefy
spherical
```
entries

### CODE REVIEW

**Comment by dirk-thomas** [comment]
While these distros might be EOL we have no policy to remove them from the database at the moment. Some users might still use them to build from source on these platforms.

**Review by tfoote — CHANGES_REQUESTED** [review]
Thanks for the thought to clean up. However as @dirk-thomas mentions we know there are users who for various reasons are still using many of those platforms and we don't want to break them. And keeping the historical data isn't too much overhead for us. Of the cleanups though removing sid would be great as that's something we explicitly discourage.

If we were to clear these rules we would want to provide a backwards compatible way to keep the information available. But we haven't put much time in as the overhead of keeping them in the database isn't that high.

**Comment by dirk-thomas** [comment]
@Alessandro-Barbieri Are you planning on addressing the feedback or should this be closed?

**Comment by Alessandro-Barbieri** [comment]
What should I do?

**Comment by mikaelarguedas** [comment]
I think that the feedback was to remove only sid but none of the EOL distros.

**Comment by Alessandro-Barbieri** [comment]
sid is already gone with https://github.com/ros/rosdistro/pull/15349

**Comment by dirk-thomas** [comment]
@Alessandro-Barbieri if this PR is obsolete can you please close it then.

**Comment by dirk-thomas** [comment]
Closing due to no reply and not being mergable.

**Pull request closed without merging**
