### PR TITLE
network_interface: 3.0.0-1 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by icolwell-as**
Increasing version of package(s) in repository `network_interface` to `3.0.0-1`:

- upstream repository: https://github.com/astuff/network_interface.git
- release repository: https://github.com/astuff/network_interface-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.1`
- previous version for package: `null`

## network_interface

```
* Add noetic CI builds (#31 <https://github.com/astuff/network_interface/issues/31>)
* Disable docker layer caching (#30 <https://github.com/astuff/network_interface/issues/30>)
* Merge pull request #26 <https://github.com/astuff/network_interface/issues/26> from astuff/fix/memory_allocation
  Fix memory initialization of buffer vector.
* Apply same buffer allocation fix to UDP interface.
* Fix memory initialization of buffer vector.
* Adding copyright to utils.cpp.
* Moving definition of return_status_desc to fix linking bug.
* Merge pull request #25 <https://github.com/astuff/network_interface/issues/25> from astuff/maint/cpp_11_cleanup
  Maint/cpp 11 cleanup
* Had to add offset to parse_tuple.
* Moving parse_tuple from ibeo_core.
* Allowing read functions to take multiple containers.
* Commenting code.
* New implementation of write_le and write_be. Tests for both.
* Changing valueOffset to float and casting in util functions.
* Replacing unsigned int with uint32_t.
* Used wrong type-trait qualifier.
* CI: Adding Melodic armhf build.
* CI: Machine executors require sudo.
* CI: Add first run at armhf build.
* Changing to reinterpret_cast instead of non-portable solution.
* Removing async calls from TCP. Allocating buffers with reserve.
* Removing apparently useless check in write_le.
* Consistent braced initializers.
* -DBUILD_ROS is no longer a thing.
* Reserving requested space in read_exactly.
* Making ByteOrder enum scoped too.
* Switching back to memcpy.
* Moving common enums into common.h.
* Scoped enum for return statuses.
* Using vectors and type traits.
* CI: Making roslint run in run_tests.
* Merge pull request #20 <https://github.com/astuff/network_interface/issues/20> from astuff/maint/ci_add_lint
  Maint/ci add lint
* CI: Adding catkin_test_results the right way.
* CI: Adding catkin_test_results.
* Making lint cover all files and adding copyright.
* CI: Need --no-deps for lint.
* CI: Oops.
* CI: Adding roslint to build tests.
* Removing unused gitlabci file.
* CI: Removing Indigo build.
* Merge pull request #19 <https://github.com/astuff/network_interface/issues/19> from astuff/maint/add_urls
  Adding website URL to package.xml.
* Adding website URL to package.xml.
* Merge pull request #18 <https://github.com/astuff/network_interface/issues/18> from astuff/maint/ci_new_docker_images
  CI: Using AS Docker images.
* CI: Using AS Docker images.
* Contributors: Ian Colwell, Joshua Whitley, Rinda Gunjala, Sam Rustan, Zach Oakes
```

### CODE REVIEW

**Comment by icolwell-as** [comment]
CI Fail:
```
AssertionError: ["In file '''/home/runner/work/rosdistro/rosdistro/noetic/distribution.yaml''': 
Could not validate source entry for repo network_interface with error 
[[[Could not validate repository with url https://github.com/astuff/network_interface.git and version 3.0.0 from entry at line 4217.
Error reason: Tags are not valid, but a tag 3.0.0 was found. Re: https://github.com/ros/rosdistro/pull/20286]]]"] is not false
```

I don't know how it was able to find a 3.0.0 tag but then determine it to be invalid?

**Comment by clalancette** [comment]
> I don't know how it was able to find a 3.0.0 tag but then determine it to be invalid?

Tags are not allowed for doc and source entries; it must be a branch.

**Comment by icolwell-as** [comment]
> Tags are not allowed for doc and source entries; it must be a branch.

Thanks for letting me know, bloom-release suggested tags are a valid option.

Slightly off-topic: why aren't tags allowed? If a branch is specified for a given release, but then later updated/changed, wouldn't the branch that this release is pointing to no longer represent the source code that the release was made with?

**Comment by clalancette** [comment]
> Slightly off-topic: why aren't tags allowed? If a branch is specified for a given release, but then later updated/changed, wouldn't the branch that this release is pointing to no longer represent the source code that the release was made with?

There is a technical limitation, but I honestly don't remember what it is at this point.  @tfoote or @nuclearsandwich may have better memory/context there.

**Pull request merged**
