### PR TITLE
add python-tensorboard-pip

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by cottsay** [comment]
As described in the [CONTRIBUTING.md](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions), please include a link to the packaging source to facilitate the review process.

Like this: https://pypi.org/project/tensorboard/

**Review by cottsay — APPROVED** [review]

**Review by hidmic — APPROVED** [review]
LGTM too, though it appears Gentoo distributes it: https://packages.gentoo.org/packages/sci-visualization/tensorboard. Would you mind @MatthijsBurgh ?

**Comment by cottsay** [comment]
@hidmic, we shouldn't add a system package rule to a pip-only key. Since the other platforms don't have system packages, I'm not sure there is any value in adding a non-pip key that only works for Gentoo.

That said, we could add a pip rule for Gentoo.

**Comment by MatthijsBurgh** [comment]
@hidmic, I think @cottsay already made my case.

**Comment by hidmic** [comment]
> we shouldn't add a system package rule to a pip-only key.

Yeap, good point. My bad.

> I'm not sure there is any value in adding a non-pip key that only works for Gentoo.

That's arguable. It's only a recommended platform, so I won't block on it.

> That said, we could add a pip rule for Gentoo.

Agreed.

**Comment by MatthijsBurgh** [comment]
Anything holding a merge?

**Pull request merged**
