### PR TITLE
add python-schedule and python3-schedule

### PR DESCRIPTION
**Pull request by knorth55**
add `python-schedule` and `python3-schedule` package in rosdep.

pypi: https://pypi.org/project/schedule/
github: https://github.com/dbader/schedule/
ubuntu: https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=python-schedule&searchon=names
ubuntu (python3): https://packages.ubuntu.com/search?keywords=python3-schedule&searchon=names&suite=all&section=all
debian: https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=python-schedule
debian (python3): https://packages.debian.org/search?keywords=python3-schedule&searchon=names&suite=all&section=all

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
We typically prefer to use system packages if at all possible.  In this case, it looks like this is available as a system package on both [Ubuntu](https://packages.ubuntu.com/search?keywords=python3-schedule&searchon=names&suite=all&section=all) and [Debian](https://packages.debian.org/search?keywords=python3-schedule&searchon=names&suite=all&section=all) (though not Fedora).  Since that is the case, please switch this to be a key in [base.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml) instead.

**Comment by knorth55** [comment]
@clalancette thank you for your comment. I didn't know that it is released in debia and ubuntu.
I will change this PR to add `python-schedule` in `base.yaml`

**Comment by knorth55** [comment]
I update to add `python-schedule` and `python3-schedule` in `python.yaml`.

**Review by clalancette — APPROVED** [review]
Looks good to me!  Thanks for iterating.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
