### PR TITLE
turtlebot_msgs: 2.2.1-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by jihoonl**
Increasing version of package(s) in repository `turtlebot_msgs` to `2.2.1-0`:
- upstream repository: https://github.com/turtlebot/turtlebot_msgs.git
- release repository: https://github.com/turtlebot-release/turtlebot_msgs-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.19`
- previous version for package: `2.2.0-0`
## turtlebot_msgs

```
* remove laptop charge status message #2 <https://github.com/turtlebot/turtlebot_msgs/issues/2>
* LaptopChargeStatus moved here from turtlebot stack.
* Contributors: Daniel Stonier, Jihoon Lee
```

### CODE REVIEW

**Comment by vrabaud** [comment]
please rebase (conflict with openni2 merge request)

**Comment by vrabaud** [comment]
@jihoonl, please rebase

**Comment by vrabaud** [comment]
@stonier , I believe you can help with that :) thx

**Comment by dirk-thomas** [comment]
ros-infrastructure/bloom#252

**Comment by stonier** [comment]
10000km away chopping down and burning trees right now :neckbeard:

Looks like @jihoonl is onto it in one way or another.

**Pull request closed without merging**
