### PR TITLE
Add python-parse, python-construct

### PR DESCRIPTION
**Pull request by ejalaa12**
- added parse package for parsing strings using  a specification based on the Python format() syntax (https://pypi.org/project/parse/)
- added the construct library for parsing and building binary data (https://pypi.org/project/construct/)

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@ejalaa12 please use `-pip` suffix for packages only available via pip.
In this particular case, `python-construct` exists in ubuntu since [at least trusty](https://packages.ubuntu.com/trusty/python-construct), so we strongly recommend using the apt package rather than the pip version.

**Review by tfoote — CHANGES_REQUESTED** [review]
Also python-parse is available from upstream as well: https://packages.ubuntu.com/trusty/python-parse

Following our guidelines please update this to use the system packages. 
https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by tfoote** [comment]
Thanks for the update, just one more request. Please add the debian rule too, support for both is our minimum requirement in the contributing guideline.

I've verified they're both available
https://packages.debian.org/stretch/python-construct
https://packages.debian.org/stretch/python-parse

**Comment by ejalaa12** [comment]
Sure! I'm adding them.

**Review by tfoote — APPROVED** [review]
Thanks for iterating!

**Pull request merged**
