### PR TITLE
add motion_capture_tracking to humble/iron/rolling

### PR DESCRIPTION
**Pull request by whoenig**
# Please Add This Package to be indexed in the rosdistro.

Humble, Iron, Rolling

# The source is here:

https://github.com/IMRCLab/motion_capture_tracking/tree/ros2

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by audrow — APPROVED** [review]

**Review by audrow — COMMENTED** [review]
Actually, I'd like a second opinion that this package doesn't have too generic of a name.

**Comment by whoenig** [comment]
Note that it's a generic name, because it supports VICON, OptiTrack, Qualisys, and several other smaller vendors in the backend. The "_tracking" part comes from the fact that we provide a custom rigid body tracker that works with single markers and identical marker configurations.

**Comment by mikeferguson** [comment]
Is there any documentation on how to use this package? (the README is pretty sparse). Good documentation would probably go a long way to justifying the generic name.

**Comment by whoenig** [comment]
Thanks for your swift and constructive feedback. I have updated the README (see https://github.com/IMRCLab/motion_capture_tracking/blob/ros2/README.md) as well as the comments in the `cfg.yaml` file to explain the various usage options.

**Review by audrow — APPROVED** [review]
The new readme provides better context, and the comments on the configuration file will probably make this much easier to use.

Thanks for adding documentation!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
