### PR TITLE
Add several rules for Debian Bookworm

### PR DESCRIPTION
**Pull request by cottsay**
All of these package names are the same in Bookworm as they are in Bullseye.

https://packages.debian.org/bookworm/clang-format
https://packages.debian.org/bookworm/clang-tidy
https://packages.debian.org/bookworm/pydocstyle
https://packages.debian.org/bookworm/python3-empy
https://packages.debian.org/bookworm/python3-flake8
https://packages.debian.org/bookworm/python3-lark
https://packages.debian.org/bookworm/python3-mypy

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
For most of these, can we just use:

```
debian: [packagename]
```

?  That will make it future-proof.  It doesn't apply to the `lark` key or the `mypy` key, but for those we could also use the `*` wild-card syntax to make them future-proof as well.

**Comment by cottsay** [comment]
I always assumed there was a reason we weren't doing that for Debian. Hopefully @nuclearsandwich can comment.

**Comment by nuclearsandwich** [comment]
> > That will make it future-proof. It doesn't apply to the `lark` key or the `mypy` key, but for those we could also use the `*` wild-card syntax to make them future-proof as well.

> I always assumed there was a reason we weren't doing that for Debian. Hopefully @nuclearsandwich can comment.

No reason I recall. I think it was just historically harder to elide Debian keys since they do fewer longer-lived distributions than Ubuntu. It's really nice to elide Ubuntu keys because it makes it easier to passively support non-LTS Ubuntu releases. But if we have the opportunity to elide and future-proof Debian keys I'm in favor.

**Review by nuclearsandwich — APPROVED** [review]
As raised in the existing discussion, eliding and future-proofing definitions would be nice but it isn't a blocker IMO. Thanks for updating these keys!

**Comment by cottsay** [comment]
Alright, I updated to use wildcard version syntax.

We should probably consider dropping Jessie and Stretch, both of which are out of LTS support, but I don't really want to block this PR on that conversation.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
