### PR TITLE
newly added python3-pre-commit-pip

### PR DESCRIPTION
**Pull request by SubaruArai**
Please add the following dependency to the rosdep database.

## Package name:

``python3-pre-commit-pip``

## Package Upstream Source:

[repo](https://github.com/pre-commit/pre-commit)
[homepage](https://pre-commit.com/index.html)

## Purpose of using this:

This python package vastly facilitates the creation of git-hooks.
It should encourage more projects using pre-commit-hooks for CI/CD.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - not available
- Ubuntu: https://packages.ubuntu.com/
   - not available
- Fedora: https://src.fedoraproject.org/browse/projects/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- pypi: https://pypi.org/
  - https://pypi.org/project/pre-commit/

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by SubaruArai** [comment]
looks like it just conflicted with #32693. (branched and tested before it, and PR'd after it)

**Comment by cottsay** [comment]
I believe that this pattern should work here:
https://github.com/ros/rosdistro/blob/5baf7c95fdddb61dc654c0fde4f7e96c43b4935d/rosdep/python.yaml#L6425-L6440

The `*` rule will be used unless a rule specific to the platform is specified. Since the older platforms will never have the package, we can add a pip rule instead. Current and future platforms will follow the `*` rule, and we'll eventually retire the platform-specific rules when those platforms reach EOL.

**Comment by SubaruArai** [comment]
Thanks! I'll make the changes

**Review by tfoote — APPROVED** [review]

**Review by cottsay — APPROVED** [review]

**Comment by SubaruArai** [comment]
thank you!

**Pull request merged**
