### PR TITLE
Add "Include What You Use (IWYU)"

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Below are useful links describing what IWYU and other related topics.

- [Why Include What You Use](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md>)
- [IWYU Documentation](https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md)
- [Exclude headers from check](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md)
- [Avoid Common Issues](https://www.incredibuild.com/blog/include-what-you-use-how-to-best-utilize-this-tool-and-avoid-common-issues/)

Package Links:

- https://packages.ubuntu.com/focal/iwyu
- https://packages.debian.org/source/sid/iwyu
- https://fedora.pkgs.org/30/fedora-x86_64/iwyu-0.9-0.1.20171001git576e80f.fc28.x86_64.rpm.html

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Can you please update your pull request description to conform with our [contribution guidelines for rosdep rules](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions).

**Comment by Levi-Armstrong** [comment]
@nuclearsandwich I updated the description; is this what you were expecting?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich I updated the description; is this what you were expecting?

Thanks for updating the description, it's plenty of info about the proposed dependency (more than enough) but it's missing a link to the Ubuntu package https://packages.ubuntu.com/focal/iwyu

It would also be nice if you could check whether the package is available in Debian and/or Fedora and add entries for those platforms as well.

**Comment by Levi-Armstrong** [comment]
I added the requested entries links

**Review by nuclearsandwich — APPROVED** [review]
Thanks for iterating @Levi-Armstrong

**Pull request merged**
