### PR TITLE
add Fedora 23

### PR DESCRIPTION
**Pull request by sorki**
Fixes
rosbag: No definition of [python-imaging] for OS version [23]

### CODE REVIEW

**Comment by vrabaud** [comment]
Don't know much about Fedora (and how much we support) but wouldn't it make sense to have  ```fedora: [python-flake8]``` for simplicity ?

**Comment by sorki** [comment]
Makes sense. python-tilestache is also the same on all versions. I'll fix both.

**Comment by vrabaud** [comment]
maybe @cottsay as an opinion on that.

**Comment by cottsay** [comment]
These keys are as they are because those packages aren't available on older Fedora versions. So rather than getting a "yum" error trying to install a package that doesn't exist, there is a key resolution error that more accurately describes the problem.

I think it would be safe to say that if all current Fedora releases plus one EOL release are the same, the key *could* be merged if someone so desires. So as of now, that means that "heisenbug" and f21-f23 would need to match.

Unless there is already an official policy on this situation...? How is this handled in Ubuntu keys?

**Comment by tfoote** [comment]
It's kind of ad-hoc. We tend to focus on the currently supported releases as well as the ones which we're still building debian packages for. We should develop a more formal policy for that. Possibly a script which could strip old rules and archive them in a non-default file would be valuable instead of simply losing them into the revision history.

**Comment by dirk-thomas** [comment]
What is the status of this PR?

**Comment by tfoote** [comment]
It's correct. Lets merge it as is. There's a larger issue of how to keep entries from ballooning in size over time.

**Pull request merged**
