### PR TITLE
Add rosbag_metdata as python rosdep

### PR DESCRIPTION
**Pull request by jacobperron**
I've found this tool handy for adding metadata to bag files.

- https://pypi.python.org/pypi/rosbag_metadata
- https://github.com/hordurk/rosbag_metadata

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
Don't use pip on gentoo

**Review by dirk-thomas — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@Alessandro-Barbieri Please provide an alternative suggestion.

**Comment by Alessandro-Barbieri** [comment]
The alternative is writing an ebuild for the package, but don't use `pip`.
Running `pip` as root on gentoo will break the system.

see https://wiki.gentoo.org/wiki/Pip

**Comment by dirk-thomas** [comment]
@Alessandro-Barbieri I guess you can't a contributor to write an ebuild so how would you like to proceed on this: should the `gentoo` entry be removed or should the patch keep the pip entry?

**Comment by mikaelarguedas** [comment]
In other PRs we just don't add the pip entry for gentoo to avoid breakage so I'd suggest to do the same here

**Review by dirk-thomas — APPROVED** [review]
Sounds good to me.

**Review by mikaelarguedas — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
@Alessandro-Barbieri feel free to submit a follow-up PR adding a gentoo entry if an ebuild for this is created for this package

**Pull request merged**
