### PR TITLE
test that source and release repos are different

### PR DESCRIPTION
**Pull request by mikaelarguedas**
fail the test if source and release repo URLs exist and are identical

### CODE REVIEW

**Review by tfoote — APPROVED** [review]

**Comment by dirk-thomas** [comment]
The condition seems to compare the repository instance rather than the url. I would expect them to never be equal. Have you tried to make this condition fail?

**Comment by mikaelarguedas** [comment]
You're right. I only confirmed that it wouldnt fail on None instances and was planning on testing before considering merging. because it seemed odd that we didnt have a single violation on all indexed repos.

**Comment by mikaelarguedas** [comment]
This seems to now do the right thing. Not sure how we want to act on the entries that don't comply. Should we contact maintainers individually ?

**Comment by dirk-thomas** [comment]
The entries which list a valid release repo as their source entry might be completely fine as they are. Maybe they add a manifest in the release process. So I consider that a valid use case.

**Comment by mikaelarguedas** [comment]
Given that there is no good way to know if the repository listed in the source entry is a valid release repository I'm going to close this. Maybe we'll think of a better way of testing that later on

**Pull request closed without merging**
