### PR TITLE
add rosdep key for libpt-dev and libopal-dev

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by ipa-fxm** [comment]
+1

**Comment by tfoote** [comment]
@ipa-fmw can you link to the packages on packages.ubuntu.com, and if you're planning to use these in released packages are there equivalents for debian and fedora?

**Comment by ipa-fmw** [comment]
Links to Ubuntu:
- http://packages.ubuntu.com/trusty/libpt-dev
- http://packages.ubuntu.com/trusty/libopal-dev

Links to Debian:
- https://packages.debian.org/jessie/libpt-dev
- https://packages.debian.org/jessie/libopal-dev

I will add the Debian packages, I have no info about Fedora.

**Comment by ipa-fmw** [comment]
@tfoote: done

**Comment by tfoote** [comment]
@ipa-fmw thanks

+1

**Pull request merged**
