### PR TITLE
add ros2_babel_fish to rosdistro

### PR DESCRIPTION
**Pull request by StefanFabian**
# Please Add This Package to be indexed in the rosdistro.

ros2_babel_fish

# The source is here:
https://github.com/LOEWE-emergenCITY/ros2_babel_fish

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by sloretz — CHANGES_REQUESTED** [review]
Would you be willing to remove the `ros2_` prefix from the package names to comply with REP 144?

> A package name should not contain ros as it is redundant. Exceptions include core packages and ROS bindings of an upstream library (e.g. moveit_ros)

---

- [X] At least one of the following must be present
  - [X] Top level license file: 
  - [ ] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>ros2_babel_fish</name>
  <name>ros2_babel_fish_test_msgs</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
./ros2_babel_fish/package.xml:  <license>MIT</license>
./ros2_babel_fish_test_msgs/package.xml:  <license>MIT</license>
```
</details>

**Comment by StefanFabian** [comment]
I would prefer not to, as the name without ros2 doesn't really make sense.
It's an introspection package for ros2 messages. So, the connection to ros is integral.

**Comment by audrow** [comment]
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-2024-06-18/)

**Comment by StefanFabian** [comment]
Any updates? @sloretz

**Comment by sloretz** [comment]
> Any updates? @sloretz

Oops, we did discuss this but I dropped the ball on reporting it back here. Thanks for your patience

In short: Please change the name to `ros_babel_fish`.

According REP-144 the package should have been named “babel_fish", but because it is in ROS 1 as “ros_babel_fish” the best name for it now would be `ros_babel_fish`. This way your package's users in ROS 1 will be able to find the ROS 2 version via the tabs for supported distros at https://index.ros.org/p/ros_babel_fish/

**Comment by StefanFabian** [comment]
Okay, done :+1:

**Review by sloretz — APPROVED** [review]
- [X] At least one of the following must be present
  - [X] Top level license file: 
  - [ ] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - yes with exception to match ROS 1 package name

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>ros_babel_fish_test_msgs</name>
  <name>ros_babel_fish</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
./ros_babel_fish_test_msgs/package.xml:  <license>MIT</license>
./ros_babel_fish/package.xml:  <license>MIT</license>
```
</details>

**Comment by sloretz** [comment]
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-06-28/)


Thanks for your patience!

**Pull request merged**
