### PR TITLE
Feature/add python distro

### PR DESCRIPTION
**Pull request by hridaybavle**
Please add the following python packages to `python.yaml`. 

## Package names:

  * [tensorboard](https://pypi.org/project/tensorboard/)
  * [pytorch-geometric](https://pypi.org/project/torch-geometric/)
  
## Purpose of using this:

pytorch-geometric required as dependencies for performing graph manipulations for [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git). tensorboard required for visualization of the training process.

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
I will note that `torch-geometric` has also been packaged in Debian: https://packages.debian.org/sid/python3-torch-geometric .  That would usually mean that we would prefer a Debian package key, rather than a `pip` key.  However, that package is only available in Debian sid, and not at all in Ubuntu, so in this case I'm OK with adding it in as a `pip` key.

**Comment by clalancette** [comment]
Arg.  Due to reasons completely not having to do with this PR, it needs a rebase/merge with the latest on the `master` branch.  If you can do that, then CI should succeed.  Sorry for the inconvenience.

**Comment by hridaybavle** [comment]
Hello @clalancette, I did the rebase with the master. Can you confirm if alls good.

**Review by clalancette — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]
We can use OS-level wildcards for these pip dependencies.

**Comment by nuclearsandwich** [comment]
@hridaybavle so you are aware, packages that use pip-based dependencies are not eligible for release on the ROS build farm.

**Comment by hridaybavle** [comment]
@nuclearsandwich thank you for the heads up. I am trying to do a ros2 release for our 
package (lidar_s_graphs)[https://github.com/ros/rosdistro/pull/40800], it depends on another ros2 python package (graph_reasoning)[https://github.com/ros/rosdistro/pull/40804] which needs the torch-geometric pip. What could be the solution you suggest in this case?

**Pull request merged**
