### PR TITLE
Adding iav_depthimage_to_laserscan to documentation index for distro

### PR DESCRIPTION
**Pull request by iav-student**
I'd like iav_depthimage_to_laserscan to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by iav-student** [comment]
iav_depthimage_to_laserscan

**Comment by dirk-thomas** [comment]
Hydro had been EOL quite a while ago and there is no build farm anymore. Therefore we don't accept PR for it anymore. Please consider adding it to Indigo or Jade instead.

@tfoote I don't know how this is being flagged as passing by Travis. Please double check the tests which seem to be not working as desired.

**Comment by tfoote** [comment]
@dirk-thomas we only check doc and release since those are the things which have generated outputs which will never change. We don't assert that the source entries don't change at the moment since they may still be used by the rosinstall generator even for EOL distros.

**Comment by dirk-thomas** [comment]
@tfoote Please feel free to reopen the PR then and merge it.

**Comment by iav-student** [comment]
Then must I adding it to the PR Indigo or Jade or it will be reopened?

**Comment by tfoote** [comment]
@iav-student I reopened it and merged it.

**Comment by iav-student** [comment]
How I index a API in http://docs.ros.org/api/ now? I thought that it'd be automatic.

**Comment by tfoote** [comment]
`source` entries are for continuous integration and rosinstall generation. You would need a `doc` entry to have documentation added. However as mentioned earlier in this thread Hydro is EOL so there are no more doc jobs running.

**Pull request merged**
