### PR TITLE
Adding rm_description to documentation index for distro

### PR DESCRIPTION
**Pull request by mlione**
I want to separate rm_description from rm_control.

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]

**Comment by adityapande-1995** [comment]
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2022-03-30/)

**Comment by mlione** [comment]
> @mlione I will merge this after you confirm that it's okay that all previous packages of `rm_description` will be deleted.

@ivanpauno Yes, it's okay that all previous packages of `rm_description` will be deleted.

**Comment by mlione** [comment]
When my pr will get merged? @ivanpauno

**Comment by hidmic** [comment]
@mlione about now :)

**Pull request merged**
