### PR TITLE
Add autoware_internal_msgs to humble, jazzy, and rolling indices

### PR DESCRIPTION
**Pull request by youtalk**
# Please Add This Package to be indexed in the rosdistro.

humble, jazzy, and rolling

# The source is here:

https://github.com/autowarefoundation/autoware_internal_msgs.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by youtalk** [comment]
@nuclearsandwich Please review it.

**Comment by nuclearsandwich** [comment]
New package review:

- [ ] At least one of the following must be present
  - [ ] Top level license file: https://github.com/autowarefoundation/autoware_internal_msgs/blob/rolling/LICENSE
  - [ ] Per package license files
    - [ ] PASTE URL
- [ ] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [ ] License correctly listed in package.xmls
  - [ ] autoware_internal_msgs: https://github.com/autowarefoundation/autoware_internal_msgs/blob/rolling/package.xml#L12
- [ ] Public source repo: https://github.com/autowarefoundation/autoware_internal_msgs/tree/rolling
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] autoware_internal_msgs

**Review by nuclearsandwich — APPROVED** [review]
@youtalk the merge conflicts will need to be resolved as the autoware packages merge on top of each other. Can you please do so?

**Comment by youtalk** [comment]
@nuclearsandwich Thank you for your review. I've merged the latest master.

**Pull request merged**
