### PR TITLE
Adding poppler-utils depend

### PR DESCRIPTION
**Pull request by pbeeson**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@pbeeson Can you please add the other platforms as well?
In the future please provide links to the packages as well as a description of the package and what you want ot use it for as per [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)

Ubuntu: https://packages.ubuntu.com/search?keywords=poppler-utils&searchon=names&exact=1&suite=all&section=all
Debian: https://packages.debian.org/search?keywords=poppler-utils&searchon=names&exact=1&suite=all&section=all
Fedora: https://apps.fedoraproject.org/packages/poppler-utils
Gentoo: https://packages.gentoo.org/packages/app-text/poppler

**Comment by pbeeson** [comment]
Done.  Thanks.

**Comment by mikaelarguedas** [comment]
Thanks, once the alphabetical order if fixed it looks good to me :+1:

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
