### PR TITLE
Add melodic.

### PR DESCRIPTION
**Pull request by clalancette**
add melodic distribution file + add melodic to index

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
Travis fails because the tests are looking for melodic in the `index.yaml`, which is added by this PR :).

**Comment by dirk-thomas** [comment]
This should be ok to be merged. It should also be easy to update the catch this corner case make it pass.

**Comment by dirk-thomas** [comment]
Please only put the line which can actually raise in the `try` / `catch` block.

**Review by dirk-thomas — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks!  Merging.

**Pull request merged**
