### PR TITLE
Add python-nltk

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@mvollrath please add the other platforms as well (debian at least, fedora and gentoo are "nice-to-have")

**Comment by Alessandro-Barbieri** [comment]
https://packages.gentoo.org/packages/dev-python/nltk
https://packages.debian.org/search?keywords=python-nltk (jessie+stretch+buster)

**Comment by mikaelarguedas** [comment]
fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/python-nltk/
for debian: you can just use `debian: [python-nltk]` to be more futureproof

@mvollrath Can you please update the PR accordingly ?

**Comment by mikaelarguedas** [comment]
Given the absence of response I'm going to close this. @mvollrath Feel free to open another PR with all the platforms

**Pull request closed without merging**
