### PR TITLE
add rosdep rules for jsonpyes

### PR DESCRIPTION
**Pull request by kenliao94**
a tool for uploading json file to Elasticsearch

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@kenliao94 Can you add a debian entry as well please ?

**Comment by kenliao94** [comment]
@mikaelarguedas , yep. Just did.

**Comment by tfoote** [comment]
@kenliao94 The update failed CI. The entries need to be in alphabetical order.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
