### PR TITLE
Rqt dotgraph

### PR DESCRIPTION
**Pull request by tdenewiler**
# Please Add This Package to be indexed in the rosdistro.

- rolling
- humble
- iron

# The source is here:

https://github.com/niwcpac/rqt_dotgraph

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by quarkytale** [comment]
### New package review checklist

- [ ] At least one of the following must be present
  - [X] Top level license file:
  - [ ] Per package license files:
- [ ] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

@tdenewiler The CC0 license is not OSI approved, please check the list and consider changing the license for the package to be indexed.

**Comment by tdenewiler** [comment]
We developed the code as part of official duties working for the US Government. We are not allowed to copyright that work. The best we can do is dedicate the work to the public domain. That is why we use the CC0 license.

**Comment by quarkytale** [comment]
@clalancette please advise!

**Comment by clalancette** [comment]
So I took a look at the package in detail.

First of all, we can accept a CC0 license.  However, it appears that not all of the code in the package is CC0.  In particular, there is this line in the README: `To visualize the DOT graphs, this module includes a version of [xdot_qt.py](https://github.com/jrfonseca/xdot.py) forked from [ROSPlan](https://github.com/KCL-Planning/ROSPlan/blob/master/rosplan_rqt/src/rosplan_rqt/xdot_qt.py) and released under [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.html). The forked version in this package has been modified and the changes to it are released under the LGPLv3.`.

The best way to handle this would be to submit the modifications to upstream `rosplan_rqt`, and then take a dependency on `rosplan_rqt`.  With that in place, the question of license in this repository would be restricted to CC0, which we can accept.

If that is not possible, then at the very least the `package.xml` here needs to add in a second `<license>` tag for LGPLv3, reflecting the fact that there are multiple licenses for this repository.  It would also be best to add a comment next to the `license` tag saying which files are covered by which license (for CC0 you can just say "all other files" or something like that).

**Comment by tdenewiler** [comment]
I went with the second license approach with comments. PRs in progress for `rqt_dotgraph` repo.

I really like your idea of adding a dependency on `rosplan_rqt`, but that package is not released. A request was made in 2019 but no action was taken: https://github.com/KCL-Planning/ROSPlan/issues/201.

**Comment by tdenewiler** [comment]
I see there is still a "changes requested" label. I have made requested changes to the license in package.xml upstream. Are there any other desired changes?

**Review by sloretz — APPROVED** [review]
- [X] At least one of the following must be present
  - [ ] Top level license file: 
  - [X] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses): acceptable https://github.com/ros/rosdistro/pull/40169#issuecomment-1992172509
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>rqt_dotgraph</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
  <license>LGPLv3</license> <!-- For rqt_dotgraph/xdot_qt.py only. -->
  <license>CC0</license> <!-- For all other files. -->
```
</details>

**Pull request merged**
