### PR TITLE
Add doc and source for mrpt_path_planning

### PR DESCRIPTION
**Pull request by jlblancoc**
# Please Add This Package to be indexed in the rosdistro.

- noetic
- rolling

# The source is here:

https://github.com/MRPT/mrpt_path_planning

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by jlblancoc** [comment]
@nuclearsandwich Fair point! It's a good moment for thinking a better name.

**Comment by jlblancoc** [comment]
@nuclearsandwich Done now!

**Review by emersonknapp — APPROVED** [review]
This LGTM to me now - thanks for putting in the effort on the rename

**Review by sloretz — APPROVED** [review]
- [x] At least one of the following must be present
  - [ ] Top level license file: 
  - [x] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses):
- [x] License correctly listed in package.xmls
- [x] Public source repo:
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>mrpt_path_planning</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license>" "{}" "+"
  <license>BSD</license>
```
</details>

**Pull request merged**
