### PR TITLE
acado: 1.2.2-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by RonaldEnsing**
Increasing version of package(s) in repository `acado` to `1.2.2-0`:

- upstream repository: https://github.com/tud-cor/acado.git
- release repository: https://github.com/tud-cor/acado-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.7.2`
- previous version for package: `null`

### CODE REVIEW

**Comment by RonaldEnsing** [comment]
I've added the `doc` and `source` entry for melodic as well, as request here: https://github.com/ros/rosdistro/pull/20511.

**Comment by RonaldEnsing** [comment]
@tfoote The `Mdev__acado__ubuntu_bionic_amd64` job fails [1]. However, if I execute the same commands in a container (`ros:melodic-ros-base`) on my system, these steps succeed. Do you have an idea what could cause the `run tests` job being unable to find the `/tmp/ws/devel_isolated/acado/setup.sh`, or a suggestion on how to reproduce this?

[1] http://build.ros.org/job/Mdev__acado__ubuntu_bionic_amd64/1/console

**Comment by tfoote** [comment]
Sorry I don't know what might be different. The console output is long enough that I can't easily pull it up in the browser and browse/search through it. I want to be able to grep through it and see where it might be failing to install the setup.sh

**Comment by RonaldEnsing** [comment]
@tfoote A `grep` in the full log on the pattern `/tmp/ws/devel_isolated/acado/setup.sh` only gives `/bin/sh: 4: .: Can't open /tmp/ws/devel_isolated/acado/setup.sh`. It does not seem to create the file `/tmp/ws/devel_isolated/acado/setup.sh` at all. However, the build on kinetic does not fail [2], and a grep on the kinetic log on `/tmp/ws/devel_isolated/acado/setup.sh` gives no result at all, even though it is the exact same source code that is released. Do you have an idea why it is looking for the file `/tmp/ws/devel_isolated/acado/setup.sh` for melodic in the first place?


[2] http://build.ros.org/job/Kdev__acado__ubuntu_xenial_amd64/1/console

**Comment by RonaldEnsing** [comment]
This may be fixed by adding the installation of the `package.xml` (https://github.com/ros/rosdistro/pull/20741).

**Pull request merged**
