### PR TITLE
gdown is missing on debian/fedra

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by wkentaro** [comment]
Thanks.

**Comment by tfoote** [comment]
Extending this looks good.

Since this is a pip-only package and only has partial coverage what do people think of updating the key to use our new standard '-pip' at the end for future compatibility?

**Comment by k-okada** [comment]
ok, added python-gdown-pip -> 701f83f

**Comment by tfoote** [comment]
Thanks @k-okada I was actually proposing replacing not extending. Such that we can leave the old key space available if it becomes system packaged in the future.

**Comment by k-okada** [comment]
oh, do you mean
```
diff --git a/rosdep/python.yaml b/rosdep/python.yaml
index 782df23..0fefb6d 100644
--- a/rosdep/python.yaml
+++ b/rosdep/python.yaml
@@ -798,7 +798,13 @@ python-fysom:
   ubuntu:
     pip:
       packages: [fysom]
-python-gdown:
+python-gdown-pip:
+  debian:
+    pip:
+      packages: [gdown]
+  fedora:
+    pip:
+      packages: [gdown]
   osx:
     pip:
       packages: [gdown]
```
?

**Comment by tfoote** [comment]
Yes

**Comment by k-okada** [comment]
Ok fixed now

**Review by tfoote — APPROVED** [review]
LGTM. Thanks for iterating @k-okada

**Pull request merged**
