### PR TITLE
ur_client_library: 1.0.0-2 in 'rolling/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by fmauch**
Increasing version of package(s) in repository `ur_client_library` to `1.0.0-2`:

- upstream repository: https://github.com/UniversalRobots/Universal_Robots_Client_Library
- release repository: https://github.com/UniversalRobots/Universal_Robots_Client_Library-release.git
- distro file: `rolling/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## ur_client_library

```
* Added Cartesian streaming interface #75 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/75>
* Added trajectory forwarding interface #72 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/72>
* Refactored Reverse interface #70 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/70> from fmauch/refactor_reverse_interface
* Added option for robot_ip as runtime argument for rtde_test (#71 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/71>)
* Added reverse_ip parameter (#52 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/52>)
* Move calibration check out of constructor. #65 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/65> from fmauch/calibration_check_optional
* Install the resources folder instead of the script file directly (#62 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/62>)
* Use a non-blocking tcp server for the ReverseInterface and ScriptSender. #46 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/46> from fmauch/tcp_server
* Added LogHandler #40 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/40> from urmahp/logging_feature
* Fixed links in README (#35 <https://github.com/UniversalRobots/Universal_Robots_Client_Library/issues/35>)
* Contributors: Felix Exner, G.A. vd. Hoorn, JS00000, Lennart Puck, Mads Holm Peters, Tristan Schnell
```

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Holding releases for an [upcoming Rolling sync](https://discourse.ros.org/t/preparing-for-rolling-sync-2022-03-03/24521).

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
@fmauch I'd like to move the release repository into the ros2-gbp organization in order to maintain access for the release automation tools for ROS 2 distributions. If that works for you I'll create a new release team for universal_robotics in https://github.com/ros2-gbp/ros2-gbp-github-org/ and mirror the release repository contents there. That way when we create Humble from Rolling in a few months the release repository is already set up for that automation.

**Comment by fmauch** [comment]
> @fmauch I'd like to move the release repository into the ros2-gbp organization in order to maintain access for the release automation tools for ROS 2 distributions. If that works for you I'll create a new release team for universal_robotics in https://github.com/ros2-gbp/ros2-gbp-github-org/ and mirror the release repository contents there. That way when we create Humble from Rolling in a few months the release repository is already set up for that automation.

That's probably something @urrsk will have to comment on.

**Comment by urrsk** [comment]
@nuclearsandwich Thanks for reaching out
We will be happy to follow up on the initiative to help out maintain the access to the releases.
Please use the name 'universal_robots' instead of the other you mentioned, as this is our company name

**Comment by tfoote** [comment]
[Sync freeze released](https://discourse.ros.org/t/preparing-for-rolling-sync-delayed-by-python-3-10-transition/24521/2?u=tfoote)

**Comment by nuclearsandwich** [comment]
> Please use the name 'universal_robots' instead of the other you mentioned, as this is our company name

My apologies for the mistake! I'll use this correct name instead.

**Comment by nuclearsandwich** [comment]
PR to create the release team is open https://github.com/ros2-gbp/ros2-gbp-github-org/pull/19 once it is merged I'll open a rosdistro PR to update the release information. @fmauch I would suggest using the ros2-gbp release repository for all future releases in any ROS 2 distribution in order to avoid bifurcating the release history.

**Pull request merged**
