### PR TITLE
update rule for libjpeg

### PR DESCRIPTION
**Pull request by wjwwood**
See:

- http://packages.ubuntu.com/yakkety/libjpeg-dev
- http://packages.ubuntu.com/zesty/libjpeg-dev

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@wjwwood could you add debian rules too please?

**Comment by wjwwood** [comment]
I guess that's the right `libjpeg` rule for stretch?

**Review by mikaelarguedas — COMMENTED** [review]
I think it is: libjpeg62-turbo-dev (https://packages.debian.org/stretch/libdevel/libjpeg62-turbo-dev) that provide the virtual package libjpeg-dev

**Comment by wjwwood** [comment]
But that's the same thing we're doing in Ubuntu:

http://packages.ubuntu.com/yakkety/libjpeg-dev

I don't know which we should prefer, because you could also do `libjpeg8-dev`.

**Comment by mikaelarguedas** [comment]
hmm good question. I guess it comes down to: do we prefer to have keys that are the same across platforms or call out versions.
I'm guessing based on the other rules that you're right we should use `libjpeg-dev` for both. Is the consensus to use the "generic" name as long as it doesn't result in ambiguity to which package provides it? (like it would be the case for `libtlfk-dev` for example provided by both  `libfltk1.3-dev` and `libfltk1.1-dev` )

**Review by mikaelarguedas — APPROVED** [review]

**Comment by wjwwood** [comment]
Yeah, but in the case of `libfltk-dev` we explicitly want the non-default version (1.3 rather than 1.1). I don't care what we do here, but I'd want to make it consistent between ubuntu and debian.

**Comment by wjwwood** [comment]
We decided to leave it as proposed here.

**Pull request merged**
