### PR TITLE
update collada-dom for xenial

### PR DESCRIPTION
**Pull request by k-okada**
see https://github.com/ros/rosdistro/issues/9945#issuecomment-194642340 for discussion

### CODE REVIEW

**Comment by tfoote** [comment]
I see libcollada-dom2.4-dep-dev but not libcollada-dom-dev

http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=collada-dom&searchon=names

**Comment by wjwwood** [comment]
I agree with @tfoote this will not work as is.

**Comment by k-okada** [comment]
anyway, I updated the PR with libcollada-dom2.4-dep-dev

**Comment by wjwwood** [comment]
Oh, well I can install that too. I guess the virtual packages don't show up on packages.ubuntu.com?

I think we should change it back to `libcollada-dom-dev`. Sorry for all the back and forth @k-okada.

**Comment by k-okada** [comment]
ok, done

--
◉ Kei Okada

**Comment by wjwwood** [comment]
+1, just to confirm I removed all collada packages and PPA's from my xenial VM and was able to install `libcollada-dom-dev` still.

**Comment by tfoote** [comment]
Sorry unfortunately rosdep cannot support virtual packages. apt-get will install it, but we cannot detect they are installed and rosdep will always try to install it.

**Comment by wjwwood** [comment]
Ok, I have to change my mind again. After talking with @tfoote we can't support the virtual package because of the way we check that it is installed with `rosdep`.

**Comment by k-okada** [comment]
ok, i added https://github.com/ros/rosdistro/pull/10700, please merge whichever you like ;-)

**Comment by k-okada** [comment]
#10700 was merged

**Pull request closed without merging**
