### PR TITLE
add mosquitto-clients to the rosdep

### PR DESCRIPTION
**Pull request by hakuturu583**
add mosquitto-clients to the rosdep.

### CODE REVIEW

**Comment by hakuturu583** [comment]
these are package description

debian https://packages.debian.org/stretch/mosquitto-clients
ubuntu https://packages.ubuntu.com/disco/mosquitto-clients

**Review by tfoote — APPROVED** [review]
This looks fine. It looks like fedora doesn't have a mosquitto-client package. Is that included in the mosquitto main package? If so it should have the main mosquitto listed as a dependency. Otherwise we can skip it.

**Review by clalancette — CHANGES_REQUESTED** [review]
Looking at my Fedora-30 box, it looks like the `mosquitto_{pub,sub}` binaries are provided by the main `mosquitto` package on Fedora, so please add that key as well.

**Comment by clalancette** [comment]
No response for a month, so I'm going to close this.  Feel free to reopen if you still want to get this rosdep key in.

**Pull request closed without merging**
