### PR TITLE
Add python3-lark-parser for gentoo

### PR DESCRIPTION
**Pull request by allenh1**
Added ebuild to ROS Overlay in commit 98f9546c61f6d14a49efa3f66c2960d7f4f9d5c2.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@allenh1 did you catch that we need a specific pre-released version is required https://github.com/ros2/ci/pull/220#issuecomment-439213675 ?

The key looks good to me as long as the ebuild contains a sufficient version.

**Comment by allenh1** [comment]
> did you catch that we need a specific pre-released version?

Uh -- nope. No I did not. I'll definitely update my ebuild in the near future to link to that version.

Thanks for catching that!

**Review by nuclearsandwich — APPROVED** [review]
Approved with the caveat that until the ebuild is updated this key won't be sufficient to enable ROS 2 on Gentoo. I'll leave it to additional reviewers and @allenh1 to decide if we should wait to merge until the ebuild is updated.

**Comment by allenh1** [comment]
I don't think it's necessary to wait, since the key will still be the same. There's a long way to go yet wrt ROS 2 on gentoo.

**Pull request merged**
