### PR TITLE
add python3-gdown-pip

### PR DESCRIPTION
**Pull request by knorth55**
I add `python3-gdown-pip` key.
I follow the instruction in https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1 and use anchor/alias for yaml.

PyPI URL: https://pypi.org/project/gdown/

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
It looks like the diff picked up a nearby key and is checking that. I've opened https://github.com/ros/rosdistro/pull/30056 to resolve that issue. As long as you're aware that pip keys cannot be used in packages released to the official build farm and the key is still useful to you I think we can review this as-is and plan to merge in master once the PR fixing python-gdal is merged.

**Review by nuclearsandwich — APPROVED** [review]
Approved pending an off-branch fix for the CI failure which is proximal not related to the added key.

**Comment by clalancette** [comment]
I've now merged in #30056 .  @knorth55 Do you mind rebasing this on the latest to see if it fixes CI?  Thanks.

**Review by clalancette — APPROVED** [review]

**Comment by knorth55** [comment]
@clalancette Thank you, I rebased this PR.

**Pull request merged**
