### PR TITLE
dynamixel-workbench: 0.2.0-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by robotpilot**
Increasing version of package(s) in repository `dynamixel-workbench` to `0.2.0-0`:

- upstream repository: https://github.com/ROBOTIS-GIT/dynamixel-workbench.git
- release repository: https://github.com/ROBOTIS-GIT-release/dynamixel-workbench-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.5.26`
- previous version for package: `0.1.9-0`

## dynamixel_workbench

```
* added conver function to PRO user
* added dxl_info_cnt init function
* added compatibility for different protocol
* added static
* added convert function
* added baudrate sorting
* added all dynamixel series
* added RX-10
* added millis
* added init dynamixel example
* added setting for packet handler
* added monitor example
* added item
* added dynamixel_item
* added toolbox_ros and modified arduino path
* added linux build and example
* added begin and getprotocolversion function
* modified linux version
* modified description
* modified model_info
* modified variable range
* modified setTools function
* modified sync function
* modified merge conflict
* modified variable name
* modified reset function
* modified function name and return variable name
* modified name of return var
* modified item name
* modified reset function
* modified item name (added underscore)
* modified function name
* modified function for ROS depend
* modified function to make space
* modified begin function to reduce storage space
* modified MX (2.0) protocol setting bug
* modified example
* modified sync and bulk comm
* modified lib
* modified begin
* modified variable
* modified begin function
* modified joint and wheel mode
* modified variable name
* modified begin function
* modified set function
* modified dynamixel item
* modified scan function
* modified folder tree
* modified dynamixel_tool
* modified toolbox structure
* modified .device and modified funtion for opencm and opencr
* modified ifdef
* modified get file
* modified arduino version
* modified get device in arduino
* fixed reset bug
* deleted dead code
* deleted empty space
* deleted xl define
* deleted debug code and update ping func
* test OpenCM
* Contributors: Darby Lim, Karl D. Hansen, Yoonseok Pyo
```

## dynamixel_workbench_controllers

```
* added blank
* added linux build and example
* added multi port example
* modified bug
* modified torque example
* modified example
* modified controllers
* modified linux version
* deleted build
* deleted footnote
* deleted annotation
* Contributors: Darby Lim, Yoonseok Pyo
```

## dynamixel_workbench_operators

```
* modified example
* deleted build
* Contributors: Darby Lim, Karl D. Hansen
```

## dynamixel_workbench_single_manager

```
* added debug code
* added scan range param
* added baudrate sorting
* added all dynamixel series
* added publisher
* added new msg header
* added AX Message
* added protocol version function
* added linux build and example
* modified merge conflict
* modified make file
* modified function name and return variable name
* modified factory rest and added baud rate function
* modified function for ROS depend
* modified linux version
* deleted warning
* Contributors: Darby Lim, Yoonseok Pyo
```

## dynamixel_workbench_single_manager_gui

```
* added baudrate sorting
* added baud rate item and operating mode item
* added linux build and example
* modified dynamixel workbench lib
* modified make file
* modified function
* deleted build
* Contributors: Darby Lim
```

## dynamixel_workbench_toolbox

```
* added conver function to PRO user
* added dxl_info_cnt init function
* added compatibility for different protocol
* added static
* added convert function
* added baudrate sorting
* added all dynamixel series
* added RX-10
* added millis
* added init dynamixel example
* added setting for packet handler
* added monitor example
* added item
* added dynamixel_item
* added toolbox_ros and modified arduino path
* added linux build and example
* added begin and getprotocolversion function
* modified linux version
* modified description
* modified model_info
* modified variable range
* modified setTools function
* modified sync function
* modified merge conflict
* modified variable name
* modified reset function
* modified function name and return variable name
* modified name of return var
* modified item name
* modified reset function
* modified item name (added underscore)
* modified function name
* modified function for ROS depend
* modified function to make space
* modified begin function to reduce storage space
* modified MX (2.0) protocol setting bug
* modified example
* modified sync and bulk comm
* modified lib
* modified begin
* modified variable
* modified begin function
* modified joint and wheel mode
* modified variable name
* modified begin function
* modified set function
* modified dynamixel item
* modified scan function
* modified folder tree
* modified dynamixel_tool
* modified toolbox structure
* modified .device and modified funtion for opencm and opencr
* modified ifdef
* modified get file
* modified arduino version
* modified get device in arduino
* fixed reset bug
* deleted dead code
* deleted empty space
* deleted xl define
* deleted debug code and update ping func
* test OpenCM
* Contributors: Darby Lim, Yoonseok Pyo
```

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Is this the same release which was reverted in #17018?

**Comment by tfoote** [comment]
It looks like it. @robotpilot should this be 0.2.1?

**Comment by robotpilot** [comment]
It is fixed version.

2018. 2. 22. 오전 6:53에 "Tully Foote" <notifications@github.com>님이 작성:

**Comment by tfoote** [comment]
I see, you retagged 0.2.0. In general we don't recommend retagging. There are many parts of build and release systems that expect tags to be constant, and cache the content/do not retrigger if the version is the same as a previously known release. I think this will go through and overwrite past tagged versions but if it doesn't you may need to release 0.2.1 to make sure the updates propagate correctly. In the future we strongly recommend avoiding changing tags.

Checking the release repo it appears that you cleared it and created a new one without the current tags. We generally recommend keeping the old tags and branchs available. Removing them will break anyone who is trying to build based on the current state and will not allow rollbacks.

**Comment by robotpilot** [comment]
@tfoote @dirk-thomas 

I didn't know the rule about retagging. I'm sorry about it. 
I would like to express my gratitude to Tully and Thomas for understanding this. 
If the problem still occurs in this revised patch, we will re-PR it again in the next sync.

I appreciate the ongoing package management and building work of the ROS community. 
I seem to be disturbed by their efforts. I will do my best to build our system to prevent this from next week.
I have to follow as much as you do, but I am really sorry that I can't.

Thank you so much.

**Pull request merged**
