### PR TITLE
Adding ardrone2islab to documentation index for indigo

### PR DESCRIPTION
**Pull request by tn0432**
I would like ardrone2islab to be indexed and documented for indigo

### CODE REVIEW

**Comment by vrabaud** [comment]
You need to close your previous pull requests. You can also update your commits and that will automatically update your pull request.

**Comment by tn0432** [comment]
Geat! It works! I will go for next step.

Thank you very much for your help! I very appreciate that.

P.S: Sorry for my trouble! I am very new with github and these upload step

**Comment by dirk-thomas** [comment]
We will wait with the merge untl the new buildfarm rollout is finished in about onr day.

**Comment by dirk-thomas** [comment]
@vrabaud meant you **don't ** need to close your previous pull requests but can update it but committing to the branch.

**Pull request merged**
