### PR TITLE
aerostack2: 0.2.2-1 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by miferco97**
Increasing version of package(s) in repository `aerostack2` to `0.2.2-1`:

- upstream repository: https://github.com/aerostack2/aerostack2.git
- release repository: https://github.com/aerostack2/aerostack2-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## aerostack2

- No changes

## as2_aerial_platform

- No changes

## as2_alphanumeric_viewer

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* as2_alphanumeric_viewer
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## as2_aruco_detector

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## as2_behavior

- No changes

## as2_behavior_tree

- No changes

## as2_behaviors

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## as2_cli

- No changes

## as2_controller

- No changes

## as2_controller_manager

- No changes

## as2_controller_plugin_base

- No changes

## as2_controller_plugin_differential_flatness

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* reformat
* Clang test df
* Contributors: Miguel, Miguel Fernandez-Cortizas, RPS98, Rafael Pérez
```

## as2_controller_plugin_speed_controller

- No changes

## as2_core

- No changes

## as2_crazyflie_platform

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* reformat
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## as2_gazebo_assets

- No changes

## as2_hardware_drivers

- No changes

## as2_keyboard_teleoperation

```
* Merge pull request #86 <https://github.com/aerostack2/aerostack2/issues/86> from aerostack2/changed_name_keyboard_teleoperation
  keyboard teleoperation name updated, behavior control updated
* copyright test passed
* keyboard teleoperation name updated, behavior control updated
* Contributors: Javilinos, Miguel Fernandez-Cortizas
```

## as2_motion_reference_handlers

- No changes

## as2_movement_behaviors

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## as2_msgs

- No changes

## as2_pixhawk_platform

- No changes

## as2_platform_behaviors

- No changes

## as2_python_api

```
* Merge pull request #89 <https://github.com/aerostack2/aerostack2/issues/89> from aerostack2/python-new-name
  [as2_python_api] Renamed following naming convention
* moved to examples folder
* as2_python_api renamed following naming convention
* Contributors: Miguel Fernandez-Cortizas, pariaspe
```

## as2_realsense_interface

- No changes

## as2_simulation_assets

- No changes

## as2_state_estimator

- No changes

## as2_state_estimator_plugin_base

- No changes

## as2_state_estimator_plugin_external_odom

- No changes

## as2_state_estimator_plugin_ground_truth

- No changes

## as2_state_estimator_plugin_mocap

- No changes

## as2_tello_platform

- No changes

## as2_trajectory_generator

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* Change trajectory generator name
* Contributors: Miguel Fernandez-Cortizas, RPS98, Rafael Pérez
```

## as2_usb_camera_interface

- No changes

## as2_user_interface

- No changes

## follow_path_behaviour

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## follow_path_plugin_base

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## follow_path_plugins

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## goto_behaviour

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## goto_plugin_base

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## goto_plugins

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## land_behaviour

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## land_plugin_base

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## land_plugins

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## takeoff_behaviour

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## takeoff_plugin_base

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

## takeoff_plugins

```
* Merge pull request #88 <https://github.com/aerostack2/aerostack2/issues/88> from aerostack2/main
  update with main
* Merge pull request #85 <https://github.com/aerostack2/aerostack2/issues/85> from aerostack2/as2_movement_behaviors_rename
  rename movement_behavior to as2_movement_behaviors
* rename
* Contributors: Miguel, Miguel Fernandez-Cortizas, Rafael Pérez
```

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
I have a few overall comments on this PR (roughly from most problematic to least problematic):

1.  A bunch of these packages have really generic names.  Names like `goto_behavior` are going to end up with installable packages named `ros-humble-goto-behavior`, which is too generic in a system like ROS.  These should be renamed to either have the `as2_` prefix, or something else that makes them less generic.
2. The installation instructions as in https://aerostack2.github.io/_installation/index.html and https://github.com/aerostack2/aerostack2/blob/main/README.md make me question whether this will work at all on the ROS buildfarm.  In particular, using custom pip packages and using custom `as2` commands will definitely not work on the buildfarm.  That said, I didn't take a close look at the packages and dependencies to see what is going on in there.
3. The release repository is not in the https://github.com/ros2-gbp organization.  While that is not strictly required, it is recommended (especially if you are going to think about releasing this into Rolling).  If you'd like to add it to the ros2-gbp organization, instructions are in 
4. There are no source or documentation entries listed here.  While they aren't strictly required, it is unusual not to list them.
5. There are a *lot* of packages here.  This is pretty unusual for repositories in the ROS ecosystem; most repositories have a small number of packages.  For instance, right now the repository with the largest number of packages is MoveIt with 38, and this one has 10 more than that.  Again, this doesn't automatically disqualify it, but it is not the norm.

Can you maybe give us an overview of what the package does and what your future plans are for this package?

**Comment by miferco97** [comment]
Dear @clalancette, Thanks for your response and sorry for the inconvenience, we are working to fix all your comments. Our goal is to be the navigation2 for aerial robots. Aerostack2 is the evolution of Aerostack, a framework developed in 2016 by the Computer Vision and Aerial Robotics Group (CVAR), which has been successfully used in a large number of projects. So our future plans is to follow the development of this framework over the years with more plugins, and capabilities.

Respect the 3rd point, we have an open issue for having our release team in ros-gbp organization (https://github.com/ros2-gbp/ros2-gbp-github-org/issues/166#issue-1504417914), i don't know if we need to do anything else to be able to create or release repository in this organization. 

How should we proceed when we fix our repository? Shall we create a new PR? 

Additionally, i have a question that maybe you could answer me. We are using a file ```depencies_repos.repos``` in order to download an external source repository, we use ```vcs-tools``` to clone these repositories using:
```
$ vcs import --recursive < ./dependency_repos.repos 
```
Is this the correct way to doing this in order to generate the built resources? If we do this we have some warnings when launching bloom, since some ```package.xml``` can't find this repos.

Thanks in advance

**Comment by miferco97** [comment]
Hi all, we have made all the changes that were propose in https://github.com/aerostack2/aerostack2. How should we proceed? 
Do we have to create a new pull request?

**Comment by nuclearsandwich** [comment]
> Hi all, we have made all the changes that were propose in https://github.com/aerostack2/aerostack2. How should we proceed?
> Do we have to create a new pull request?

The first thing I would suggest is manually creating a pull request which adds just the source and doc entries for aerostack2 to Humble. (Be sure to link this PR in the description so that the reviewers have context, we have a rotation for triaging incoming rosdistro PRs so you're not guaranteed to get reviewers who are familiar with this discussion)

The review process of that PR will get you through naming review and unblock https://github.com/ros2-gbp/ros2-gbp-github-org/issues/166 after which a new bloom release will be required in order to release the version of aerostack2 with the requested changes made.

**Comment by sloretz** [comment]
I'll close this since #36015 merged 🎉 . The next step is to create another bloom release.

**Pull request closed without merging**
