### PR TITLE
rosdep: add websocketpp

### PR DESCRIPTION
**Pull request by vzts**
This PR adds websocketpp resolution in rosdep.

### CODE REVIEW

**Comment by tfoote** [comment]
Please link to the upstream packages for contributed rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

This will save time for anyone reviewing from having to search them out. I just tried but the Ubuntu server is giving internal server errors at the moment. I suspect it's updating it's database. Once it's back online we can take a look.

**Comment by vzts** [comment]
Oh, sure. I didn't know there was a guideline.

Package Links:
arch: https://www.archlinux.org/packages/community/any/websocketpp/
debian: https://packages.debian.org/search?searchon=sourcenames&keywords=websocketpp
fedora: https://apps.fedoraproject.org/packages/websocketpp
gentoo: https://packages.gentoo.org/packages/dev-cpp/websocketpp
ubuntu: https://packages.ubuntu.com/search?keywords=libwebsocketpp-dev&searchon=names

Upstream:
https://www.zaphoyd.com/websocketpp
https://github.com/zaphoyd/websocketpp

Description:
WebSocket++ is an open source library which implements RFC6455 The WebSocket Protocol.

Use Case:
Being one of the most popular websocket libraries written in C++, the library can provide us with a bidirectional communication channel between two parties through its WebSocket protocol implementation. In my case, I needed to open a bidirectional connection from a ROS node to connect with a WebSocket relay server in order to achieve WebRTC signaling.

**Review by tfoote — APPROVED** [review]
I switched it to use our standard of the same key as the ubuntu package. Since there's no non-dev package I used that. And restored the fedora `-devel` extension to match.

lgtm pending CI and another review.

**Comment by vzts** [comment]
@tfoote Thanks for the fix! It looks great.

**Review by cottsay — APPROVED** [review]

**Pull request merged**
