### PR TITLE
homer pkgs

### PR DESCRIPTION
**Pull request by raphaelmemmesheimer**
homer pkgs added for:
- object recognition
- speech synthesis
- mapping navigation
- robot face

### CODE REVIEW

**Comment by vrabaud** [comment]
https://gitlab.uni-koblenz.de/robbie/homer_android_speech is an empty repo, therefore it has no master branch

**Comment by airglow** [comment]
Thanks! Forgot to push, is up now.

**Comment by vrabaud** [comment]
Your release repo need to be a proper release repo. Please read: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by airglow** [comment]
Okay, worked for one package, will do it completely with the bloom tutorial.

**Pull request closed without merging**
