### PR TITLE
python-colorama is only available on trusty

### PR DESCRIPTION
**Pull request by k-okada**
see http://packages.ubuntu.com/search?lang=en&suite=trusty&searchon=names&keywords=python-colorama

or did you intened to install via pip?

### CODE REVIEW

**Comment by tfoote** [comment]
These should be undefined, not zero length lists. Zero length lists implies that the item is expected to be already available on the system.

**Comment by k-okada** [comment]
If we have package that depends on python-colorama, and try to build deb on
your buildfirm with indigo, it will fail on utopic  and vivid, except
trusty. Is it right? Of course we can patch for each ubuntu release to
avoid this problem, but may be this is confusing.Should we use pip for this
package?

--
◉ Kei Okada

**Comment by dirk-thomas** [comment]
No, PIP is not an option since released packages are depending on it (I just assume this until proven otherwise). The package is available in Trusty, Utopic as well as Vivid. So the rosdep key should be registered for these.

Then you can use it for Jade releases (using T, U, V) and partly Indigo (T will work, S will fail).

**Comment by k-okada** [comment]
ok, I have created another PR that remove null list -> https://github.com/ros/rosdistro/pull/7289,

**Pull request merged**
