### PR TITLE
Update the axis_camera release for Melodic and Kinetic to 0.3.1-1

### PR DESCRIPTION
**Pull request by civerachb-cpr**

### CODE REVIEW

**Comment by jacobperron** [comment]
What is the reason `bloom` was not used to commit to rosdistro and open pull requests?

**Comment by civerachb-cpr** [comment]
I did use bloom but it ran into errors with my oauth token and instructed me to manually submit a PR.  This is that PR.

**Comment by jacobperron** [comment]
Okay, it LGTM. Typically separate PRs are opened per distro, but you can keep this PR as-is.

Holding for [Kinetic sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-12-17/18074)

Holding for [Melodic sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2020-12-17/18056)

**Comment by civerachb-cpr** [comment]
I wasn't sure if I should do two PRs (one for Melodic and one for Kinetic) or combine them, since both failed and said to do manual PRs.  I figured combining them would be simpler. But now I know for next time.  And hopefully I can get that oath glitch sorted so this won't actually be a problem in the future.

**Comment by jacobperron** [comment]
No worries, I was just checking that there wasn't some other reason :slightly_smiling_face:

**Pull request merged**
