### PR TITLE
add lilypond to rosdep/base.yaml

### PR DESCRIPTION
**Pull request by Juphex**
Please add the following dependency to the rosdep database.

## Package name:

lilypond

## Package Upstream Source:

[TODO link to source repository
](https://github.com/lilypond/lilypond)
## Purpose of using this:

Used for a robot project. Visualization of notes.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/bullseye/lilypond
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/focal/lilypond
   - REQUIRED

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by Flova** [comment]
@Juphex I think it should be placed in https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml as this is a upstream binary package that does not need to be build from source. We only want to map the name to a apt package, so rosdep knows about it.

**Comment by Flova** [comment]
This also makes it ROS version agnostic.

**Review by Flova — APPROVED** [review]
LGTM

**Review by tfoote — DISMISSED** [review]
Please fill in the suggestions for arch fedora and opensuse from the linter as they're exact matches.

**Comment by Flova** [comment]
Looks good

**Comment by Flova** [comment]
Are there any TODOs left with this PR?

**Review by cottsay — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
