### PR TITLE
Add mrl_ipcamera package for documentation and continuous integration indexing

### PR DESCRIPTION
**Pull request by alireza-hosseini**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
what does `mrl` stand for ?
Could this package just be `ipcamera`?
In case its useful, the package naming rules can be found [here](http://www.ros.org/reps/rep-0144.html#package-naming)

**Comment by alireza-hosseini** [comment]
@mikaelarguedas Thanks for your review, 
MRL stands for the "Mechatronic Research Laboratory". I implemented this package when I was a member of this research lab, so I just didn't think of dropping the **mrl** prefix.
I took a look on the ROS existing packages and apparently there is no package called **ipcamera** so I think I can use it, however, shouldn't it be **ipcamera_driver**?

**Comment by alireza-hosseini** [comment]
@mikaelarguedas I'm closing this PR as I created a new one using bloom which has the release tag and its name is renamed to ipcamera_driver:
https://github.com/ros/rosdistro/pull/18742

**Comment by mikaelarguedas** [comment]
:+1:

**Pull request closed without merging**
