### PR TITLE
Add python3-semver

### PR DESCRIPTION
**Pull request by aaronplusone**
PyPi: https://pypi.org/project/semver/

Supported [linux distributions](https://python-semver.readthedocs.io/en/latest/install.html#linux-distributions)

Packages Lists:
[Ubuntu](https://packages.ubuntu.com/search?keywords=python3-semver&searchon=names&suite=all&section=all)
[Debian](https://packages.debian.org/search?keywords=python3-semver&searchon=names&suite=all&section=all)

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
This looks good.

One process question. Did you see the rosdep Pull Request template when you opened this PR?

**Comment by aaronplusone** [comment]
> One process question. Did you see the rosdep Pull Request template when you opened this PR?

I did not. Dialog was blank and I just looked at other PRs to see if there was a common format.

I assume it should've populated this [https://github.com/ros/rosdistro/blob/master/.github/PULL_REQUEST_TEMPLATE/rosdep_pull_request_template.md]?

**Comment by tfoote** [comment]
Yeah, I'd like to get that prompt in so that everyone uses that. But clearly it's not popping up to make things easier. i'll have to look into cleaning that up.

**Comment by aaronplusone** [comment]
Brief look I took, with multiple templates you need to modify the url query to include the template name. I didn't see anything in the CONTRIBUTING.md that indicated to use anything other than the github interface, and I didn't see anything in the PR interface that would allow switching templates like in gitlab.

Seems somewhat cumbersome to have to append `?template=rosdep_pull_request_template.md` to the url when opening a PR, but I did confirm that the template populates when you do.

**Review by mabelzhang — COMMENTED** [review]
Could you add the Gentoo dependency `[dev-python/semver]`, since it exists:
https://packages.gentoo.org/packages/dev-python/semver

**Comment by aaronplusone** [comment]
> Could you add the Gentoo dependency `[dev-python/semver]`, since it exists:
> https://packages.gentoo.org/packages/dev-python/semver

My knowledge of gentoo is pretty minimal. When testing in docker with `gentoo/stage3`, I ran into an issue with `emerge dev-python/semver` where the package was masked and required enabling a test branch. Is that typical?

```bash
5fcc6bcd120c / # emerge dev-python/semver

 * IMPORTANT: 6 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

!!! All ebuilds that could satisfy "dev-python/semver" have been masked.
!!! One of the following masked packages is required to complete your request:
- dev-python/semver-2.13.0::gentoo (masked by: ~amd64 keyword)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

5fcc6bcd120c / # export ACCEPT_KEYWORDS="~amd64"
5fcc6bcd120c / # emerge dev-python/semver

 * IMPORTANT: 6 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-python/semver-2.13.0::gentoo
...
```

Happy to add it, if so.

**Comment by tfoote** [comment]
If there's a potential issue with it on gentoo lets skip it and let someone validate it and submit it.

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
