### PR TITLE
Added new packages to distribution

### PR DESCRIPTION
**Pull request by carlos3dx**
I hope the changes are correct :S

### CODE REVIEW

**Comment by tfoote** [comment]
This looks reasonable, but you'll need to rebase it due to a merge conflict. And when you do could you squash it to get ride of all the fixup commits.

**Comment by carlos3dx** [comment]
Sorry, I'm a bit noob on ros and git. Could you explain me what do you mean with "rebase it", please? Which is the merge conflict?

Thanks.

**Comment by tfoote** [comment]
Overviews of rebasing: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

This pull-request is requesting that we merge your branch into ros/rosdistro's master branch. However your changes are out of date with the latest content on master and there are changes in the same region of the file which means that git cannot automatically merge your changes with the master branch. https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by carlos3dx** [comment]
Trying to rebase, work in progress...

**Pull request closed without merging**
