### PR TITLE
add libqt5-serialport-dev key to provide build headers

### PR DESCRIPTION
**Pull request by zflat**
Please add the following dependency to the rosdep database.

## Package name:

libqt5-serialport-dev

## Package Upstream Source:

https://www.qt.io/
https://github.com/qt/qtserialport

## Purpose of using this:

This package provides header and Qt5SerialPortConfig.cmake files to build an application using the Qt5::SerialPort module.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
  - https://packages.debian.org/sid/libdevel/libqt5serialport5-dev
- Ubuntu: https://packages.ubuntu.com/
   - REQUIRED
   - https://packages.ubuntu.com/hirsute/i386/libqt5serialport5-dev/filelist
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
  - https://archlinux.org/packages/extra/x86_64/qt5-serialport/files/
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by ivanpauno** [comment]
Could you add?

https://src.fedoraproject.org/rpms/qt5-qtserialport
https://packages.gentoo.org/packages/dev-qt/qtserialport
https://pkgs.alpinelinux.org/package/edge/community/x86/qt5-qtserialport

**Comment by zflat** [comment]
Hi @ivanpauno thanks for the feedback. Note that there already is a rosdep key for `libqt5-serialport` and what I want to add is a key for packages that contain the development header and CMake files.

-------------

> https://src.fedoraproject.org/rpms/qt5-qtserialport

It looks like the fedora package does include this RPM with development files https://koji.fedoraproject.org/koji/rpminfo?rpmID=27106679 so I will specify `qt5-qtserialport`.

-------------

> https://packages.gentoo.org/packages/dev-qt/qtserialport

I am having trouble finding the list of files included in that package. Do you have any tips on where that information can be found? 

-------------


> https://pkgs.alpinelinux.org/package/edge/community/x86/qt5-qtserialport

It looks like the alpinelinux package that I want to add is https://pkgs.alpinelinux.org/package/edge/community/armhf/qt5-qtserialport-dev which does include the development headers and CMake Qt5SerialPortConfig.cmake files. I will specify that package.

**Comment by ivanpauno** [comment]
> Hi @ivanpauno thanks for the feedback. Note that there already is a rosdep key for libqt5-serialport and what I want to add is a key for packages that contain the development header and CMake files.

Thanks for clarifying, I didn't notice that.

> > https://packages.gentoo.org/packages/dev-qt/qtserialport
> I am having trouble finding the list of files included in that package. Do you have any tips on where that information can be found?

I couldn't find that, but I think they do include header files there.
e.g.: https://github.com/ros/rosdistro/blob/50786bb7164fdd424a78ced35efa87f4fe33b0e0/rosdep/base.yaml#L4630

**Comment by zflat** [comment]
@ivandariojr I found a way to list the package contents on this site https://www.portagefilelist.de/site/query/listPackageFiles/?category=dev-qt&package=qtserialport&version=5.9.4&do#result

I confirmed that the gentoo package has the development files so I will add it to the rosdep entry.

**Review by ivanpauno — APPROVED** [review]

**Review by hidmic — APPROVED** [review]

**Pull request merged**
