### PR TITLE
Add franka_description package

### PR DESCRIPTION
**Pull request by AndreasKuhner**
Please add the following dependency to the rosdep database.

## Package name:

franka_description

## Package Upstream Source:

https://github.com/frankaemika/franka_description

## Purpose of using this:

The Franka Description package provides URDF files for the FR3 robot and toolings (e.g. Franka Hand).

This PR is the first step to for releasing a ROS 2 package.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - not available yet
- Ubuntu: https://packages.ubuntu.com/
  -  not available yet
- Fedora: https://packages.fedoraproject.org/
  - not available
- Arch: https://www.archlinux.org/packages/
  - not available
- Gentoo: https://packages.gentoo.org/
  - not available
- macOS: https://formulae.brew.sh/
  - not available
- Alpine: https://pkgs.alpinelinux.org/packages
  - not available
- NixOS/nixpkgs: https://search.nixos.org/packages
  - not available
- openSUSE: https://software.opensuse.org/package/
  - not available
- rhel: https://rhel.pkgs.org/
  - not available

# Please Add This Package to be indexed in the rosdistro.

not yet available

# The source is here:

https://github.com/frankaemika/franka_description

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by sloretz** [comment]
@gollth & @marcbone I see you've done franka_description (via franka_ros) releases in ROS 1 in the past. Does this PR adding a source entry for a new repo containing franka_description into ROS Humble look good to you?

**Comment by AndreasKuhner** [comment]
@sloretz The idea is that we (from Franka Robotics side) want to provide the data currently sitting in our main ros 1/2 (franka_ros/2) repo, to an own one and provide a ros 2 package.  

With that, no one needs to compile/construct the URDFs but can just use the package.

**Comment by BarisYazici** [comment]
@sloretz thank you for reviewing our PR. Is there any more to do here that we can help?

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/frankaemika/franka_description/blob/main/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
  - [x] franka_description: https://github.com/frankaemika/franka_description/blob/main/package.xml#L8
- [x] Public source repo: https://github.com/frankaemika/franka_description/tree/main/
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] franka_description

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
