### PR TITLE
catkin_pure_python: 0.1.3-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by asmodehn**
Increasing version of package(s) in repository `catkin_pure_python` to `0.1.3-0`:
- upstream repository: https://github.com/asmodehn/catkin_pure_python.git
- release repository: https://github.com/asmodehn/catkin_pure_python-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.21`
- previous version for package: `0.1.2-0`
## catkin_pip

```
* renaming catkin_pure_python to catkin_pip for clarity
* Contributors: alexv
```

### CODE REVIEW

**Comment by asmodehn** [comment]
renamed repository and package. I will fix packages that depend on it soon...

**Comment by dirk-thomas** [comment]
@tfoote if this gets merged the various resources (doc, source debs, binary debs) of the old name should be removed.

**Comment by tfoote** [comment]
This only actually changes the repo name. The package itself stays the same which means the artifacts should stay the same, sourcedeb, binarydeb doc results. There will be a new doc job, but the old one should get cleared when the farm reconfigures. If there's anything that doesn't get cleared we should ticket it.

**Comment by dirk-thomas** [comment]
No, the package name was changes from `catkin_pure_python` to `catkin_pip` so all old artifacts need to be removed manually.

**Pull request merged**
