### PR TITLE
mrpt_navigation: 1.0.0-1 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by jlblancoc**
Increasing version of package(s) in repository `mrpt_navigation` to `1.0.0-1`:

- upstream repository: https://github.com/mrpt-ros-pkg/mrpt_navigation.git
- release repository: https://github.com/mrpt-ros-pkg-release/mrpt_navigation-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.1`
- previous version for package: `null`

## mrpt_local_obstacles

```
* Update URLs to https
* Update build dep to mrpt2
* Fix build against mrpt2
* Contributors: Jose Luis Blanco Claraco, Jose Luis Blanco-Claraco, Jose-Luis Blanco
```

## mrpt_localization

```
* Update URLs to https
* Update build dep to mrpt2
* Merge pull request #118 <https://github.com/mrpt-ros-pkg/mrpt_navigation/issues/118> from mx-robotics/ag-remove_laser_tf_cache
  continuous laser pose update from tf tree fag added
* added ROS parameter continuous sensor pose update
* Fix incorrect publication of estimated pose (Closes: #117 <https://github.com/mrpt-ros-pkg/mrpt_navigation/issues/117>)
* Contributors: Jose Luis Blanco Claraco, Markus Bader
```

## mrpt_map

```
* Update URLs to https
* Update build dep to mrpt2
* Contributors: Jose Luis Blanco Claraco
```

## mrpt_navigation

```
* Update URLs to https
* Contributors: Jose Luis Blanco Claraco
```

## mrpt_rawlog

```
* Update URLs to https
* Update build dep to mrpt2
* Merge pull request #126 <https://github.com/mrpt-ros-pkg/mrpt_navigation/issues/126> from lukschwalb/master
  Fix incorrect class check
* Fix incorrect class name
* Merge pull request #119 <https://github.com/mrpt-ros-pkg/mrpt_navigation/issues/119> from mx-robotics/develop
  rawlog_record: fnc call fileNameStripInvalidChars removed
* Contributors: Jose Luis Blanco Claraco, Markus Bader, Schwalb, Luk
```

## mrpt_reactivenav2d

```
* Update URLs to https
* Update build dep to mrpt2
* Contributors: Jose Luis Blanco Claraco
```

## mrpt_tutorials

- No changes

### CODE REVIEW

**Review by jacobperron — COMMENTED** [review]
Though this is already released into an existing distribution, it would be nice if you could add a LICENSE file to the source repository, [following our contributing guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-package-contents).

**Comment by jlblancoc** [comment]
Oh, you're right!! Thanks

**Comment by jacobperron** [comment]
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2022-05-04/25386)

**Comment by methylDragon** [comment]
Merging, you might want to add the license file to your other branches for posterity, but it's up to you (: 🎉

**Review by sloretz — APPROVED** [review]

**Pull request merged**
