### PR TITLE
alpine: add first round of ROS2 dependencies

### PR DESCRIPTION
**Pull request by russkel**
This is the first round of adding the Alpine ROS2 dependencies.

The missing ones I have listed here https://github.com/russkel/rosdistro/issues/1 and I will work on creating packages and getting them into the alpine ports tree.

### CODE REVIEW

**Comment by tfoote** [comment]
Could you link to an online resource that lists the packages that are available? Such as when we add new packages for ubuntu we usually link to  packages.ubuntu.com to make sure they're present and there's an easy way to check what the package contains.

**Comment by russkel** [comment]
asio: https://pkgs.alpinelinux.org/package/edge/community/x86_64/asio-dev
cppcheck: https://pkgs.alpinelinux.org/package/edge/community/x86_64/cppcheck
cppunit: https://pkgs.alpinelinux.org/package/edge/main/x86_64/cppunit
curl: https://pkgs.alpinelinux.org/package/edge/main/x86_64/curl-dev
eigen: https://pkgs.alpinelinux.org/package/edge/community/x86_64/eigen-dev
libopencv-dev: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/opencv-dev
qtbase5-dev: https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase-dev
tango-icon-theme: https://pkgs.alpinelinux.org/package/edge/main/x86_64/tango-icon-theme
uncrustify: https://pkgs.alpinelinux.org/package/edge/community/x86_64/uncrustify
yaml: https://pkgs.alpinelinux.org/package/edge/main/x86_64/yaml-dev
zlib: https://pkgs.alpinelinux.org/package/edge/main/x86_64/zlib-dev

**Review by tfoote — APPROVED** [review]
Thanks for the links!

**Comment by russkel** [comment]
No problem!

**Comment by russkel** [comment]
I missed three deps that are already in the alpine ports tree. I have added them and force pushed.

python3-pep8: py3-pycodestyle https://pkgs.alpinelinux.org/package/edge/community/x86_64/py3-pycodestyle 
libqt5-widgets: qt5-qtbase-x11 https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtbase-x11
freetype/libfreetype6: freetype-dev --> https://pkgs.alpinelinux.org/package/edge/main/x86_64/freetype
libfreetype6-dev: freetype-dev --> https://pkgs.alpinelinux.org/package/edge/main/x86_64/freetype-dev

**Comment by nuclearsandwich** [comment]
I notice the package links all reference the rolling `edge` release. We don't have any officially supported alpine releases so in some ways it's up to the ROS on Alpine community to decide when an elided `alpine: [example_package]` key can be used versus having explicit keys for edge and currently supported releases that may lack packages in edge and later releases.

If alpine is going to follow the model that we use for Debian, Ubuntu, and Fedora, elided keys should be in all versions currently supported upstream.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by russkel** [comment]
I didn't bother linking to point-releases mainly because a number of packages existed only in edge. 

> If alpine is going to follow the model that we use for Debian, Ubuntu, and Fedora, elided keys should be in all versions currently supported upstream.

Seeing as I had to upstream a few packages (and not all have been merged yet), which places them in edge/testing (a repo you need to add manually) I think this will only be worthwhile when all the dependencies make their way out of testing and then out of edge. 

My idea is alpine support is considered experimental and once all the dependencies are available in a point-release, we can hopefully look at making Alpine packages and hosting them on the ROS infrastructure, making it a second class supported OS.

**Comment by tfoote** [comment]
We should be clear about that repositories are required for Alpine (and all the other ones.) To that end I've created #21252 

@russkel Could you submit a PR against that PR to add an explaination of how it's currently requiring testing/edge, but with the next point release (called out by name )it will be expected to be upstream?

**Comment by nuclearsandwich** [comment]
@russkel I missed that packages labeled `py3-*` are being used where python2 dependencies are being used for other platforms. I know it's possible for python3 packages to include modules that support python2 and python3. Can you confirm that that is the case here?

**Comment by russkel** [comment]
@nuclearsandwich I'm not entirely sure what you're asking me to do. Why would ROS2 deps bring in python2?

**Comment by nuclearsandwich** [comment]
I'm looking specifically at the python-qt-bindings key

https://github.com/russkel/rosdistro/blob/9dbaf38474dc9cbbdba5fbfa28399dc82dde6f2e/rosdep/python.yaml#L3287-L3305

```yaml
python-qt5-bindings:
  alpine: [py3-qt5]
  arch: [python2-pyqt5]
  debian:
    buster: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev, qtbase5-dev]
    jessie: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev, qtbase5-dev]
    stretch: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev, qtbase5-dev]
  fedora: [python-qt5-devel, sip]
  freebsd: [py27-qt5]
  gentoo: ['dev-python/PyQt5[gui,widgets]']
  opensuse: [python-qt5]
  slackware: [PyQt5]
  ubuntu:
    artful: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev]
    bionic: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev]
    wily: [libpyside2-dev, libshiboken2-dev, pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-pyside2, python-sip-dev, shiboken2]
    xenial: [libpyside2-dev, libshiboken2-dev, pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-pyside2, python-sip-dev, shiboken2]
    yakkety: [libpyside2-dev, libshiboken2-dev, pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-pyside2, python-sip-dev, shiboken2]
    zesty: [pyqt5-dev, python-pyqt5, python-pyqt5.qtsvg, python-sip-dev]
```

This key is for python2 bindings. I misinterpreted what was going here. I think what we actually need to do is move the alpine definition to https://github.com/russkel/rosdistro/blob/9dbaf38474dc9cbbdba5fbfa28399dc82dde6f2e/rosdep/python.yaml#L5017-L5025

If there are ROS 2 packages using the `python-qt5-bindings` key (which on Ubuntu can be satisfied by either python2 or python3 then we should swap that to use the python3 key so that other platforms are also compatible.

**Comment by russkel** [comment]
Instead of reverting couldn't you have removed that particular entry?

Anyway, I will have to rerun the compile and see what comes up. It might have been a mistake.

**Comment by russkel** [comment]
It is a mistake. I actually picked it up in one of my later commits that were going to be merged once I added the remaining deps. I have fixed the commit in this repo that was reverted should you want to reapply it.

https://github.com/russkel/rosdistro/commit/b3298d424383142e50b12fb074a0f18cc435a0e5#diff-701c2f61a9f7ac8fc393ccc6630c8fa5L3360

**Comment by nuclearsandwich** [comment]
Now I'm confused. I haven't reverted anything... I have just opened https://github.com/ros/rosdistro/pull/22031 which I believe is the only change needed.

**Comment by russkel** [comment]
I am also confused. It says a revert commit was applied to the branch in this PR, but it was never reverted in the main branch. Haha, never mind then, sorry for the confusion.

**Comment by nuclearsandwich** [comment]
:dizzy_face: all good. I've never claimed to be clear minded but I try to be only as confused as everyone else aroundme.

**Pull request merged**
