### PR TITLE
libccd-dev: new rosdep key

### PR DESCRIPTION
**Pull request by scpeters**
This will replace the libccd ROS package.

subset of #10874

### CODE REVIEW

**Comment by scpeters** [comment]
Should I add the homebrew formula too?

**Comment by wjwwood** [comment]
@scpeters if there is one, yes.

**Comment by wjwwood** [comment]
lgtm

**Comment by scpeters** [comment]
homebrew formula in 1c39c0c8a803e3993c016a99a69303767a9e856b

**Comment by wjwwood** [comment]
@scpeters I'm waiting on a +1/merge from one of the other ROS team people (it's a new policy we have for rosdep rules).

**Comment by scpeters** [comment]
Addresses https://github.com/ros/rosdistro/pull/10879

**Comment by scpeters** [comment]
Addresses https://github.com/ros-gbp/libccd-release/issues/1

**Pull request merged**
