### PR TITLE
Add PyQt6 to older Ubuntu versions with Pip

### PR DESCRIPTION
**Pull request by InvincibleRMC**
## Purpose of using this:

To make Guis with PyQt6 on older Ubuntu Versions

Distro packaging links:

## Links to Distribution Packages

https://pypi.org/project/PyQt6/

### CODE REVIEW

**Comment by marcoag** [comment]
I would say we usually don't accept pip packages that have a system version. In this case for `focal` and `jammy` it seems that `pyqt5` is available, even though an older version there's still a system version of it. With that said let me still run it through the ROS Core meeting and come back with the outcome of that.

**Comment by marcoag** [comment]
Adding a precedent: https://github.com/ros/rosdistro/pull/41870#pullrequestreview-2148978970

**Comment by InvincibleRMC** [comment]
Following up on this I would like to note that pyqt5 is available but eol https://endoflife.date/qt

**Comment by InvincibleRMC** [comment]
If this solution does not get accepted would it be possible to add a python3-pyqt6-pip instead only for releases that don't have a pre-built package?

**Comment by marcoag** [comment]
The problem is the releases you mentioned have a pre-built package, just that is from a previous version.

**Pull request closed without merging**
