### PR TITLE
smacc: 0.9.5-2 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by pabloinigoblasco**
Increasing version of package(s) in repository `smacc` to `0.9.5-2`:

- upstream repository: https://github.com/robosoft-ai/SMACC
- release repository: https://github.com/robosoft-ai/SMACC-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

### CODE REVIEW

**Review by methylDragon — CHANGES_REQUESTED** [review]
Needs fixing, see the nosetests

I think the version key needs to point to the branch. You might want to rebloom

**Comment by pabloinigoblasco** [comment]
Thanks.
I am having a look to this.

**Comment by pabloinigoblasco** [comment]
From my understanding the only error was that the reference source version did not exist. Now I fixed that. 
It would be good to relaunch the Nosetests.

**Comment by methylDragon** [comment]
How does this relate to https://github.com/ros/rosdistro/pull/35288 ?

**Comment by pabloinigoblasco** [comment]
Hello.
This is an older version corrected.
https://github.com/ros/rosdistro/pull/35288  is a newer version.
Both should be valid, but it is okay if only one is accepted. 

I created this second one because of your suggestion of "reblooming".

In any case, both PRs have the same error in nosetests:

```
FAIL: test_function (test.test_url_validity.TestUrlValidity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/rosdistro/rosdistro/test/test_url_validity.py", line 380, in test_function
    self.assertFalse(detected_errors)
AssertionError: ["In file '''/home/runner/work/rosdistro/rosdistro/noetic/distribution.yaml''': Could not validate source entry for repo smacc with error [[[Could not validate repository with url https://github.com/robosoft-ai/smacc.git and version 0.9.7 from entry at line 10276. Error reason: Tags are not valid, but a tag 0.9.7 was found. Re: https://github.com/ros/rosdistro/pull/20286]]]"] is not false
```

Do you know what that error exactly mean?

this is our repo: https://github.com/robosoft-ai/smacc
this is the tag we are trying to add: https://github.com/robosoft-ai/smacc/tree/0.9.7
this is the release repo: https://github.com/robosoft-ai/smacc-release

**Comment by ivanpauno** [comment]
> Do you know what that error exactly mean?

`version` can only be a branch in the case of `source` or `doc` entries.
The only `version` entry that should be a tag is the release one.

> https://github.com/ros/rosdistro/pull/35288 is a newer version.
> Both should be valid, but it is okay if only one is accepted.

I would suggest going ahead with the new one to make the process easier.
I think it's also having the same CI issue.

**Comment by pabloinigoblasco** [comment]
moving discussion to #35288.
I will fix there this issue.

**Pull request closed without merging**
