### PR TITLE
Add pocketsphinx for pip

### PR DESCRIPTION
**Pull request by fransiska**
This package is a python interface for [Pocketsphinx and Sphinxbase](https://cmusphinx.github.io/) which are used for speech recognition. 
- link to package description: https://pypi.python.org/pypi/pocketsphinx/0.1.3
- link to github repository: https://github.com/bambocher/pocketsphinx-python

### CODE REVIEW

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
Thanks @fransiska for contributing to rosdep database.

However there are a few missing information in this PR and I invite you to consult the [contribution guildelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions).
Could you please provide the following information:
- link to the web listing of the package
> For convenience in reviewing please link to the web listings of packages such as on http://packages.ubuntu.com, http://packages.debian.org, and https://admin.fedoraproject.org/pkgdb/packages/ or if a pip package pypi.python.org.

- description of the package and what use case you want to use it for
> Please also briefly describe the package being added and what use case you want to use it for. It's valuable to have a record of the packages as submitted and their intended purpose for clarity in the future so that if there's a conflict there's information to fall back on instead of speculation about the original use cases.

This package is available in official repositories in Ubuntu and Debian, please contribute these rules rather than the pip version.
> Native packages are strongly preferred. (They are required for packaging and have upgrade and conflict tracking.)

**Comment by tfoote** [comment]
There's also already a pocketsphinx ROS package: http://wiki.ros.org/pocketsphinx

And if this is only the python bindings does it need a dependency on the actual pocketsphinx implementation rosdep key?

**Comment by fransiska** [comment]
I am sorry for the lack of information and research.

This package is a python interface for [Pocketsphinx and Sphinxbase](https://cmusphinx.github.io/) which are used for speech recognition. 
- link to package description: https://pypi.python.org/pypi/pocketsphinx/0.1.3
- link to github repository: https://github.com/bambocher/pocketsphinx-python

It compiles Pocketsphinx from source, so it shouldn't need a dependency on other Pocketsphinx package.

I am aware that there is a ROS package on Pocketsphinx http://wiki.ros.org/pocketsphinx
It is a gstreamer implementation of Pocketsphinx, and requires installation of [gstreamer0.10-pocketsphinx](https://launchpad.net/ubuntu/xenial/+package/gstreamer0.10-pocketsphinx) (listed on base.yaml), which used old version of Pocketsphinx. 

However, I just found out that there is a newer version ([gstreamer1.0-pocketsphinx](https://launchpad.net/ubuntu/xenial/+package/gstreamer1.0-pocketsphinx), not listed in base.yaml). As I will also use gstreamer, I will try this package, but I thought it would be a good package for others who don't use gstreamer.

**Comment by dirk-thomas** [comment]
What is the status of this PR?

**Comment by dirk-thomas** [comment]
Closing due to no response.

**Pull request closed without merging**
