### PR TITLE
rosdep: add libzstd-dev

### PR DESCRIPTION
**Pull request by xqms**
needed for nimbro_network (see https://github.com/AIS-Bonn/nimbro_network)

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
lgtm. I simplified the ubuntu logic as it's available on all currently supported platforms.

https://packages.ubuntu.com/bionic/libzstd-dev

**Comment by xqms** [comment]
Hmm, I selected libzstd1-dev (note the 1) for xenial since it's slightly newer, with features that I need. Is that possible?

Sorry, should have pointed that one out.

**Comment by tfoote** [comment]
Sorry I missed that it was differrent. In that case we can do a '*' rule with a specific callout for xenial, could you update it that way?

**Comment by xqms** [comment]
Updated with '*' syntax. Thanks for the hint, wasn't aware of this feature :-)

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
