### PR TITLE
gpp: 0.1.0-1 in 'noetic/distribution.yaml'

### PR DESCRIPTION
**Pull request by dorezyuk**

### CODE REVIEW

**Comment by mabelzhang** [comment]
Could you use Bloom for the release? That is recommended https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md

**Comment by dorezyuk** [comment]
> Could you use Bloom for the release? That is recommended https://github.com/ros/rosdistro/blob/master/REVIEW_GUIDELINES.md

Hey, I've tried but it didnt work on my system... hope its not a big issue

**Comment by jacobperron** [comment]
> Hey, I've tried but it didnt work on my system... hope its not a big issue

What was the problem you faced? Generally, it's better if you can use bloom since it makes reviewing rosdistro PRs  much easier. You'll likely receive a similar question every time you want to bump the release version.

**Comment by dorezyuk** [comment]
I was within a docker container (not bloom's fault) and had issues with the github authentication. I could retry it on another machine (without docker). Is there a way to retry run bloom-release without bumping the release number at all?

**Comment by tfoote** [comment]
Bloom has a `--pull-request-only` mode if it completed but you just need to open the PR for the previous successful run.

**Comment by dorezyuk** [comment]
Thank you all, here is the new pr  #28212

**Comment by dorezyuk** [comment]
.

**Pull request closed without merging**
