### PR TITLE
Adding iot_bridge to documentation index for indigo and jade

### PR DESCRIPTION
**Pull request by corb555**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The release repository seems to only contain branches and tags for indigo but not for jade.

**Comment by vrabaud** [comment]
@corb555 , any update on that ?

**Comment by corb555** [comment]
I just ran bloom-release --rosdistro jade --track jade iot_bridge --edit 
and it seemed to be successful.

**Comment by vrabaud** [comment]
yes, thx ! That is a step forward. Please rebase this pull request so that it's mergeable.

**Comment by vrabaud** [comment]
@corb555 , any news on that ? you just need to rebase and push

**Comment by dirk-thomas** [comment]
I will close this due to lack of response. Please either fix the branch and comment to reopen or create a new pull request.

**Pull request closed without merging**
