### PR TITLE
Adding pcan_topics to documentation index for indigo

### PR DESCRIPTION
**Pull request by najkirdneh**
Adding pcan_topics to documentation index for indigo

### CODE REVIEW

**Comment by najkirdneh** [comment]
Dear Mr. Rabaud,

I am currently stuck trying to create a release repo. I get the following
failure when using the bloom-release command:

[image: Inline afbeelding 1]

Can you tell me in which direction to look for a solution to this failure?

Kind regards,

Hendrik

2014-12-19 17:02 GMT+01:00 Vincent Rabaud <notifications@github.com>:

**Comment by vrabaud** [comment]
Your image did not get inlined. Please copy paste your error message. answers.ros.org could be a better place to ask such questions too.

**Comment by najkirdneh** [comment]
Dear Mr. Rabaud,

hendrik@Hendrik-PC:~$ bloom-release --rosdistro indigo --track indigo
pcan_topics  --edit
ROS Distro index file associate with commit
'5ab7e1213396eb72fe45515b179904450dec37a0'
Specified repository 'pcan_topics' is not in the distribution file located
at 'https://raw.github.com/ros/rosdistro/master/indigo/distribution.yaml'
Could not determine release repository url for repository 'pcan_topics' of
distro 'indigo'
You can continue the release process by manually specifying the location of
the RELEASE repository.
To be clear this is the url of the RELEASE repository not the upstream
repository.
For release repositories on GitHub, you should provide the `https://` url
which should end in `.git`.
Here is the url for a typical release repository on GitHub:
https://github.com/ros-gbp/rviz-release.git
Release repository url [press enter to abort]:
https://github.com/najkirdneh/pcan_topics-release.git
==> Fetching 'pcan_topics' repository from '
https://github.com/najkirdneh/pcan_topics-release.git'
Cloning into '/tmp/tmpYoNz6p'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
Creating track 'indigo'...
Repository Name:
  upstream
    Default value, leave this as upstream if you are unsure
  <name>
    Name of the repository (used in the archive name)
  ['upstream']:
Upstream Repository URI:
  <uri>
    Any valid URI. This variable can be templated, for example an svn url
    can be templated as such: "https://svn.foo.com/foo/tags/foo-:{version}"
    where the :{version} token will be replaced with the version for this
release.
  [None]: https://github.com/najkirdneh/pcan_topics
Upstream VCS Type:
  svn
    Upstream URI is a svn repository
  git
    Upstream URI is a git repository
  hg
    Upstream URI is a hg repository
  tar
    Upstream URI is a tarball
  ['git']:
Version:
  :{ask}
    This means that the user will be prompted for the version each release.
    This also means that the upstream devel will be ignored.
  :{auto}
    This means the version will be guessed from the devel branch.
    This means that the devel branch must be set, the devel branch must
exist,
    and there must be a valid package.xml in the upstream devel branch.
  <version>
    This will be the version used.
    It must be updated for each new upstream version.
  [':{auto}']:
Release Tag:
  :{none}
    For svn and tar only you can set the release tag to :{none}, so that
    it is ignored.  For svn this means no revision number is used.
  :{ask}
    This means the user will be prompted for the release tag on each
release.
  :{version}
    This means that the release tag will match the :{version} tag.
    This can be further templated, for example: "foo-:{version}" or
"v:{version}"

    This can describe any vcs reference. For git that means {tag, branch,
hash},
    for hg that means {tag, branch, hash}, for svn that means a revision
number.
    For tar this value doubles as the sub directory (if the repository is
    in foo/ of the tar ball, putting foo here will cause the contents of
    foo/ to be imported to upstream instead of foo itself).
  [':{version}']:
Upstream Devel Branch:
  <vcs reference>
    Branch in upstream repository on which to search for the version.
    This is used only when version is set to ':{auto}'.
  [None]:
ROS Distro:
  <ROS distro>
    This can be any valid ROS distro, e.g. groovy, hydro
  ['indigo']:
Patches Directory:
  :{none}
    Use this if you want to disable overlaying of files.
  <path in bloom branch>
    This can be any valid relative path in the bloom branch. The contents
    of this folder will be overlaid onto the upstream branch after each
    import-upstream.  Additionally, any package.xml files found in the
    overlay will have the :{version} string replaced with the current
    version being released.
  [None]:
Release Repository Push URL:
  :{none}
    This indicates that the default release url should be used.
  <url>
    (optional) Used when pushing to remote release repositories. This is
only
    needed when the release uri which is in the rosdistro file is not
writable.
    This is useful, for example, when a releaser would like to use a ssh url
    to push rather than a https:// url.
  [None]:
Created 'indigo' track.
==> Testing for push permission on release repository
==> git remote -v
origin    https://github.com/najkirdneh/pcan_topics-release.git (fetch)
origin    https://github.com/najkirdneh/pcan_topics-release.git (push)
==> git push --dry-run
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': najkirdneh
Password for 'https://najkirdneh@github.com':
To https://github.com/najkirdneh/pcan_topics-release.git
   34d8447..67b41f9  master -> master
==> Releasing 'pcan_topics' using release track 'indigo'
==> git-bloom-release indigo
Processing release track settings for 'indigo'
Checking upstream devel branch for package.xml(s)
Cloning into '/tmp/tmpEcV8Vg/upstream'...
remote: Counting objects: 554, done.
remote: Compressing objects: 100% (256/256), done.
remote: Total 554 (delta 248), reused 551 (delta 246)
Receiving objects: 100% (554/554), 2.14 MiB | 726.00 KiB/s, done.
Resolving deltas: 100% (248/248), done.
Checking connectivity... done.
Looking for packages in 'master' branch... found 'pcan_topics'.
Detected version '1.0.2' from package(s): ['pcan_topics']

Executing release track 'indigo'
==> bloom-export-upstream /tmp/tmpEcV8Vg/upstream git --tag 1.0.2
--display-uri https://github.com/najkirdneh/pcan_topics --name upstream
--output-dir /tmp/tmpMoWYU0
Checking out repository at 'https://github.com/najkirdneh/pcan_topics' to
reference '1.0.2'.
Exporting to archive: '/tmp/tmpMoWYU0/upstream-1.0.2.tar.gz'
md5: 3b8a1d3621c668c6de57150988ac84de

==> git-bloom-import-upstream /tmp/tmpMoWYU0/upstream-1.0.2.tar.gz
--release-version 1.0.2 --replace
Creating upstream branch.
Importing archive into upstream branch...
'execute_command' failed to call 'git add src README.md can messages.txt~
Makefile CMakeLists_handle.txt~ CMakeLists.txt CHANGELOG.rst manifest.xml~
doc package.xml mainpage.dox~ mainpage.dox CMakeLists.txt~' which had a
return code (128):
```
fatal: pathspec 'can' did not match any files

```
'execute_command' failed to call 'git checkout "master"' which had a return
code (1):
```
error: The following untracked working tree files would be overwritten by
checkout:
    README.md
Please move or remove them before you can switch branches.
Aborting

```
Failed to checkout to 'master' because the working directory
CalledProcessError: Command 'git checkout "master"' returned non-zero exit
status 1

++ git status:

On branch upstream
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    CHANGELOG.rst
    CMakeLists.txt
    CMakeLists.txt~
    CMakeLists_handle.txt~
    Makefile
    README.md
    can messages.txt~
    doc/
    mainpage.dox
    mainpage.dox~
    manifest.xml~
    package.xml
    src/

nothing added to commit but untracked files present (use "git add" to track)
Traceback (most recent call last):
  File "/usr/bin/git-bloom-import-upstream", line 9, in <module>
    load_entry_point('bloom==0.5.16', 'console_scripts',
'git-bloom-import-upstream')()
  File
"/usr/lib/python2.7/dist-packages/bloom/commands/git/import_upstream.py",
line 388, in main
    args.replace)
  File
"/usr/lib/python2.7/dist-packages/bloom/commands/git/import_upstream.py",
line 315, in import_upstream
    import_tarball(tarball_path, 'upstream', version, name)
  File
"/usr/lib/python2.7/dist-packages/bloom/commands/git/import_upstream.py",
line 159, in import_tarball
    execute_command(cmd)
  File "/usr/lib/python2.7/dist-packages/bloom/git.py", line 359, in
__exit__
    checkout(self.current_branch, raise_exc=True, directory=self.directory)
  File "/usr/lib/python2.7/dist-packages/bloom/git.py", line 307, in
checkout
    cwd=directory)
  File "/usr/lib/python2.7/dist-packages/bloom/util.py", line 434, in
execute_command
    raise CalledProcessError(result, cmd)
CalledProcessError: Command 'git checkout "master"' returned non-zero exit
status 1

<== Error running command '['/usr/bin/git-bloom-import-upstream',
'/tmp/tmpMoWYU0/upstream-1.0.2.tar.gz', '--release-version', '1.0.2',
'--replace']'
Release failed, exiting.


kind regards,

Hendrik

2015-01-01 17:36 GMT+01:00 Vincent Rabaud <notifications@github.com>:

**Comment by dirk-thomas** [comment]
@wjwwood fyi

**Comment by tfoote** [comment]
@najkirdneh I suggest you remove all the *~ files from source control. In particular I think [can messages.txt~](https://github.com/najkirdneh/pcan_topics/blob/master/can%20messages.txt~) with the space is exposing an string escaping issue in bloom. I've opened a ticket here: https://github.com/ros-infrastructure/bloom/issues/351

Hopefully that will be fixed soon, but in the mean time you should clean up those old files anyway.

**Comment by wjwwood** [comment]
@najkirdneh I would second what @tfoote said, and that you should probably have a line like `*~` in your `.gitignore` file in the root of your repository to prevent these types of files from getting committed in the future.

**Comment by wjwwood** [comment]
@najkirdneh also, the dependencies you have listed in your `package.xml` are not formatted correctly: https://github.com/najkirdneh/pcan_topics/blob/master/package.xml#L15-20

**Comment by wjwwood** [comment]
Also, this is the output from `catkin_lint`:

```
% catkin_lint
pcan_topics: error: missing include_directories(${catkin_INCLUDE_DIRS})
pcan_topics: error: unknown run_depend 'package="libpcan"'
pcan_topics: error: unknown run_depend 'package="roscpp"'
pcan_topics: error: unknown run_depend 'package="std_msgs"'
pcan_topics: error: unknown buildtool_depend 'catkin'
pcan_topics: error: unknown build_depend 'package="libpcan"'
pcan_topics: error: unknown build_depend 'package="roscpp"'
pcan_topics: error: unknown build_depend 'package="std_msgs"'
pcan_topics: CMakeLists.txt(8): error: unknown package 'roscpp'
pcan_topics: CMakeLists.txt(8): error: unknown package 'libpcan'
catkin_lint: checked 1 packages and found 10 problems
catkin_lint: 2 notices have been ignored. Use -W2 to see them
```

Most of those are addressable and include warnings for your strange entries in the dependency tags of your `package.xml`.

---

@roehling what is the line `pcan_topics: error: unknown buildtool_depend 'catkin'` about? I assume it is because those packages are not in the RPP? The lines like `pcan_topics: CMakeLists.txt(8): error: unknown package 'roscpp'` also seem like false positives in the corner case that no environment is sourced or those packages are not installed locally.

**Comment by najkirdneh** [comment]
Dear Mr. Woodall,

Thank you for the information I will edit the package.xml file.

kind regards,

Hendrik

2015-01-05 22:39 GMT+01:00 William Woodall <notifications@github.com>:

**Comment by roehling** [comment]
@wjwwood: it looks like the rosdep database view is empty or at least missing vital parts. catkin_lint only checks if the rosdep2 module is available, but it does not ensure that the returned view actually contains packages. I should probably do some sanity checks and disable "unknown package" messages if the environment is broken, i.e. `catkin` is not found.

**Comment by wjwwood** [comment]
@roehling I have a working `rosdep`:

```
william@dosa /tmp/pcan_topics (git:master:5326831)
% rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://github.com/ros/rosdistro/raw/master/rosdep/osx-homebrew.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/gentoo.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/base.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/python.yaml
Hit https://github.com/ros/rosdistro/raw/master/rosdep/ruby.yaml
Hit https://github.com/ros/rosdistro/raw/master/releases/fuerte.yaml
Ignore legacy gbpdistro "groovy"
Ignore legacy gbpdistro "hydro"
Query rosdistro index https://raw.github.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "hydro"
Add distro "indigo"
Add distro "jade"
updated cache in /Users/william/.ros/rosdep/sources.cache

william@dosa /tmp/pcan_topics (git:master:5326831)
% catkin_lint
pcan_topics: error: missing include_directories(${catkin_INCLUDE_DIRS})
pcan_topics: error: unknown run_depend 'package="libpcan"'
pcan_topics: error: unknown run_depend 'package="roscpp"'
pcan_topics: error: unknown run_depend 'package="std_msgs"'
pcan_topics: error: unknown buildtool_depend 'catkin'
pcan_topics: error: unknown build_depend 'package="libpcan"'
pcan_topics: error: unknown build_depend 'package="roscpp"'
pcan_topics: error: unknown build_depend 'package="std_msgs"'
pcan_topics: CMakeLists.txt(8): error: unknown package 'roscpp'
pcan_topics: CMakeLists.txt(8): error: unknown package 'libpcan'
catkin_lint: checked 1 packages and found 10 problems
catkin_lint: 2 notices have been ignored. Use -W2 to see them
```

Is it because there is no `ROS_DISTRO` set?

**Comment by roehling** [comment]
Unsetting `ROS_DISTRO` does have an effect, but it looks pretty random to me. In my configuration, it makes catkin_lint complain about an unknown run_depend "map_server", but nothing else.

**Pull request closed without merging**
