### PR TITLE
Update distribution.yaml

### PR DESCRIPTION
**Pull request by michael1309**
Please add the sick_scan package to the distribution.

Thanks in advance

### CODE REVIEW

**Comment by clalancette** [comment]
This failed CI because of the following:

```
Unable to fetch package.xml: Could not clone repository "https://github.com/SICKAG/sick_scan-release.git" at reference "release/melodic/sick_scan/0.0.14-0"
```

It looks like a release for melodic wasn't properly done into the release repository.  We highly suggest using bloom to do releases, which will do this for you; documentation on how to do it is here: http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage .  Let us know if you have any questions about the process.

**Comment by michael1309** [comment]
Hello Chris,

Please excuse the inconvenience. We have fixed the problem and it should work now.

Thanks in advance

**Comment by nuclearsandwich** [comment]
I've triggered a Travis rebuild to check.

**Comment by clalancette** [comment]
This latest one failed because it looks like what is tagged in the gbp repository is 0.0.15, but this PR is trying to set it to 0.0.14.

**Comment by nuclearsandwich** [comment]
@michael1309 can you please update this PR to specify the version you intend to release? Thanks

**Comment by michael1309** [comment]
Hi Steven,

we will release a new version on Thursday 14th Feb and update the information the day after tomorrow.

Best regards,
Michael

**Comment by nuclearsandwich** [comment]
> we will release a new version on Thursday 14th Feb and update the information the day after tomorrow.

Sounds good. With that in mind I'll close this PR for now. Feel free to re-open it if you decide to update it manually. Or if you're releasing with bloom it can automatically open the PR for you.

**Pull request closed without merging**
