### PR TITLE
python: add gpiozero as pip dependency

### PR DESCRIPTION
**Pull request by kyrofa**
Ubuntu is the only platform I have to test, and it's not packaged.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Please use the `-pip` suffix when adding pip only keys.
And add python packages in the python.yaml file rather that base.yaml.

Even if you dont test with it can you please add a debian entry as well?

Note for the future: this package will be available in apt soon:
- ubuntu arm since zesty no amd64 yet
- debian since buster

**Comment by mikaelarguedas** [comment]
same comments apply to #16545

**Comment by kyrofa** [comment]
Sure thing, done. Fixed #16545 as well.

**Comment by tfoote** [comment]
I see ubuntu and debian packages for this too: 

https://packages.ubuntu.com/zesty/python-gpiozero
https://packages.debian.org/source/buster/gpiozero

**Comment by kyrofa** [comment]
Alright, updated.

**Comment by tfoote** [comment]
Thanks for iterating. Two slight requests, add yakkety which was skipped and CI needs the keys in alphabetical order.

you can validate locally with `nosetests -s` or specifically for rosdep `nostests -s test/test_rosdep_formatting.py`

**Comment by kyrofa** [comment]
Whoops, not sure how I missed Y! Done and done.

**Comment by mikaelarguedas** [comment]
Can you please add ubuntu bionic as well? and rename the key to python-gpiozero

**Comment by kyrofa** [comment]
Ah yes of course. Renamed and added bionic.

**Comment by tfoote** [comment]
Sorry, also top level alphabetization here.

**Comment by kyrofa** [comment]
Fixed here as well.

**Review by tfoote — APPROVED** [review]

**Review by mikaelarguedas — APPROVED** [review]

**Pull request merged**
