### PR TITLE
Add rhel definitions for python3-lttng & python3-babeltrace

### PR DESCRIPTION
**Pull request by christophebedard**
Required for https://gitlab.com/ros-tracing/ros2_tracing-release/-/issues/1

### CODE REVIEW

**Comment by christophebedard** [comment]
Note: I'm not sure if the packages actually exist for RHEL. I never know where to check. Is there no public list of packages for RHEL?

**Comment by clalancette** [comment]
@cottsay Would you mind taking a look?

**Comment by christophebedard** [comment]
According to this website, they might exist at least as RPM packages: https://pkgs.org/

According to this list, they don't exist: http://mirror.centos.org/centos/7/os/x86_64/Packages/

And this website is 503ing (maybe it'll come back): https://apps.fedoraproject.org/packages/

**Comment by cottsay** [comment]
Unfortunately, neither of these packages are available right now.
Here are my PRs to get them built:
* python3-lttng: https://src.fedoraproject.org/rpms/lttng-tools/pull-request/2
* python3-babeltrace: https://src.fedoraproject.org/rpms/babeltrace/pull-request/2

@christophebedard, I'll coordinate with you on how to deal with this in `ros2_tracing` on the ticket I opened there.

**Pull request closed without merging**
