### PR TITLE
Added GDAL (with python bindings)

### PR DESCRIPTION
**Pull request by felixdivo**
Tested on Ubuntu. Searched online package repositories for the other platforms.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@felixdivo Can you please provide the links of the package for the various platforms?

**Comment by felixdivo** [comment]
A summary can be found [here](https://pkgs.org/download/python-gdal). Is that enough?

**Comment by mikaelarguedas** [comment]
I think that we prefer to have the links for each platform directly referenced in the PRs as we assume the `packages.<debian/ubuntu>.<org/com>` websites are more likely to stay up and not change URLs than aggregators.

**Comment by mikaelarguedas** [comment]
Found a gentoo version as well: https://packages.gentoo.org/packages/sci-libs/gdal
`gentoo: ['sci-libs/gdal[python]']`

**Comment by felixdivo** [comment]
Sure:

Debian: https://packages.debian.org/stretch/python-gdal
Fedora: https://apps.fedoraproject.org/packages/gdal-python
Gentoo: https://packages.gentoo.org/packages/sci-libs/gdal
Ubuntu: https://packages.ubuntu.com/artful/python-gdal

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @felixdivo for the quick iteration!

**Pull request merged**
