### PR TITLE
performance_test: 2.3.0-1 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by ErikAtApex**
Increasing version of package(s) in repository `performance_test` to `2.3.0-1`:

- upstream repository: https://gitlab.com/ApexAI/performance_test.git
- release repository: https://github.com/ros2-gbp/performance_test-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.12.0`
- previous version for package: `1.2.1-1`

### CODE REVIEW

**Comment by ErikAtApex** [comment]
I am not very experienced with bloom. Should the `performance_test/doc/version` entry also be updated to 2.3.0-1? I don't really understand why it is still 1.2.1-1.

**Comment by clalancette** [comment]
> I am not very experienced with bloom. Should the `performance_test/doc/version` entry also be updated to 2.3.0-1? I don't really understand why it is still 1.2.1-1.

In almost all circumstances, the `doc` branch should match the `source` branch (there are cases where it makes sense for them to be different, but they are fairly uncommon).  So I'd update it to be `master` in this case.

**Comment by ErikAtApex** [comment]
Thanks @clalancette . I changed it to `master`, and I'll do the same on the other two MRs.

**Comment by audrow** [comment]
You might not have access, since you're not a maintainer. I reran jobs.

**Comment by audrow** [comment]
It looks like we're still getting CI errors:

```
```

**Comment by ErikAtApex** [comment]
Thanks @audrow . Why would we get that CI error on this MR only, and not the other two? They're all pointing to the same tag, and package.xml does exist:

https://gitlab.com/ApexAI/performance_test/-/blob/master/performance_test/package.xml?ref_type=heads

**Comment by audrow** [comment]
I am not sure 🤔

**Comment by ErikAtApex** [comment]
@audrow Let's try to isolate it, I suppose. I'll revert the rolling commit, and open a new MR for it. Maybe the humble will pass and rolling will fail, or maybe they will pass independently :shrug:

**Comment by ErikAtApex** [comment]
@audrow the new MR has the same problem, but at least this MR is now green.

**Pull request merged**
