### PR TITLE
relocate docs for utexas-art repository

### PR DESCRIPTION
**Pull request by jack-oquin**
The sources moved from googlecode to github.

### CODE REVIEW

**Comment by wjwwood** [comment]
This will not cause the documentation to be rebuilt, but at least it's updated in our records.

**Comment by jack-oquin** [comment]
Is there no longer any way to get the docs rebuilt?

**Comment by dirk-thomas** [comment]
No, the build farm only operates on the current distros. The jobs for EOLed distros are being removed shortly after announcing the EOL.

**Comment by wjwwood** [comment]
You can build them manually.

**Comment by jack-oquin** [comment]
The last actual release of these packages was Fuerte. They are no longer maintained, and were never converted to catkin. 

Since there has recently been some interest in them, I was hoping to get the docs working again.

Is it possible to build docs for rosbuild packages on Indigo?

**Comment by dirk-thomas** [comment]
No, the last distribution which supported rosbuild documentation was Hydro: http://www.ros.org/reps/rep-0003.html#indigo-igloo-may-2014

**Comment by wjwwood** [comment]
The fuerte documentation still exists: http://docs.ros.org/fuerte/api/art_common/html/index.html

**Comment by jack-oquin** [comment]
Yes, it does. 

The problem may be less pervasive than I had initially thought. The main difficulty I've noticed (so far) is that wiki references like ``<<MsgLink(art_msgs/BrakeCommand)>>`` are not getting resolved correctly. The message pages actually still exist, but the references don't work any more.

See: http://wiki.ros.org/art_msgs

Is this just a bug in the ``MsgLink`` macro? The macro links to:

 * http://docs.ros.org/api/art_msgs/html/msg/BrakeCommand.html

The actual page is here:

 * http://docs.ros.org/groovy/api/art_msgs/html/msg/BrakeCommand.html

Should I open a roswiki issue for this?

**Comment by wjwwood** [comment]
https://github.com/ros-infrastructure/roswiki/issues/137

**Pull request merged**
