### PR TITLE
add pyqrcode from pip

### PR DESCRIPTION
**Pull request by fmessmer**
as available here: https://pypi.org/project/PyQRCode/

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Is this the same package as https://packages.ubuntu.com/bionic/python-pyqrcode ?

If so please use the apt version rather than pip for the disctributions where it's available

**Comment by ipa-fxm** [comment]
I also added the packages for
arch: https://www.archlinux.org/packages/?sort=&q=qrcode&maintainer=&flagged=
debian: https://packages.debian.org/search?suite=default&section=all&arch=any&lang=de&searchon=names&keywords=python-qrcode
gentoo: https://packages.gentoo.org/packages/dev-python/pyqrcode

**Comment by mikaelarguedas** [comment]
@ipa-fxm thanks for iterating.
Please see review of https://github.com/ros/rosdistro/pull/17950 for details about:
- how to add keys in a future proof way
- not adding entries for EOL distros
- providing pip keys for debian distributions that don't have the package

**Comment by ipa-fxm** [comment]
I hope everything looks good now

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @ipa-fxm for iterating :+1:

**Pull request merged**
