### PR TITLE
feat: add source entry for ecal

### PR DESCRIPTION
**Pull request by wep21**
Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ecal

# The source is here:

https://github.com/eclipse-ecal/ecal.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by wep21** [comment]
@FlorianReimold Is it okay to add ecal into rosdistro for eclipse ecal team?

**Comment by sloretz** [comment]
[Holding for Iron sync](https://discourse.ros.org/t/preparing-for-iron-sync-2023-08-11/)

**Comment by FlorianReimold** [comment]
> @FlorianReimold Is it okay to add ecal into rosdistro for eclipse ecal team?

Sure, go for it! Thanks for tagging me in this issue!

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/eclipse-ecal/ecal/blob/master/LICENSE.txt
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
  - [x] ecal: https://github.com/eclipse-ecal/ecal/blob/master/package.xml#L8
- [x] Public source repo: https://github.com/eclipse-ecal/ecal/blob/master/
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] ecal

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
