### PR TITLE
Python3 version of pydot

### PR DESCRIPTION
**Pull request by stonier**
Wondering if '*_python3' works and is a better solution?

### CODE REVIEW

**Comment by stonier** [comment]
Ok, so I tried to do some validation here and ended up yak shaving. I've got a python3 version of rosdep now pointed at `python.yaml` of a local clone before the default version and `ROSDISTRO_INDEX_URL` discovering the bionic bouncy packages. 

However, for the life of me, I cannot work out how to get it to resolve to the `bionic_python3` versions of anything. It doesn't use `ROS_PYTHON_VERSION` and I've crawled the rosdep sources and there doesn't seem to be any redirection of this sort happening at all. The only way I can get it to trigger is if I call `rosdep --os ubuntu:bionic_python3`.

This is all in the name of getting the rosdeps lined up so I can bloom a python package for bouncy. I may be entering the fray too early?

**Comment by nuclearsandwich** [comment]
> This is all in the name of getting the rosdeps lined up so I can bloom a python package for bouncy. I may be entering the fray too early?

I'd recommend adding a new key `python3-pydot`. For most existing ROS 2 packages we're creating separate python3-LIBNAME keys and using the explicitly python3 keys for ROS 2. The `_python3` distribution codenames were part of an python3 compatibility effort. To use them requires the passing of a custom distribution name when running rosdep (e.g. `rosdep resolve --os=ubuntu:xenial_python3 ...`). To the best of my knowledge there's no settled discussion on having rosdep choose an appropriate python version for a package so the two separate keys approach will be recommended for Bouncy and Crystal.

There's more ongoing discussions in https://github.com/ros2/design/pull/139, https://github.com/ros-infrastructure/rosdep/pull/607, https://github.com/ros-infrastructure/rep/pull/149

**Comment by stonier** [comment]
Updated with the new key `python3-pydot`. I'll keep an eye on how things progress there.

**Comment by clalancette** [comment]
Hm, weird.  Let me close and reopen to see if this was a temporary Travis thing.

**Comment by nuclearsandwich** [comment]
I've added keys for Archlinux and Gentoo which aren't required but are nice to have.

Gentoo: https://packages.gentoo.org/packages/dev-python/pydot
Archlinux: https://www.archlinux.org/packages/community/any/python-pydot/

pydot does not appear to be packaged for Fedora or Alpine Linux at this time.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
