### PR TITLE
Condense python-imaging rules for Fedora

### PR DESCRIPTION
**Pull request by cottsay**
The last differing rule was for Fedora 18 (spherical), which went EOL in early 2014.

The same package provides both subpackages referenced here:
https://apps.fedoraproject.org/packages/python-pillow

### CODE REVIEW

**Comment by cottsay** [comment]
I believe that this check is failing because of our dear friend `schrödinger’s`. Fortunately, this change removes it.

**Comment by clalancette** [comment]
Wasn't that problem fixed by https://github.com/ros/rosdistro/pull/6989 ?  Did we regress somehow?

**Comment by cottsay** [comment]
I'm fairly sure this was regressed by #18374.

**Comment by clalancette** [comment]
> I'm fairly sure this was regressed by #18374.

Right.  So the question essentially boils down to whether we care to keep the tests working with Python 2.  If we do, then we should probably fix the regression.  If we don't, then we should probably disable the Python 2 jobs in Travis.  Thoughts?

**Comment by nuclearsandwich** [comment]
> So the question essentially boils down to whether we care to keep the tests working with Python 2.

:+1: retiring the python2 test runs. We have other parts of our infrastructure that are python3-required at this point and I don't see a strong value in running these tests on both.

**Comment by cottsay** [comment]
So I dug into this, and the regression was also caused by #6741. According to the documentation [1], the `cStringIO` implementation "is not able to accept Unicode strings that cannot be encoded as plain ASCII strings."

The reason we're even using `cStringIO` appears to trace back to here: http://wiki.ros.org/python_2_and_3_compatible_code#StringIO. I tried simply switching to `io.StringIO`, and everything worked fine.

I have no preference as to whether or not we run tests on Python 2.

[1] https://docs.python.org/2/library/stringio.html#cStringIO.StringIO

**Comment by nuclearsandwich** [comment]
> I tried simply switching to `io.StringIO`, and everything worked fine.

I say PR the fix and that will unblock the issue. If I'm feeling sinister I'll open a separate PR to turn off the python2 testing.

**Comment by cottsay** [comment]
Done. See #20304.

**Pull request merged**
