### PR TITLE
Added python-redis for 14.10 -> 16.10

### PR DESCRIPTION
**Pull request by josephduchesne**
Updated rosdep python package list for ubuntu 14.10 through 16.10 for the python-redis package.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@josephduchesne Is it possible to add the entry for zesty (17.04) as well ?

**Review by mikaelarguedas — APPROVED** [review]
thanks @josephduchesne for the quick iteration

**Comment by dirk-thomas** [comment]
Since all the Ubuntu entries are the same it would be easier to just fold it into `ubuntu: [python-redis]` to avoid any future work on this.

**Comment by dirk-thomas** [comment]
Thank you for iterating on this.

**Pull request merged**
