### PR TITLE
use protobuf9 on jessie and sid

### PR DESCRIPTION
**Pull request by dirk-thomas**
@vrabaud Is this what you want?

### CODE REVIEW

**Comment by jacquelinekay** [comment]
Again we make the same pull request, except I forgot about squeeze (#11112). I think this will fix the failing vision_opencv jobs. I have no idea if opencv3 is still API compatible with protobuf9 or if it matters, but that's Vincent's problem :P

+1

**Comment by dirk-thomas** [comment]
Looks like @vrabaud asked us both for the same thing...

**Comment by jacquelinekay** [comment]
Dirk asked me to look at existing packages that depend on protobuf. I believe opencv3 is the only ros package currently released into Kinetic with a dependency on protobuf. Using the DependencyWalker API:

```
>>> dependency_walker.get_recursive_depends_on("protobuf", ['build', 'run', 'buildtool'])
set(['image_geometry', 'imu_tools', 'image_proc', 'rviz', 'image_view', 'cv_bridge', 'image_rotate', 'image_pipeline', 'rviz_imu_plugin', 'opencv3', 'jsk_common_msgs', 'posedetection_msgs', 'stereo_image_proc', 'depth_image_proc', 'camera_calibration', 'vision_opencv'])
>>> dependency_walker.get_depends_on("protobuf", 'run')
set(['opencv3'])
>>> dependency_walker.get_depends_on("protobuf", 'build')
set([])
```

so this won't affect anyone's currently released packages in Kinetic besides Vincent.

**Comment by tfoote** [comment]
Links to upstream packages from @jacquelinekay #11112 

https://packages.debian.org/jessie/libprotobuf9
https://packages.debian.org/sid/libprotobuf9
https://packages.debian.org/wheezy/libprotobuf7

**Comment by vrabaud** [comment]
thx guys, let's go for an "I just woke up" release.

**Pull request merged**
