### PR TITLE
DepthAI-ROS

### PR DESCRIPTION
**Pull request by saching13**
# Please Add This Package to be indexed in the rosdistro.

Kinetic  
Melodic 
Noetic

# The source is here: 
https://github.com/luxonis/depthai-ros

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by ahcorde — DISMISSED** [review]
Hi @saching13, 

This is not the way to include a new package in the rosdistro repository. Please read [how to bloom a new package for the first time](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)

**Comment by saching13** [comment]
> Hi @saching13,
> 
> This is not the way to include a new package in the rosdistro repository. Please read [how to bloom a new package for the first time](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)

Ah. got it. 
I was following this. [http://wiki.ros.org/ROS/ReleasingAPackage](http://wiki.ros.org/ROS/ReleasingAPackage) which made me think I need to index it, do pre-release before releasing.

**Comment by cottsay** [comment]
I think adding only source and doc stanzas without a release stanza is OK - it adds the packages to the index and enables consumption via `rosinstall_generator`.

That said, Kinetic is EOL so we're no longer accepting changes to that distro.

**Comment by saching13** [comment]
> I think adding only source and doc stanzas without a release stanza is OK - it adds the packages to the index and enables consumption via `rosinstall_generator`.
> 
> That said, Kinetic is EOL so we're no longer accepting changes to that distro.

Ah got it. Will remove from Kinetic. Thanks

**Review by cottsay — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
