### PR TITLE
Adding ethercat_grant

### PR DESCRIPTION
**Pull request by maxzieba**
Added ethercat_grant to noetic distribution list

### CODE REVIEW

**Comment by maxzieba** [comment]
hey, can this be merged?

**Comment by nuclearsandwich** [comment]
@maxzieba since this pull request was not created with bloom-release it is missing some information that we rely on to review.

My suggestion would be to create an new pull request with bloom-release. You can do this by re-running your bloom-release command with the `--pull-request-only` flag so that all the usual information is there.

**Comment by maxzieba** [comment]
Done, thanks. https://github.com/ros/rosdistro/pull/28668

**Comment by jacobperron** [comment]
Closing in favor of https://github.com/ros/rosdistro/pull/28668

**Pull request closed without merging**
