### PR TITLE
Add python-pyaudio-pip

### PR DESCRIPTION
**Pull request by thomasbi1**
https://pypi.python.org/pypi/PyAudio

This installs newer versions of PyAudio than with apt.

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by tfoote** [comment]
Since there's already a version packaged upstream we generally prefer not to overlay pip versions as they will effect and override any other version installed on the system. This can relatively easily break any other package that expects the system version that they were packaged against, and can end up getting out of date since the pip version is not tracked by apt and will not auto update. 

Can you explain your reasoning for needing a new package. I only see bugfixes in the recent changelog. https://people.csail.mit.edu/hubert/pyaudio/

**Comment by thomasbi1** [comment]
Apt installs pyAudio v. 0.2.8 which has bugs relating "overflow error handling" which are fixed starting from v. 0.2.9.

A ROS package I am currently developing is dependant on these bugs being fixed, or else it's core cannot run properly.

**Comment by thomasbi1** [comment]
@tfoote Could this potentially be merged, or do you prefer not to, due to your mentioned reasons?

**Comment by tfoote** [comment]
I'd strongly prefer not to diverge from the upstream packaged version. If it's just patch fixes those should be acceptable for release into the debian packages.

**Comment by dirk-thomas** [comment]
I will close this based on the previous feedback.

**Pull request closed without merging**
