### PR TITLE
adding ira_laser_tools

### PR DESCRIPTION
**Pull request by pietrocolombo**
refer #18409

### CODE REVIEW

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by mikaelarguedas** [comment]
@pietrocolombo This package [fails to build](http://build.ros.org/view/Lbin_ds_dS64/job/Lbin_ds_dS64__ira_laser_tools__debian_stretch_amd64__binary/10) on Debian Stretch, This PR should fix it https://github.com/iralabdisco/ira_laser_tools/pull/11 (you will need to release a new version once the PR merged).

Can you please add yourself as a maintainer of this package by adding a maintainer tag at https://github.com/iralabdisco/ira_laser_tools/blob/e9e3913a597bc75b0f316fd2f84614149db0a182/package.xml#L7. This way you will receive the emails the buildfarm sends when packages fail to build. Thanks!

**Comment by pietrocolombo** [comment]
ok I do it

**Comment by pietrocolombo** [comment]
I release a new version for fixing the problem
#18966 
#18965 

now is ok?

**Comment by mikaelarguedas** [comment]
@pietrocolombo Yes it built on all platforms :tada: and was part of the last [Lunar sync](https://discourse.ros.org/t/new-packages-lunar-2018-08-28/5887)
Thanks!

**Pull request merged**
