### PR TITLE
Update wxwidgets key.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Since all supported Debian and Ubuntu distributions now provide this key
the distribution version/codename can be elided.

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
That's a weird rename but it appears to be on all platforms. 

Debian: https://packages.debian.org/buster/libwxgtk3.0-gtk3-dev
Ubuntu: https://packages.ubuntu.com/bionic/libwxgtk3.0-gtk3-dev

But digging in a little deeper the two ubuntu packages on bionic don't provide the same files: 

https://packages.ubuntu.com/bionic/amd64/libwxgtk3.0-dev/filelist
vs https://packages.ubuntu.com/bionic/amd64/libwxgtk3.0-gtk3-dev/filelist which clearly is necessary to avoid installation collisions. But what is the difference between /usr/lib/x86_64-linux-gnu/libwx_gtk2u_adv-3.0.so and /usr/lib/x86_64-linux-gnu/libwx_gtk3u_adv-3.0.so


I suggest that we not fully collapse these rules but keep the new rule as a wildcard and make a special rule for existing platforms (bionic, stretch, and buster) with the existing keys. It's a little less cleanup, but will be much less likely to break someone.

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
We had an odd CI failure on this one failing in the setup stage: https://github.com/ros/rosdistro/runs/4784291694?check_suite_focus=true 

```
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_070005fe-2f62-415f-bc45-1589bccccde5/7c1f40d3-56ba-431c-b217-aa9c0dd95438.tar.gz. return code: 2.
```

Retriggering it now fails for two parallel issues

```
Error: Package 'gurumdds-2.6' could not be found for ubuntu jammy on amd64
Package 'gurumdds-2.7' for ubuntu bionic on amd64 was found: http://repos.ros.org/repos/ros_bootstrap/pool/main/g/gurumdds-2.7/gurumdds-2.7.3017-bionic-x86_64.deb
Package 'gurumdds-2.7' for ubuntu focal on amd64 was found: http://repos.ros.org/repos/ros_bootstrap/pool/main/g/gurumdds-2.7/gurumdds-2.7.3017-focal-x86_64.deb

Error: Package 'gurumdds-2.7' could not be found for ubuntu jammy on amd64
```

And soccer_visualization is out of date
```
======================================================================
FAIL: test_function (test.test_url_validity.TestUrlValidity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/rosdistro/rosdistro/test/test_url_validity.py", line 380, in test_function
    self.assertFalse(detected_errors)
AssertionError: ["In file '''/home/runner/work/rosdistro/rosdistro/galactic/distribution.yaml''': Could not validate source entry for repo soccer_visualization with error [[[Could not validate repository with url https://github.com/ijnek/soccer_visualization.git and version main from entry at line 4525. Error reason: No branch found matching main]]]", "In file '''/home/runner/work/rosdistro/rosdistro/galactic/distribution.yaml''': Could not validate doc entry for repo soccer_visualization with error [[[Could not validate repository with url https://github.com/ijnek/soccer_visualization.git and 
```

But that's fixed in main: https://github.com/ros/rosdistro/pull/31739 
Ahh this is testing those because this one is different from main, in the removal way. It needs to be rebased.

**Comment by cottsay** [comment]
Probably related to https://github.com/ros/rosdistro/issues/31439#issuecomment-994093767

Rebase or merge from master should help.

**Comment by nuclearsandwich** [comment]
> Rebase or merge from master should help.

Thanks and welcome back but see you next week!

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
