### PR TITLE
release rplidar_ros 1.7.0 on indigo

### PR DESCRIPTION
**Pull request by kintzhao**

### CODE REVIEW

**Comment by kintzhao** [comment]
bloom-release rplidar_ros --track indigo --rosdistro indigo --edit
`<== Pushed tags successfully
==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml'
Failed to open pull request: URLError - <urlopen error <urlopen error [Errno -2] Name or service not known> (https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml)>
`
how can i reopen the PR by command when bloom-release error like up? 
I have change the message:
Upstream Repository URI:
['https://github.com/robopeak/rplidar_ros.git']: https://github.com/Slamtec/rplidar_ros.git
Release Repository Push URL:
  ['https://github.com/kintzhao/rplidar_ros-release.git']: https://github.com/Slamtec/rplidar_ros-release.git

so i fork the repo and add commit ,then pull request..

**Comment by mikaelarguedas** [comment]
> how can i reopen the PR by command when bloom-release error like up?

You can use the `-p` flag to just open the PR.
```
$ bloom-release --help
...
  --pull-request-only, -p
                        skips the release actions and only tries to open a
                        pull request
```

**Comment by kintzhao** [comment]
==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml'
Failed to open pull request: URLError - <urlopen error <urlopen error [Errno -2] Name or service not known> (https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml)>
kint@ubuntu:~/rplidar_release/src/rplidar_ros$ bloom-release -p  -r indigo -t indigo rplidar_ros --override-release-repository-url https://github.com/Slamtec/rplidar_ros-release.git
ROS Distro index file associate with commit '3082d26b48b26e9059a2ff2500af6de0bd621b87'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/index.yaml'
Overriding the release repository url, using 'https://github.com/Slamtec/rplidar_ros-release.git'
==> Fetching 'rplidar_ros' repository from 'https://github.com/Slamtec/rplidar_ros-release.git'
Cloning into '/tmp/tmp2wpbbu'...
remote: Counting objects: 1054, done.
remote: Compressing objects: 100% (561/561), done.
remote: Total 1054 (delta 474), reused 1032 (delta 452), pack-reused 0
Receiving objects: 100% (1054/1054), 296.50 KiB | 245.00 KiB/s, done.
Resolving deltas: 100% (474/474), done.
Checking connectivity... done.
==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml'
Unified diff for the ROS distro file located at '/tmp/tmpkXGapX/rplidar_ros-1.7.0-0.patch':
--- 3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml
+++ 3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml
@@ -13228,8 +13228,8 @@
     release:
       tags:
         release: release/indigo/{package}/{version}
-      url: https://github.com/kintzhao/rplidar_ros-release.git
-      version: 1.5.7-0
+      url: https://github.com/Slamtec/rplidar_ros-release.git
+      version: 1.7.0-0
     source:
       type: git
       url: https://github.com/robopeak/rplidar_ros.git

Looks like bloom doesn't have an oauth token for you yet.
Therefore bloom will require your GitHub username and password just this once.
With your GitHub username and password bloom will create an oauth token on your behalf.
The token will be stored in `~/.config/bloom`.
You can delete the token from that file to have a new token generated.
Guard this token like a password, because it allows someone/something to act on your behalf.
If you need to unauthorize it, remove it from the 'Applications' menu in your GitHub account page.

Would you like to create an OAuth token now [Y/n]? n
The release of your packages was successful, but the pull request failed.
Please manually open a pull request by editing the file here: 'https://raw.githubusercontent.com/ros/rosdistro/3082d26b48b26e9059a2ff2500af6de0bd621b87/indigo/distribution.yaml'
<== No pull request opened.


bloom-release -p  -r ,  but the source git is robopeak/rplidar_ros not slamtec/rplidar_ros

     source:
       type: git
       url: https://github.com/robopeak/rplidar_ros.git

**Comment by kintzhao** [comment]
Is the PR  the same as  by command?

**Comment by kintzhao** [comment]
ok , I close it and retry by command

**Pull request closed without merging**
