### PR TITLE
added bionic to python list of python-pymongo

### PR DESCRIPTION
**Pull request by frederico-klein**
Single line added to support bionic.

### CODE REVIEW

**Comment by frederico-klein** [comment]
added mongodb-dev as well

**Review by tfoote — CHANGES_REQUESTED** [review]
Please link to the packages that you're adding and since they're different packages demonstrate how they're providing the same functionality.

Related it would be good to fill in the other versions inbetween xenial and bionic too.

**Comment by frederico-klein** [comment]
Actually I suppose it adds a bit more functionality because I am also including https://packages.debian.org/stretch/libmongoclient0 which is the  mongo-cxx-driver-legacy (see https://github.com/ros-planning/warehouse_ros_mongo ) 
A bit of googling showed me that this is only available from bionic onwards https://packages.ubuntu.com/bionic/libmongoclient-dev (bionic, cosmic, disco), so I suppose this only makes things easier for newer distros. 
For yakkety, zesty and artful the lines should probably be the same as xenial, but I haven't tested it

**Comment by frederico-klein** [comment]
Oh, https://packages.ubuntu.com/bionic/libdevel/python-pymongo seems it would be alright, but mongodb-dev mongodb-dev probably would not be so straightforward...

**Comment by tfoote** [comment]
My point is that 
https://packages.ubuntu.com/bionic/libmongoclient-dev
and 
https://packages.ubuntu.com/bionic/libmongo-client-dev

Appear to be completely different projects thus a package that depends on one will not be expected to compile or work against the other.

I see that https://github.com/algernon/libmongo-client is obsolete and likely should be transitioned off of, but the new replacement that's not a drop in replacement should be a new key not an evolution of the current key. Especially since the current key is still valid and is released as far forward as cosmic https://packages.ubuntu.com/cosmic/libmongo-client-dev

**Comment by tfoote** [comment]
Since this is a new/different package we can add it but we should use a different key to make sure that people don't expect the same content. I'm going to close this in it's current form. Please update the branch and we can reopen this or create a new PR.

**Pull request closed without merging**
