### PR TITLE
add python-defusedxml

### PR DESCRIPTION
**Pull request by codebot**
Tested on Ubuntu. I attempted to chase it down on other distros.

### CODE REVIEW

**Comment by tfoote** [comment]
+1 packages found at: 

ubuntu: http://packages.ubuntu.com/search?keywords=python-defusedxml
debian: https://packages.debian.org/search?keywords=python-defusedxml
arch: https://www.archlinux.org/packages/extra/any/python-defusedxml/
fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/python-defusedxml/
gentoo: https://packages.gentoo.org/packages/dev-python/defusedxml

**Comment by tfoote** [comment]
Note this is not available on Saucy so it cannot go into indigo until after the next sync when saucy is disabled.

**Comment by wjwwood** [comment]
You need OS X (pip).

**Comment by tfoote** [comment]
It's fine to add the rules at any time. We could do it for Kinetic only but this seems like an improvement that could be considered for backporting.

**Comment by dirk-thomas** [comment]
The package is available in *Saucy*.

**Pull request merged**
