### PR TITLE
add joystick rule for fedora 25 and 26

### PR DESCRIPTION
**Pull request by mikaelarguedas**
https://admin.fedoraproject.org/pkgdb/package/rpms/linuxconsoletools/

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
retriggering travis...

**Comment by dirk-thomas** [comment]
Should this rule be collapsed or are there any Fedora distros before 21?

**Comment by tfoote** [comment]
I see builds back to fedora 18 on the above link. We can probably collapse this.

**Comment by mikaelarguedas** [comment]
Yeah I was wondering the same thing. I didn't want to remove existing rules so I defaulted to adding them. But I don't think many people did or are targetting beefy (fedora 17) so I can collapse them if we agree on removing it

**Comment by tfoote** [comment]
+1 for collapsing, It's been EOL since January 2014 and is the 8th oldest EOL fedora release (24 is already EOL). Fedora moves quickly.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
