### PR TITLE
picovoice-ros 0.0.2-1

### PR DESCRIPTION
**Pull request by reinzor**
## Picovoice ROS wrappers

- Rhino speech to intent node
- Porcupine speech to keyword node (hot word detection)

upstream repository: https://github.com/reinzor/picovoice_ros.git
release repository: https://github.com/reinzor/picovoice_ros-release.git

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please add a LICENSE file in the root of your repository for clarity on the licensing.

**Comment by reinzor** [comment]
Added `LICENSE`

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
Thanks for the followup.

**Comment by reinzor** [comment]
Thanks @tfoote . Not sure whether I should ask this here but it seems that the `arm` builds are failing:

AMD64:
- https://build.ros.org/job/Nbin_uF64__picovoice_driver__ubuntu_focal_amd64__binary/
- https://build.ros.org/job/Nbin_db_dB64__picovoice_driver__debian_buster_amd64__binary/

ARM:
- https://build.ros.org/job/Nbin_ufhf_uFhf__picovoice_driver__ubuntu_focal_armhf__binary/
- https://build.ros.org/job/Nbin_ufv8_uFv8__picovoice_driver__ubuntu_focal_arm64__binary/
- https://build.ros.org/job/Nbin_dbv8_dBv8__picovoice_driver__debian_buster_arm64__binary/

Would it be possible to build only for AMD64 or should I work on ARM support?

**Comment by reinzor** [comment]
Added support for arm here https://github.com/ros/rosdistro/pull/29016

**Comment by reinzor** [comment]
@tfoote , added support for arm in #29016 but the `armhf` build still seems to fail. I'm pointing to a specific `picovoice` library for the desired architecture using `${CMAKE_HOST_SYSTEM_PROCESSOR}` but for the `armhf` build it holds a `aarch64` value. Any ideas how I can distinguish the `arm64` build from the `armhf` build. Or any example projects that are already doing something like this? I'm kinda out of my comfort zone here. Thanks :)

**Comment by reinzor** [comment]
In https://github.com/ros/rosdistro/pull/29090, I tried to use the `${CMAKE_SYSTEM_PROCESSOR}` variable but apparently still returns `aarch64` for the `armhf` build. Could someone point me in the right direction here? I'm a little bit in the dark here since I don't know the specifics of the build farm. @cottsay @tfoote @clalancette

**Comment by tfoote** [comment]
I don't have a good suggestion. The dpkg host is armhf in your builds https://build.ros.org/job/Nbin_ufhf_uFhf__picovoice_driver__ubuntu_focal_armhf__binary/47/console

```
23:15:22 # BEGIN SUBSECTION: build binarydeb
23:15:22 Package 'ros-noetic-picovoice-driver' version: 0.0.4-1focal.20210512.061352
23:15:22 Invoking 'apt-src build ros-noetic-picovoice-driver' in '/tmp/binarydeb/ros-noetic-picovoice-driver-0.0.4'
23:15:24 I: Building in /tmp/binarydeb/ros-noetic-picovoice-driver-0.0.4 ..
23:15:25 dpkg-buildpackage: info: source package ros-noetic-picovoice-driver
23:15:25 dpkg-buildpackage: info: source version 0.0.4-1focal.20210512.061352
23:15:25 dpkg-buildpackage: info: source distribution focal
23:15:25 dpkg-buildpackage: info: source changed by Rein Appeldoorn <reinzor@gmail.com>
23:15:25  dpkg-source --before-build .
23:15:25 dpkg-buildpackage: info: host architecture armhf
23:15:25 dpkg-source: info: using options from ros-noetic-picovoice-driver-0.0.4/debian/source/options: --auto-commit
23:15:25  fakeroot debian/rules clean
```

At that point this is basically stock debian build pipeline. We don't do much with prebuilt binaries. 

I'll note that in the CMAKE world HOST is likely interpreted in the cross compiling sense which might not match the dpkg host.

**Pull request merged**
