### PR TITLE
add pyxhook and sphinxcontrib-bibtex for osx as well

### PR DESCRIPTION
**Pull request by mikaelarguedas**
follow-up of #16288 and #16305

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
+1 for adding them, but note that it's not strictly required unless people using the key want to support macOS.

**Comment by mikaelarguedas** [comment]
> but note that it's not strictly required unless people using the key want to support macOS.

:+1: I just figured that it's easy enough when it's pip to just add the entry for the 4 distros to avoid needing a follow up PR to add them when someone face the issue. Is it preferred to make this opt-in and for mac users to submit follow-up PRs if they want to ?

**Comment by wjwwood** [comment]
I would say opt-in is fine. If we're going to use it in desktop-full then I'd say we should require it for mac, otherwise opt-in is fine imo.

**Comment by mikaelarguedas** [comment]
Sounds good, thanks for clarifying

**Pull request merged**
