### PR TITLE
Add entry of python-pkg-resources to rosdep/python.yaml

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/ros/catkin/pull/798

### CODE REVIEW

**Review by mikaelarguedas — APPROVED** [review]
lgtm, @dirk-thomas to confirm given the referenced PR

**Comment by dirk-thomas** [comment]
I don't think this is required for the PR since `pkg-resources` is afaik always a dependency of `setuptools` but having this rosdep key is ok.

**Comment by wkentaro** [comment]
> I don't think this is required for the PR since pkg-resources is afaik always a dependency of setuptools but having this rosdep key is ok.

Yeah. But should I add it as a dependency for safety?

**Comment by dirk-thomas** [comment]
> should I add it as a dependency for safety?

If the code imports the package it should indeed be listed as a dependency.

**Pull request merged**
