### PR TITLE
[dep] Add devscripts.

### PR DESCRIPTION
**Pull request by 130s**
- debian https://packages.debian.org/sid/devscripts
- fedora https://fedora.pkgs.org/27/fedora-x86_64/devscripts-2.17.10-1.fc27.x86_64.rpm.html
- gentoo https://packages.gentoo.org/packages/dev-util/checkbashisms
- Ubuntu https://packages.ubuntu.com/search?keywords=devscripts

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@130s thanks for the links.

This PR looks good to me once the alphabetical order is fixed

**Comment by 130s** [comment]
Thanks. CI passed.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by mikaelarguedas** [comment]
@ros/rosdistro-maintainers can I get a second review on this please?

**Pull request merged**
