### PR TITLE
Add andino to humble index.

### PR DESCRIPTION
**Pull request by francocipollone**
# Please Add This Package to be indexed in the rosdistro.

humble

# The source is here:

https://github.com/Ekumen-OS/andino

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by sloretz — APPROVED** [review]
LGTM. I'd recommend removing the top level `LICENSE` file since you already have per-package license files. I checked they're all the same with `sha256sum`, though I noticed the top level file is copyright 2023 while the rest have the copyright date as 2022.

---

- [x] At least one of the following must be present
  - [X] Top level license file: 
  - [X] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>andino_description</name>
  <name>andino_bringup</name>
  <name>andino_firmware</name>
  <name>andino_navigation</name>
  <name>andino_control</name>
  <name>andino_hardware</name>
  <name>andino_slam</name>
  <name>andino_base</name>
  <name>andino_gz_classic</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license" "{}" "+"
./andino/andino_description/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_bringup/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_firmware/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_navigation/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_control/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_hardware/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_slam/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_base/package.xml:  <license file="LICENSE">BSD Clause 3</license>
./andino/andino_gz_classic/package.xml:  <license file="LICENSE">BSD Clause 3</license>
```
</details>

**Comment by francocipollone** [comment]
> LGTM. I'd recommend removing the top level `LICENSE` file since you already have per-package license files. I checked they're all the same with `sha256sum`, though I noticed the top level file is copyright 2023 while the rest have the copyright date as 2022.
> 
> * [x]  At least one of the following must be present
>   
>   * [x]  Top level license file:
>   * [x]  Per package license files
> * [x]  License is [OSI-approved](https://opensource.org/licenses):
> * [x]  License correctly listed in package.xmls
> * [x]  Public source repo:
> * [x]  Source repository contains ROS packages
> * [x]  Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
> 
> Package name details
> License details

Thanks a lot! @sloretz !

**Comment by francocipollone** [comment]
Hey @sloretz , quick question if I may. I am trying to link the jenkins build to the Pull Request: Do you know if this invitation to the repo for the `ros-pull-request-builder` bot is automatically or manually accepted?
image
Thanks!

**Comment by sloretz** [comment]
@francocipollone Ah I don't know. I think I've only used the per-repo webhook for PR jobs . @tfoote or @nuclearsandwich do either of you know how @ros-pull-request-builder accepts invites?

**Comment by francocipollone** [comment]
> @francocipollone Ah I don't know. I think I've only used the per-repo webhook for PR jobs . @tfoote or @nuclearsandwich do either of you know how @ros-pull-request-builder accepts invites?

Oh thanks for forwarding the question :smiley: . In my case I am following the https://wiki.ros.org/buildfarm/Pull%20request%20testing instructions for the case I add the bot only to the repository.
I've already added the webhook that is required for triggering the events (and that's going well the PRs jobs are already triggered: See [jenkins](https://build.ros2.org/job/Hpr__andino__ubuntu_jammy_amd64/))

Checking out the logs I see this, I guess this is failing due to the bot doesn't have bits because it hasn't accepted the invite to the repo.
```
12:40:38 FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
12:40:38 org.kohsuke.github.GHFileNotFoundException: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
12:40:38 	at org.kohsuke.github.Requester.handleApiError(Requester.java:699)
12:40:38 	at org.kohsuke.github.Requester._to(Requester.java:306)
12:40:38 	at org.kohsuke.github.Requester.to(Requester.java:247)
```

**Comment by tfoote** [comment]
It's a manual triage process. I think that @nuclearsandwich or @clalancette are the ones who get the notifications or should know who does.

**Comment by clalancette** [comment]
> It's a manual triage process. I think that @nuclearsandwich or @clalancette are the ones who get the notifications or should know who does.

Ah, this should be @gbiggs .  Geoff, can you take a look and see if there is an invitation?

**Pull request merged**
