### PR TITLE
Feature/python scipy debian

### PR DESCRIPTION
**Pull request by RFRIEDM-Trimble**
This is to solve #33053 
Not sure if we also need to update the arm build; I don't have that hardware accessible.

### CODE REVIEW

**Review by methylDragon — APPROVED** [review]

**Review by sloretz — CHANGES_REQUESTED** [review]
Thanks for the PR! Please add a new key `python3-scipy` instead of modifying this one.

https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#python-3

**Comment by RFRIEDM-Trimble** [comment]
> Thanks for the PR! Please add a new key `python3-scipy` instead of modifying this one.
> 
> https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#python-3

Fix (I think). I don't see how to test this, and according to documentation, I need to add the ubuntu key, but I'm not sure how to go about testing it all; I don't have environment for every version of ubuntu. 
`When adding a new key, Ubuntu and Debian are required, Fedora, Gentoo, and openSUSE are encouraged if the package also exists on those Linux distributions.`

**Comment by RFRIEDM-Trimble** [comment]
> Thanks for the PR! Please add a new key `python3-scipy` instead of modifying this one.
> 
> https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#python-3

Fix (I think). I don't see how to test this, and according to documentation, I need to add the ubuntu key, but I'm not sure how to go about testing it all; I don't have environment for every version of ubuntu. 
`When adding a new key, Ubuntu and Debian are required, Fedora, Gentoo, and openSUSE are encouraged if the package also exists on those Linux distributions.`

**Comment by tfoote** [comment]
You don't need to test it on all platforms if you can link to it, like you have to the ubuntu platform for all supported versions. Note that with the key rename it will need to be realphabetized.

**Comment by RFRIEDM-Trimble** [comment]
It's actually already in there as python3-scipy; just another 4000 lines down. My bad, totally missed it. 

Any reason there isn't a pre-commit hook set up to do the following?
```
Keep everything in alphabetical order for better merging.
No trailing whitespace.
No blank lines.
```

**Comment by tfoote** [comment]
Pre commit hooks have to be configured by the user. We can't automatically deploy them on a checkout. We just have the CI run them and document how to run the unit tests too which is also recommended for the user.

**Pull request closed without merging**
