### PR TITLE
Add python-plyfile

### PR DESCRIPTION
**Pull request by cglwn**
Package is only in PyPI. I am only using it to simplify dependency management and have no plans to make a release with it so it should be alright.

PyPI: https://pypi.python.org/pypi/plyfile

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Great, thanks for the link and the rationale!
A few comments based on the [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules):
- Please use the suffix `-pip` for packages available in pip only as per
- Use the smallest notation possible, for example
```
  ubuntu:
    pip:
      packages: [plyfile]
```
rather than listing each ubuntu distribution

**Comment by cglwn** [comment]
Thanks for the review. I've added the changes requested.

**Comment by mikaelarguedas** [comment]
@cglwn can you add the other platforms as well ? 
"Fedora and Gentoo have packaging jobs and should be filled in if they are available.
OSX is also nice to have."
Thanks!

**Review by mikaelarguedas — APPROVED** [review]
thanks @cglwn for iterating

**Comment by mikaelarguedas** [comment]
ready for 2nd review

**Pull request merged**
