### PR TITLE
naoqi_libqicore: 2.9.0-4 in 'melodic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by mbusy**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@Pandhariix FYI I opened https://github.com/ros-naoqi/libqicore-release/pull/2 to pass over maintainership.
After merge we'll need to run bloom/release again

**Comment by Pandhariix** [comment]
By the way, naoqi_libqicore depends on naoqi_libqi: should I wait for naoqi_libqi to be released at least once for melodic before running bloom/release again for naoqi_libqicore?

**Review by tfoote — CHANGES_REQUESTED** [review]
This needs a rebase due to inserting in the same place as libqi likely. Please request a rereview after you've resolved the conflict.

**Comment by Pandhariix** [comment]
Some updates were added to naoqi_libqicore, we'll need to make a new release anyway. I'm closing this PR, once naoqi_libqi is properly released for melodic, I'll open a new one for naoqi_libqicore

**Pull request closed without merging**
