### PR TITLE
Adding openexr to rosdep

### PR DESCRIPTION
**Pull request by SteveMacenski**

### CODE REVIEW

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
Can you please provide the links of the packages?
You can look at the [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) for more details.

I don't think these packages have the same name for Arch, Fedora and Gentoo.

If you want to provide the development version of the package, please add the suffix `-dev` to the key name.

On [Debian](https://packages.debian.org/stretch/libopenexr-dev) and [Ubuntu](https://packages.ubuntu.com/xenial/libopenexr-dev) `libopenexr-dev` already depends on `libopenexr22` so `libopenexr22` should not be listed

**Comment by SteveMacenski** [comment]
thanks for the info and help.

OpenEXR is helping with a new spatio-temporal voxel grid I've recently released and looking at to add the the ROS build farm. 

ubuntu: https://packages.ubuntu.com/trusty/libopenexr-dev
debian: https://packages.debian.org/stretch/libopenexr-dev

You're right, the names are inconsistent in a handful of other releases, hadn't checked I suspected Travis CI would check for me and when it went through I shrugged it off. 

Arch was verified as openexr. https://www.archlinux.org/packages/extra/x86_64/openexr/

I'll update to reflect those changes and removing gentoo and fedora.

**Comment by mikaelarguedas** [comment]
Gentoo `media-libs/openexr`: https://packages.gentoo.org/packages/media-libs/openexr
Fedora: `OpenEXR-devel`: https://rpmfind.net/linux/rpm2html/search.php?query=OpenEXR-devel

**Comment by SteveMacenski** [comment]
added

**Review by tfoote — APPROVED** [review]

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @SteveMacenski for iterating

**Pull request merged**
