### PR TITLE
octomap: 1.7.1-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by ahornung**
Increasing version of package(s) in repository `octomap` to `1.7.1-0`:
- upstream repository: https://github.com/OctoMap/octomap.git
- release repository: https://github.com/ros-gbp/octomap-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.5.21`
- previous version for package: `null`

### CODE REVIEW

**Comment by ahornung** [comment]
Should be only be merged after https://github.com/ros/rosdistro/pull/10878

**Comment by wjwwood** [comment]
@ahornung how did you run bloom before #10878 was merged?

**Comment by ahornung** [comment]
> how did you run bloom before #10878 was merged?

Locally pointed the rosdep source list to my fork!

**Comment by wjwwood** [comment]
Ok, that should work.

**Pull request merged**
