### PR TITLE
modify astra_camera astra_launch release url

### PR DESCRIPTION
**Pull request by ob-tim-liu**
modify astra_camera astra_launch release url

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please remove the `indigo/.distribution.yaml.swp` file. And it looks like the repository is there. I see a single branch relating to kinetic 0.2. However I don't see any of the expected 0.2.0 tags that I would expect for a release, nor the updates in the readme that bloom generates? Did you run bloom to generate the new release? http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Releasing_Your_Packages

**Comment by ob-tim-liu** [comment]
it's not first release,  because i can't modify the https://github.com/ros-drivers-gbp/astra_camera-release.git, i want to change the release repository url. 
i have provider the tag 2.0 --https://github.com/ob-tim-liu/astra_camera-release/tree/release/kinetic/astra_camera/0.2.0-0.
i do't know if it's right, maybe i should del the release repository, follow the Releasing a package for the first time , use bloom add release reposiotry url?

**Comment by tfoote** [comment]
Hi @ob-tim-liu You'll want to follow the procedures for a new version of the package: http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage 

Instead of manually creating that tag bloom will create that tag as well as the dozen or so other tags necessary for a successful build. If you want to switch the release repository you should use the `--override-release-repository-url` however since you're taking over ownership of this repository I've invited you to have access to the existing release repository. Once you accept that you should be able to run bloom without the override.

**Comment by ob-tim-liu** [comment]
@tfoote  sorry, To bloom release astra_launch, i need the permissions for https://github.com/ros-drivers-gbp/astra_launch-release too,  pls open access for me，thanks

**Comment by tfoote** [comment]
invited there too

**Pull request closed without merging**
