### PR TITLE
nixos: Add some missing packages

### PR DESCRIPTION
**Pull request by kjeremy**
Adds missing nixos keys for libxmlrpc-c++, pugixml-dev, spirv-headers and spirv-tools

## Links to Distribution Packages

- NixOS/nixpkgs: https://search.nixos.org/packages
  - https://search.nixos.org/packages?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=xmlrpc_c
  - https://search.nixos.org/packages?channel=21.05&show=pugixml&from=0&size=50&sort=relevance&type=packages&query=pugixml
  - https://search.nixos.org/packages?channel=21.05&show=spirv-headers&from=0&size=50&sort=relevance&type=packages&query=spirv-headers
  - https://search.nixos.org/packages?channel=21.05&show=spirv-headers&from=0&size=50&sort=relevance&type=packages&query=spirv-tools

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by ivanpauno** [comment]
please provide links to the packages being added, e.g.: https://search.nixos.org/packages?channel=21.05&show=xmlrpc_c&from=0&size=50&sort=relevance&type=packages&query=xmlrpc_c.

The pull request template has a section for that https://github.com/ros/rosdistro/blob/master/.github/pull_request_template.md#links-to-distribution-packages.
Thanks!

**Comment by kjeremy** [comment]
Hopefully that's what you are looking for.

**Review by ivanpauno — APPROVED** [review]

**Comment by ivanpauno** [comment]
> Hopefully that's what you are looking for.

Yes, thanks for adding that!

**Comment by ivanpauno** [comment]
@kjeremy could you update this branch (i.e. merge with `origin/master`)?

The nosetests are failing because of an unrelated reason (repository deleted branch after updating rosdep https://github.com/ros/rosdistro/pull/30609).

**Comment by kjeremy** [comment]
Why is this still failing?

**Comment by cottsay** [comment]
> Why is this still failing?

Now it's hitting #29964, which I'm hoping to resolve this week. The workaround is to merge the master branch back into your source branch. Normally I just do it for you, but you didn't enable maintainer pushes in this PR, so you'll need to do it yourself.

**Review by hidmic — APPROVED** [review]

**Comment by hidmic** [comment]
Patch LGTM and CI's green. Thanks for your contribution @kjeremy.

**Pull request merged**
