### PR TITLE
Adding pouco2000 to documentation index for distro

### PR DESCRIPTION
**Pull request by PouceHeure**
i'd like pouco2000 to be indexed and documented on ros.org.

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
A quick look at the repository had no license declaration or information. Similarly the package.xml files don't have any license or maintainer information. Please update the repository to have those.

There's a good list of licenses you can choose at: https://choosealicense.com/licenses/ We recommend the Apache 2.0 to be the default for ROS projects.

**Comment by PoussPouss** [comment]
Sorry, I forgot. Licenses and maintainer information have been added.

**Review by clalancette — APPROVED** [review]
Seems reasonable to me now, but I'll leave this open for @tfoote to re-review.

**Review by tfoote — APPROVED** [review]
Thanks for the prompt updates.

**Pull request merged**
