### PR TITLE
Updated package upstream sources for depthai 

### PR DESCRIPTION
**Pull request by saching13**
Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
   - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
Galactic is now End-of-Life, so we won't be taking new changes to it.  Please remove that change from this PR (which will also fix the failing CI).

**Comment by saching13** [comment]
Ah got it. Will do.

**Comment by saching13** [comment]
@clalancette any idea why CI still failing ?

**Comment by clalancette** [comment]
> @clalancette any idea why CI still failing ?

CI says: `RuntimeError: humble: missing package.xml file for package "depthai_ros_driver"`.

Indeed, if you look at https://github.com/luxonis/depthai-ros-release/blob/master/README.md , you can see that in the latest humble release, `depthai_ros_driver` is not listed there.  It looks like the bloom for this was not correct.  In particular, my guess is that this line is wrong: https://github.com/luxonis/depthai-ros-release/blob/51567a2d515ac3dbe87fb0bfc49b9e014a71623e/tracks.yaml#L69 .  You should probably change that to `humble`, and then do a new bloom release.

Given all of that, I'm going to close this one out.

**Comment by saching13** [comment]
> https://github.com/luxonis/depthai-ros-release/blob/master/README.md

@clalancette  Please correct me if I'm wrong here. 
The depthai_ros_driver  is the new package. and it gets listed there when I make a new release of it. But to make a release for it. Don't I need to add it to the distro yaml here first to be able to picked up in the build.ros.org ?

**Comment by clalancette** [comment]
> The depthai_ros_driver is the new package. and it gets listed there when I make a new release of it. But to make a release for it. Don't I need to add it to the distro yaml here first to be able to picked up in the build.ros.org ?

No, it is the other way around.  When you use `bloom-release`, it updates the release repository (in this case, https://github.com/luxonis/depthai-ros-release), and then opens a PR to rosdistro here.

**Pull request closed without merging**
