### PR TITLE
add rosdep for pigz (parallel gzip)

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@mikeferguson can you please update this PR to conform to our Contribution guidelines for rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions? Thanks.

**Comment by mikeferguson** [comment]
@nuclearsandwich - fixed

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich - fixed

Appreciate the added package. Can you also link to the packages added in the web registries for each distro. The second paragraph of the link above has examples.

**Comment by mikeferguson** [comment]
Links:

 * Ubuntu 16.04: https://packages.ubuntu.com/xenial/pigz
 * Ubuntu 18.04: https://packages.ubuntu.com/bionic/pigz
 * Ubuntu 20.04: https://packages.ubuntu.com/focal/pigz
 * Fedora: https://apps.fedoraproject.org/packages/pigz
 * Debian: https://packages.debian.org/buster/pigz
 * Gentoo: https://packages.gentoo.org/packages/app-arch/pigz

Use:

This is a parallel implementation of gzip and gunzip. It's just a utility that is helpful when downloading test data, etc.

**Review by nuclearsandwich — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
