### PR TITLE
Add ruby ronn

### PR DESCRIPTION
**Pull request by BMarchi**
debian: [https://packages.debian.org/stretch/ruby-ronn](https://packages.debian.org/stretch/ruby-ronn)
fedora: [https://apps.fedoraproject.org/packages/rubygem-ronn](https://apps.fedoraproject.org/packages/rubygem-ronn)
gentoo: [https://packages.gentoo.org/packages/app-text/ronn](https://packages.gentoo.org/packages/app-text/ronn)
ubuntu: [https://packages.ubuntu.com/disco/ruby-ronn](https://packages.ubuntu.com/disco/ruby-ronn)

### CODE REVIEW

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
Please review the [contribution guidelines for rosdep rules](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) and update your PR to conform with them.

**Comment by clalancette** [comment]
So it looks like ruby-ronn is only available in Ubuntu since Xenial: https://packages.ubuntu.com/search?keywords=ruby-ronn&searchon=names&suite=all&section=all .  @nuclearsandwich @tfoote I forget what our policy is about new rosdep keys for out-of-support distros.  Do we want to just use what's in this PR, or should we explicitly call out the distros since xenial as being supported?

**Comment by nuclearsandwich** [comment]
> I forget what our policy is about new rosdep keys for out-of-support distros. Do we want to just use what's in this PR, or should we explicitly call out the distros since xenial as being supported?

Since Xenial is the oldest currently-supported Ubuntu release I think it's fine to keep the simplified key.

**Comment by nuclearsandwich** [comment]
Added an archlinux entry: https://www.archlinux.org/packages/community/any/ruby-ronn/

**Comment by nuclearsandwich** [comment]
What are other @ros/rosdeputies opinions on using the rosdep key `ronn` rather than `ruby-ronn` matching the Debian package name as we've been doing lately?

My preference would probably be to use the package name to avoid possible confusion if a future non-ruby package called ronn is introduced.

**Comment by clalancette** [comment]
> My preference would probably be to use the package name to avoid possible confusion if a future non-ruby package called ronn is introduced.

Oh yeah, I missed that.  I agree, a key of `ruby-ronn` is preferable.

**Review by nuclearsandwich — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
