### PR TITLE
fields2cover: 1.2.1-1 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by Gonzalo-Mier**
Increasing version of package(s) in repository `fields2cover` to `1.2.1-1`:

- upstream repository: https://github.com/Fields2Cover/fields2cover.git
- release repository: https://github.com/Fields2Cover/fields2cover-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

### CODE REVIEW

**Review by adityapande-1995 — COMMENTED** [review]
Could you also add the "source" tag here ?

**Comment by mjcarroll** [comment]
@Gonzalo-Mier friendly ping

**Comment by Gonzalo-Mier** [comment]
I don't understand why or how to solve this error. @mjcarroll do you have any insight? Thank you

**Comment by mjcarroll** [comment]
Typically an entry will have a `source`, `doc` and `release` tag, something like:

```
  filters:
    doc:
      type: git
      url: https://github.com/ros/filters.git
      version: ros2
    release:
      tags:
        release: release/humble/{package}/{version}
      url: https://github.com/ros2-gbp/filters-release.git
      version: 2.1.0-3
    source:
      test_pull_requests: true
      type: git
      url: https://github.com/ros/filters.git
      version: ros2
    status: maintained
```

Can you update your pull request to at least include `source`, but maybe additionally `doc`?

**Comment by Gonzalo-Mier** [comment]
Done. @mjcarroll Thank you for your support!

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
