### PR TITLE
dwm1001_ros: 1.0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by 20chix**
Hi 

That's the first time I'm realising a package. Followed all the steps, hope everything is OK ? 

Thanks in advance

### CODE REVIEW

**Comment by 20chix** [comment]
Sorry forgot about these info

release repository: https://github.com/20chix/dwm1001_ros
distro file: kinetic/distribution.yaml

**Comment by tfoote** [comment]
Overall it looks like you've constructed this appropriately. 

However please add a license to your software. It's currently listed as a TODO: https://github.com/20chix/dwm1001_ros/blob/f0b78245c0c155b54098f8fc7d0b2c9628b62d65/package.xml#L16

https://help.github.com/en/articles/licensing-a-repository

We recommend the Apache 2.0 or BSD. If you want more information please see here: https://choosealicense.com/

**Comment by 20chix** [comment]
Hi 

Thanks for comments:

Updated license and email  in `package.xml`
https://github.com/20chix/dwm1001_ros/blob/4d9e7e3355ab85ae068ee0c41057aa292cc45927/package.xml#L16

Added `LICENSE`

Thanks in advance
 Hadi

**Comment by tfoote** [comment]
Thanks for the updates!

**Pull request merged**
