### PR TITLE
feat: add darknet

### PR DESCRIPTION
**Pull request by wep21**
Please add the following dependency to the rosdep database.

## Package name:

darknet

## Package Upstream Source:

https://github.com/pjreddie/darknet

## Purpose of using this:

deep learning framework

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/unstable/darknet
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/it/jammy/science/darknet
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by wep21** [comment]
Is it okay to remove darknet from indigo because it's a legacy package?

**Comment by clalancette** [comment]
See https://github.com/ros/rosdistro/pull/39402, which fixes CI.

**Comment by clalancette** [comment]
@wep21 Now that https://github.com/ros/rosdistro/pull/39402 is in, you should be able to rebase this PR and it should pass CI.

**Comment by wep21** [comment]
@clalancette Now, I rebased the branch, thanks!

**Review by methylDragon — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
