### PR TITLE
Libcxxtools

### PR DESCRIPTION
**Pull request by Vuwij**
https://packages.debian.org/buster/libcxxtools-dev
https://packages.ubuntu.com/eoan/libcxxtools-dev

Contains many useful tools including an argument parser

### CODE REVIEW

**Comment by sloretz** [comment]
Mind adding Fedora and gentoo keys as well?

Fedora: `cxxtools-devel`
* https://src.fedoraproject.org/rpms/cxxtools
* https://pkgs.org/download/cxxtools-devel

Gentoo: `dev-libs/cxxtools`
* https://packages.gentoo.org/packages/dev-libs/cxxtools

**Comment by claireyywang** [comment]
@Vuwij friendly ping

**Review by tfoote — CHANGES_REQUESTED** [review]
Please add the additional rules found by @sloretz so we can have consistent rules across the platforms.

**Comment by dirk-thomas** [comment]
@Vuwij Friendly ping.

**Comment by mjcarroll** [comment]
@Vuwij friendly ping.

**Comment by clalancette** [comment]
It's been more than a month here with no response.  I'm going to go ahead and close this out.  Feel free to fix the problems pointed out in review and reopen.  Thanks for the contribution.

**Pull request closed without merging**
