### PR TITLE
add sixad rosdep rule

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by mikeferguson** [comment]
@mikepurvis does this look good to you? I just realized that there is no rosdep key for sixad that I can find....

**Comment by jack-oquin** [comment]
For bloom release support, a fedora definition would also be helpful.

**Comment by mikepurvis** [comment]
LGTM.

Is an RPM of this available somewhere? If not, then there isn't much we can do. I'm happy to support it by adding packaging files to my repo if someone wants to build and push binaries to bintray or something, but I can't personally invest any time in it.

**Comment by tfoote** [comment]
@cottsay re: Fedora packages

**Comment by cottsay** [comment]
I don't see it in any popular repositories, and it certainly isn't a part of the official Fedora repos or RPMFusion.

It isn't currently up for official packaging review, either.

I'll take a look, and if it is a pretty clean package, I could submit it for inclusion myself.

Probably best to merge this without Fedora support for now. I'll ping back with news.

**Comment by cottsay** [comment]
Okay, I made the package, but now I'm no longer sure it is necessary. In Fedora, `bluez` has native support for sixaxis controllers. You can use `bluetoothctl` to "trust" the device, and then it connects every time. You don't need `sixpair` or `sixad` to make it happen. You may need the `kernel-modules-extra` package installed, but I haven't double-checked yet.

I'm not sure what you're planning on using it for - would it be possible (or worth while) to leverage the existing system on Fedora?

In any case, I've completed the RPM, but as I mentioned earlier, I'm not sure the review process will take kindly the fact that the python code is run out of `/usr/share`. Should I still pursue getting the package into the repos?

Thanks!

--scott

**Comment by tfoote** [comment]
If we can use an existing package that would be much better.

**Comment by mikeferguson** [comment]
For the most part, this is only useful on-robot. So the question would be: are people deploying fully released robots on Fedora -- my guess is not so.

At Fetch we currently have a hand-rolled deb that pulls in the sixad dependency, however we're looking at moving it down into one of our ROS packages since it looks like we can move towards not having to hack the sixad startup jobs with @mikepurvis new deb.

I personally don't care if we have Fedora support or not, I actually won't even be releasing any packages depending on this rosdep to the main ROS buildfarm.

**Comment by mikepurvis** [comment]
@cottsay @tfoote BlueZ 5+ has [native support for sixaxis](http://git.kernel.org/cgit/bluetooth/bluez.git/tree/plugins/sixaxis.c), and you can [try it out on Ubuntu Trusty via PPA](https://launchpad.net/~vidplace7/+archive/ubuntu/bluez5). However, upon giving it a shot, the following factors have prompted us (Clearpath) to take on maintaining sixad rather than switch over:

 - Unresolved issues in bluez, eg: http://article.gmane.org/gmane.linux.bluez.kernel/62305
 - Fussy bluetoothctl invocations seem to be required on startup, some scripting required there.
 - Disinterest from the bluez devs in work on the safety timeout/cutoff concerns which prompted our initial investigation into sixad and alternatives.
 - Lack of a public bugtracker or other developer accountability in bluez.

In general, BlueZ 5 doesn't meet our needs, and it seems like a lot of bureaucracy to get it there, where sixad does continue to serve our purpose. Clearpath and Fetch can continue to just install sixad using orchestration tools, but it would be convenient to be able to rosdep on it from, eg, the `jackal_robot` metapackage.

**Comment by jack-oquin** [comment]
For me, the safety issue is paramount. 

I suppose the rosdep could resolve to sixad on Ubunutu and bluez on Fedora. I dislike that idea, but maybe Fedora users would consider it adequate and more convenient for their environment.

**Comment by cottsay** [comment]
I would say that @mikepurvis's comments make it clear that `sixad` has value despite BlueZ support for sixaxis. I'll pursue pushing the package to Fedora. For any interested parties, I put the package in Copr for now [1].

You should go ahead and merge without a Fedora key.

[1] http://copr.fedoraproject.org/coprs/cottsay/QtSixA/

**Comment by mikepurvis** [comment]
@cottsay Just a heads-up that the new upstream is here: https://github.com/mikepurvis/sixad

The [original qtsixa is abandonware](https://github.com/ros/rosdistro/issues/6435#issuecomment-70165912), so I'm carrying sixad forward, but I have no interest in maintaining the QT frontend, so I've forked off just the sixad portion of it. I've probably broken RPM packaging in the process, but would be happy for a PR which makes that part easier for you (or I can just give you write access to the repo).

**Comment by 130s** [comment]
> You should go ahead and merge without a Fedora key.

+1

**Comment by tfoote** [comment]
Ok, I'll merge this. Note that we only seem to have debs for saucy and trusty x86 at the moment.

**Pull request merged**
