### PR TITLE
Add python module readchar to ubuntu

### PR DESCRIPTION
**Pull request by bajo**
Adds the ability to get keyboard input without waiting for the enter key being pressed. For details see https://pypi.python.org/pypi/readchar

### CODE REVIEW

**Comment by tfoote** [comment]
If you're just targeting the pip package please add `-pip` to the key. In the future when/if debian or others packages it we'll want to use the name `python-readchar` and if we use it for pip it's much harder to transition.

**Comment by bajo** [comment]
Sure, that make sense. 
Sorry for not following the convention in the first place.

**Comment by tfoote** [comment]
+1

**Comment by bajo** [comment]
@tfoote Thanks for the +1. Do you know who I should ping to get this merged?

**Comment by bajo** [comment]
@dirk-thomas Thank you for merging my pr.  :)

**Pull request merged**
