### PR TITLE
Added sphinxcontrib-bibtex for multiple distros

### PR DESCRIPTION
**Pull request by fsuarez6**
For your reference: https://pypi.python.org/pypi/sphinxcontrib-bibtex

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Can you please rename the key to use the suffix `-pip` if this package is only available via pip?
Thanks!

**Comment by fsuarez6** [comment]
`sphinxcontrib-bibtex` is only available via `pip`. Should I add the `-pip` suffix?

**Comment by mikaelarguedas** [comment]
Yes please

**Comment by fsuarez6** [comment]
Done

**Comment by mikaelarguedas** [comment]
Lgtm thanks @fsuarez6 for iterating

**Pull request merged**
