### PR TITLE
iai_common_msgs: 0.0.6-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by fairlight1337**
Increasing version of package(s) in repository `iai_common_msgs` to `0.0.6-0`:
- upstream repository: https://github.com/code-iai/iai_common_msgs.git
- release repository: https://github.com/code-iai-release/iai_common_msgs-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.21`
- previous version for package: `0.0.5-3`
## attache_msgs

```
* Added attache messages
* Contributors: Jan Winkler
```
## data_vis_msgs

```
* Changelog files for release
* Added label to ValueList entry
  This is needed for generating a legend for multiple data rows, for instance multiple timelines
* Contributors: Jan Winkler, Moritz Tenorth
* Added label to ValueList entry
  This is needed for generating a legend for multiple data rows, for instance multiple timelines
* Contributors: Moritz Tenorth
```
## designator_integration_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## dna_extraction_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## grasp_stability_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## iai_common_msgs

```
* Added attache messages
* Changelog files for release
* Reordered deps in metapackage, and added missing deps iai_control_msgs, iai_urdf_msgs, grasp_stability_msgs.
* Added planning request/response service messages
* Contributors: Georg Bartels, Jan Winkler
* Reordered deps in metapackage, and added missing deps iai_control_msgs, iai_urdf_msgs, grasp_stability_msgs.
* Added planning request/response service messages
* Contributors: Georg Bartels, Jan Winkler
```
## iai_content_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## iai_control_msgs

```
* Changelog files for release
* Add a jointlimits message
* arm_ik_controller: report seconds since the goal started
* Add a State message for the Cartesian Controller
* Added a action message for the PTU
* added goal for the arms
* Contributors: Alexis Maldonado, Jan Winkler
* Add a jointlimits message
* arm_ik_controller: report seconds since the goal started
* Add a State message for the Cartesian Controller
* Added a action message for the PTU
* added goal for the arms
* Contributors: Alexis Maldonado
```
## iai_kinematics_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## iai_robosherlock_actions

```
* Changelog files for release
* added a new message type for perceived objects
* Contributors: Ferenc Balint-Benczedi, Jan Winkler
* added a new message type for perceived objects
* Contributors: Ferenc Balint-Benczedi
```
## iai_urdf_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## iai_wsg_50_msgs

```
* added header to wsg status msg
* Changelog files for release
* Contributors: Jan Winkler, ichumuh
```
## json_prolog_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## mln_robosherlock_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## person_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## planning_msgs

```
* Fixed version number in planning_msgs
* Added duration field in planning messages steps and plans
* Per-step scoring
* Scoring methods in planning request
* Added extra call pattern field for plan steps
* Added structure supporting attributes to planning messages
* Added field for unused bindings
* Changed the nature of planning request and response messages again a bit
* Updated planning messages
* Added score and extra Step msg type
* Added planning request/response service messages
* Contributors: Jan Winkler
* Fixed version number in planning_msgs
* Added new CHANGELOG.rst file to planning_msgs
* Added duration field in planning messages steps and plans
* Per-step scoring
* Scoring methods in planning request
* Added extra call pattern field for plan steps
* Added structure supporting attributes to planning messages
* Added field for unused bindings
* Changed the nature of planning request and response messages again a bit
* Updated planning messages
* Added score and extra Step msg type
* Added planning request/response service messages
* Contributors: Jan Winkler
* Added duration field in planning messages steps and plans
* Per-step scoring
* Scoring methods in planning request
* Added extra call pattern field for plan steps
* Added structure supporting attributes to planning messages
* Added field for unused bindings
* Changed the nature of planning request and response messages again a bit
* Updated planning messages
* Added score and extra Step msg type
* Added planning request/response service messages
* Contributors: Jan Winkler
```
## saphari_msgs

```
* Changelog files for release
* new message saphari_msgs/GestureData required for saphari final review.
* Correct BodyPart.msg: FOREARM->LEFTFOREARM.
* adjust CMakefile to build with renamed HumansState.msg (new Humans.msg)
* rename HumansState to Humans
* add HumansState
  - HumansState has observed_user_ids for fast access to the actual observed users without looping the hole list of humans
* Contributors: Georg Bartels, Jan Winkler, beld_rc
* new message saphari_msgs/GestureData required for saphari final review.
* Correct BodyPart.msg: FOREARM->LEFTFOREARM.
* adjust CMakefile to build with renamed HumansState.msg (new Humans.msg)
* rename HumansState to Humans
* add HumansState
  - HumansState has observed_user_ids for fast access to the actual observed users without looping the hole list of humans
* Contributors: Georg Bartels, beld_rc
```
## scanning_table_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```
## sherlock_sim_msgs

```
* Changelog files for release
* Contributors: Jan Winkler
```

### CODE REVIEW

**Comment by tfoote** [comment]
We're in a  quiet period holding indigo releases in preparation for a sync. If it's important for this to be in the sync please comment on the  ros-release thread titled [Preparations for final releases for Saucy, Utopic, and Vivid for Indigo and Jade April 1st.](http://lists.ros.org/pipermail/ros-release/2016-April/004841.html)

Also note that this pull request was generated using an outdated version of python-rosdistro. It references the incorrect REP 141 vs 143. Please update python-rosdistro to the latest version and rerun `bloom-release` with the `--pull-request-only` or `-p` for short to generate a new pull request. If you do this please close this pull request. 

Alternatively if you're comfortable you can simply edit the branch for this pull request in place to point to the right version of the REP and comment back so we know it's fixed.

**Comment by tfoote** [comment]
@fairlight1337 note for all your PRs to be merged they need the comment change in line 3 to be reverted.

**Comment by fairlight1337** [comment]
@tfoote will do, sorry for the inconvenience. Haven't updated my tools in a while.

**Comment by dirk-thomas** [comment]
Closing due to no response.

**Comment by fairlight1337** [comment]
@tfoote thanks for the comments, appreciate your time. I'll re-request once everything is in place (see https://github.com/ros/rosdistro/pull/11192#issuecomment-215104916). Its not super important to have it in right now, so no problem with holding it back a bit longer.

**Pull request closed without merging**
