### PR TITLE
Move ros2/kdl_parser -> ros/kdl_parser

### PR DESCRIPTION
**Pull request by sloretz**
`ros2/kdl_parser` is being recombined with `ros/kdl_parser`.

### CODE REVIEW

**Comment by sloretz** [comment]
The single test failure is expected because this changes the repo URL in EOL distros

```
AssertionError: ["In file '''/home/runner/work/rosdistro/rosdistro/crystal/distribution.yaml''': There is a change to a doc section of an EOLed distribution. Lines: [735]"] is not false
```

**Review by clalancette — APPROVED** [review]
> The single test failure is expected because this changes the repo URL in EOL distros

I think we've typically left the EOL distros alone, but I don't feel strongly about it one way or the other.  I'm going to approve, but I'll suggest getting one other approval before merging.

**Review by jacobperron — COMMENTED** [review]
I'm not sure about modifying the EOL distros, maybe someone else can weigh in.

Can you also open PRs to update the repos file in ros2/ros2 for the active distros?

**Review by tfoote — APPROVED** [review]
It's fine to update references to moved resources in EOL as long as we expect the content to be the same. The EOL distro can still be useful for people potentially building from source etc. And we would break them if we refused to update the urls for the moved resources.

We don't want to have "new" releases or other changes. but fixing external references is fine. Since we don't necessarily host everything we can't guarantee the urls will resolve forever. But hopefully there will remain copies of the open source projects.

**Review by nuclearsandwich — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
