### PR TITLE
Add libpcl-all-dev for "el capitan"

### PR DESCRIPTION
**Pull request by jmtatsch**

### CODE REVIEW

**Comment by jmtatsch** [comment]
I have no idea why the check complains about the the whitespace in "el capitan" but not in "mountain lion"

**Comment by wjwwood** [comment]
@jmtatsch I had to update the tests, please rebase this once https://github.com/ros/rosdistro/pull/9610 has been merged.

**Comment by wjwwood** [comment]
@jmtatsch it's been merged so once you rebase the CI should pass and we can merge this.

**Comment by jmtatsch** [comment]
Ouch this is too messed up. Will start a new pr

**Pull request closed without merging**
