### PR TITLE
add python-pathtools, python-watchdog on xenial

### PR DESCRIPTION
**Pull request by yichoe**
Only adding ubuntu for now to validate switching from trusty ros-package to kinetic xenial packages.

### CODE REVIEW

**Comment by asmodehn** [comment]
Any hint about why check_duplicates fail ?

We are defining the rosdistro key on kinetic here to be the same as the ros-package on indigo (and the same as the ubuntu package) on purpose, hoping to migrate from a backported ros package on indigo to a system package on kinetic. Does this cause any problem ?

Or maybe we missed something somewhere else ?

FYI @yotabits @tfoote @dirk-thomas 
Ref : https://github.com/ros/rosdistro/pull/15095

**Comment by dirk-thomas** [comment]
@k-okada The new test checking for duplicates seem to not handle this case correctly. Can you please provide a PR to update the logic which works for this case.

**Comment by mikaelarguedas** [comment]
@yichoe I know that this won't pass until the test it fix but is it possible to add these packages for the ubuntu distribution after xenial (yakkety, zesty and artful) as well as a generic debian entry given that these packages are available since jessie ? thanks!

**Comment by k-okada** [comment]
sorry for trouble, https://github.com/ros/rosdistro/pull/15599 should be ok

**Comment by dirk-thomas** [comment]
@yichoe Can you please rebase your patch to the latest master. That will hopefully make CI pass.

**Review by mikaelarguedas — APPROVED** [review]
lgtm thanks @yichoe for iterating

**Pull request merged**
