### PR TITLE
pr2_props_stack: 1.0.3-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by UltronDestroyer**
Increasing version of package(s) in repository `pr2_props_stack` to `1.0.3-0`:
- upstream repository: https://github.com/pr2/pr2_props_stack.git
- release repository: https://github.com/pr2-gbp/pr2_props_stack-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.18`
- previous version for package: `null`
## pr2_props
- No changes

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This PR removes `pr2_kinematics` and `pr2_map_navigation_app`.

**Comment by TheDash** [comment]
Hmm..

**Comment by TheDash** [comment]
Is there a reason why it suggested to remove those two? That's rather disheartening

**Comment by dirk-thomas** [comment]
Bloom bug: ros-infrastructure/bloom#252

**Pull request closed without merging**
