### PR TITLE
Adding grid_map to documentation index for distro.

### PR DESCRIPTION
**Pull request by pfankhauser**
I'd like grid_map to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The PR is not mergable with the current master. Please rebase.

**Comment by vrabaud** [comment]
you need to rebase, not merge your branch

**Comment by vrabaud** [comment]
hey, that looks cool btw, how does that compare to costmap_2d ?

**Comment by pfankhauser** [comment]
I initiated a new pull request for this, I hope it looks better now.

**Pull request closed without merging**
