### PR TITLE
added dual_laser_merger

### PR DESCRIPTION
**Pull request by pradyum**
# Please Add This Package to be indexed in the rosdistro.

dual_laser_merger

# The source is here:

https://github.com/pradyum/dual_laser_merger

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
name is generic, but the package looks general purpose to me

lgtm, but waiting for a second reviewer

**Comment by christophebedard** [comment]
- [x] At least one of the following must be present
  - [ ] Top level license file:
  - [x] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses):
- [x] License correctly listed in package.xmls
- [x] Public source repo:
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

I agree it's pretty generic, but it describes what it does.

---

There's an unrelated CI failure that I believe should be fixed by #43359. Can you rebase on your branch on this repo's `master` branch?

**Comment by pradyum** [comment]
I have updated updated the `master` branch

**Comment by christophebedard** [comment]
Thank you, now CI passes!

**Review by christophebedard — APPROVED** [review]

**Pull request merged**
