### PR TITLE
Add Gazebo Garden packages for Gentoo

### PR DESCRIPTION
**Pull request by gentoo90**
Please update gentoo package names for the following dependencies in the rosdep database.

I've created a pull request to `ros-overlay` with packages for gentoo: ros/ros-overlay#1038
**Please merge it before merging this one**.

|Rosdep|Gentoo|
|-|-|
|`gz-cmake3`|[`'dev-build/gz-cmake:3'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-0fc8352e0103b092e4f9fd5d0485b5813c5ab1250dc824f90956ddcd717f9115)|
|`gz-common5`|[`'sci-libs/gz-common:5'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-0ff38df7a50bf68cb16bc33b6bb331f032079276918f35f7d24ef8f797c3e7b5)|
|`gz-fuel-tools8`|[`'sci-libs/gz-fuel-tools:8'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-0ec1d178f36c672286f16d692d9256ef0a86ba10dcb8e43685da6d02e7f9d3ed)|
|`gz-garden`|[`'sci-electronics/gz-garden'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-33c27ef177186d0d0cf71b6367182e4313d5c2129dfad46a9879d1b2c842697f)|
|`gz-gui7`|[`'sci-libs/gz-gui:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-cb2c50a92fe3cf2c9abee9ade95a00bdd88892ca0eb70eb1d7f0cba49d5297be)|
|`gz-launch6`|[`'sci-electronics/gz-launch:6'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-bb2aca107f6d7037c0821a68054faeb8232b57626b55584da5f0d45c7f0e181e)|
|`gz-math7`|[`'sci-libs/gz-math:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-155a551759e015718c8a1ad0847fea178572fbf5607304377393df4f35e1035f)|
|`gz-math7-eigen3`|[`'sci-libs/gz-math:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-155a551759e015718c8a1ad0847fea178572fbf5607304377393df4f35e1035f)|
|`gz-msgs9`|[`'net-libs/gz-msgs:9'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-7cdb07dabfd6d1e1d4b746d6daa63e0014ee9b5f73cb8b607f134b317a806631)|
|`gz-physics6`|[`'sci-libs/gz-physics:6'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-7fa95d097c8b9742054952dee017765040f250850c74b4e7e9c8a8aa56fc8cb0)|
|`gz-plugin2`|[`'dev-libs/gz-plugin:2'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-e02b5e4edc5d4a0fcd886ca3fa46d7db7ec62a252c1bc600361f90eecb9fd491)|
|`gz-rendering7`|[`'media-gfx/gz-rendering:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-adf2169dde64b08ea576d88b28c4788027212fe714def0c5a3966bc099f6cd4d)|
|`gz-sensors7`|[`'sci-libs/gz-sensors:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-1e76366c7cd6c7926b81858007bd693d9af1b9b73d9609b1977510542a8d6c52)|
|`gz-sim7`|[`'sci-electronics/gz-sim:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-b3bb620e1c71c6dd7f2632a00ceaa27ae00e99ca8f98893841965bc331c3e291)|
|`gz-sim7-plugins`|[`'sci-electronics/gz-sim:7'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-b3bb620e1c71c6dd7f2632a00ceaa27ae00e99ca8f98893841965bc331c3e291)|
|`gz-tools2`|[`'sci-electronics/gz-tools:2'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-ee1e9618c6cf438e8204bc1eeb1aaf210eaeda0383f5b229c807ffd2d221d67c)|
|`gz-transport12`|[`'net-libs/gz-transport:12'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-50e10178e734b45397ba134322c6f3a3478ab9f2f73c59d7346ece040849c29a)|
|`gz-utils2`|[`'dev-libs/gz-utils:2'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-cda99821060a559c6c71b221b9c1fe97355221d8971be3c3300d9293523ddeb2)|
|`gz-utils2-cli`|[`'dev-libs/gz-utils:2'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-cda99821060a559c6c71b221b9c1fe97355221d8971be3c3300d9293523ddeb2)|
|`sdformat13`|[`'dev-libs/sdformat:13'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-2567c98c61a5e985973562de3651a1795bb1c3a9e6bdb7e264f84774438f48b4)|

## Python
|Rosdep|Gentoo|
|-|-|
|`python3-gz-math7`|[`'sci-libs/gz-math:7[python]'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-155a551759e015718c8a1ad0847fea178572fbf5607304377393df4f35e1035f)|
|`python3-gz-sim7`|[`'sci-electronics/gz-sim:7[python]'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-b3bb620e1c71c6dd7f2632a00ceaa27ae00e99ca8f98893841965bc331c3e291)|
|`python3-sdformat13`|[`'dev-libs/sdformat:13[python]'`](https://github.com/ros/ros-overlay/pull/1038/files#diff-2567c98c61a5e985973562de3651a1795bb1c3a9e6bdb7e264f84774438f48b4)|

### CODE REVIEW

**Comment by mjcarroll** [comment]
CC: @azeey and @j-rivero.  Outside of gentoo, this is adding newer entries in the rosdeps for Ubuntu as well.

**Comment by j-rivero** [comment]
> CC: @azeey and @j-rivero. Outside of gentoo, this is adding newer entries in the rosdeps for Ubuntu as well.

The linter is complaining just correclty about the lack of Garden packages for ROS or Ubuntu repositories. We've never imported Garden into ROS, only [Citadel and Fortress](https://gazebosim.org/docs/harmonic/ros_installation#summary-of-compatible-ros-and-gazebo-combinations) has been added until today and the next planned in directly Harmonic. Following this I think that we can not add the Ubuntu entries to the rosdep registry if I'm not wrong.

Side comment @gentoo90: I have mostly the same Ubuntu entries in the unofficial [`gazebo.yaml`](https://github.com/osrf/osrf-rosdep/blob/master/gz/gazebo.yaml#L2-L44) file of the osrf-rosdep repository (used for various Gazebo/ROS special use cases when combining Gazebo and ROS repositories together). I miss the `python3-sdformat13` entry, otherwise the Gentoo entries look correct to me.

**Comment by gentoo90** [comment]
@j-rivero Ahh, so rosdep can have overlays. Ok, removing Ubuntu entries then. And adding `python3-sdformat13` for gentoo.

**Comment by gentoo90** [comment]
bump

**Review by cottsay — CHANGES_REQUESTED** [review]
I think we should at least be adding the Ubuntu rules to these new keys as well. Would you mind making that change?

**Comment by gentoo90** [comment]
@cottsay you mean roll back 2a054511bad7027f52a4203e9c28dfc2aec3f319 ?

**Review by cottsay — APPROVED** [review]
:facepalm: I should have read the thread. Thanks for pushing back there.

I think this looks fine to me.

**Review by sloretz — APPROVED** [review]

**Comment by gentoo90** [comment]
@sloretz could you also merge ros/ros-overlay#1038 which contains the packages referenced here?

**Pull request merged**
