### PR TITLE
add release of "turtlebot_exploration_3d"

### PR DESCRIPTION
**Pull request by baishibona**
Hi I run "bloom-release" on my repository and got the following:
Everything went as expected, you should check that the new tags match your expectations, and then push to the release repo with:
  git push --all && git push --tags  # You might have to add --force to the second command if you are over-writing existing tags
<== Released 'turtlebot_exploration_3d' using release track 'indigo' successfully
==> git remote -v
origin	https://github.com/RobustFieldAutonomyLab/turtlebot_exploration_3d-release.git (fetch)
origin	https://github.com/RobustFieldAutonomyLab/turtlebot_exploration_3d-release.git (push)
Releasing complete, push to release repository?
Continue [Y/n]? 

However, failed with git  push --all to the release repository... Was it successfully released?
Please let me know if there is anything wrong with the release, sorry that this is the first time I am been doing this, thanks a lot!!

### CODE REVIEW

**Comment by tfoote** [comment]
It looks like you have put your source code into the release repo. If it already has content that has a different git history on the master branch the push will fail because it will conflict. 

When you first run bloom the release repo should be empty. I'd recommend deleting and recreating https://github.com/RobustFieldAutonomyLab/turtlebot_exploration_3d-release.git as an empty repo. Then let bloom populate it for you from empty. 

You can add the documentation and source entries manually, but you cannot add the release entries.

**Comment by baishibona** [comment]
Thanks a lot @tfoote ! It make a lot of sense to me when you suggest release repo should be an empty one initially.
I did a second time(actually went back and forth as I am new to the process), and I think I made it. (generated by bloom a pull request: #13441).

**Comment by tfoote** [comment]
Glad to see that it looks to have worked!

**Comment by baishibona** [comment]
@tfoote Thanks for the help, I was really getting stuck during that time.
Wish people find it interesting and useful. I dropped an email to "ros-news@googlegroups.com" when I first setup the documentation in ros wiki, however didn't hear back from it(I guess it won't be accepted before a 'release'), would you suggest I do it again now so that it might get approved(to be shown in ROS News on the wiki page)?

**Pull request closed without merging**
