### PR TITLE
add gnuplot-x11

### PR DESCRIPTION
**Pull request by yuki-asano**

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please add links to the package descriptions online as well as look for at least fedora packages for this following our CONTRIBUTING guide: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by yuki-asano** [comment]
I couldn't find the alternative of gnuplot-x11 in fedora.

**Comment by tfoote** [comment]
We can merge this without fedora support if you reopen and add links for the debian and ubuntu packages.

**Comment by yuki-asano** [comment]
I found those links below. Where should I add those links? Is here ok?

ubuntu: 
https://packages.ubuntu.com/en/trusty/gnuplot-x11

debian:
https://packages.debian.org/en/jessie/gnuplot-x11

**Comment by yuki-asano** [comment]
If the links are ok, I will create new pull request same with this because this cannot be reopened due to wrong branch operation.

**Comment by tfoote** [comment]
Those are what we are looking for. Thanks!

**Comment by yuki-asano** [comment]
Thank you for your review!
I created the new PR.

**Pull request closed without merging**
