### PR TITLE
add python-rosinstall for additional ubuntu distros

### PR DESCRIPTION
**Pull request by fmessmer**
[xenial](https://packages.ubuntu.com/search?suite=xenial&arch=any&searchon=names&keywords=python-rosinstall)
[zesty](https://packages.ubuntu.com/search?suite=zesty&arch=any&searchon=names&keywords=python-rosinstall)

or do you want me to introduce a line like this to cover all distros?
```
 ubuntu: [python-rosinstall]
```

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
thanks @ipa-fxm,
Can you also add ubuntu `yakkety` and `artful` for completeness as well as debian `jessie`?

**Comment by ipa-fxm** [comment]
@mikaelarguedas 
or do you want me to introduce a line like this to cover all distros?
```
 ubuntu: [python-rosinstall]
```

**Comment by mikaelarguedas** [comment]
unfortunately these lines cannot be collapsed because there is a rule for the python3 version of the package `trusty_python3: [python3-rosinstall]` that will disappear if we do so. So we are forced to add a new line for each distro for now.

If it's not too cumbersome it would be great if we can fill in all the missing ubuntu distributions even if they are EOL (so ubuntu U, V, W, Y and AA)

**Comment by ipa-fxm** [comment]
@mikaelarguedas :+1:

**Review by tfoote — APPROVED** [review]

**Pull request merged**
