### PR TITLE
Adding new repository for indexing: swarm_ros_bridge

### PR DESCRIPTION
**Pull request by shupx**
# Please Add This Package to be indexed in the rosdistro.

swarm_ros_bridge

# The source is here:

https://github.com/shupx/swarm_ros_bridge.git

# Introduction

This is a lightweight middle interface ROS package that enables the specified ROS message transmission among swarm robots through ZeroMQ socket communication.

Compared with ROS1 multi-robot wireless communication configuration, it has the following benefits:

-  **Robust**: No need for base station ROS master launching first. Support each robot launching in a random sequence and connecting each other autonomously.

-  **Flexible**:  You can choose the sending/receiving ROS topics rather than transferring all topics as ROS1 does.

-  **Easy to use**:  Specify all the IP and ROS topics in one configuration file.

Compared with ROS2 DDS communication, it has the following benefits:

-  **Lightweight**: It is a small ROS bridge node subscribing and sending remote ROS topics, so connecting with other ROS1 nodes is easy.

-  **Reliable**: It uses ZeroMQ socket communication based on TCP protocol while ROS2 is based on DDS, whose default protocol is UDP (unreliable).

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
Looking at the package, I see a few problems:

1.  You are missing a package.xml dependency on libzmqpp-dev, which looks to be needed to compile.
2. Your CMakeLists.txt has duplicate compile_options: https://github.com/shupx/swarm_ros_bridge/blob/5394dffa7e1c77d7242f15d59dde40f7d9e019a0/CMakeLists.txt#L5-L6
3. Your CMakeLists.txt fails to `find_package` zmqpp, or otherwise discover it.

Once those are fixed, I think we can accept this.

**Comment by shupx** [comment]
Thanks for your review @clalancette . I have fixed these problems according to your advice:
1. `libzmqpp-dev` is added in [package.xml line16](https://github.com/shupx/swarm_ros_bridge/blob/90cef4e5ad591e7e69f4fd71f06a2f74309af73c/package.xml#L16) now.
2. I have deleted the duplicated compile option c++11 in  [CMakeLists.txt line4](https://github.com/shupx/swarm_ros_bridge/blob/90cef4e5ad591e7e69f4fd71f06a2f74309af73c/CMakeLists.txt#L4) as c++14 is needed by this project.
3. zmqpp does not support `find_package()` in cmake. To compile this project, `target_link_libraries(zmq,zmqpp)` in [CMakeLists.txt line26](https://github.com/shupx/swarm_ros_bridge/blob/90cef4e5ad591e7e69f4fd71f06a2f74309af73c/CMakeLists.txt#L26-L27) is enough. `catkin_make` will success if `libzmqpp-dev` is installed. I have tested it on several computers (ubuntu18, ROS melodic)

The [README](https://github.com/shupx/swarm_ros_bridge/blob/master/README.md) file is also updated.

Source code: https://github.com/shupx/swarm_ros_bridge.git

**Comment by nuclearsandwich** [comment]
New package review:

- [ ] At least one of the following must be present
  - [x] Top level license file: https://github.com/shupx/swarm_ros_bridge/blob/master/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): BSD-3-Clause
- [x] License correctly listed in package.xmls
  - [x] swarm_ros_bridge: https://github.com/shupx/swarm_ros_bridge/blob/master/package.xml#L9 (https://github.com/shupx/swarm_ros_bridge/pull/1)
- [x] Public source repo: https://github.com/shupx/swarm_ros_bridge/tree/master
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] swarm_ros_bridge

**Review by nuclearsandwich — APPROVED** [review]
Aside from some of @clalancette deeper comments, this package meets our usual review requirements.

**Review by clalancette — CHANGES_REQUESTED** [review]
This generally looks good to me now, thanks for the updates.  I'm still not 100% convinced that this would build on the buildfarm, but we are in good enough shape for now to put the `doc` entry in.

That said, due to reasons that do not have to do with this PR, this needs a rebase to pass CI.  Once you've rebased this, CI should run and come back clean, and then we are good to merge it.

**Review by clalancette — APPROVED** [review]
This looks good now, thanks for iterating.

**Pull request merged**
