### PR TITLE
Add teleop_legged_robots for melodic

### PR DESCRIPTION
**Pull request by tarasborov**
Added teleop_legged_robots package

### CODE REVIEW

**Comment by clalancette** [comment]
I'm going to wait on the outcome of https://github.com/ros/rosdistro/pull/28021#pullrequestreview-571282597 before merging.

**Review by ivanpauno — CHANGES_REQUESTED** [review]
can you add `source` and `doc` entries?
thanks!

(edit) I didn't see `clalancette` comment above, so first wait for that too.

**Comment by tarasborov** [comment]
@ivanpauno Thanks for your comments. I have added source and doc.

**Review by ivanpauno — APPROVED** [review]
Holding because of melodic sync: https://discourse.ros.org/t/preparing-for-melodic-sync-2021-01-22/18607.

**Pull request merged**
