### PR TITLE
Adding ess_imu_ros1_uart_driver to documentation index for noetic

### PR DESCRIPTION
**Pull request by cubicleguy**
# Please Add This Package to be indexed in the rosdistro.

ess_imu_ros1_uart_driver

# The source is here:

https://github.com/cubicleguy/ess_imu_ros1_uart_driver.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by audrow — COMMENTED** [review]
The repository looks okay to me, but @cubicleguy, it doesn't seem like you used Bloom to make this release - is there any reason why you didn't use Bloom?

Here is documentation on releasing a package with Bloom: https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by cubicleguy** [comment]
Hi Audrow,

Yeah, please bare with me as I am going through the bloom tutorial (first time) to make sure I don't screw something up.
I am trying to do single distro first. Then hopefully add more legacy distros.

I basically followed the order of the step 8 of "Get Involved - ROS Wiki<http://wiki.ros.org/Get%20Involved>" which suggested to do the pull request for the distribution.yaml first.
This is seemed to me kind of confusing, because the bloom tutorial seems to suggest that it can be done after the "bloom-release" process.

I plan to do the bloom release later this afternoon.

-Raymond



________________________________

**Comment by audrow** [comment]
No worries. I think using Bloom will clear up these errors.

> I am trying to do single distro first. Then hopefully add more legacy distros.

By the way, melodic is the only other ROS 1 distribution that is not end-of-life (EOL). If you were to make a PR for an EOL ROS distribution, that distribution would never have another sync, so the changes would never be included. Here is more information on the active ROS 1 distributions:
http://wiki.ros.org/Distributions

> This is seemed to me kind of confusing, because the bloom tutorial seems to suggest that it can be done after the "bloom-release" process.

Yeah, unfortunately the process is somewhat confusing. Hopefully, the link I sent helps. Let me know if there's more confusion and I can try to help.

**Comment by cubicleguy** [comment]
Closing this pull because running bloom-release which starts a new PR.

**Pull request closed without merging**
