### PR TITLE
added apache2 entry to file rosdep/base.yaml

### PR DESCRIPTION
**Pull request by davefeilseifer**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@davefeilseifer Can you please provide a description of the package and your use case, the links to the package in the distro's package index and the rules for at least ubuntu and debian (gentoo and fedora would be great).

You can find more details in the [contributions guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)

**Comment by davefeilseifer** [comment]
The rosdep rule "apache2" will be used to install this package: https://packages.ubuntu.com/artful/apache2 . This is used by web_interface/ros_apache2 (https://github.com/UNR-RoboticsResearchLab/web_interface), the web GUI for the PR2 (legacy package used in 10.04/12.04 cturtle-hydro finally being packaged for indigo)

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
Please add rules for the other platforms (Debian, Fedora Gentoo) as per previous review

**Comment by mikaelarguedas** [comment]
Pushed https://github.com/ros/rosdistro/pull/17196/commits/7803d0a17762cc4eaa74ceb1ddade27d4f5eed0d to fix the gentoo rule.

Links to the packages (please post this is your PR description in the future):
- Debian: https://packages.debian.org/search?keywords=apache2&searchon=names&exact=1&suite=all&section=all
- Fedora: https://koji.fedoraproject.org/koji/packageinfo?packageID=280
- Gentoo: https://packages.gentoo.org/packages/www-servers/apache

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
