### PR TITLE
added dependency to libcgal-qt5-dev which is said to fix a bug for CG…

### PR DESCRIPTION
**Pull request by ipa-rmb**
…AL with kinetic and 16.04

### CODE REVIEW

**Comment by tfoote** [comment]
Can you link to the bug you're referencing? And also please look at filling in the other target platforms for this according to the CONTRIBUTING.md.

**Comment by ipa-rmb** [comment]
The bug is described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804539 . For us, it appears when compiling our software, which depends on cgal, on Travis for Kinetic with 16.04.

**Comment by ipa-rmb** [comment]
I have added the other dependencies, however, there is only one really new dependency for debian but for the other architectures, the qt part seems to be included in cgal already.

**Review by tfoote — APPROVED** [review]
Thanks for the extra details.

**Pull request merged**
