### PR TITLE
rosdep: add python3-smc-pip

### PR DESCRIPTION
**Pull request by XDGFX**
Please add the following dependency to the rosdep database.

## Package name:

Pololu Simple Motor Controller

## Package Upstream Source:

https://github.com/MomsFriendlyRobotCompany/smc

## Purpose of using this:

Used to provide a simple Python interface for Pololu motor controllers.

## PIP packaging links:
   - https://pypi.org/project/smc/

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Pushed a merge of master to this PR branch to resolve the issue fixed by #30010.

**Review by nuclearsandwich — APPROVED** [review]
@XDGFX

Are you aware that ROS packages which depend on pip packages cannot be released to the official build farm? As long as you're aware of that limitation and this PR is still useful to you it's good.

**Review by mabelzhang — APPROVED** [review]
Feel free to merge after the question above is answered.

**Comment by XDGFX** [comment]
Yeah that's all good, the package in question is for internal use. Many thanks!

**Pull request merged**
