### PR TITLE
Additions for ubuntu:bionic and melodic

### PR DESCRIPTION
**Pull request by leolchat**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@leolchat please provide the entries in alphabetical order to make CI happy.

As you are adding bionic rules please consider providing the artful rules as well as both are required for users to release packages depending on these keys.

**Comment by leolchat** [comment]
I do not have a artful system to check if the packages install well and rosdesktop build, so I would let you/ROS maintenance team check it... on my side, it seems to allow building from source without missing dependencies.

**Comment by mikaelarguedas** [comment]
Please add the rules anyway, as all the rules you're adding here are all the same as in Zesty, it's extremely unlikely that the name is different for artful.

**Comment by leolchat** [comment]
If you insist, please go ahead and add that change, that pull request should be editable by maintainers.

**Comment by wjwwood** [comment]
@leolchat for future reference, they can be looked up (without a running Artful system) here:

https://packages.ubuntu.com/artful/

**Comment by wjwwood** [comment]
I'll add the artful entries eventually, since I need at least `assimp` myself to do the `rviz` release. It might be a few days before I catch up on rviz issues, however. @leolchat if you have time in the meantime we would appreciate the contribution and merge it sooner.

**Comment by leolchat** [comment]
I guess if it breaks on artful, you will catch it early enough.

**Review by wjwwood — APPROVED** [review]
Yeah, we'll notice, thanks for adding them. I'll touch them up if needed when we start using them on our released packages.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
