### PR TITLE
librealsense2: 2.45.0-1 in 'dashing/distribution.yaml'

### PR DESCRIPTION
**Pull request by doronhi**
replace librealsense2 entry to match package name.
replace source for librealsense2. Change status to developed
update librealsense2 version.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@doronhi the latest release of librealsense2 appears to be missing considerable contents compared to the previous release:

<details>
<summary>

`dpkg -c ros-dashing-librealsense2_2.16.5-1bionic.20201125.035912_amd64.deb`

</summary>

```
drwxr-xr-x root/root         0 2020-11-24 19:59 ./
drwxr-xr-x root/root         0 2020-11-24 19:59 ./lib/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./lib/udev/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./lib/udev/rules.d/
-rw-r--r-- root/root      4788 2019-05-20 04:43 ./lib/udev/rules.d/60-ros-dashing-librealsense2.rules
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/bin/
-rwxr-xr-x root/root   1398744 2020-11-24 19:59 ./opt/ros/dashing/bin/realsense-viewer
-rwxr-xr-x root/root    416424 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-align
-rwxr-xr-x root/root    101016 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-capture
-rwxr-xr-x root/root     10232 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-color
-rwxr-xr-x root/root    219400 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-convert
-rwxr-xr-x root/root    145616 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-data-collect
-rwxr-xr-x root/root     10232 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-depth
-rwxr-xr-x root/root   1484776 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-depth-quality
-rwxr-xr-x root/root     10232 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-distance
-rwxr-xr-x root/root    137408 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-enumerate-devices
-rwxr-xr-x root/root    306376 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-fw-logger
-rwxr-xr-x root/root    137880 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-measure
-rwxr-xr-x root/root    117400 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-multicam
-rwxr-xr-x root/root    100528 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-pointcloud
-rwxr-xr-x root/root    420520 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-post-processing
-rwxr-xr-x root/root    416424 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-record-playback
-rwxr-xr-x root/root   1031384 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-rosbag-inspector
-rwxr-xr-x root/root    112872 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-save-to-disk
-rwxr-xr-x root/root    133784 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-sensor-control
-rwxr-xr-x root/root    213944 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-software-device
-rwxr-xr-x root/root    256208 2020-11-24 19:59 ./opt/ros/dashing/bin/rs-terminal
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/include/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/include/librealsense2/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/include/librealsense2/h/
-rw-r--r-- root/root      2712 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_advanced_mode_command.h
-rw-r--r-- root/root      5642 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_context.h
-rw-r--r-- root/root      7053 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_device.h
-rw-r--r-- root/root     19889 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_frame.h
-rw-r--r-- root/root      7329 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_internal.h
-rw-r--r-- root/root     11056 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_option.h
-rw-r--r-- root/root     22299 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_pipeline.h
-rw-r--r-- root/root      9961 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_processing.h
-rw-r--r-- root/root      8803 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_record_playback.h
-rw-r--r-- root/root     23725 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_sensor.h
-rw-r--r-- root/root      9826 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/h/rs_types.h
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/include/librealsense2/hpp/
-rw-r--r-- root/root      8167 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_context.hpp
-rw-r--r-- root/root     10218 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_device.hpp
-rw-r--r-- root/root     32104 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_frame.hpp
-rw-r--r-- root/root      6306 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_internal.hpp
-rw-r--r-- root/root     24369 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_pipeline.hpp
-rw-r--r-- root/root     27764 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_processing.hpp
-rw-r--r-- root/root      9047 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_record_playback.hpp
-rw-r--r-- root/root     16272 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_sensor.hpp
-rw-r--r-- root/root      5246 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/hpp/rs_types.hpp
-rw-r--r-- root/root      4282 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/rs.h
-rw-r--r-- root/root      2700 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/rs.hpp
-rw-r--r-- root/root      4675 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/rs_advanced_mode.h
-rw-r--r-- root/root     12446 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/rs_advanced_mode.hpp
-rw-r--r-- root/root      7445 2019-05-20 04:39 ./opt/ros/dashing/include/librealsense2/rsutil.h
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/realsense2/
-rw-r--r-- root/root      1276 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Config.cmake
-rw-r--r-- root/root      1270 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/realsense2/realsense2ConfigVersion.cmake
-rw-r--r-- root/root      1396 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Targets-none.cmake
-rw-r--r-- root/root      3423 2020-11-24 19:59 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Targets.cmake
-rw-r--r-- root/root   1134230 2020-11-24 19:59 ./opt/ros/dashing/lib/librealsense-file.a
-rw-r--r-- root/root   6249352 2020-11-24 19:59 ./opt/ros/dashing/lib/librealsense2.so.2.16.5
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/pkgconfig/
-rw-r--r-- root/root       438 2020-11-24 19:59 ./opt/ros/dashing/lib/pkgconfig/realsense2.pc
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/package_run_dependencies/
-rw-r--r-- root/root        82 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/package_run_dependencies/librealsense2
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/packages/
-rw-r--r-- root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/packages/librealsense2
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/parent_prefix_path/
-rw-r--r-- root/root         8 2020-11-24 19:59 ./opt/ros/dashing/share/ament_index/resource_index/parent_prefix_path/librealsense2
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/cmake/
-rw-r--r-- root/root       781 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/cmake/ament_cmake_export_include_directories-extras.cmake
-rw-r--r-- root/root      5046 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/cmake/ament_cmake_export_libraries-extras.cmake
-rw-r--r-- root/root       433 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/cmake/librealsense2Config-version.cmake
-rw-r--r-- root/root      1283 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/cmake/librealsense2Config.cmake
drwxr-xr-x root/root         0 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/environment/
-rw-r--r-- root/root       160 2020-11-24 11:33 ./opt/ros/dashing/share/librealsense2/environment/ament_prefix_path.sh
-rw-r--r-- root/root       411 2019-10-11 13:28 ./opt/ros/dashing/share/librealsense2/environment/library_path.sh
-rw-r--r-- root/root       185 2020-11-24 11:33 ./opt/ros/dashing/share/librealsense2/environment/path.sh
-rw-r--r-- root/root      1592 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/local_setup.bash
-rw-r--r-- root/root      3899 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/local_setup.sh
-rw-r--r-- root/root      1955 2020-11-24 19:59 ./opt/ros/dashing/share/librealsense2/local_setup.zsh
-rw-r--r-- root/root      1648 2019-05-20 04:39 ./opt/ros/dashing/share/librealsense2/package.xml
drwxr-xr-x root/root         0 2020-11-24 19:59 ./usr/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./usr/share/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-11-24 19:59 ./usr/share/doc/ros-dashing-librealsense2/
-rw-r--r-- root/root       269 2020-11-24 19:59 ./usr/share/doc/ros-dashing-librealsense2/changelog.Debian.gz
lrwxrwxrwx root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/librealsense2.so -> librealsense2.so.2
lrwxrwxrwx root/root         0 2020-11-24 19:59 ./opt/ros/dashing/lib/librealsense2.so.2 -> librealsense2.so.2.16.5
```

</details>

<details>
<summary>

`dpkg -c ros-dashing-librealsense2_2.45.0-1bionic.20210510.174411_amd64.deb`

</summary>

```
drwxr-xr-x root/root         0 2021-05-10 10:44 ./
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/include/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/include/librealsense2/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/include/librealsense2/h/
-rw-r--r-- root/root      2765 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_advanced_mode_command.h
-rw-r--r-- root/root     11605 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_config.h
-rw-r--r-- root/root      6792 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_context.h
-rw-r--r-- root/root     27744 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_device.h
-rw-r--r-- root/root     22081 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_frame.h
-rw-r--r-- root/root     26873 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_internal.h
-rw-r--r-- root/root     20822 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_option.h
-rw-r--r-- root/root     16974 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_pipeline.h
-rw-r--r-- root/root     16255 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_processing.h
-rw-r--r-- root/root      9489 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_record_playback.h
-rw-r--r-- root/root     37284 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_sensor.h
-rw-r--r-- root/root     16873 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/h/rs_types.h
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/include/librealsense2/hpp/
-rw-r--r-- root/root      8185 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_context.hpp
-rw-r--r-- root/root     35933 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_device.hpp
-rw-r--r-- root/root     17998 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_export.hpp
-rw-r--r-- root/root     39464 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_frame.hpp
-rw-r--r-- root/root     20621 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_internal.hpp
-rw-r--r-- root/root      4974 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_options.hpp
-rw-r--r-- root/root     29176 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_pipeline.hpp
-rw-r--r-- root/root     41119 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_processing.hpp
-rw-r--r-- root/root      9800 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_record_playback.hpp
-rw-r--r-- root/root     26757 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_sensor.hpp
-rw-r--r-- root/root      1564 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_serializable_device.hpp
-rw-r--r-- root/root      6460 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/hpp/rs_types.hpp
-rw-r--r-- root/root      5644 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/rs.h
-rw-r--r-- root/root      7501 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/rs.hpp
-rw-r--r-- root/root      4604 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/rs_advanced_mode.h
-rw-r--r-- root/root     12200 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/rs_advanced_mode.hpp
-rw-r--r-- root/root     10533 2021-05-10 01:53 ./opt/ros/dashing/include/librealsense2/rsutil.h
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/realsense2/
-rw-r--r-- root/root      1276 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Config.cmake
-rw-r--r-- root/root      1270 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/realsense2/realsense2ConfigVersion.cmake
-rw-r--r-- root/root      1830 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Targets-none.cmake
-rw-r--r-- root/root      3939 2021-05-10 10:44 ./opt/ros/dashing/lib/cmake/realsense2/realsense2Targets.cmake
-rw-r--r-- root/root  13263674 2021-05-10 10:44 ./opt/ros/dashing/lib/libfw.a
-rw-r--r-- root/root   1143042 2021-05-10 10:44 ./opt/ros/dashing/lib/librealsense-file.a
-rw-r--r-- root/root  20090984 2021-05-10 10:44 ./opt/ros/dashing/lib/librealsense2.so.2.45.0
drwxr-xr-x root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/pkgconfig/
-rw-r--r-- root/root       438 2021-05-10 10:44 ./opt/ros/dashing/lib/pkgconfig/realsense2.pc
drwxr-xr-x root/root         0 2021-05-10 10:44 ./usr/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./usr/share/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./usr/share/doc/
drwxr-xr-x root/root         0 2021-05-10 10:44 ./usr/share/doc/ros-dashing-librealsense2/
-rw-r--r-- root/root       258 2021-05-10 10:44 ./usr/share/doc/ros-dashing-librealsense2/changelog.Debian.gz
lrwxrwxrwx root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/librealsense2.so -> librealsense2.so.2.45
lrwxrwxrwx root/root         0 2021-05-10 10:44 ./opt/ros/dashing/lib/librealsense2.so.2.45 -> librealsense2.so.2.45.0
```


</details>

I may try reverting the most recent release to see if 2.16.5 will build against the current version of Dashing.

**Comment by doronhi** [comment]
@nuclearsandwich , Can you help me understand what the issue is and how can I help to fix it? What content is missing?
I followed the link but everything seems green now so I still didn't understand what to look for.

**Comment by nuclearsandwich** [comment]
@dorohni thanks again for your assistance as we prepare to wrap up support for one of our distributions. :love_letter:

> Can you help me understand what the issue is and how can I help to fix it?

Since the 2.45.0-1 release of `librealsense2` in Dashing, the downstream package `` has failed to build with the following error despite the fact that the `ros-dashing-librealsense2` package is installed:

```
23:06:19 CMake Warning at CMakeLists.txt:52 (find_package):
23:06:19   By not providing "Findlibrealsense2.cmake" in CMAKE_MODULE_PATH this
23:06:19   project has asked CMake to find a package configuration file provided by
23:06:19   "librealsense2", but CMake did not find one.
23:06:19 
23:06:19   Could not find a package configuration file provided by "librealsense2"
23:06:19   with any of the following names:
23:06:19 
23:06:19     librealsense2Config.cmake
23:06:19     librealsense2-config.cmake
23:06:19 
23:06:19   Add the installation prefix of "librealsense2" to CMAKE_PREFIX_PATH or set
23:06:19   "librealsense2_DIR" to a directory containing one of the above files.  If
23:06:19   "librealsense2" provides a separate development package or SDK, be sure it
23:06:19   has been installed.
23:06:19 
23:06:19 
23:06:19 CMake Error at CMakeLists.txt:54 (message):
23:06:19   
23:06:19 
23:06:19   
23:06:19 
23:06:19    Intel RealSense SDK 2.0 is missing, please install it from https://github.com/IntelRealSense/librealsense/releases
23:06:19 
23:06:19   
23:06:19 
23:06:19 
23:06:19 
23:06:19 -- Configuring incomplete, errors occurred!
```



> What content is missing?

Comparing the `dpkg` output in https://github.com/ros/rosdistro/pull/29474#issuecomment-856224741 it seems like the latest release is missing some of the ROS 2 specific files: the package.xml, ament resource index files, and package setup scripts

```
-./opt/ros/dashing/share/
-./opt/ros/dashing/share/ament_index/
-./opt/ros/dashing/share/ament_index/resource_index/
-./opt/ros/dashing/share/ament_index/resource_index/package_run_dependencies/
-./opt/ros/dashing/share/ament_index/resource_index/package_run_dependencies/librealsense2
-./opt/ros/dashing/share/ament_index/resource_index/packages/
-./opt/ros/dashing/share/ament_index/resource_index/packages/librealsense2
-./opt/ros/dashing/share/ament_index/resource_index/parent_prefix_path/
-./opt/ros/dashing/share/ament_index/resource_index/parent_prefix_path/librealsense2
-./opt/ros/dashing/share/librealsense2/
-./opt/ros/dashing/share/librealsense2/cmake/
-./opt/ros/dashing/share/librealsense2/cmake/ament_cmake_export_include_directories-extras.cmake
-./opt/ros/dashing/share/librealsense2/cmake/ament_cmake_export_libraries-extras.cmake
-./opt/ros/dashing/share/librealsense2/cmake/librealsense2Config-version.cmake
-./opt/ros/dashing/share/librealsense2/cmake/librealsense2Config.cmake
-./opt/ros/dashing/share/librealsense2/environment/
-./opt/ros/dashing/share/librealsense2/environment/ament_prefix_path.sh
-./opt/ros/dashing/share/librealsense2/environment/library_path.sh
-./opt/ros/dashing/share/librealsense2/environment/path.sh
-./opt/ros/dashing/share/librealsense2/local_setup.bash
-./opt/ros/dashing/share/librealsense2/local_setup.sh
-./opt/ros/dashing/share/librealsense2/local_setup.zsh
-./opt/ros/dashing/share/librealsense2/package.xml
```

As well as the udev rules

```
-./lib/
-./lib/udev/
-./lib/udev/rules.d/
-./lib/udev/rules.d/60-ros-dashing-librealsense2.rules
```

And binaries

```
-./opt/ros/dashing/bin/
-./opt/ros/dashing/bin/realsense-viewer
-./opt/ros/dashing/bin/rs-align
-./opt/ros/dashing/bin/rs-capture
-./opt/ros/dashing/bin/rs-color
-./opt/ros/dashing/bin/rs-convert
-./opt/ros/dashing/bin/rs-data-collect
-./opt/ros/dashing/bin/rs-depth
-./opt/ros/dashing/bin/rs-depth-quality
-./opt/ros/dashing/bin/rs-distance
-./opt/ros/dashing/bin/rs-enumerate-devices
-./opt/ros/dashing/bin/rs-fw-logger
-./opt/ros/dashing/bin/rs-measure
-./opt/ros/dashing/bin/rs-multicam
-./opt/ros/dashing/bin/rs-pointcloud
-./opt/ros/dashing/bin/rs-post-processing
-./opt/ros/dashing/bin/rs-record-playback
-./opt/ros/dashing/bin/rs-rosbag-inspector
-./opt/ros/dashing/bin/rs-save-to-disk
-./opt/ros/dashing/bin/rs-sensor-control
-./opt/ros/dashing/bin/rs-software-device
-./opt/ros/dashing/bin/rs-terminal
```

so even though the build of librealsense2 succeeded it looks like it might have done so with an incomplete configuration. Let me know how best to assist further.

**Comment by doronhi** [comment]
Regarding CMake not finding librealsense2:
I don't know why CMake does not find librealsense2 if it is installed. I couldn't find out which package it is that is being compiled. Which package is this CMake belongs to?
Is the target package builds successfully in foxy? The reason I'm asking is that the new ros-dashing-librealsense2 package should be identical to the ros-foxy-librealsense2 that has been around a little longer now.

Regarding the missing librealsense2 tools:
The idea behind the packages ros-$ROS_DISTRO-librealsense2 is to support ros-$ROS_DISTRO-realsense2-camera. librealsense2 utilities, such as realsense-viewer, rs-enumerate-devices, and so on, are available in the package librealsense2-utils. Not related to ROS. Therefore they were not added to the ros-dashing-librealsense2

Regarding the missing udev-rules:
udev rules were added to realsense2_camera for simplicity reasons with the assumption that these 2 packages, ros-dashing-librealsense2 and ros-dashing-realsense2_camera, goes together.

A little background:
The previous debian version, 2.16.5 was based on a copy of librealsense2 with modifications for ROS. It was not actively maintained - hence the big gap in releases. The 2.45.0 version is built from the source repository of librealsense2 with minor [patches](https://github.com/IntelRealSense/librealsense2-release/tree/patches/release/dashing/librealsense2) for ROS/ROS2 applied during the debian creation process, the same way it is done for kinetic, melodic, noetic, eloquent, and foxy. That's why it is easier to update at a rate closer to the librealsense2 repository itself.

**Comment by nuclearsandwich** [comment]
Thanks for the information about the each of the observed discrepancies between the different packaged versions of librealsense2 on Dashing. Based on this information, together with the fact that this is Dashing's final release before we officially end support for it. I think the best thing to do is to revert this release and leave Dashing at the 2.16.5 package version. The improvements to the realsense in ROS workflow that you've outlined are a definite improvement, but for Dashing in particular it also represents a substantial change just as we're preparing to end support and while I recognize the prior status quo is sub-optimal it has been that way for the entirety of Dashing's support window and those who may be using Dashing beyond its support window will benefit most from maintaining that status quo.

I have opened and will merge #29820 to set Dashing back to the previous release. It's not my intention to refute or invalidate your work and responsiveness. On the contrary I wouldn't have had the information necessary to understand the changes without this discussion and I know the work you've put in is benefiting our other active distributions and appreciate the extra effort it took to try and bring those improvements to our most venerable of active ROS 2 distributions.

> Is the target package builds successfully in foxy?

As far as I can tell the equivalent packages in Foxy are building just fine so part of the problem may be specific to either Dashing or Ubuntu Bionic and how CMake packages are found. Since for the stated reasons above we are not going to include this in Dashing the question is now somewhat academic.

**Comment by doronhi** [comment]
I think your conclusion is correct. Thanks for taking care of this, including #29823 .

**Pull request merged**
