### PR TITLE
adding xtensor to rosdep

### PR DESCRIPTION
**Pull request by SteveMacenski**
arch: https://aur.archlinux.org/packages/xtensor
fedora: https://src.fedoraproject.org/rpms/xtensor
ubuntu: 
- Jammy: https://packages.ubuntu.com/jammy/libxtensor-dev
- bionic: https://packages.ubuntu.com/source/bionic/xtensor
- focal: https://packages.ubuntu.com/focal/xtl-dev

debian: https://packages.debian.org/sid/main/xtensor-dev

Needed for a new Nav2 controller in the works

### CODE REVIEW

**Comment by cottsay** [comment]
From the log:
```
Error: Package 'xtensor-dev' could not be found for debian buster on amd64
Error: Package 'xtensor-dev' could not be found for debian bullseye on amd64
```

Indeed, if you take a look at the dashboard link you have in the PR description, the package isn't available for any of the Debian releases that ROS targets.

Since the package isn't available for any released Debian versions, I think it should probably be omitted.

**Comment by SteveMacenski** [comment]
Done

Thanks for pointing that out, I was looking at the logs near the error message, I didn't even think to look at the header :facepalm:

**Comment by SteveMacenski** [comment]
Removed xtl from Focal, I've found this is not the full same package so it doesn't count as xtensor

**Review by adityapande-1995 — APPROVED** [review]

**Comment by adityapande-1995** [comment]
@ivanpauno could you please take a look at this one ? LGTM

**Review by ivanpauno — APPROVED** [review]

**Pull request merged**
