### PR TITLE
[ROS Noetic] Unrelease collada_urdf_jsk_patch and bayesian_belief_networks

### PR DESCRIPTION
**Pull request by sloretz**
Has always failed to build on all platforms.

https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/213
https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/215

Partially reverts https://github.com/ros/rosdistro/pull/26088 @k-okada FYI

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
LGTM; waiting for another reviewer to double check and merge :bow:

**Comment by mabelzhang** [comment]
Looks good to me? But I have no idea the implications. The world can't be as innocent as it looks. I'm gonna let someone more useful approve this.

**Comment by k-okada** [comment]
@sloretz @mabelzhang I think https://github.com/ros/rosdistro/pull/26311 fixed issues.

**Comment by sloretz** [comment]
Closing in favor of #26311

**Pull request closed without merging**
