### PR TITLE
Adding python-gpxpy

### PR DESCRIPTION
**Pull request by mr337**
Added python pip package as python-gpxpy since not available as a system package.

gpxpy (https://github.com/tkrajina/gpxpy) we use for reading and writing GPX files.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@mr337 This package is available in upstream ubuntu and debian. So we should use those rather than the python installer for the platforms it's available: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules

Also CI is failing because this is not in alphabetical order in the list

**Comment by mr337** [comment]
Let me get both of those fixed!

**Comment by mikaelarguedas** [comment]
Thanks @mr337 for iterating. I removed sid as per [contributions guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules)

Can you also add the gentoo rule please? [`sci-geosciences/gpxpy`](https://packages.gentoo.org/packages/sci-geosciences/gpxpy)

**Comment by mr337** [comment]
Done @machielbruinink , I apologize for adding 'sid', was skimming the docs and once I ready OSX my eyes glazed over.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks for iterating

**Pull request merged**
