### PR TITLE
Enable test_pull_requests for phidgets_drivers

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am not sure you have followed these instructions to provide the necessary access for the ROS buildfarm GitHub user to the org unit yet?

**Comment by mintar** [comment]
No, I haven't. I was hoping that the Jenkins user already has access to the ros-drivers org. Do you have any way to check?

**Comment by mintar** [comment]
I've added another commit to move phidgets_drivers on indigo to ros-drivers as well. Everything else would get confusing anyway. :)

**Comment by dirk-thomas** [comment]
Looks good. Thanks for iterating.

**Pull request merged**
