### PR TITLE
[I, J] Add meta-ros doc

### PR DESCRIPTION
**Pull request by 130s**
https://github.com/bmwcarit/meta-ros/issues/357#issuecomment-143976855
@bulwahn

### CODE REVIEW

**Comment by vrabaud** [comment]
hydro is e.o.l-ed, please remove.

**Comment by 130s** [comment]
Done.

(I was going to ask "even only the document update isn't allowed?" but looks like test failed maybe for Hydro.)

**Comment by vrabaud** [comment]
not sure if it's allowed. But you forgot ```:``` after meta-ros

**Comment by 130s** [comment]
> But you forgot : after meta-ros

Sorry, now corrected.

**Pull request merged**
