### PR TITLE
add libcos4-dev

### PR DESCRIPTION
**Pull request by eisoku9618**
For libcos4-dev

Ubuntu: https://packages.ubuntu.com/bionic/libcos4-dev

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@eisoku9618 thanks for linking to the Ubuntu package. It would be really helpful to us if you could add rules for the other common platforms, Debian and Fedora.

**Comment by eisoku9618** [comment]
debian: https://packages.debian.org/stretch/libcos4-dev

@nuclearsandwich I've added a rule for Debian. There is no corresponding package in Fedora.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
> [](https://packages.debian.org/stretch/libcos4-dev)
> 
> @nuclearsandwich I've added a rule for Debian. There is no corresponding package in Fedora.

Thanks for checking!

**Comment by eisoku9618** [comment]
@cottsay Could you merge this PR?

**Review by clalancette — APPROVED** [review]

**Comment by eisoku9618** [comment]
Thank you @nuclearsandwich and @clalancette

**Pull request merged**
