### PR TITLE
Update git url of multipoint_navigation_receiver

### PR DESCRIPTION
**Pull request by SuperAruba**
Update git url

### CODE REVIEW

**Review by tfoote — DISMISSED** [review]
This looks to have a merge conflict with your other changes. Please rebase this onto master for us to review.

**Comment by SuperAruba** [comment]
Now, I have pulled and resubmitted

**Review by jacobperron — APPROVED** [review]

**Comment by dirk-thomas** [comment]
@SuperAruba please keep one pull request to one semantic change. That allows to iterate on independent changes separately. E.g. using all uppercase names isn't used by any other repo so please use lowercase for the new entries.

**Comment by SuperAruba** [comment]
Now,I have force rollback to "Update url".Should I submit other content separately after this modification is successful?

**Comment by dirk-thomas** [comment]
> Should I submit other content separately after this modification is successful?

Yes please.

**Pull request merged**
