### PR TITLE
add protobuf-c-compiler package

### PR DESCRIPTION
**Pull request by hakuturu583**
Please add the following dependency to the rosdep database.

## Package name:

protobuf-c-compiler

## Package Upstream Source:

https://github.com/protobuf-c/protobuf-c

## Purpose of using this:

I plan to perform serialization in C to achieve communication between the microcontroller and ROS 2.
I need this package because I want to automatically generate the C source code to be used inside the microcontroller in the ROS 2 package.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/bookworm/protobuf-c-compiler
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/noble/protobuf-compiler-grpc
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/pkgs/protobuf-c/protobuf-c/
  - IF AVAILABLE
- Arch: https://archlinux.org/packages/extra/x86_64/protobuf-c/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/packages/dev-libs/protobuf-c
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/formula/protobuf-c#default
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/package/edge/main/x86_64/protobuf-c-compiler
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages?channel=24.05&size=50&sort=relevance&type=packages&query=protobuf-c
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/protobuf-c
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/8/raven-x86_64/protobuf-c-compiler-1.5.0-3.el8.x86_64.rpm.html
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

protobuf-c-compiler

# The source is here:

https://github.com/protobuf-c/protobuf-c

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by hakuturu583** [comment]
I could not understand what the error is...

```
=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        files = os.listdir('rosdep')
    
        with Fold() as fold:
            print("""Running 'scripts/check_rosdep.py' on all '*.yaml' in the 'rosdep' directory.
    If this fails you can run 'scripts/clean_rosdep_yaml.py' to help cleanup.
    """)
    
            for f in sorted(files):
                fname = os.path.join('rosdep', f)
                if not f.endswith('.yaml'):
                    print("Skipping rosdep check of file %s" % fname)
                    continue
                print("Checking rosdep file: %s" % fname)
>               assert check_rosdep(fname), fold.get_message()
E               AssertionError: see folded block 'block2' above for details
E               assert False
E                +  where False = check_rosdep('rosdep/base.yaml')

test/rosdep_formatting_test.py:24: AssertionError
=========================== short test summary info ============================
FAILED test/rosdep_formatting_test.py::test - AssertionError: see folded block 'block2' above for details
assert False
 +  where False = check_rosdep('rosdep/base.yaml')
```

**Comment by mjcarroll** [comment]
The error was a little further up in the log:

```
No 'protobuf-c-compiler' package for openembedded master (). Looking for variants...
```

**Comment by mjcarroll** [comment]
@hakuturu583 I believe that you need to tweak the openembedded key for this to pass linting.

**Comment by clalancette** [comment]
No activity in a number of weeks, so I'm going to close this out.  If you'd still like to get this in, please feel free to address the feedback and reopen.  Thanks for the contribution.

**Pull request closed without merging**
