### PR TITLE
Improve license parsing

### LINKED ISSUE #271: License parsing doesn't parse e.g. LGPLv3 correctly
When regenerating recipes for newer eloquent release from 2020-01-24, I've noticed that generated mavlink recipe has license LGPL-2 while the original package.xml has LGPLv3 (https://github.com/mavlink/mavlink-gbp-release/blob/release/eloquent/mavlink/2019.12.30-1/package.xml#L20)

Which for OE triggers this warning:
```
WARNING: mavlink-2019.12.30-1-r0 do_populate_lic: mavlink: No generic license file exists for: LGPL-2 in any provider
```
because LGPL-2 isn't valid SPDX identifier (https://spdx.org/licenses/) nor OE licenses.conf has mapping from LGPL-2 to the valid LGPL-2.0 (http://git.openembedded.org/openembedded-core/tree/meta/conf/licenses.conf#n28)

Mapping LGPLv3 to LGPL-2 is quite wrong and dangerous. I've tried to update the regexps here:
https://github.com/ros-infrastructure/superflore/blob/master/superflore/utils.py#L149
but that's also a bit error prone with the free form of license identifiers people are using in package.xml.

What do you think about using exact mapping for known identifier variants, like licenses.conf in OE does http://git.openembedded.org/openembedded-core/tree/meta/conf/licenses.conf and then mapping them only to valid SPDX identifiers or issuing the warning and passing the value when it's not one of the explicitly supported variants?

That would also cover the issue that LGPL (without any version) is currently being mapped to this LGPL-2 which is very misleading when the actual license in the component is LGPL-3.0.

I have already couple cases in `meta-ros` (mostly from `melodic` release) where this happens:
```
meta-ros1-melodic/recipes-bbappends/navigation/amcl_1.16.3-1.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/navigation/amcl_1.16.3-1.bbappend-LICENSE = "LGPL-2.1+"
meta-ros1-melodic/recipes-bbappends/navigation/amcl_1.16.3-1.bbappend-
--
meta-ros1-melodic/recipes-bbappends/open-karto/open-karto_1.2.0.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/open-karto/open-karto_1.2.0.bbappend-LICENSE = "LGPL-3.0"
--
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_1.4.0.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_1.4.0.bbappend-# https://github.com/orocos/orocos-kdl-release/issues/4
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_1.4.0.bbappend-LICENSE = "LGPL-2.1"
--
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kinematics-dynamics_1.4.0.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kinematics-dynamics_1.4.0.bbappend-# https://github.com/orocos/orocos-kdl-release/issues/4
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/orocos-kinematics-dynamics_1.4.0.bbappend-LICENSE = "LGPL-2.1"
--
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/python-orocos-kdl_1.4.0.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/python-orocos-kdl_1.4.0.bbappend-# https://github.com/orocos/orocos-kdl-release/issues/4
meta-ros1-melodic/recipes-bbappends/orocos-kinematics-dynamics/python-orocos-kdl_1.4.0.bbappend-LICENSE = "LGPL-2.1"
--
meta-ros1-melodic/recipes-bbappends/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bbappend-# https://github.com/ANYbotics/rqt_multiplot_plugin/issues/35
meta-ros1-melodic/recipes-bbappends/rqt-multiplot-plugin/rqt-multiplot_0.0.10.bbappend-LICENSE = "LGPL-3.0"
--
meta-ros1-melodic/recipes-bbappends/slam-karto/slam-karto_0.8.1.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/slam-karto/slam-karto_0.8.1.bbappend-# https://github.com/ros-perception/slam_karto/issues/28
meta-ros1-melodic/recipes-bbappends/slam-karto/slam-karto_0.8.1.bbappend-LICENSE = "LGPL-3.0+ & CC-BY-2.0"
--
meta-ros1-melodic/recipes-bbappends/variant/variant-msgs_0.1.5.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/variant/variant-msgs_0.1.5.bbappend-# https://github.com/ANYbotics/variant-release/issues/1
meta-ros1-melodic/recipes-bbappends/variant/variant-msgs_0.1.5.bbappend-LICENSE = "LGPL-3.0+"
--
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-test_0.1.5.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-test_0.1.5.bbappend-# https://github.com/ANYbotics/variant-release/issues/1
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-test_0.1.5.bbappend-LICENSE = "LGPL-3.0+"
--
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-tools_0.1.5.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-tools_0.1.5.bbappend-# https://github.com/ANYbotics/variant-release/issues/1
meta-ros1-melodic/recipes-bbappends/variant/variant-topic-tools_0.1.5.bbappend-LICENSE = "LGPL-3.0+"
--
meta-ros1-melodic/recipes-bbappends/variant/variant_0.1.5.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros1-melodic/recipes-bbappends/variant/variant_0.1.5.bbappend-# https://github.com/ANYbotics/variant-release/issues/1
meta-ros1-melodic/recipes-bbappends/variant/variant_0.1.5.bbappend-LICENSE = "LGPL-3.0+"
--
meta-ros2-dashing/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros2-dashing/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend-# https://github.com/ros2-gbp/orocos_kinematics_dynamics-release/issues/2
meta-ros2-dashing/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend-LICENSE = "LGPL-2.1"
--
meta-ros2-eloquent/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend:# Missing license version in package.xml maps it to invalid LGPL-2
meta-ros2-eloquent/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend-# https://github.com/ros2-gbp/orocos_kinematics_dynamics-release/issues/2
meta-ros2-eloquent/recipes-bbappends/orocos-kinematics-dynamics/orocos-kdl_3.2.1-1.bbappend-LICENSE = "LGPL-2.1"

```

### PR DESCRIPTION
**Pull request by shr-project**
Fixes https://github.com/ros-infrastructure/superflore/issues/271

Corresponding changes for catkin_pkg:
https://github.com/ros-infrastructure/catkin_pkg/pull/296

### CODE REVIEW

**Comment by clalancette** [comment]
@shr-project Friendly ping; what's the status of this PR?  It is still marked as "Draft".

**Comment by shr-project** [comment]
> @shr-project Friendly ping; what's the status of this PR? It is still marked as "Draft".

@clalancette It depends on https://github.com/ros-infrastructure/catkin_pkg/pull/296 which wasn't merged yet

**Review by ivanpauno — COMMENTED** [review]
Though the idea is nice, I'm not sure if a check like this can be added:

- I don't think we currently require a license to have a spdx identifier.
  e.g.: if someone wants to add a package with a customly modified MIT license, I think that's currently being accepted (though I'm not completely sure).
- There's currently lots of packages that aren't using a valid spdx identifier in the package.xml license field.
  I've seen lots of packages that have "BSD" as the identifier.
  To avoid the burden of correcting all the existing packages, we could only apply this test to packages being added/modified by the PR in question.

**Comment by hidmic** [comment]
@shr-project friendly ping.

**Comment by shr-project** [comment]
@hidmic I'm sorry, I don't have the test environment for this anymore and don't work on meta-ros (where the license parsing changes were already applied through superflore).

Someone else will need to pick this up or close, sorry.

**Comment by ivanpauno** [comment]
There hasn't been any progress in a long time, so I will close the PR.
@shr-project if you or someone else are planning to pick this up feel free to reopen or open a new PR.

**Pull request closed without merging**
