### PR TITLE
solving the dependency issue

### PR DESCRIPTION
**Pull request by mehdish89**
'rqt_dyn_tune' dependency on 'dyn_tune' is added in the distribution.yaml

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Does the documentation fail to generate without this ? rosdoc_lite seems to run without error.
@dirk-thomas do you know why an expllicit dependency is necessary here ? It doesnt seem that any other ROS package in kinetic need it

**Comment by mehdish89** [comment]
@mikaelarguedas yes it does. 'rqt_dyn_tune' depends on another package i am indexing 'dyn_tune'. and because 'dyn_tune' is not released, apparently it cannot be resolved as a dependency on Jenkins. @tfoote suggested to use this format.

**Comment by mikaelarguedas** [comment]
Ok so this is necessary because the package is not released and is using package format 1 so cannot declare the doc depend directly in the package.xml. That must be a rare situation expllaining why I didnt see it before. Thanks for clarifying!

**Comment by tfoote** [comment]
@mikaelarguedas I believe you still need the dependency in the rosdistro even if it's format2 if it's unreleased since the rosdistro doesn't have the repo to package indexing available for unreleased packages.

**Comment by mikaelarguedas** [comment]
@tfoote oh interesting, thanks for the info. I need to learn more about how doc jobs work :/.
So if `dyn_tune` was released but `rqt_dyn_param` was not, this would work without adding the depend here ? (we can move the discussion somewhere else, I'm just asking questions to make more correct comments in the future and understand how the other unreleased packages work without this extra step)

**Comment by dirk-thomas** [comment]
> So if `dyn_tune` was released but `rqt_dyn_param` was not, this would work without adding the depend here ?

Correct.

**Pull request merged**
