### PR TITLE
catkin_virtualenv: 0.6.0-1 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by paulbovbel**
Increasing version of package(s) in repository `catkin_virtualenv` to `0.6.0-1`:

- upstream repository: https://github.com/locusrobotics/catkin_virtualenv.git
- release repository: https://github.com/locusrobotics/catkin_virtualenv-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.9.7`
- previous version for package: `null`

## catkin_virtualenv

```
* Don't require catkin_package to be called before catkin_generate_virtualenv (#67 <https://github.com/locusrobotics/catkin_virtualenv/issues/67>)
* Revert "Downgrade docutils so that boto works (#66 <https://github.com/locusrobotics/catkin_virtualenv/issues/66>)"
  This reverts commit 998cd6add2e43e12036d0db15a7c4d58fe3411cf.
* Downgrade docutils so that boto works (#66 <https://github.com/locusrobotics/catkin_virtualenv/issues/66>)
  See https://github.com/boto/botocore/issues/1942 and related threads.
* Make regex for Python bytecode more selective (#65 <https://github.com/locusrobotics/catkin_virtualenv/issues/65>)
  Fix regex to match only files ending in ".py[co]" and not files ending
  in "py[co]".
* Remove user specific paths (#63 <https://github.com/locusrobotics/catkin_virtualenv/issues/63>)
  * Remove user specific paths
  * Change working directory of venv_lock command
  * Lock catkin_virtualenv base requirements
  Co-authored-by: Paul Bovbel <mailto:paul@bovbel.com>
* RST-3172 Check that requirements file is locked (#62 <https://github.com/locusrobotics/catkin_virtualenv/issues/62>)
* Two helpful hints (#61 <https://github.com/locusrobotics/catkin_virtualenv/issues/61>)
* Fix input requirements warning (#58 <https://github.com/locusrobotics/catkin_virtualenv/issues/58>)
  * Only warn about INPUT_REQUIREMENTS if a package exports requirements to begin with
  * Update catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
  Co-authored-by: Andrew Blakey <mailto:ablakey@gmail.com>
  Co-authored-by: Andrew Blakey <mailto:ablakey@gmail.com>
* Preserve symlinks during copy (#57 <https://github.com/locusrobotics/catkin_virtualenv/issues/57>)
* Don't ignore unknown args
* RST-3172 Refactor catkin_virtualenv to allow locking dependencies (#55 <https://github.com/locusrobotics/catkin_virtualenv/issues/55>)
  * Remove unused options
  * Fix regex for comments
  * Migrate scripts
  * Remove old code
  * Move common requirements to an export file
  * Minor cleanup
  * Remove requirement-parsing unit tests
  * Fix logging config
  * Fix test builds
  * Generate lock files
  * Fix tests
  * Move dh-virtualenv functions into separate file
  * Fix roslint
  * Update docs
  * Update requirements
  * CMake comments
  * Fix pip-args
  * README fixup
  * Correct ARG_LOCK_FILE handling
  * Remove headers
  * Use set comprehension
  * Add migration doc
  * Respin
* Use exec to dive into python (#51 <https://github.com/locusrobotics/catkin_virtualenv/issues/51>)
* First python2 issue of 2020 (#49 <https://github.com/locusrobotics/catkin_virtualenv/issues/49>)
  * Clean up options, virtualenv installs setuptools by default
  * Make sure we install a compatible setuptools version for py2 venv
* catkin-pkg-modules has disappeared off pypi (#46 <https://github.com/locusrobotics/catkin_virtualenv/issues/46>)
  * catkin-pkg-modules has disappeared off pypi, but catkin-pkg is still there
  * Version all requirements
* Contributors: David V. Lu!!, Michael Johnson, Paul Bovbel, abencz
```

### CODE REVIEW

**Review by sloretz — DISMISSED** [review]
@paulbovbel it looks like `catkin_virtualenv` has some Python 2 dependencies listed in the `package.xml`, but ROS Noetic is targeting Python 3. Is that intentional?

https://github.com/locusrobotics/catkin_virtualenv-release/blob/e308c52686ebd640bac6706d0df1c18c4cb52a66/package.xml#L34

https://github.com/locusrobotics/catkin_virtualenv-release/blob/e308c52686ebd640bac6706d0df1c18c4cb52a66/package.xml#L40

If not, please consider [using package format 3 and conditional dependencies](http://wiki.ros.org/UsingPython3/SourceCodeChanges#Conditional_Dependencies) so the `ros-noetic-catkin-virtualenv` debian package does not depend on them.

```xml
<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
...
  <build_export_depend condition="$ROS_PYTHON_VERSION == 2">python-virtualenv</build_export_depend>
...
  <build_export_depend condition="$ROS_PYTHON_VERSION == 2">virtualenv</build_export_depend>
...
```

**Comment by sloretz** [comment]
holding for the [upcoming Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2020-07-17/15434)

**Comment by paulbovbel** [comment]
@sloretz it is intentional - catkin_virtualenv allows a package to bundle either a python2 or python3 virtualenv, hence depending on both trees.

**Comment by paulbovbel** [comment]
> holding for the upcoming Noetic sync

missed that before requesting review, my bad.

**Review by sloretz — APPROVED** [review]

**Pull request merged**
