### PR TITLE
Add postgis for Wily and Xenial

### PR DESCRIPTION
**Pull request by cberner**

### CODE REVIEW

**Comment by tfoote** [comment]
+1 http://packages.ubuntu.com/search?keywords=postgresql there's only one version per ubuntu distro

@cberner Do these debian packages look equivalent? 

wheezy: https://packages.debian.org/wheezy/postgresql-9.1-postgis
jessie: https://packages.debian.org/jessie/postgresql-9.4-postgis-2.1

**Comment by wjwwood** [comment]
lgtm. It would be nice to get the Debian rules in too.

**Comment by cberner** [comment]
@tfoote, yes I think so

**Comment by cberner** [comment]
Updated to include the Debian packages

**Pull request merged**
