### PR TITLE
Update distribution.yaml

### PR DESCRIPTION
**Pull request by pabloinigoblasco**
Updating Smacc humble to 1.22.1-2

https://github.com/robosoft-ai/SMACC2-release

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
   - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by methylDragon** [comment]
Could you release this [via bloom](https://docs.ros.org/en/rolling/How-To-Guides/Releasing/Releasing-a-Package.html) instead?

**Comment by pabloinigoblasco** [comment]
I think we should remove the SMACC2 entry. I am getting this via bloom:

Failed to open pull request: AssertionError - Duplicate package name 'smacc2' exists in repository 'smacc2' as well as in repository 'SMACC2'

**Comment by clalancette** [comment]
> Failed to open pull request: AssertionError - Duplicate package name 'smacc2' exists in repository 'smacc2' as well as in repository 'SMACC2'

This shouldn't be.  There is only one repository for SMACC2 in here, and it matches the upstream named one.  Are you sure you didn't have something else going on locally?  It also looked like bloom totally failed, since CI is complaining it can't find things.

> I think we should replace the SMACC2 entry by a smacc2 entry.

In general, this shouldn't matter too much.  I have a slight preference for keeping it as `SMACC2` (since that matches the repository name), but I don't have a strong opinion about it.

**Comment by clalancette** [comment]
Actually I'm going to close this one in favor of #36408 for now, even though I don't think that is necessarily the direction we should go in.

**Pull request closed without merging**
