### PR TITLE
Add python-chainercv-pip entry

### PR DESCRIPTION
**Pull request by knorth55**
add `python-chainercv-pip` in `distro/python.yaml`
- `chainercv`:  https://github.com/chainer/chainercv

cc. @yuyu2172

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
The change looks good to me. Though the package fails to install on my ubuntu machine (16.04) because of missing dependencies

**Comment by tfoote** [comment]
If there are missing dependencies those should be caught in the rosdep rule. @knorth55 do you know what the dependencies are for installing?

**Comment by knorth55** [comment]
Dependencys are `cython` and `python-numpy`.
I added these dependencies and update this PR.

**Comment by knorth55** [comment]
it seems that `python-numpy` is always installed in ros, I removed its dependency.

**Comment by knorth55** [comment]
I made a mistake and close PR.
I reopend, sorry.

**Comment by knorth55** [comment]
I checked with docker image and my osx machine and resolve the dependency problem!

**Review by mikaelarguedas — APPROVED** [review]
LGTM, thanks for the follow-up

**Pull request merged**
