### PR TITLE
Removed source builds from recent commit f3c15d0

### PR DESCRIPTION
**Pull request by kmhallen**

### CODE REVIEW

**Comment by wjwwood** [comment]
We can certainly do this, but if the reason is to disable the build farm trying to build each commit you make, you can do that with the `test_commits: false` line inside the `source:` block.

**Comment by dirk-thomas** [comment]
The advantage of the approach @wjwwood mentioned is that users can still easily fetch your code using tools like `rosinstall_generator`.

**Comment by wjwwood** [comment]
Hmm, looks like something went wrong and now you're partially removing the doc sections. You'll either have to undo that or remove the `doc:` line as well (if you're intention is disable doc jobs). You want something like this:

```yaml
  dataspeed_can:
    doc:
      type: hg
      url: https://bitbucket.org/dataspeedinc/dataspeed_can
      version: default
    source:
      test_commits: false
      type: hg
      url: https://bitbucket.org/dataspeedinc/dataspeed_can
      version: default
    status: developed
```

**Comment by kmhallen** [comment]
Fixed, silly mistake...

**Comment by wjwwood** [comment]
No worries, thanks for fixing it up quickly.

**Pull request merged**
