### PR TITLE
Add python3 opencv dependency for ubuntu

### PR DESCRIPTION
**Pull request by gaoethan**
Ubuntu: https://packages.ubuntu.com/bionic/python3-opencv

Now only add for ubuntu firstly to use, because it's already on the way for the other Linux flavors while they're finally ready and stable, e.g Debian: https://packages.debian.org/search?keywords=python3-opencv

### CODE REVIEW

**Comment by tfoote** [comment]
Please go ahead and add the debian rule. Since it's already in buster and that's no longer a rolling release we can target dependencies in it.

**Comment by mikaelarguedas** [comment]
This package is not available on ubuntu xenial that is targeted by 2 active ROS 2 distributions.
So the rule should be modified to target bionic only or add an explicit `null` entry for the other active ubuntu distributions

**Comment by gaoethan** [comment]
The support to debian buster has already been enabled @tfoote 
For Ubuntu Xenial, even though it has no python3-opencv, it has pip support via `pip3 install opencv-python` and I added its pip enabling instead of `null`, but not sure whether it will invoke **pip3 but not pip** with the following rule @mikaelarguedas  

```
xenial:
      pip:
        packages: [opencv-python]
``` 

thanks !

**Comment by mikaelarguedas** [comment]
> but not sure whether it will invoke pip3 but not pip with the following rule

It will invoke pip and not pip3. Support for pip3 is not available in rosdep at the moment.
It also looks like this package is not working out of the box at the moment because of missing dependencies:
```
# pip3 install opencv-python
# python3
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by gaoethan** [comment]
okay. thanks for clarification, I've already set it to `null` for ubuntu:xenial

**Review by mikaelarguedas — APPROVED** [review]
lgtm,

added a `null` rule for debian stretch as well in https://github.com/ros/rosdistro/pull/18686/commits/f0b85671710223c6853a5aebfbabc4bfc157d3ae

**Comment by mikaelarguedas** [comment]
@ros/rosdistro-maintainers can I get a second review on this please?

**Comment by dirk-thomas** [comment]
I don't understand what the `null` entries are for? There is no usage of a wildcard so what is the purpose of the `null` entries compared to them not being present?

**Comment by mikaelarguedas** [comment]
oh right, we added the null entry originally because these were global rules to start with (`ubuntu: [python3-opencv]`) now that distros are listed explicitly the null entries are not necessary anymore

**Comment by mikaelarguedas** [comment]
Updated in https://github.com/ros/rosdistro/pull/18686/commits/c4025f1a15b8a71a70e82e5e9797f9c80cc98862

**Review by dirk-thomas — APPROVED** [review]
LGTM

Should Artful / Cosmic be added to?

**Comment by mikaelarguedas** [comment]
As this was a key expected for ROS 2 usage we didnt bother (we added only distros targeted by active ROS2 distributions).

But it doesn't hurt to add them if we think it's better. I don't feel storngly either way as we currently don't have guidelines for python 3 packages

**Comment by dirk-thomas** [comment]
Fine with me. Can merge as is.

**Pull request merged**
