### PR TITLE
rosdep: add some openeuler support.

### PR DESCRIPTION
**Pull request by Z572**
hello, i add some openeuler package at rosdep
and other pr
https://github.com/ros-infrastructure/rospkg/pull/260
https://github.com/ros-infrastructure/rosdep/pull/919

### CODE REVIEW

**Comment by mjcarroll** [comment]
Thanks for the contribution.  As this depends on the rospkg and rosdep prs outlined above, I'm going to mark it as draft until those are merged.

Can you also provide more context about the openeuler platform?  I'm currently unfamiliar with it and it's benefits.

**Comment by Z572** [comment]
openEuler (formerly EulerOS) is a Red-Hat-like Linux distribution. It is the successor of Huawei's EulerOS.

openEuler is an open source project incubated and operated by the OpenAtom Foundation.

It use DNF as package-management, but no base on other distribution, many package name are different from rhel, like RHEL named "libzstd-devel",but openEuler named "zstd-dev"

have some linux Commercial Editions base on it, see https://www.openeuler.org/en/download/commercial-release/

official website: https://www.openeuler.org/en/
use case: https://www.openeuler.org/en/showcase/
you can search package from https://pkgmanage.openeuler.org/Packagemanagement or https://oepkgs.net/

**Comment by clalancette** [comment]
Before we put these keys in here, I think we'll need openeuler support in rosdep itself.  That is, I don't think we should consider merging this until we come to consensus on https://github.com/ros-infrastructure/rosdep/pull/919 .

With that in mind, I'm actually going to close this out.  Once we figure out how we are moving forward with the PR above, please feel free to reopen.

**Comment by wuxiaoqiang12** [comment]
The rospkg PR [[#260](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rospkg/pull/260%5D(https://github.com/ros-infrastructure/rospkg/pull/260))]([https://github.com/ros-infrastructure/rospkg/pull/260](https://github.com/ros-infrastructure/rospkg/pull/260)) was closed, and its changes were merged through [[#274](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rospkg/pull/274%5D(https://github.com/ros-infrastructure/rospkg/pull/274))]([https://github.com/ros-infrastructure/rospkg/pull/274](https://github.com/ros-infrastructure/rospkg/pull/274)).
Also, rosdep PR [[#919](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rosdep/pull/919%5D(https://github.com/ros-infrastructure/rosdep/pull/919))]([https://github.com/ros-infrastructure/rosdep/pull/919](https://github.com/ros-infrastructure/rosdep/pull/919)) has been resolved by the merge of [[#1021](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rosdep/pull/1021%5D(https://github.com/ros-infrastructure/rosdep/pull/1021))]([https://github.com/ros-infrastructure/rosdep/pull/1021](https://github.com/ros-infrastructure/rosdep/pull/1021)).

Since all prerequisite work is now complete, would you mind reopening this PR for further review?

**Comment by Z572** [comment]
> The rospkg PR [[#260](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rospkg/pull/260%5D(https://github.com/ros-infrastructure/rospkg/pull/260))]([ros-infrastructure/rospkg#260](https://github.com/ros-infrastructure/rospkg/pull/260)) was closed, and its changes were merged through [[#274](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rospkg/pull/274%5D(https://github.com/ros-infrastructure/rospkg/pull/274))]([ros-infrastructure/rospkg#274](https://github.com/ros-infrastructure/rospkg/pull/274)). Also, rosdep PR [[#919](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rosdep/pull/919%5D(https://github.com/ros-infrastructure/rosdep/pull/919))]([ros-infrastructure/rosdep#919](https://github.com/ros-infrastructure/rosdep/pull/919)) has been resolved by the merge of [[#1021](https://www.doubao.com/chat/%5Bhttps://github.com/ros-infrastructure/rosdep/pull/1021%5D(https://github.com/ros-infrastructure/rosdep/pull/1021))]([ros-infrastructure/rosdep#1021](https://github.com/ros-infrastructure/rosdep/pull/1021)).
> 
> Since all prerequisite work is now complete, would you mind reopening this PR for further review?

The original repository has been deleted, so this pr cannot be reopen. Maybe you could create a new one instead?

**Pull request closed without merging**
