### PR TITLE
Mark Kinetic as end-of-life

### PR DESCRIPTION
**Pull request by tfoote**
We've finished the [final sync](https://discourse.ros.org/t/new-package-for-kinetic-kame-2021-05-11-final-sync/20370?u=tfoote). It's time to retire Kinetic.

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/kinetic-kame-officially-end-of-life/20394/1

**Review by hidmic — APPROVED** [review]
@tfoote let me know when you want this to go in.

**Comment by ipa-mdl** [comment]
@tfoote: Is there a reason why the [snapshots](http://snapshots.ros.org/kinetic/) of the final sync are still missing?

**Comment by tfoote** [comment]
It's a manual process that requires @nuclearsandwich 's time. We haven't had the time to automate the process.

**Pull request merged**
