### PR TITLE
Adding new repository for indexing: z_laser_projector

### PR DESCRIPTION
**Pull request by rluqueb**
Request to add _z_laser_projector_ repository for indexing.

The z_laser_projector package is a ROS wrapper for ZLP1 Z-LASER Projector, developed under the Focused Technical Project (FTP) grant instrument within the ROSIN (ROS-Industrial) EU project. This package provides libraries that allow the user to operate the device.

Thank you very much.

### CODE REVIEW

**Comment by ahcorde** [comment]
linters are not happy, do you mind to have a look ?

**Comment by rluqueb** [comment]
Yes of course, I'm looking for the errors

**Comment by dirk-thomas** [comment]
@rluqueb You need to move the new entry `z_laser_projector` *above* the existing entry `zeroconf_msgs` since the character `_` is alphabetically *before* the character A-Z. Then you should be able to readd the `source` and `status` without a problem.

**Comment by rluqueb** [comment]
Thank you very much for your help! @dirk-thomas

**Comment by dirk-thomas** [comment]
@rluqueb Do you also want to add a `source` entry (as in 166366f30a3d853d83078baff761afd01b74252c) in order to have a Jenkins job which runs CI for your repository?

**Comment by hidmic** [comment]
@rluqueb just to be sure: only indexing, no release?

**Comment by rluqueb** [comment]
@hidmic Yes only indexing. This repository is still in the first stage of the project and we plan to release it further on. Thank you for your comment

**Pull request merged**
