### PR TITLE
Add graph_reasoning to rosdistro

### PR DESCRIPTION
**Pull request by hridaybavle**
## Package names:

  * [graph_reasoning](https://github.com/snt-arg/graph_reasoning.git)
  
## Package Upstream Source:

https://github.com/snt-arg/graph_reasoning.git

## Purpose of using this:

Reasoning on the low-level graph (i.e planes) generated by [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git) for the automatic generation of high-level entities likes rooms, walls etc. 

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/snt-arg/graph_reasoning.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): GPLv3
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/snt-arg/graph_reasoning
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - Unfortunately the name is very generic, and doesn't really tell us what it does.  I'm going to suggest you rename this to `situational_graph_reasoning` or `snt_situational_graph_reasoning`, which will explain what it does a lot better.

**Comment by hridaybavle** [comment]
Hello @clalancette, could you update if the changes made to the repos names are okay?

**Review by clalancette — APPROVED** [review]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): GPLv3
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/snt-arg/situational_graphs_reasoning
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

I'm going to approve this, but I suggest that you update https://github.com/snt-arg/situational_graphs_reasoning/blob/develop/setup.py to add in the maintainer and license.

**Comment by hridaybavle** [comment]
Rebased with master :)

**Comment by clalancette** [comment]
Since I've merged in some of the other things, this one needs to be rebased again.  We're getting closer.

**Comment by hridaybavle** [comment]
@clalancette done!

**Comment by sloretz** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-06-07/38086)

**Pull request merged**
