### PR TITLE
Update default gazebo version on debian buster to 11

### PR DESCRIPTION
**Pull request by StefanFabian**
This would fix the inconsistency described in #27851

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
Thanks for the long hanging followup.

**Comment by mabelzhang** [comment]
For the 2nd approval, I tried to follow the conversations but it looks complicated. Is it normal that gazebo11 isn't actually listed as an available package in Buster? https://packages.debian.org/search?keywords=gazebo

**Comment by StefanFabian** [comment]
> Thanks for the long hanging followup.

I guess there was some miscommunication. I thought you guys would consider it and change it if there isn't any reason not to.
I'm always hesitant to make single-line change PRs for systems I can't even test on.
However, I've made an exception since the build server kept emailing me to remind me.

> For the 2nd approval, I tried to follow the conversations but it looks complicated. Is it normal that gazebo11 isn't actually listed as an available package in Buster? https://packages.debian.org/search?keywords=gazebo

I think it's available from the ros build farm / debian repo: http://packages.ros.org/ros/ubuntu/dists/buster/main/binary-amd64/Packages
but I'm not 100% sure and I don't have a debian system to confirm this.

**Comment by tfoote** [comment]
There's two versions of gazebo available on Buster gazebo9 is upstream gazebo11 is available from the ROS sources. 

Eloquent used gazebo9 on buster but is EOL: https://www.ros.org/reps/rep-2000.html#id36

Noetic uses gazebo11 on buster and is still supported. https://www.ros.org/reps/rep-0003.html#id23
Foxy uses gazebo11 on buster and is still supported. https://www.ros.org/reps/rep-2000.html#id37

Luckily Melodic only supports stretch so it doesn't confound this issue.

This will mean that the gazebo that you install on buster by the generic `gazebo` key will match the one in both of our active LTS releases instead of conflict. If you need gazebo 9 specifically you can use the `gazebo9` key. The key was originally picked for Eloquent

**Review by mabelzhang — APPROVED** [review]
Thanks for the explanation guys!

**Pull request merged**
