### PR TITLE
add OpenCV3 to lunar

### PR DESCRIPTION
**Pull request by vrabaud**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
looks like `libpng12-dev` doesn't exist in yakkety zesy and stretch. the new key is libpng-dev in [new ubuntus](http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libpng-dev&searchon=names) and [Debian Stretch](https://packages.debian.org/stretch/libpng-dev)
@vrabaud FYI

**Comment by vrabaud** [comment]
I saw there is a problem with libjasper too which does not exist in zesty ... http://packages.ubuntu.com/yakkety/libjasper-dev

**Comment by mikaelarguedas** [comment]
Yeah I saw that too. Rationale here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818193, maybe one of the alternative implementations mentioned in that thread will do the job?

**Comment by vrabaud** [comment]
Thx ! I'll remove it, who needs better image compression anyway ..... I heard of some cool format called WebP, I'll use it instead.

**Pull request merged**
