### PR TITLE
Revert "ompl: 1.3.2-2 in 'lunar/distribution.yaml' [bloom]"

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Reverts ros/rosdistro#16349

@mamoll FYI
See https://github.com/ros/rosdistro/pull/16349#issuecomment-344441361 for more information

### CODE REVIEW

**Review by tfoote — APPROVED** [review]

**Comment by mamoll** [comment]
In OMPL version 1.3.2 I changed the hacky custom OMPL cmake module to one that is auto-generated with the cmake `CMakePackageConfigHelpers` module. The new OMPL cmake module gets installed in `${prefix}/lib/cmake/ompl/omplConfig.cmake`, which is supposed to be in the cmake module path according to https://cmake.org/cmake/help/v3.10/command/find_package.html. Perhaps the build failure can be fixed by just changing `find_package(OMPL)` to `find_package(ompl)`? @davetcoleman , do you have time to check this out?

**Comment by davetcoleman** [comment]
I've looked at the build failure but I am not sure what fix is needed...

**Comment by tfoote** [comment]
The find_package is case sensitive so that will break everyone using the old name. You might be able to put in one with the old name and redirect to the new one with a deprecation warning. @dirk-thomas Do you have a way you might suggest doing this?

**Comment by dirk-thomas** [comment]
From the CMake docs:

> The command searches for a file called <name>Config.cmake or <lower-case-name>-config.cmake for each name specified.

Only the first pattern is case sensitive. The second one is case insensitive. But the variables the CMake config file sets should not change the case since that would break compatibility anyway.

**Comment by tfoote** [comment]
>Only the first pattern is case sensitive.
So for backwards compatibility @mamoll I'd strongly suggest keeping using OMPL as the CMake package name. In CMake terms ompl and OMPL are completely different. You should still be able to use the generated config, just pass it OMPL as the package name instead of ompl.

**Comment by mamoll** [comment]
> So for backwards compatibility @mamoll I'd strongly suggest keeping using OMPL as the CMake package name. In CMake terms ompl and OMPL are completely different. You should still be able to use the generated config, just pass it OMPL as the package name instead of ompl.

As far as I can tell the only ROS package that depends on ompl is `moveit_planners`. The following change in the moveit repo is sufficient to make everything work again (I can make it PR, @davetcoleman, but this is so minimal):
```
diff --git a/moveit_planners/ompl/CMakeLists.txt b/moveit_planners/ompl/CMakeLists.txt
index 697c8f353..a0a0698f6 100644
--- a/moveit_planners/ompl/CMakeLists.txt
+++ b/moveit_planners/ompl/CMakeLists.txt
@@ -20,7 +20,7 @@ find_package(catkin REQUIRED COMPONENTS
   eigen_conversions
   )
 
-find_package(OMPL REQUIRED)
+find_package(ompl REQUIRED)
 
 generate_dynamic_reconfigure_options("ompl_interface/cfg/OMPLDynamicReconfigure.cfg")
 
@@ -40,7 +40,6 @@ include_directories(ompl_interface/include
                     ${catkin_INCLUDE_DIRS}
                     ${OMPL_INCLUDE_DIRS})
 
-link_directories(${OMPL_LIBRARY_DIRS})
 link_directories(${catkin_LIBRARY_DIRS})
 link_directories(${Boost_LIBRARY_DIRS})
```

**Pull request merged**
