### PR TITLE
Prepare Rolling for platform transition.

### PR DESCRIPTION
**Pull request by marcoag**
As part of the transition process using the [rosdistro migration tools](https://github.com/ros/rosdistro/tree/master/migration-tools) we need an empty target distribution with the intended target platforms.

The first commit of this PR empties the repositories list which will get re-populated when the migration tool runs.
The second commit removes ubuntu jammy, adds ubuntu noble, and adds debian bookworm leaving RHEL9 in place.
It is easier to review each commit separately.

I'd like to get review of this pull request in two phases.

I'd like on review phase to approve the platform list and source ref as I prepare to run the migration tool. This PR won't be merged as-is once approved. Instead it will be used as the foundation for a migration using the commit after the pending `ros2-gbp` PRs are merged. Once those are merged I'll update here with the correct commit here and in the migration command.

Migration command:
```
python3 migration-tools/migrate-rosdistro.py --source rolling --dest rolling \
  --source-ref cf4a78801b6083b4898cec267a25bb2061cf333d \
  --release-org ros2-gbp \
```

Once the migration is complete, I'll update this PR and request a second phase of reviews for merging the completed migration.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@marcoag you can update and trivially resolve the merge conflicts with
```
git pull --rebase origin master
git checkout --theirs rolling (when rebasing "ours" is the new base and "theirs" are the changes that you're rebasing)
git add rolling
git rebase --continue
```

**Review by nuclearsandwich — COMMENTED** [review]
The updated platforms are right.

For the proposed command, the source ref argument is only a commit, not the GitHub commit url (i.e. `abc1234` rather than `https://github.com/ros/rosdistro/commit/abc1234`).

**Comment by nuclearsandwich** [comment]
cf4a78801b6083b4898cec267a25bb2061cf333d is the current commit on Rolling which be used as the source-ref

**Comment by nuclearsandwich** [comment]
I think we're ready for a first run.

**Review by clalancette — APPROVED** [review]

**Review by nuclearsandwich — APPROVED** [review]
We'll have to fix some of the packages that failed in follow-up PRs.

Many of these changes will be due to missing rosdep keys for Bookworm, which the non-interactive bloom in the script treats as equally fatal to missing Ubuntu dependencies but a manual run of bloom can override.

Other failures will need to be triaged and are most likely related to rosdep differences between jammy and noble.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-ros-2-rolling-for-the-transition-to-ubuntu-24-04/35673/8

**Pull request merged**
