### PR TITLE
Fix libjpeg mapping for OpenEmbedded (#21648)

### LINKED ISSUE #21648: Incorrect OE value for libjpeg in rosdep/base.yaml
Should be `jpeg` not `libjpeq-turbo`.

### PR DESCRIPTION
**Pull request by herb-kuta-lge**
Fixes #21648

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Hi @herb-kuta-lge is there any web listing of openembedded packages or other method we can use to check this change? Otherwise it is completely opaque to us as reviewers. Thanks!

**Comment by herb-kuta-lge** [comment]
In general, you can check for OE recipes using the [OE Layer Index for **thud**](http://layers.openembedded.org/layerindex/branch/thud/recipes/). However, in this case, you'll need to look at the recipe itself and see that the one for `libjpeg-turbo` provides `jpeg`: http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-graphics/jpeg/libjpeg-turbo_2.0.0.bb?h=thud#n25, which is the mapping to which this commit changes.

**Comment by nuclearsandwich** [comment]
So the updated key will still resolve to libjpeg-turbo but if ever a different library provided jpeg instead, this would still be valid?

**Comment by herb-kuta-lge** [comment]
If a different recipe ever declared that it provided `jpeg`, then, yes, it would be valid. OpenEmbedded would then warn that multiple recipes provide the same thing, and a PREFERRED_PROVIDER setting would need to be added to `meta-ros` to select the desired one.

**Review by tfoote — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
