### PR TITLE
rosdep: bionic: [ruby, ruby-dev] in 'rosdistro/ruby.yaml'

### PR DESCRIPTION
**Pull request by ivandariojr**
Added ruby and ruby-dev  for ubuntu: bionic.

### CODE REVIEW

**Comment by tfoote** [comment]
Closing and reopening to try to trigger travis

**Review by tfoote — APPROVED** [review]
Travis is passing but the status isn't being reported back here.
Link from above pending button: https://travis-ci.org/ros/rosdistro/builds/426881519?utm_source=github_status&utm_medium=notification

**Review by mikaelarguedas — APPROVED** [review]
lgtm, I added https://github.com/ros/rosdistro/pull/19097/commits/a9818e03b2668d8a21572a3742c1245ba10bc4eb to apply the same logic for new Debian distros (I started with buster as the stretch key has been used in Lunar for a while)

**Comment by tfoote** [comment]
Good catch @mikaelarguedas There's still overlap on some of the others but we can let that be for now as too many dependencies is not the end of the world.

**Pull request merged**
