### PR TITLE
Added can-utils for wily and xenial.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]
Since all names are the same I would suggest to remove the specific Ubuntu distros names to avoid the maintenance effort on the future.

**Comment by tonybaltovski** [comment]
It is missing is precise.  Not sure if it that matters any more.

**Comment by dirk-thomas** [comment]
No non-EOL ROS distro supports "precise" anymore. Therefore I wouldn't spend effort on maintaining this entry but collapse them.

**Comment by tonybaltovski** [comment]
Sounds good, thanks.

**Review by tfoote — APPROVED** [review]
I made the debian rule more generic too. Since can-utils is available for stretch and sid too.

https://packages.debian.org/stretch/can-utils

It's good to go once ci passes.

**Comment by tonybaltovski** [comment]
Are packages in testing available by default in Debian? Jessie was the only one with can-utils in stable.

**Comment by tfoote** [comment]
Yes, Stretch itself is "testing" at the moment. Jessie is the "stable" release. Eventually Stretch will transition from "testing" to "stable" and jessie will be eol'd.

**Comment by tonybaltovski** [comment]
Perfect, thanks!

**Pull request merged**
