### PR TITLE
python-twisted-core on yakkety and zesty

### PR DESCRIPTION
**Pull request by jihoonl**

### CODE REVIEW

**Comment by jihoonl** [comment]
Required to release rosbridge_suite in lunar

**Comment by mikaelarguedas** [comment]
@jihoonl can you please collapse the ubuntu rules into a single one? `ubuntu: [python-twisted-core]`
That will allow to not have to add each platform individually in the future

**Comment by jihoonl** [comment]
Done.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks for iterating

**Pull request merged**
