### PR TITLE
Adding voronoi_planner to documentation index for distro    

### PR DESCRIPTION
**Pull request by frontw**
I'd like voronoi_planner to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by vrabaud** [comment]
branch indigo does not exist

**Comment by frontw** [comment]
Branch indigo added.
Would it retry automatically?

**Comment by vrabaud** [comment]
no: how would it know when to retry ? Just triggered it though so we'll see.

**Comment by vrabaud** [comment]
you can also set your version to master if you know you only have one branch

**Pull request merged**
