### PR TITLE
robosense: 1.0.1-0 in 'melodic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by amc-nu**
Increasing version of package(s) in repository `robosense` to `1.0.1-0`:

- upstream repository: https://github.com/CPFL/robosense.git
- release repository: https://github.com/CPFL/robosense-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.7.2`
- previous version for package: `null`

## rslidar_driver

```
* Fixes to packages and missing install commands
* Added install commands
* Fixed conflict with velodyne when installing on shared space
* renamed driver_nodelet to rsdriver_nodelet
* Fixed CMake, packages and Launch files
* Merge branch 'cut_angle_and_difop' into develop-curves-function
* bug: fix scan stamp mistake npackets - 1 to back in cut angle
* Merge branch 'develop-curves-function' of 192.168.1.20:system_group/ros_rslidar into develop-curves-function
* perf:improve the ordered pointcloud code
* fix:change "velodyne" to "rslidar"
* refactor:rename port to msop_portRename the port to msop_portDelete the uncessary debug information
* style: clang format code files and less cmake warning
* perf: set CMAKE_BUILD_TYPE Release, cpu drop from 28% to 19%
* feat: add the cut at specific angle featureIf the cut_angle is set to (0-2pi), the cut at specific angle featureactivated, otherwise use the fixed packets number mode.
* feat: add nodelet version
* feat: add difop parse
* Fix the bug that add in the CMakelist
* Merge pull request #5 <https://github.com/CPFL/robosense/issues/5>_ from enwaytech/ml/fix_cmake_warningsml/fix cmake warnings
* [ros_rslidar] fixed cmake warnings, removed unneccessary deps
* Merge pull request #1 <https://github.com/CPFL/robosense/issues/1>_ from RoboSense-LiDAR/develop-curves-functionMerge latest robosense updates
* Remove the uncessary dependency in package.xml
* Merge pull request #2 <https://github.com/CPFL/robosense/issues/2>_ from enwaytech/fix_cmake_installremove wrong install instructions in CMakeLists
* remove wrong install instructions in CMakeLists
* Modify the readme.Add the rviz startup in launch file.
* Covert double to float2. Remove the re-defined variable.
* Reformate the code style.
* Modify the code expression.2. Remove the unnecessary variables.
* Modify the parameter for the type of lidar in the launch file and add the intensity into display of RS-32.
* Merge RS-16 and RS-32 code.
* formate the code in input.cc
* Modify the ip to device ip
* Add send message function when poll out
* Fix the unpack logic to avoid cloud to be empty
* Add the diagnostic_updater into build depend to avoid someone occur the compile error
* Fix the wrong delete the rslidarScan header file
* Delete double set header files
* Add the license declaration.
* Modify the CMakeLists to avoid compile error and remove some uncessary definition.
* Clear the code
* Delete the empty include directory
* Remove the uncessary PWR file content
* Add inlcude directory
* Remove the uncessary network configuration
* Add mutil lidar function
* Clear unnecessary variables.
* rslidar mutil node version 1.0.0
* Contributors: Bo Chen, Lizhongpeng, Matthias Loebach, Tony Zhang, amc-nu, baoxianzhang, guoleiming, zhangbaoxian
```

## rslidar_msgs

```
* Fixed CMake, packages and Launch files
* perf:improve the ordered pointcloud code
* Covert double to float 2. Remove the re-defined variable.
* Modify the code expression. 2. Remove the unnecessary variables.
* Remove the uncessary PWR file content
* rslidar mutil node version 1.0.0
* Contributors: Tony Zhang, amc-nu
```

## rslidar_pointcloud

```
* Fixes to packages and missing install commands
* install commands
* renamed conflicts on install space
* Added missing install commands
* Fixed conflict with velodyne when installing on shared space
* Merge https://github.com/RoboSense-LiDAR/ros_rslidar into develop-curves-function
* Merge branch 'develop-curves-function' of 192.168.1.20:system_group/ros_rslidar into develop-curves-function
* fix: the bug for dis_resolution_mode syntax
* feat: distance threshold as parameter pass by launch file
* fix: distance resolution type judgement error
* feat: add the default CurvesRate value 1.0
* feat: add 0.5cm support for RS16
* feat:add the 0.5cm resolution support
* feat: select the intensity mode into difop
* feat:add intensity factor
* feat: add intensity mode two
* fix: the parameter calculation should be 0.0001
* Renamed cloud_nodelet to rscloud_nodelet
* cloud_node renamed to rscloud_node, to play nice with other cloud_nodes
* Fixed CMake, packages and Launch files
* Merge branch 'cut_angle_and_difop' into develop-curves-function
* bug: fix scan stamp mistake npackets - 1 to back in cut angle
* fix: fix the minus missing bug in processDifop
* fix:the intensity calculation
* Merge branch 'develop-curves-function' of 192.168.1.20:system_group/ros_rslidar into develop-curves-function
* perf:improve the ordered pointcloud code
* fix:change "velodyne" to "rslidar"
* style: change the file mode
* refactor: Modify the readme
* fix: bug for intensity caculation
* refactor:rename port to msop_port
* fix: change difop data byte to both consider 0x00 and 0x ff
* style: clang format code files and less cmake warning
* perf: set CMAKE_BUILD_TYPE Release, cpu drop from 28% to 19%
* fix: fix check difop region not include 0xff case bug
* feat: add the cut at specific angle feature
* feat: add nodelet version
* fix: fix angle_flag from wrong position bug
* feat: add difop parse
* Delete the unnecessary debug output when load config files.
* Add the temperature into the old calIntensity function.
* add curves
* Merge pull request from RoboSense-LiDAR/develop-curves-function
* Remove the unnecessary dependency in package.xml
* Comment the judgement for ChannelNum colums. Do not use sigle columns.
* Remove round function in the calculation of intensity.
* Add curvesRate function for RS-LiDAR-32
* Remove a annotation.
* Add temperature compensation.
* Upload again for the last commit.
* Fix the bug for read parameter for curves function.
* Remove an output.
* Add curves function.
* Change the temperature range for RS32 from 31-71 to 31-81.
* Fix the build bug for catkin build.
* Remove an output.
* Add curves function.
* Modify the readme.
* Modify the readme to compatible with the new code structrue.
* Covert double to float 2. Remove the re-defined variable.
* Remove unnecessary log information
* Reformate the code style.
* Modify the 16 beams and 32 beams unpack function logic to simplify the code.
* Modify the code expression. 2. Remove the unnecessary variables.
* Merge branch 'develop-RS16-RL32' of 192.168.1.20:system_group/ros_rslidar into develop-RS16-RL32
* Delet unnecessary parameters.
* Adjust the file structure to compitable with 16 beams and 32 beams
* Fix the bug in the last commit.
* Fix the bug in the calculation of azimuth interpolation.
* Fix the bug of abnormal display color for intensity when the original intensity value is zero.
* Modify the parameter for the type of lidar in the launch file and add the intensity into display of RS-32.
* Merge RS-16 and RS-32 code.
* Change the temperature 70 to 71. Replace the default file on lidar1 and lidar2 directory to all 0.
* Change the temperature from 30 to 31
* Comment the debug log for temperature 2. Replace the default ChanneNum to 41 colunm 0.
* Ingnore the abnormal angle packet. Remove the ChannleNum column judge
* Add device ip parameters in the launch file
* Remove the opencv
* update temperature per 20000 packets
* add temperature version
* Modify the configuration path setting 2. Modify the launch file according to the new path setting
* Modify the max distance to 180m
* Change the X&Y axis direction.
* Modify the intensity caculate formula to compitable with rslidar-16 2.0
* Improve the code runtime
* Fix the unpack logic to avoid cloud to be empty
* code style fix
* Delete double set header files
* Updated the license declaration
* Add the license declaration.
* Modify the CMakeLists to avoid compile error and remove some unnecessary definition.
* Updated the launch file example
* Clear the code
* Delete the empty include directory
* Remove the unnecessary PWR file content
* Add inlcude directory
* Remove the unnecessary network configuration
* Add mutil lidar function
* Clear unnecessary variables.
* rslidar multi node version 1.0.0
* Contributors: Bo Chen, Lizhongpeng, Tony Zhang, amc-nu, baoxianzhang, guoleiming, songkan, zhangbaoxian, zhwu
```

### CODE REVIEW

**Comment by clalancette** [comment]
There are a couple of things that are unclear for this package:

1.  It seems like https://github.com/CPFL/robosense is forked from https://github.com/RoboSense-LiDAR/ros_rslidar.  While that in itself is not a problem, it does seem like @Tony-HIT is listed as the package maintainer.  What is the relationship between these forks?
1.  In several of the source files, it says that the license is "modified BSD", but the package.xml all say "BSD", and there doesn't seem to be a file anywhere that describes what the modifications are.  Can you clarify the license here?

**Comment by amc-nu** [comment]
@clalancette Thank you for your prompt reply.

> 1. It seems like https://github.com/CPFL/robosense is forked from https://github.com/RoboSense-LiDAR/ros_rslidar. While that in itself is not a problem, it does seem like @Tony-HIT is listed as the package maintainer. What is the relationship between these forks?

We forked this repo a while ago, and been using it to connect to the  LiDAR devices. We found some issues, and fixed [them](https://github.com/CPFL/robosense/commits/develop-curves-function). We also itegrated CI, and tried to push these improvements to [original repo](https://github.com/RoboSense-LiDAR/ros_rslidar/pull/6), but we haven't received reply from the original maintainers.

Anyway, after using it inside our [repository](https://github.com/CPFL/Autoware/blob/master/.gitmodules#L1), we realized the driver works well, and it hasn't changed in a while. So, we are trying to move the code to a debian, so it gets easily installed using `rosdep`. I'm sure this will also help other users, and simplify the setup of the device. 

> In several of the source files, it says that the license is "modified BSD", but the package.xml all say "BSD", and there doesn't seem to be a file anywhere that describes what the modifications are. Can you clarify the license here?

Good question. I'm not completely sure. However, since we also use Velodyne devices, and also modify their code, we realized the Robosense code is an adaptation of Velodyne's ROS [Driver](https://github.com/ros-drivers/velodyne).
For instance, [Velodyne's `driver.cc`](https://github.com/ros-drivers/velodyne/blob/master/velodyne_driver/src/driver/driver.cc) and [Robosense's `rsdriver.cc`](https://github.com/RoboSense-LiDAR/ros_rslidar/blob/develop-curves-function/rslidar_driver/src/rsdriver.cpp
).

Here is the original [Velodyne's Modified BSD License](https://github.com/ros-drivers/velodyne/blob/master/COPYING)

Please let me know if any update is required. I'll address it as soon as possible.

**Comment by clalancette** [comment]
> We forked this repo a while ago, and been using it to connect to the LiDAR devices. We found some issues, and fixed [them](https://github.com/CPFL/robosense/commits/develop-curves-function). We also itegrated CI, and tried to push these improvements to [original repo](https://github.com/RoboSense-LiDAR/ros_rslidar/pull/6), but we haven't received reply from the original maintainers.
> 
> Anyway, after using it inside our [repository](https://github.com/CPFL/Autoware/blob/master/.gitmodules#L1), we realized the driver works well, and it hasn't changed in a while. So, we are trying to move the code to a debian, so it gets easily installed using `rosdep`. I'm sure this will also help other users, and simplify the setup of the device.

Got it, thanks for the detailed explanation.  Since it does seem like a while between opening of that original PR and now, so I'm happy for this to go forwards.

> Good question. I'm not completely sure. However, since we also use Velodyne devices, and also modify their code, we realized the Robosense code is an adaptation of Velodyne's ROS [Driver](https://github.com/ros-drivers/velodyne).
> For instance, [Velodyne's `driver.cc`](https://github.com/ros-drivers/velodyne/blob/master/velodyne_driver/src/driver/driver.cc) and [Robosense's `rsdriver.cc`](https://github.com/RoboSense-LiDAR/ros_rslidar/blob/develop-curves-function/rslidar_driver/src/rsdriver.cpp).
> 
> Here is the original [Velodyne's Modified BSD License](https://github.com/ros-drivers/velodyne/blob/master/COPYING)

Thanks for the link.  Reading that license, it is word-for-word identical to the [BSD 3-clause license](https://opensource.org/licenses/BSD-3-Clause), with the exception that it replaces "copyright holders" with "University of Texas at Austin, nor Austin Robot Technology".  I guess that's the modification, though it is a little weird.  My main concern is that there is no explicit link between the "Modified BSD Software License Agreement" mentioned at the top of the source files, and the Velodyne license that you linked to.  There is, however, an implied link there, since as you mention the code does seem originally derived from the velodyne driver.

My suggestion here is to put a copy of the original velodyne "COPYING" file at the top of your repository.  I'd also recommend putting a comment at the top of the files that are clearly derived from the original velodyne sources, with a link to the file they were derived from.  With all of that in place, there won't be any ambiguity about the license or where it all came from.  Please let me know if you have any questions or concerns about this, and thanks for your patience.

**Comment by amc-nu** [comment]
@clalancette thanks for your prompt reply. I’ll attend and push those changes.

**Comment by amc-nu** [comment]
@clalancette Finished attending your kind suggestions. I pushed 3 commits:
* Adding a copy of the [license ](https://github.com/CPFL/robosense/commit/c6667f2cfcdd6cb2aef28092162f79eb9e3b0320)to our fork.
* Adding the license to each source [file ](https://github.com/CPFL/robosense/commit/e0809f5a597142fed78e38757367206031f0f92d)(which is common).
* [Updated ](https://github.com/CPFL/robosense/commit/c89b58327a3f8ef839f697c1a910e96043a770bf)the maintainer of the driver. (of course left the authorship).

Since I pushed new commits, should I create a new PR using catkin and bloom?

**Comment by clalancette** [comment]
> @clalancette Finished attending your kind suggestions. I pushed 3 commits:
> 
>     * Adding a copy of the [license ](https://github.com/CPFL/robosense/commit/c6667f2cfcdd6cb2aef28092162f79eb9e3b0320)to our fork.
> 
>     * Adding the license to each source [file ](https://github.com/CPFL/robosense/commit/e0809f5a597142fed78e38757367206031f0f92d)(which is common).
> 
>     * [Updated ](https://github.com/CPFL/robosense/commit/c89b58327a3f8ef839f697c1a910e96043a770bf)the maintainer of the driver. (of course left the authorship).

Fantastic, thanks, that is much easier to see what the license is.

> Since I pushed new commits, should I create a new PR using catkin and bloom?

Yes, that's the best thing to do.  Make sure to bump the patch number, then do another catkin/bloom release, and we should be good to go here.  Thanks for the quick turnaround.  I'll close this PR out in anticipation of a new one.

**Comment by amc-nu** [comment]
Thanks! I’ll do that.

**Pull request closed without merging**
