### PR TITLE
Add qml-module-qt-labs-settings

### PR DESCRIPTION
**Pull request by wep21**
Signed-off-by: wep21 <border_goldenmarket@yahoo.co.jp>

Please add the following dependency to the rosdep database.

## Package name:

qml-module-qt-labs-settings

## Package Upstream Source:

See https://doc.qt.io/qt-5/qt-labs-settings-qmlmodule.html.

## Purpose of using this:

This provides platform-independent application settings.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/bullseye/qml-module-qt-labs-settings
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/impish/qml-module-qt-labs-settings
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@wep21 can you please fill out the pull request template so we can review this pull request?

**Comment by wep21** [comment]
@nuclearsandwich I filled out the template. Could you review?

**Review by ivanpauno — APPROVED** [review]

**Review by hidmic — APPROVED** [review]

**Comment by hidmic** [comment]
@wep21 this now needs a rebase. Would you mind?

**Comment by wep21** [comment]
@hidmic rebased at https://github.com/ros/rosdistro/pull/31454/commits/a7ffd711b6ed212a7ec5ac09005155f3a944a53f.

**Comment by hidmic** [comment]
@wep21 much appreciated.

**Pull request merged**
