### PR TITLE
pr2_ethercat_drivers: 1.8.18-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by davefeilseifer**
Increasing version of package(s) in repository `pr2_ethercat_drivers` to `1.8.18-0`:

- upstream repository: https://github.com/PR2-prime/pr2_ethercat_drivers.git
- release repository: https://github.com/PR2-prime/pr2_ethercat_drivers-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.6.4`
- previous version for package: `1.8.17-0`

## fingertip_pressure

```
* updated maintainer
* Contributors: David Feil-Seifer
```

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
It looks like bloom is still using the previous release repository for the PR. I guess you want ot use this one instead ? https://github.com/PR2-prime/pr2_ethercat_drivers-release

**Comment by davefeilseifer** [comment]
yes, the old repositories are orphaned, so I'm making copies so that changes can be made.

**Comment by mikaelarguedas** [comment]
@davefeilseifer Can you please update the release repository URL on this PR ? The current URL will prevent the package to build as 1.8.18 in unknown from the previous release repository

**Comment by davefeilseifer** [comment]
done

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
