### PR TITLE
network_interface: 2003.1.1-2 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by cullenstoneAS**
Increasing version of package(s) in repository `network_interface` to `2003.1.1-2`:

- upstream repository: https://github.com/astuff/network_interface.git
- release repository: https://github.com/astuff/network_interface-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## network_interface

```
* Ros2 devel (#42 <https://github.com/astuff/network_interface/issues/42>)
  * changes for ros2
  * foxy ci
  * install boost library in docker container
* Contributors: cullenstoneAS
```

### CODE REVIEW

**Review by emersonknapp — APPROVED** [review]

**Comment by cottsay** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2023-09-11/33303)

**Comment by cullenstoneAS** [comment]
Do I need to do something about this rosdep checks issue? Seems to be caused by another package (unrelated to mine) not having a `main` branch.

**Comment by cottsay** [comment]
If in doubt, it's probably a good idea to merge `master` into your branch. Maybe the problem was already fixed.

**Comment by cullenstoneAS** [comment]
Thanks!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
