### PR TITLE
remove rtshell_core

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by tfoote** [comment]
Why are you removing this from hydro?

**Comment by k-okada** [comment]
we want to switch to 
http://github.com/tork-a/rtshell-release
http://github.com/tork-a/rtsprofile-release
http://github.com/tork-a/rtctree-release

**Comment by dirk-thomas** [comment]
Can't you change the existing entry instead?

**Comment by k-okada** [comment]
each upstream (rtshell/rtsprofile/rtctree) have different upstream url so I think we need different release repo for each of them and that need different entry, I think.

**Pull request merged**
