### PR TITLE
Add bitstring pip package

### PR DESCRIPTION
**Pull request by anassinator**
https://pypi.python.org/pypi/bitstring

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by dirk-thomas** [comment]
The latest Ubuntu distros have that package: http://packages.ubuntu.com/xenial/python-bitstring

**Comment by anassinator** [comment]
Oh, sorry I was running 14.04.
Should I add it? And if so, should the `-pip` suffix be removed?

**Comment by wjwwood** [comment]
@anassinator you can have both, the `-pip` suffixed one and the one without.

**Comment by anassinator** [comment]
Alright! I think I fixed it in #10893

**Pull request merged**
