### PR TITLE
python: debian|fedora|ubuntu: add casadi dependency

### PR DESCRIPTION
**Pull request by TSC21**
Adds [CasADi](https://github.com/casadi/casadi) to the dependency list.

### CODE REVIEW

**Comment by TSC21** [comment]
@mikaelarguedas can you take a look? Thank you!

**Review by mikaelarguedas — COMMENTED** [review]
lgtm, @TSC21 can you please add Fedora for completness? thanks!

**Comment by TSC21** [comment]
@mikaelarguedas done! Thanks for reviewing!

**Review by tfoote — APPROVED** [review]

**Comment by TSC21** [comment]
Thanks Tully!

**Pull request merged**
