### PR TITLE
Adding radar_omnipresense to documentation index for distro

### PR DESCRIPTION
**Pull request by garrenhendricks**
I'd like radar_omnipresense to be indexed and documented on ros.org

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@garrenhendricks thanks for contributing your package.

CI is currently failing because the repository urls are missing the `.git` at the end.

If you just want to index your package you don't need the `release` section.
If you want to release your package, you will need to follow the release process detailed [here](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)

**Comment by garrenhendricks** [comment]
@mikaelarguedas would you mind elaborating what CI is? I would like to release my package so I will try to follow the bloom tutorial

**Comment by garrenhendricks** [comment]
pr #17378 was made using bloom-release, so I'm closing this one.

**Comment by mikaelarguedas** [comment]
> would you mind elaborating what CI is?

I was referring to the travis test that runs on incoming pull requests on this repository. It was reported as failing on this PR (red cross next to the commit message, https://travis-ci.org/ros/rosdistro/builds/363372477?utm_source=github_status&utm_medium=notification)

> I would like to release my package so I will try to follow the bloom tutorial

:+1:

**Pull request closed without merging**
