### PR TITLE
Revert "ml_classifiers: 1.0.0-0 in 'kinetic/distribution.yaml' [bloom]"

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Reverts ros/rosdistro#20839 see https://github.com/ros/rosdistro/pull/20841#issuecomment-481860668 for details

### CODE REVIEW

**Review by JWhitleyWork — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
this may not actually be necessary

**Comment by JWhitleyAStuff** [comment]
@nuclearsandwich - Since merge, Kinetic, Lunar, and Melodic are failing (though I'm not sure why Lunar is failing, because I didn't release a new version for Lunar) on http://build.ros.org/. Why not necessary?

**Comment by nuclearsandwich** [comment]
@JWhitleyAStuff it would help me out a lot if we could continue the conversation in https://github.com/ros/rosdistro/pull/20841

**Comment by nuclearsandwich** [comment]
Resolving without reverting. https://github.com/ros/rosdistro/pull/20841#issuecomment-481868339

**Pull request closed without merging**
