### PR TITLE
Adding trac_ik to documentation index for lunar

### PR DESCRIPTION
**Pull request by pbeeson**
Added trac_ik to lunar distribution.yaml in preparation for release.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The release repository doesn't seem to contain a Lunar release. Did you run `bloom` for Lunar?

**Comment by pbeeson** [comment]
Sorry, I thought I needed to do this first.  I'll run bloom now.

**Comment by pbeeson** [comment]
Yeah, when I run bloom, it complains about not seeing my package in the distribution.yaml for lunar.

**Comment by pbeeson** [comment]
OK, it looks like the bloom script made the PR for me.

**Pull request closed without merging**
