### PR TITLE
adding python-cookiecutter

### PR DESCRIPTION
**Pull request by asmodehn**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by tfoote** [comment]
Ubuntu: http://packages.ubuntu.com/search?keywords=python-cookiecutter
Debian: https://packages.debian.org/jessie/python/python-cookiecutter
OSX: looks like either pip or brew https://cookiecutter.readthedocs.org/en/latest/installation.html
Fedora I'm not finding a package quickly 
Could you also look up the package names for debian, osx and fedora? We're trying to keep things

**Comment by asmodehn** [comment]
couldn't find fedora... so I used pip for that as well.

**Comment by tfoote** [comment]
Thanks for filling it in.

**Pull request merged**
