### PR TITLE
qb_move: 2.2.1-1 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by umbertofontana93**
Increasing version of package(s) in repository `qb_move` to `2.2.1-1`:

- upstream repository: https://bitbucket.org/qbrobotics/qbmove-ros.git
- release repository: https://bitbucket.org/qbrobotics/qbmove-ros-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## qb_move

- No changes

## qb_move_control

- No changes

## qb_move_description

- No changes

## qb_move_gazebo

- No changes

## qb_move_hardware_interface

- No changes

### CODE REVIEW

**Review by audrow — APPROVED** [review]

**Comment by ivanpauno** [comment]
@umbertofontana93 could you resolve conflicts?

**Comment by ivanpauno** [comment]
@umbertofontana93 could you resolve conflicts?

**Comment by sloretz** [comment]
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-09-06/)

**Comment by tfoote** [comment]
@umbertofontana93 FYI a new commit doesn't send a notification. I suggest that you comment back when you've made an update so we will know you've made the change sooner next time you make a revision.

**Pull request merged**
