### PR TITLE
create javascript.yaml file

### PR DESCRIPTION
**Pull request by k-okada**
to support npm installer and move nodejs/npm from base.yaml to javascript.yaml

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Has there been a discussion among the community and @ros/rosdeputies about continuing the use of separate files for language-specific package managers? I seem to remember us wanting to get away from it but perhaps that was the os-specific files and I'm mis-remembering.

**Review by tfoote — CHANGES_REQUESTED** [review]
Yeah, I think in general we'd rather not end up with a proliferation of files. For example if we moved the keys to the new location anyone who didn't reinit rosdep would suddenly stop resolving any of the keys which have been migrated.

**Comment by tfoote** [comment]
I'm going to close this. Please add rosdep rules for the debian to base.yaml The npm support is something we should talk about more generally.

**Comment by k-okada** [comment]
@tfoote  Ok, Please check https://github.com/ros-infrastructure/rosdep/pull/692 for npm support.

**Pull request closed without merging**
