### PR TITLE
OpenCV 3.3.1

### PR DESCRIPTION
**Pull request by vrabaud**
This bump is needed for the Gentoo release.

### CODE REVIEW

**Review by wjwwood — COMMENTED** [review]
Does this need to be updated? http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021

Kinetic is already wrong, claiming 3.1, and lunar says 3.2.

**Comment by vrabaud** [comment]
We can keep it as is: the reason for bumping from 3.1 to 3.2 was to get all the deep neural stuff in (it seems to be useful these days). The reason to get to 3.3.x is for Gentoo support to be releasable (ask  Hunter Allen for details, we needed a new high version of OpenCV).
The REP can stay as is: code should still compile/work with 3.1.

**Comment by mikaelarguedas** [comment]
@ros/ros_team does REP3 has to be updated for minor version bump ? Happy to submit a PR if needed

**Comment by vrabaud** [comment]
Just give me the green light to merge and I'll do it this weekend with other vision-related packages. Thx.

**Comment by wjwwood** [comment]
Is it an API breaking change, an ABI breaking change, or neither?

It might be sufficient to update the REP with "a version of OpenCV compatible with X.Y.Z" for each. Separately, if it is an ABI breaking change, then you should probably make an announcement that you're breaking ABI and they should do a dist-upgrade.

**Comment by vrabaud** [comment]
It should not be an API/ABI change. Then again, it is a huge project and there are some modules contributed by users so there might be some changes.
 The vision* packages I maintain will depend on a higher version so that it is installed for sure.

**Comment by vrabaud** [comment]
Done in https://github.com/ros-infrastructure/rep/pull/140.
Feel free to merge all the vision related PR, I am done for today :)

**Comment by mikaelarguedas** [comment]
It looks like this caused a few regressions in Lunar (Lunar arm packages and Kinetic all platforms are still rebuilding so we don't have a full list of regressions yet)
http://build.ros.org/view/Lbin_ds_dS64/job/Lbin_ds_dS64__posedetection_msgs__debian_stretch_amd64__binary/  @k-okada FYI
http://build.ros.org/view/Lbin_ds_dS64/job/Lbin_ds_dS64__visp__debian_stretch_amd64__binary/ @fspindle  FYI

**Comment by vrabaud** [comment]
posdetection_msgs had a problem:
https://github.com/jsk-ros-pkg/jsk_common_msgs/commit/5a22605a0a806e01caf3b9f56b97a61951afd59b
For visp, the fix got in: https://github.com/lagadic/visp/commit/ad26dd38f9005808bb332342728fa39756209cb0 , it just needs a backport.
For ecto_opencv, I'll fix it tonight.

**Comment by mikaelarguedas** [comment]
Awesome, thanks @vrabaud for the quick follow-up!

**Comment by fspindle** [comment]
I will patch visp next week

**Pull request merged**
