### PR TITLE
Added ur_simulation_gz pkg

### PR DESCRIPTION
**Pull request by VinDp**
# Please Add This Package to be indexed in the rosdistro.

Humble, Iron, Rolling, Jazzy

# The source is here:

https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by mjcarroll** [comment]
[Holding for Iron sync](https://discourse.ros.org/t/preparing-for-iron-sync-2024-09-06/)

If you want these in faster, it's better to separate them.  Otherwise we will wait until there are no sync holds for the impacted distros.

**Comment by VinDp** [comment]
No problem, I can wait until there are no more sync holds.

**Review by Yadunund — APPROVED** [review]

**Comment by VinDp** [comment]
Since the Iron sync is done, are there other reasons for not merging this?

**Comment by Yadunund** [comment]
@VinDp thanks for the reminder.

**Pull request merged**
