### PR TITLE
Adding vizanti and line_planner to documentation index for noetic

### PR DESCRIPTION
**Pull request by MoffKalast**
# Please Add These Packages to be indexed in the rosdistro.

Noetic

# The source is here:

https://github.com/MoffKalast/vizanti
https://github.com/MoffKalast/line_planner

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] These repositories have a LICENSE file
 - [x] These packages are expected to build on the submitted rosdistro

### CODE REVIEW

**Review by cottsay — APPROVED** [review]
Thanks!

Non-blocking: You might consider adding license headers to source files and dropping the `__pycache__` artifacts from your repository.

**Comment by MoffKalast** [comment]
Hey @cottsay if I can bother you with a slight follow-up, I see you've also added the packages to be built (not just the docs) which is cool, but while line_planner seems to build fine, I'm seeing some weird logs that I can't really explain for vizanti:


https://build.ros.org/job/Ndev__vizanti__ubuntu_focal_amd64/lastBuild/console
```
11:17:36 Resolved the dependencies to the following binary packages:
11:17:36   - ros-noetic-actionlib-msgs
11:17:36   - ros-noetic-catkin
11:17:36   - ros-noetic-dynamic-reconfigure
11:17:36   - ros-noetic-geometry-msgs
11:17:36   - ros-noetic-message-generation
11:17:36   - ros-noetic-move-base-msgs
11:17:36   - ros-noetic-rospy
11:17:36   - ros-noetic-std-msgs
11:17:36 Traceback (most recent call last):
11:17:36   File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
11:17:36     rawpkg = self._cache[key]
11:17:36 KeyError: 'ros-noetic-catkin'
11:17:36 
11:17:36 During handling of the above exception, another exception occurred:
11:17:36 
11:17:36 Traceback (most recent call last):
11:17:36   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 21, in <module>
11:17:36     run_module('ros_buildfarm.scripts.devel.create_devel_task_generator', run_name='__main__')
11:17:36   File "/usr/lib/python3.8/runpy.py", line 210, in run_module
11:17:36     return _run_code(code, {}, init_globals, run_name, mod_spec)
11:17:36   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
11:17:36     exec(code, run_globals)
11:17:36   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 304, in <module>
11:17:36     sys.exit(main())
11:17:36   File "/tmp/ros_buildfarm/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 140, in main
11:17:36     get_binary_package_versions(apt_cache, debian_pkg_names))
11:17:36   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
11:17:36     pkg = apt_cache[debian_pkg_name]
11:17:36   File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
11:17:36     raise KeyError('The cache has no package named %r' % key)
11:17:36 KeyError: "The cache has no package named 'ros-noetic-catkin'"
11:17:36 Build step 'Execute shell' marked build as failure
```

Meanwhile line_planner has that same catkin dep which works fine:

https://build.ros.org/job/Ndev__line_planner__ubuntu_focal_amd64/lastBuild/console
```
02:58:39 Resolved the dependencies to the following binary packages:
02:58:39   - ros-noetic-actionlib-msgs
02:58:39   - ros-noetic-catkin
02:58:39   - ros-noetic-dynamic-reconfigure
02:58:39   - ros-noetic-geometry-msgs
02:58:39   - ros-noetic-move-base-msgs
02:58:39   - ros-noetic-rospy
02:58:39   - ros-noetic-std-msgs
02:58:39 Identified the following run and test dependencies (ignoring packages available from source):
02:58:39   - actionlib_msgs
02:58:39   - dynamic_reconfigure
02:58:39   - geometry_msgs
02:58:39   - move_base_msgs
02:58:39   - rospy
02:58:39   - std_msgs
02:58:39 Resolved the dependencies to the following binary packages:
02:58:39   - ros-noetic-actionlib-msgs
02:58:39   - ros-noetic-dynamic-reconfigure
02:58:39   - ros-noetic-geometry-msgs
02:58:39   - ros-noetic-move-base-msgs
02:58:39   - ros-noetic-rospy
02:58:39   - ros-noetic-std-msgs
02:58:39 Using the following distribution repositories:
02:58:39   http://repositories.ros.org/ubuntu/testing (/tmp/keys/0.key)
02:58:39 Generating Dockerfile '/tmp/docker_build_and_install/Dockerfile':
02:58:39   # generated from devel/devel_task.Dockerfile.em
```
Plus the pacakge.xmls are virtually identical, aside from message gen and the two extras:
image


I've retested the build process on a clean-ish install of Noetic and they both seem to resolve deps and build fine, I've tried a few random things that could've been tipping it off but so far it's always failed for what seems to be no reason at all, so I'm really at a loss as to what's happening. I imagine you might've seen such issues before?

**Comment by cottsay** [comment]
Hello @MoffKalast -

The `ros-noetic-catkin` issue was a problem on the buildfarm unrelated to your package. It was resolved last week. I retried your job and it appears to have passed the issue previously blocking it.

**Comment by MoffKalast** [comment]
Ah, it's always nice to hear that it's not an issue on my side.

> If you don't want the builds, add the test_commits: False configuration to your source stanza.

Good to know, though these are fairly general packages that would be handy to have apt-installable eventually, I was just rather surprised that you guys are doing all of this building for free 😄

**Pull request merged**
