### PR TITLE
geometry2: 0.6.6-1 in 'melodic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by tfoote**
Increasing version of package(s) in repository `geometry2` to `0.6.6-1`:

- upstream repository: https://github.com/ros/geometry_experimental.git
- release repository: https://github.com/ros-gbp/geometry2-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.9.0`
- previous version for package: `0.6.5-0`

## geometry2

- No changes

## tf2

```
* Fix compile error missing ros/ros.h (#400 <https://github.com/ros/geometry2/issues/400>)
  * ros/ros.h -> ros/time.h
  * tf2_eigen doesn't need ros/ros.h
* rework Eigen functions namespace hack
* separate transform function declarations into transform_functions.h
* use ROS_DEPRECATED macro for portability (#362 <https://github.com/ros/geometry2/issues/362>)
* Remove signals from find_package(Boost COMPONENTS ...).
* Remove legacy inclusion in CMakeLists of tf2.
* Contributors: James Xu, Maarten de Vries, Marco Tranzatto, Shane Loretz, Tully Foote
```

## tf2_bullet

```
* Fix compile error missing ros/ros.h (#400 <https://github.com/ros/geometry2/issues/400>)
  * ros/ros.h -> ros/time.h
  * tf2_bullet doesn't need ros.h
  * tf2_eigen doesn't need ros/ros.h
* use find_package when pkg_check_modules doesn't work (#364 <https://github.com/ros/geometry2/issues/364>)
* Contributors: James Xu, Shane Loretz
```

## tf2_eigen

```
* Fix compile error missing ros/ros.h (#400 <https://github.com/ros/geometry2/issues/400>)
  * ros/ros.h -> ros/time.h
  * tf2_bullet doesn't need ros.h
  * tf2_eigen doesn't need ros/ros.h
* rework Eigen functions namespace hack
* separate transform function declarations into transform_functions.h
* Contributors: James Xu, Shane Loretz, Tully Foote
```

## tf2_geometry_msgs

```
* Make kdl headers available (#419 <https://github.com/ros/geometry2/issues/419>)
* Fix python3 compatibility for noetic (#416 <https://github.com/ros/geometry2/issues/416>)
* add <array> from STL (#366 <https://github.com/ros/geometry2/issues/366>)
* use ROS_DEPRECATED macro for portability (#362 <https://github.com/ros/geometry2/issues/362>)
* Contributors: James Xu, Shane Loretz, Tully Foote
```

## tf2_kdl

```
* Make kdl headers available (#419 <https://github.com/ros/geometry2/issues/419>)
* Fix python3 compatibility for noetic (#416 <https://github.com/ros/geometry2/issues/416>)
* Remove roslib.load_manifest #404 <https://github.com/ros/geometry2/issues/404> from otamachan/remove-load-manifest
* Python 3 compatibility: relative imports and print statement
* Contributors: Shane Loretz, Tamaki Nishino, Timon Engelke, Tully Foote
```

## tf2_msgs

- No changes

## tf2_py

```
* use .pyd instead of .so on Windows and export symbols #363 <https://github.com/ros/geometry2/issues/363> from kejxu/fix_tf2_py_export
* limit MSVC-only change to MSVC scope (#10 <https://github.com/ros/geometry2/issues/10>)
* Fix the pyd extension and export the init function.
* use windows counterpart for .so extension
* Contributors: James Xu, Sean Yen, Tully Foote
```

## tf2_ros

```
* Remove roslib.load_manifest #404 <https://github.com/ros/geometry2/issues/404>
* Fix message filter #402 <https://github.com/ros/geometry2/issues/402>
* resolve virtual function call in destructor
* remove pending callbacks in clear()
* spelling fix: seperate -> separate #372 <https://github.com/ros/geometry2/issues/372>
* Fix dangling iterator references in buffer_server.cpp #369 <https://github.com/ros/geometry2/issues/369>
* Remove some useless code from buffer_server_main.cpp #368 <https://github.com/ros/geometry2/issues/368>
* Mark check_frequency as deprecated in docstring.
* Follow #337 <https://github.com/ros/geometry2/issues/337>: use actionlib API in BufferClient::processGoal()
* Test for equality to None with 'is' instead of '==' #355 <https://github.com/ros/geometry2/issues/355>
* added parameter to advertise tf2-frames as a service, if needed
* Contributors: Daniel Ingram, Emre Sahin, JonasTietz, Lucas Walter, Michael Grupp, Robert Haschke, Tamaki Nishino, Tully Foote
```

## tf2_sensor_msgs

```
* Affine->Isometry #378 <https://github.com/ros/geometry2/issues/378>
* Python 3 compatibility: relative imports and print statement
* Contributors: Martin Pecka, Timon Engelke, Tully Foote
```

## tf2_tools

```
* Allow to choose output precision in echo #377 <https://github.com/ros/geometry2/issues/377>
* use yaml.safe_load instead of deprecated yaml.load #373 <https://github.com/ros/geometry2/issues/373>
* Python 3 compatibility: relative imports and print statement
* Contributors: Mikael Arguedas, Timon Engelke, Tully Foote, Victor Lamoine
```

### CODE REVIEW

**Comment by tfoote** [comment]
hold until after melodic sync

**Comment by rhaschke** [comment]
Hi @tfoote and @clalancette,

looks like https://github.com/ros/geometry2/pull/367 breaks downstream projects like MoveIt.
The issue was pointed out already in November: https://github.com/ros-planning/moveit/issues/1785, https://github.com/ros/geometry2/issues/430.
Potential solutions were suggested in https://github.com/ros/geometry2/pull/431 and https://github.com/ros/geometry2/pull/433. But, at least https://github.com/ros/geometry2/pull/431 relies on the include order, which is IMHO not acceptable.

This issue should be fixed before the next sync. As a short-time solution, I suggest to revert https://github.com/ros/geometry2/pull/367 and ask @kejxu to provide a valid new PR to replace https://github.com/ros/geometry2/pull/367.

**Comment by clalancette** [comment]
> This issue should be fixed before the next sync. As a short-time solution, I suggest to revert [ros/geometry2#367](https://github.com/ros/geometry2/pull/367) and ask @kejxu to provide a valid new PR to replace [ros/geometry2#367](https://github.com/ros/geometry2/pull/367).

For the time being, I'm going to revert this PR to get us back to the last version of geometry2.  I'll let @tfoote handle fixing the sources.

**Comment by clalancette** [comment]
https://github.com/ros/rosdistro/pull/23559

**Pull request merged**
