### PR TITLE
Added libzmqpp-dev library

### PR DESCRIPTION
**Pull request by tobyhijzen**

### CODE REVIEW

**Comment by tfoote** [comment]
Your commit looks good. However your branch needs to be rebased against master. There are 19 additional commits in this pr which need to be removed before we can merge this.

**Comment by tobyhijzen** [comment]
Like this?

**Comment by tfoote** [comment]
No, you've brought in more commits now. You can see them all here: https://github.com/ros/rosdistro/pull/9747/commits

You need to get a branch which is up to date with origin/master and put your commits on top of that. You can either rebase or cherry-pick your changes.

**Comment by tobyhijzen** [comment]
I created a new pull request at https://github.com/ros/rosdistro/pull/9767 with correct history

**Comment by dirk-thomas** [comment]
Please close obsolete PRs like this one in the future.

**Pull request closed without merging**
