### PR TITLE
slam_toolbox: 2.3.0-1 in 'foxy/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by SteveMacenski**
Increasing version of package(s) in repository `slam_toolbox` to `2.3.0-1`:

- upstream repository: https://github.com/SteveMacenski/slam_toolbox.git
- release repository: https://github.com/SteveMacenski/slam_toolbox-release.git
- distro file: `foxy/distribution.yaml`
- bloom version: `0.9.7`
- previous version for package: `null`

### CODE REVIEW

**Comment by clalancette** [comment]
@SteveMacenski Apologies, I merged something that conflicted.  Can you rebase?

**Comment by SteveMacenski** [comment]
Fixed the merge - please squash merge (if you don't already)

**Review by jacobperron — COMMENTED** [review]
CI is failing. Alphabetizing the new entry should fix it.

**Comment by SteveMacenski** [comment]
Got it - sorry, I assumed the conflict staging mode would have shown them in order

**Pull request merged**
