### PR TITLE
Add pip keys for: cvxpy, gurobipy, glpk

### PR DESCRIPTION
**Pull request by wxmerkt**
I manually formatted the file - `rosdistro_reformat` does not format the python file, `yamllint` does not complain about the alphabetical ordering, and my YAML formatter changed all `"` to `'`. Which is the correct tool / command to use?

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
The CI issues seem to be unrelated (see https://github.com/ros/rosdistro/issues/31439) and shouldn't affect future CI runs.

**Comment by nuclearsandwich** [comment]
https://github.com/ros/rosdistro/pull/31475 should address the rosdep repo check fixes.



> `rosdistro_reformat` does not format the python file

That formatter is for rosdistro distribution files rather than rosdep definition lists.

> `yamllint` does not complain about the alphabetical ordering, and my YAML formatter changed all `"` to `'`. Which is the correct tool / command to use?

I'm pretty sure that yamllint and an explicit checker should both be enforcing lexical sort on the rosdep definition lists but my local `yamllint` is broken by a move to python3.10 and I'll need to fix that before I can better answer that question.

In the meantime https://github.com/ros/rosdistro/pull/31475 has been opened to fix some of the collateral failures unrelated to this PR. Once that has merged we can rebase this PR to include that and run CI again.

**Comment by hidmic** [comment]
@wxmerkt friendly ping.

I think we can rebase now.

**Comment by wxmerkt** [comment]
@hidmic Thanks for the ping - I've rebased it on top of master

**Review by hidmic — APPROVED** [review]

**Pull request merged**
