### PR TITLE
[rosdep] Adding setpriv for Ubuntu Bionic and Debian Stretch.

### PR DESCRIPTION
**Pull request by tonybaltovski**
Please add the following dependency to the rosdep database.

## Package name:

setpriv

## Package Upstream Source:

https://github.com/karelzak/util-linux/blob/master/sys-utils/setpriv.c

## Purpose of using this:

This allows packages is a tool to run a program with different Linux privilege settings.  Used in robot_upstart.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/search?searchon=names&keywords=setpriv
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=setpriv

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
It's unfortunate that Debian maintainers chose to release `setpriv` only for Stretch -- it joins the `util-linux`  package for Buster and onwards. Same for Gentoo and Fedora. 

@cottsay thoughts?

**Comment by tonybaltovski** [comment]
> It's unfortunate that Debian maintainers chose to release `setpriv` only for Stretch -- it joins the `util-linux` package for Buster and onwards. Same for Gentoo and Fedora.
> 
> @cottsay thoughts?

Yeah it was, I added `util-linux` here: https://github.com/ros/rosdistro/pull/28955.

**Comment by cottsay** [comment]
I think that, despite the convention of naming rosdep keys after the Ubuntu packages, the idea is more that a rosdep key resolves to a resource, and the rules should ensure that the resource is available after installation.

By that logic, `util-linux` should be listed under this key for those platforms.

@tfoote, does that check out?

**Review by tfoote — COMMENTED** [review]
Yes the keys are relating to a resource availability. 

In this case we could have the setpriv explicitly called out here `setpriv` for bionic and stretch, and then for everything after that this resources is provided by the `util-linux` package. However, this is a very specific thing that since it's expected to be bundled in the future, I would actually recommend that we just extend the existing definitions of `util-linux` to call out both the `util-linux` and `setpriv` on the exception platforms (stretch and bionic). To a current developer setpriv is already expected in `util-linux` on most platforms and as such they'd expect it on the older platforms too. Thus we'd consider `util-linux` key to include the `setpriv` functionality on all platforms. This will keep things consistent and easier going forward too.

So to be explicit I'm suggesting modifying util-linux like this for ubuntu below and debian stretch. 

```
util-linux:
   ...
   ubuntu:
     '*': util-linux
     bionic: [setpriv, util-linux]
```

**Comment by jacobperron** [comment]
@tonybaltovski Friendly ping. I think updating the existing `util-linux` key as suggested by tfoote makes sense.

**Comment by tonybaltovski** [comment]
@jacobperron updated! Sorry for the delay.

**Review by nuclearsandwich — APPROVED** [review]
In general I would expect that a split-out package ought to be given a second key rather than added to an existing one. However since this package exists only in stretch and bionic and is not part of later distributions, this key arrangement makes some sense to me.

**Pull request merged**
