### PR TITLE
h4r_thermapp_camera: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by cyborg-x1**
Increasing version of package(s) in repository `h4r_thermapp_camera` to `0.0.1-0`:
- upstream repository: https://github.com/Hacks4ROS/h4r_thermapp_camera.git
- release repository: https://github.com/Hacks4ROS-releases/h4r_thermapp_camera.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.20`
- previous version for package: `null`
## h4r_thermapp_camera

```
* fix License information
* add install to CMakeLists
* update ReadMe with install information
* add udev file
* change thermapp.launch
* Merge branch 'develop'
* fix submodule for ThermAppCam project
* Initial commit
* add author tag
* fix dynamic reconfigure
* change #define for header file
* change package name to h4r
  add default values to dynamic_reconfigure
  tidy up package.xml
* integrate reading camera
* rename namespace,
  add first functions
  make it compile with ThermAppCam files
* delete old thermapp code
* delete class for own code
* add new thermapp code to library and to node in CMakeLists
* create include for catkin for not breaking up with origin of the thermapp code
* update ThermAppCam
* add ThermAppCam from PidBip (Alexander G)
* last of my own tries to get protocol working
* removed prints
* stable image but slow
* fix filename of perspective in launchfile
* reformat launchfile code
* add current code to main node to have easier testing
* add current code to bulk class
* create rqt perspective with image view and launchfile
* add Code from test application
* add function for opening usb device
  add function for closing
  add function for requesting image (unfinished)
* add libusb to CMakeLists
* add class for usb bulk transfer
* add thermapp_camera_node
  -add boost thread bind
  -add dynamic reconfigure
  -add CameraPublisher
  -add cv bridge
* Add maintainer and description to package.xml
* initial commit, create ros package
* initial commit, create ros package
* Contributors: Christian Holl
```

### CODE REVIEW

**Comment by vrabaud** [comment]
any reason why you closed your pull request ?

**Comment by cyborg-x1** [comment]
Ehm yes, there was, I realized that I only need one release repository for all my packages. I had created another organization where I wanted to create my release repositories for all of my packages before, but when I looked closely on what bloom created, I saw that I could use one release repository for multiple packages. That's why I closed the pull request and created another repository called release, where I will release my package(s) again. Otherwise you would have had to add repositories for all my packages, when I create a new one. Or would that be the better way?

Regards, Christian

**Comment by vrabaud** [comment]
well, I guess you could but what is usually done is a release repo per source repo: it makes it easier to keep things clean over time.

**Comment by cyborg-x1** [comment]
hmm... so I should have a release repo per package ... ok ... than I will do it like that

**Pull request closed without merging**
