### PR TITLE
Add gazebo_video_monitors in humble and iron

### PR DESCRIPTION
**Pull request by nlamprian**
# Please Add This Package to be indexed in the rosdistro.

Humble and Iron

# The source is here:

https://github.com/nlamprian/gazebo_video_monitors

# Checks
 - [x] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by quarkytale — APPROVED** [review]

**Comment by quarkytale** [comment]
It turns out that all 3 distros are currently not in a sync hold, so we can do this all at once. But keep in mind for the future that cross-distribution changes can be hard to get in since we can only merge when all of them are not held.

**Comment by quarkytale** [comment]
@nlamprian missing LICENSE files!!! Merged it by mistake before adding the comment, can you please add a top-level license?

**Comment by nlamprian** [comment]
It's been a while, but isn't a [COPYING](https://github.com/nlamprian/gazebo_video_monitors/blob/ros2/COPYING) file what is required by GPLv3?

**Comment by quarkytale** [comment]
Ooh okay wasn't aware of that, thanks for the update, all good!

**Pull request merged**
