### PR TITLE
drop iproute2 for old ubuntu distro

### PR DESCRIPTION
**Pull request by furushchev**
The package `iproute2` is not found on ubuntu raring and earlier.
This pull request drops `iproute2` on old ubuntu distros which has no key for this package.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@furushchev this is removing a recently added key, can you please rebase the branch?

**Comment by mikaelarguedas** [comment]
the iproute2 key was added way after Hydro was dropped and there shouldn't be any package released in hydro depending on it.
What is the use case you are trying to cover?
If you have a package that declare this as a dependency on a platform older than saucy, this PR will not fix it because the rule will not exist anymore.
A proper solution would be to declare that rule as empty for the platforms that dont have this package `precise: []`.

**Comment by furushchev** [comment]
@mikaelarguedas Thank you for comment. I see, we are currently releasing the same packages for all distros (without dividing branches) and our test on hydro env stopped on `rosdep install` because of this error.
https://github.com/jsk-ros-pkg/jsk_common/pull/1570

But it seems this approach for fix was not so good according to your comment...
If you'd like to merge this, it's fine, otherwise just close this issue please.

**Comment by mikaelarguedas** [comment]
Can you please add artful and bionic to the list (in alphabetical order)? 

> If you'd like to merge this, it's fine, otherwise just close this issue please

I'm fine with merging this (now that the empty rules have been added) if this covers your use case. 
I'll leave it up to another rosdistro maintainer to comment on the approach / close or merge accordingly

**Comment by wjwwood** [comment]
+1 with @mikaelarguedas' request to have the new ubuntu distros represented.

**Comment by furushchev** [comment]
@mikaelarguedas @wjwwood Got it, updated!

**Review by mikaelarguedas — DISMISSED** [review]
lgtm once ci green, thanks @furushchev for the quick iteration

**Review by tfoote — CHANGES_REQUESTED** [review]
The empty list `[]` implies that the dependency is already provided (for example it's built-in) which is not the case for the older distros. We should not encode that this dependency is resolved without installing anything if in fact it's not available.

This cannot be a required dependency if the package was not provided on those targets, and this is embedding a specific use cases optional resolution into a generic rosdep key.

The "correct" thing for this would be to have no entries for those distros as that dependency is not resolvable. We've generally held that having the generic keys that fail to install on no longer supported platforms is ok for the sake of compactness. as the rule currently is defined.

**Review by wjwwood — CHANGES_REQUESTED** [review]
> This cannot be a required dependency if the package was not provided on those targets, and this is embedding a specific use cases optional resolution into a generic rosdep key.

Actually that's true, I agree with @tfoote. The `[]` implies "implicitly installed" which is not right in this case.

**Comment by mikaelarguedas** [comment]
ok my bad, I wasnt sure that's why I wanted another set of eyes on this.

If I read @tfoote's comment properly it would actuallly be preferred to close this PR given that @furushchev's team will stop supporting hydro regardless of this getting merged. And not merging this will allow the definition to stay compact and maintainable more easily in the future. Is that correct?

**Comment by tfoote** [comment]
+1 for closing as leaving as is to keep the compact format. If someone wants to skip this during development they can use the `--skip-key` option for rosdep.

**Comment by mikaelarguedas** [comment]
closing then, sorry @furushchev for the unnecessary iteration

**Comment by furushchev** [comment]
@mikaelarguedas Completely no problem!
Thank you all for comments!! :+1:

**Pull request closed without merging**
