### PR TITLE
Add libjansson-dev to rosdep/base.yaml

### PR DESCRIPTION
**Pull request by pauldinh**
Adding key for another JSON C library dependency

https://packages.ubuntu.com/xenial/libjansson-dev
https://packages.debian.org/jessie/libjansson-dev

### CODE REVIEW

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by Alessandro-Barbieri** [comment]
`dev-libs/jansson` in gentoo

**Comment by mikaelarguedas** [comment]
Please create another PR for this. We don't require contributors to add entries for distributions other than ubuntu and debian given that we don't build packages for these on the buildfarm

**Comment by Alessandro-Barbieri** [comment]
Ok

**Pull request merged**
