### PR TITLE
feat: add source entries for proxsuite

### PR DESCRIPTION
**Pull request by wep21**
# Please Add This Package to be indexed in the rosdistro.

rolling and humble

# The source is here

https://github.com/Simple-Robotics/proxsuite

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]
Thanks a lot @wep21 for this PR.

**Comment by wep21** [comment]
@nuclearsandwich friendly ping

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich friendly ping

Although an automated review request pops up for me as a "codeowner" for Rolling, the rosdistro review team is primarily responsible for new package review.

I've specifically taken a step back from reviewing this PR because I'd like others to check the package name `proxsuite` to make sure that it's consistent with REP-144 package naming. I asked explicitly for other reviews in the packaging and release management chat yesterday https://discourse.ros.org/chat/c/-/11/637

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/Simple-Robotics/proxsuite/blob/main/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): BSD-2-Clause
- [x] License correctly listed in package.xmls
  - [x] proxsuite: https://github.com/Simple-Robotics/proxsuite/blob/main/package.xml#L12 (It would be ideal if the full SPDX identifier `BSD-2-Clause` was used instead of `BSD-2`.)
- [x] Public source repo: https://github.com/Simple-Robotics/proxsuite/tree/main
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] proxsuite

**Comment by wep21** [comment]
@clalancette @methylDragon @audrow @sloretz @wjwwood
I'm sorry for my mention, but could someone kindly give a second opinion about this PR?

**Comment by sloretz** [comment]
I'd vote that the name is fine, but @clalancette would be the authority on that.

**Comment by clalancette** [comment]
I'd also vote that the name is fine.  That's three votes for, none against, so I'd say we can go ahead with this.

That said, we are currently in a sync hold for Rolling, so we'll have to wait for that to lift before merging this in.

**Comment by clalancette** [comment]
Held for an upcoming [Rolling sync](https://discourse.ros.org/t/preparing-for-rolling-sync-2023-03-14/30176)

**Comment by nuclearsandwich** [comment]
@wep21 thanks for your patience. Although we're in a sync hold for Rolling the approvals here are enough to unblock the ros2-gbp process so that will be set up when the current sync hold is released

**Pull request merged**
