### PR TITLE
Add mp2p_icp for indexing

### PR DESCRIPTION
**Pull request by jlblancoc**
Add mp2p_icp for indexing

# Please Add This Package to be indexed in the rosdistro.

rolling

# The source is here:

https://github.com/MOLAorg/mp2p_icp

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

NOTE: This package is right now already published within another package ("mola") but in the next release it will be released as an independently package & git repository, hence this PR.

### CODE REVIEW

**Comment by audrow** [comment]
Hey @jlblancoc, I don't see the license file. Would you add a license file at the top of the repository?

**Comment by jlblancoc** [comment]
> Hey @jlblancoc, I don't see the license file. Would you add a license file at the top of the repository?

Hi @audrow ! It's there, named "copying"... Old fashion 😄 should it be renamed or linked somehow for better visibility?

**Comment by nuclearsandwich** [comment]
> Hi @audrow ! It's there, named "copying"... Old fashion 😄 should it be renamed or linked somehow for better visibility?

I think it would be optimal to refer to it in the `file=` attribute of the `<license>` tag in package.xml https://www.ros.org/reps/rep-0149.html#license-multiple-but-at-least-one that way it can be found by automation without relying on the LICENSE / COPYING filename convention but it's not required.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/MOLAorg/mp2p_icp/blob/master/COPYING
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses):  BSD-3-Clause
- [x] License correctly listed in package.xmls
  - [x] mp2p_ipc: https://github.com/MOLAorg/mp2p_icp/blob/master/package.xml#L16
- [x] Public source repo: https://github.com/MOLAorg/mp2p_icp/tree/master/
- [x] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [x] mp2p_ipc

**Pull request merged**
