### PR TITLE
Add debian and fedora rosdep keys for libgeos++

### PR DESCRIPTION
**Pull request by evenator**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by tfoote** [comment]
It looks like on Fedora it's `geos-devel` not `libgeos-devel`

Debian: https://packages.debian.org/jessie/libgeos++-dev
Fedora: https://apps.fedoraproject.org/packages/geos-devel

**Comment by tfoote** [comment]
This also reports to be unmergeable. I suspect it's based on an out of date master branch and needs a rebase against the latest master.

**Comment by evenator** [comment]
Whoops, I must have been looking at the wrong site. I'll fix and rebase.

**Pull request merged**
