### PR TITLE
Adding alembic

### PR DESCRIPTION
**Pull request by asmodehn**
It s python code, so I assume this is the right place ?

### CODE REVIEW

**Comment by dirk-thomas** [comment]
It might be better to name the package `python-alembic` and also use that Ubuntu package as of `utopic`. Only on `trusty` it could fall back to the name without the Python prefix.

**Comment by tfoote** [comment]
What is the difference between these: http://packages.ubuntu.com/trusty/alembic and 
http://packages.ubuntu.com/search?keywords=python-alembic

There's also python3 version which a rule might be added for: http://packages.ubuntu.com/utopic/python3-alembic

**Comment by asmodehn** [comment]
I m using python2 on trusty and I'm not sure what ros policy is regarding versions of python...
So I just setup python-alembic for > trusty and alembic for trusty.

**Comment by dirk-thomas** [comment]
Thanks for updating. I think this is the first package for `wily`...

**Pull request merged**
