### PR TITLE
Gazebo 11 on Ubuntu Focal

### PR DESCRIPTION
**Pull request by chapulina**
Just getting the ball rolling. This is not ready to be merged until we have Gazebo 11 on http://packages.ros.org/ .

CC @j-rivero

### CODE REVIEW

**Comment by j-rivero** [comment]
> Just getting the ball rolling. This is not ready to be merged until we have Gazebo 11 on http://packages.ros.org/ .

here we go https://github.com/ros-infrastructure/reprepro-updater/pull/75

**Comment by sloretz** [comment]
Are gazebo releases available for Debian Buster too?

**Comment by scpeters** [comment]
> Are gazebo releases available for Debian Buster too?

I see an amd64 build for debian buster in the debbuilder job list:

https://build.osrfoundation.org/job/gazebo11-debbuilder/26/

how many architectures do you need?

**Comment by ruffsl** [comment]
It's be nice if this matched the same architectures within Tier 1 support for ROS2:

https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023

but having at least amd64 soon would be welcome.

**Comment by sloretz** [comment]
> how many architectures do you need?

If possible, [all the arch's the buildfarm builds binaries for](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/dc488145f592c75d1536444814231fac86d89e55/index.yaml#L84-L88)

* Focal amd64
* Buster amd64
* Buster arm64/armv8
* Focal armhf
* Focal arm64/armv8

**Comment by scpeters** [comment]
I manually compiled the following

# latest gazebo11 binaries

there are amd64 builds but no arm* builds yet

## [Ubuntu](http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo11/)

* bionic amd64 / i386: 11.0.0-1
* focal amd64: 11.0.0-2

## [debian](http://packages.osrfoundation.org/gazebo/debian-stable/pool/main/g/gazebo11/)

* buster amd64: 11.0.0-2

# latest gazebo9 binaries

I think gazebo9 is a useful reference point, since we have had more time to try to get it to support multiple architectures. We have had successful builds of arm* architectures at some point, but none of them are current.

## [Ubuntu](http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/g/gazebo9/)

* bionic amd64 / i386: 9.13.0
* focal amd64: 9.13.0
* bionic arm64: 9.8.0
* bionic armhf: 9.7.0

## [debian](http://packages.osrfoundation.org/gazebo/debian-stable/pool/main/g/gazebo9/)

* sid amd64 / i386: 9.13.0
* stretch amd64 / i386: 9.12.0
* stretch arm64: 9.10.0
* stretch armhf: 9.7.0

**Comment by scpeters** [comment]
the latest bionic arm64 build of gazebo 9.13.0 failed:

* [Build Status](https://build.osrfoundation.org/job/gazebo9-debbuilder/515/) https://build.osrfoundation.org/job/gazebo9-debbuilder/515/

console output: https://gist.github.com/scpeters/b4ffa58661eb0e3273fa817668c884d2

**Comment by scpeters** [comment]
the latest attempts at building Ubuntu focal arm64 binaries of gazebo 9.13.0 took over 24 hours and were cancelled

* [Build Status](https://build.osrfoundation.org/job/gazebo9-debbuilder/530/) https://build.osrfoundation.org/job/gazebo9-debbuilder/530/
* [Build Status](https://build.osrfoundation.org/job/gazebo9-debbuilder/529/) https://build.osrfoundation.org/job/gazebo9-debbuilder/529/

**Comment by clalancette** [comment]
@chapulina I'm going to convert this to a draft PR until it is ready to be considered for merging (that way I don't have to look at it again).  Feel free to undo if you think that is inappropriate.

**Comment by sloretz** [comment]
Looks like we're just waiting on `libignition-common3-dev` (and any of it's dependencies not shipped with upstream)

Using just packages.ros.org
```console
$ apt depends libgazebo11-dev
libgazebo11-dev
  Depends: libtbb-dev
  Depends: libxml2-dev
  Depends: qtbase5-dev
  Depends: libqwt-qt5-dev
  Depends: libprotoc-dev
  Depends: libfreeimage-dev
  Depends: libprotobuf-dev
  Depends: libboost-all-dev
  Depends: freeglut3-dev
  Depends: libogre-1.9-dev
  Depends: libtar-dev
  Depends: libcurl4-openssl-dev
  Depends: libgts-dev
  Depends: libusb-1.0-0-dev
  Depends: libgdal-dev
  Depends: libavformat-dev
  Depends: libavcodec-dev
  Depends: libswscale-dev
  Depends: libavdevice-dev
  Depends: libsdformat9-dev
  Depends: libignition-math6-dev
  Depends: libignition-transport8-dev
  Depends: libignition-msgs5-dev
  Depends: libignition-fuel-tools4-dev
  Depends: <libignition-common3-dev>
  Depends: libignition-common3-graphics-dev
  Depends: libignition-common3-profiler-dev
  Depends: libsimbody-dev (>= 3.0.0)
  Depends: libsimbody-dev (<< 4.0.0)
  Depends: libbullet-dev
  Depends: libgazebo11 (= 11.0.0-2~focal)
  Depends: gazebo11-common (= 11.0.0-2~focal)
  Depends: gazebo11-plugin-base (= 11.0.0-2~focal)
```

**Comment by sloretz** [comment]
closing and reopening to kick off CI

**Review by sloretz — APPROVED** [review]
LGTM! I'm now able to install `gazebo11` and `libgazebo11-dev` packages on Focal, so I think this PR can be merged

**Review by sloretz — APPROVED** [review]
confirmed `gazebo11` and `libgazebo11-dev` are now installable on both Focal and Buster

**Review by jacobperron — APPROVED** [review]
LGTM

**Pull request merged**
