### PR TITLE
teraranger-description: 1.0.0-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by pl-kabaradjian**
Increasing version of package(s) in repository `teraranger-description` to `1.0.0-0`:

- upstream repository: https://github.com/Terabee/teraranger_description.git
- release repository: https://github.com/Terabee/teraranger_description-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.5.26`
- previous version for package: `null`

## teraranger_description

```
* Update README.md
* Initial commit
* Contributors: Zurad Krzysztof, Kabaradjian PL, Potier Baptiste
```

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Same comment as on #15940.

**Comment by pl-kabaradjian** [comment]
Indeed, naming was corrected also.

**Comment by mikaelarguedas** [comment]
Same comment as https://github.com/ros/rosdistro/pull/15940#issuecomment-330267102

**Comment by pl-kabaradjian** [comment]
Package section also removed.

**Comment by pl-kabaradjian** [comment]
Conflict solved.

**Pull request merged**
