### PR TITLE
weight_scale_interfaces: 0.0.1-1 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by Kansea**
Increasing version of package(s) in repository `weight_scale_interfaces` to `0.0.1-1`:

- upstream repository: https://github.com/TechMagicKK/weight_scale_interfaces.git
- release repository: https://github.com/TechMagicKK/weight_scale_interfaces-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `null`

## weight_scale_interfaces

```
* Release
* Initial commit
* Contributors: Ravi Joshi, Ryosuke Tajima, koki-ogura
```

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Current rosdistro reviewers: the ros2-gbp repository for this package is blocked on naming and license review. Could you please perform that review in this PR and pending approval, cc me to help the author rewrite the PR once the ros2-gbp repository is prepared. Thanks.

**Comment by Kansea** [comment]
@nuclearsandwich 

> Could you please perform that review in this PR and pending approval, cc me to help the author rewrite the PR once the ros2-gbp repository is prepared. Thanks.

Because this is my first time release, could you explain the meaning of the previous comment? Thank you. Do I need to do anything and how to do, or should I just wait?

**Review by Kansea — COMMENTED** [review]
## Review Check

@nuclearsandwich 
- [x] At least one of the following must be present
    - [x] Top level license file:
    - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses):
- [x] License correctly listed in package.xmls
- [x] Public source repo:
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

**Comment by clalancette** [comment]
This name is a bit generic, but because it is an interfaces package for a pretty generic set of functionality, we are OK with that.  With the fact that it is generic functionality, we just want to make sure you'll be OK with additions from the community in general.

If you think this functionality is specific to your application, then please feel free to add a prefix to this package with your organization.  If you are OK with it being a generic set of functionality package, then we can merge this as-is.

**Comment by longjie0723** [comment]
@clalancette Thanks for reviewing,
Yes, we want to make this package and name generic, because we intend to make this interface package for all type of weight scale devices. This interfaces should define the minimum set of message/service/action commonly used with weight scales. Device dependent interfaces should be included to each device driver package. Of course the addition and modification of this package from community are truely welcomed.
We have expertises of using several type of weight scales, and we plan to release these driver packages following this package.

**Comment by Kansea** [comment]
@nuclearsandwich, @clalancette 
We agree with this naming approach. Please initiate the merging process.
Thank you.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
