### PR TITLE
base.yaml updates for openSUSE  (1 of 6)

### PR DESCRIPTION
**Pull request by neotinker**
I have a lot of updates for openSUSE and was asked to break them up for easier digestion.

These keys are not necessarily related to each other. I'm just processing these commits alphabetically and breaking them up into groups of approx. 10.

https://software.opensuse.org/package/alsa-oss
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/alsa-oss/standard
https://software.opensuse.org/package/alsa-utils
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2:Update/patchinfo.15468/standard
https://software.opensuse.org/package/assimp
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/assimp/standard
https://software.opensuse.org/package/libbullet
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/libbullet/standard
https://software.opensuse.org/package/ca-certificates
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/ca-certificates/standard
https://software.opensuse.org/package/cppunit
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/cppunit/standard
https://software.opensuse.org/package/doxygen
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/doxygen/standard
https://software.opensuse.org/package/texlive-dvipng-bin
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/texlive/standard
https://software.opensuse.org/package/eigen3
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.2/eigen3/standard

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
Added keys seem fine to me, though I'm not thrilled about batching unrelated updates. @wjwwood WDYT?

**Comment by wjwwood** [comment]
> was asked to break them up for easier digestion.

Where were you asked? I assume there was another issue?

I'd personally prefer either one large commit with all opensuse changes OR a pr for each individual change (could group related rules I guess), but arbitrarily doing it batches of 10 or so, doesn't really make sense to me. But perhaps whoever asked had different reasoning.

**Comment by clalancette** [comment]
> Where were you asked? I assume there was another issue?

I asked for smaller batches.  I just figured it would be easier to look at a handful at a time rather than trying to look at a hundred of them.  The number 10 is arbitrary, but since they are rosdep keys it doesn't really matter too much.

**Comment by neotinker** [comment]
> > was asked to break them up for easier digestion.
> 
> Where were you asked? I assume there was another issue?
> 

This was the original Draft PR where changes were discussed and where I was asked to break the PR into smaller batches.
https://github.com/ros/rosdistro/pull/28385

**Review by tfoote — APPROVED** [review]
Thanks for going through and providing all the links. 

The batching is a compromise. Optimal clarity would be to have individual PRs, but opening 100PRs is a lot of overhead for opening and reviewing. One large one is feasible, but makes the review much harder and longer and increases the likelyhood of human errors and also merge collisions. Smaller batches can be reviewed moderately quickly and w/o too much risk of oversights or collisions.

**Review by mabelzhang — APPROVED** [review]
Thanks for providing all the links!

**Pull request merged**
