### PR TITLE
Updated name of python-catkin-pkg for Arch.

### PR DESCRIPTION
**Pull request by zootboy**
A bit of minor package renaming is happening for Arch.

### CODE REVIEW

**Comment by tfoote** [comment]
Can you provide a reference for this change so we can see the discussion?

**Comment by zootboy** [comment]
I wasn't personally involved in the change, it seems like it was done as part of making both python2 and python3 packages available. There is some discussion in the comments here:

https://aur.archlinux.org/packages/python-catkin_pkg/

**Comment by dirk-thomas** [comment]
@tfoote @zootboy What is the status on this?

**Review by tfoote — APPROVED** [review]
Sorry I missed the comment. Thanks for the reference. lgtm

**Pull request merged**
