### PR TITLE
Add fxload to base.yaml

### PR DESCRIPTION
**Pull request by toliver**

### CODE REVIEW

**Comment by clalancette** [comment]
In general, it is easier to review these if you follow the contributing guidelines [here](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md).  We're usually looking to see the keys for Ubuntu, Debian, and Fedora (with extra points for Gentoo and Arch).

Here it looks like this is available:
- Ubuntu - https://packages.ubuntu.com/search?keywords=fxload&searchon=names&suite=all&section=all
- Debian - https://packages.debian.org/search?keywords=fxload&searchon=names&suite=all&section=all
- Fedora - https://apps.fedoraproject.org/packages/fxload

So an update to this key for Debian and Fedora would be appreciated.  Thanks.

**Review by tfoote — CHANGES_REQUESTED** [review]
Please fill in the debian and fedora rules pointed out by @clalancette

**Comment by toliver** [comment]
Thanks for your comments @clalancette. I think I have addressed them.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by clalancette** [comment]
> Thanks for your comments @clalancette. I think I have addressed them.

Perfect, thank you!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
