### PR TITLE
ypspur: 0.0.1-1 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by DaikiMaekawa**
Increasing version of package(s) in repository `ypspur` to `0.0.1-1`:
- upstream repository: https://openspur.org/repos/yp-spur.git
- release repository: https://github.com/DaikiMaekawa/ypspur-release
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.20`
- previous version for package: `null`

### CODE REVIEW

**Comment by vrabaud** [comment]
your URL's need to end in ```.git```. And your source should be a proper source repo, while your release one a proper release one, cf http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease. Thx

**Comment by DaikiMaekawa** [comment]
@vrabaud Thank you for your advice.

**Comment by vrabaud** [comment]
one last thing: your source repo is also your release one. You want to keep them separate to avoid confusion usually.

**Comment by DaikiMaekawa** [comment]
I know that but this repo is third party package from [here](https://openspur.org/repos/yp-spur.git).
So, which one should I use my release repo or original repo?

**Comment by vrabaud** [comment]
well then, you don't need to have a source, this is only for a devel job: anytime you make a commit, a job is created to check it. You probably don't need that.

**Comment by vrabaud** [comment]
one last thing: your source repo is also your release one. You want to keep them separate to avoid confusion usually.

**Comment by DaikiMaekawa** [comment]
I'm done with removing the source tag.

**Pull request merged**
