### PR TITLE
Adding outsight_alb_driver to the ros index 

### PR DESCRIPTION
**Pull request by EclOutsight**
Hello rosdistro-Team,

We would like to add to the index a package to interact with our Augmented Lidar Box (https://www.outsight.ai/)

Thanks in advance

# Please Add This Package to be indexed in the rosdistro.

* Melodic
* Noetic

# The source is here: 

https://gitlab.com/outsight-public/outsight-drivers/outsight_alb_driver.git

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by mabelzhang — COMMENTED** [review]
Have you tried opening this PR with [Bloom](http://wiki.ros.org/bloom)? That is the recommended way. More details are at https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

In addition, it is preferred to have 1 PR per distro - 1 for Melodic and 1 for Noetic.

**Comment by EclOutsight** [comment]
Correct me if I am wrong, but I thought Bloom was for releasing a binary package, but here it's just to be added in the index, as explained [here](http://wiki.ros.org/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation).
Before releasing with Bloom, the package needs to be listed in the index, right ?

If it's better to have on PR for each distro, then sure I will do it

**Comment by mabelzhang** [comment]
Ah, sorry I missed that this isn't a binary release.

But yeah 1 PR per distro would be better, because for example, right now Noetic is in sync, Melodic isn't, so we can merge the Melodic one, but the Noetic one would have to wait.

**Comment by EclOutsight** [comment]
Ok thanks !

**Pull request closed without merging**
