### PR TITLE
Adding rm_description to documentation index for distro

### PR DESCRIPTION
**Pull request by mlione**

### CODE REVIEW

**Review by mabelzhang — COMMENTED** [review]
Could you add a LICENSE file? I see that there is one in the rm_control repo, which presumably is what this package is refactored from. That file will work.

**Comment by mlione** [comment]
> Could you add a LICENSE file? I see that there is one in the rm_control repo, which presumably is what this package is refactored from. That file will work.

I follow the steps on https://wiki.ros.org/cn/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation and it doesn't mention anything about LICENSE file.
I need to separate it from rm_control. What should i do? Should i delete the rm_description in rm_control  repo?
@mabelzhang

**Comment by mabelzhang** [comment]
Oh I just meant, you can use the same LICENSE file for rm_description.
The contributing guide has more information about the LICENSE file: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by mlione** [comment]
> Oh I just meant, you can use the same LICENSE file for rm_description. The contributing guide has more information about the LICENSE file: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

Do u mean if i add the same LICENSE file to the rm_description and my pull-request will be merged?

**Comment by mlione** [comment]
@mabelzhang

**Pull request closed without merging**
