### PR TITLE
Add orocos toolchain to ROS kinetic

### PR DESCRIPTION
**Pull request by Timple**
This should hopefully solve https://github.com/gt-ros-pkg/ethercat-soem/issues/2 and https://github.com/orocos/rtt_ros_integration/issues/78

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The Travis test couldn't find the release tags for the `rtt*` packages. Please check that you have updated the release repo and the mentioned version exists.

**Comment by dirk-thomas** [comment]
Retriggering Travis...

**Comment by Timple** [comment]
I cannot seem to view the travis log... So I am unable to debug why the build fails.

Is this due to the [issues](https://www.traviscistatus.com/incidents/hmwq9yy5dh9d) that travis experienced yesterday?

**Comment by mikaelarguedas** [comment]
yes most likely, re-triggering now

**Comment by tfoote** [comment]
@Timple Looking a little closer at your error messages this is not an issue with outages etc. The packages you are attempting to add to the index have not been released for Kinetic, and that is why the CI is failing. Please ask the maintainers to make a release of the packages. Until they've run bloom for the packages to generate the correct metadata the release tags cannot be added to the index. If you'd like to do some more reading there's some good tutorials at: http://wiki.ros.org/bloom as well Dirk's talk at ROSCon 2016: http://roscon.ros.org/2016/  [pdf](http://roscon.ros.org/2016/presentations/ROSCon2016%20Build%20Farm.pdf) [video](https://vimeo.com/187705230)

Bloom will automatically open a PR to add it to the index and duplicate this I'm going to close this in favor of the automated PRs when the code is released.

**Comment by Timple** [comment]
@tfoote Still strange I could not view the error messages. That is why I suspected the travis outage.

The maintainers of the packages seem unresponsive to the issues I've submitted. Maybe I am doing this at the wrong place. This is the reason I tried it myself. I expected it to work since the same version numbers released before also compile under kinetic.

I will see If I can figure out how to use bloom.

**Comment by tfoote** [comment]
@Timple Please work a little harder on requesting a release from the maintainers instead of going around them. I don't see any traffic on the repositories. I'd recommend opening an issue on the upstream repo requesting release. The Orocos team is usually quite responsive.

**Comment by Timple** [comment]
@tfoote Thanks for the feedback. I've already submitted these in the past: gt-ros-pkg/ethercat-soem#2 and orocos/rtt_ros_integration#78. Also I have put an item on their [mailing list](http://orocos.org/forum/orocos/orocos-users/kinetic-release)

Do you suggest I also open issues on the [release repos](https://github.com/orocos-gbp/rtt-release)? There seem to be no issues yet, so it seems to me nobody would notice there.

PS. I now also opened an issue on the ocl repo: https://github.com/orocos-toolchain/ocl/issues/56

**Comment by tfoote** [comment]
The issues on the main repos should be fine in this case since the maintainers are the same. I see you've already gotten some +1s. We need to ping them about kdl for the upcoming lunar, I'll mention this too.

**Comment by Timple** [comment]
I see the pinging about kdl worked. Did you also mention the orocos toolchain @tfoote?

**Comment by tfoote** [comment]
ocl was released into kinetic over the weekend: #14725

**Pull request closed without merging**
