### PR TITLE
Adding openreroc_pwm to documentation index for groovy

### PR DESCRIPTION
**Pull request by kazuyamashi**

### CODE REVIEW

**Comment by 130s** [comment]
[Travis failed](https://travis-ci.org/ros/rosdistro/builds/98659539#L324); `ROS Groovy` is EOLed (end-of-life).

Since you're only adding document and source, why not target active distros (e.g. Indigo, Jade)?

**Comment by ohkawatks** [comment]
I am also working with the openreroc_pwm package. 
Since we were mainly working with Groovy on ARM/FPGA environment, we wrote our package in groovy/distribution.yaml. However, it is EOLed as pointed out.
Now we have changed the target distros into Indigo and Jade. 
Please review the change. Thanks!

**Comment by 130s** [comment]
Thanks for the update! LGTM.

**Comment by 130s** [comment]
Maybe you want to squash commits into a single commit?

**Comment by ohkawatks** [comment]
Yes I would like to merge the multiple commits into single commit. I'll try it...

**Comment by ohkawatks** [comment]
Finally, it seems to succeed. Please review again.

**Pull request merged**
