### PR TITLE
Added arch references for clang

### PR DESCRIPTION
**Pull request by Souritra-Garai**
Please add the following dependency to the rosdep database.

## Package name:

clang

## Package Upstream Source:

[link](https://github.com/llvm/llvm-project) to source repository

## Purpose of using this:

This system dependency is required for micro-ros. Previously keys for Arch Linux were not present and rosdep threw error for installation of micro-ros.

Distro packaging links:

## Links to Distribution Packages

- Arch: https://www.archlinux.org/packages/
  - [AVAILABLE](https://archlinux.org/packages/extra/x86_64/clang/)

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Review by methylDragon — APPROVED** [review]

**Comment by ivanpauno** [comment]
@Souritra-Garai could you rebase?
I think that will fix the test errors.

**Comment by Souritra-Garai** [comment]
I rebased as per @ivanpauno 's suggestions. Still, the nosetests are failing. Any clues?

**Review by ivanpauno — COMMENTED** [review]
from the logs:

```
checking for item order...
  ERR: list out of alphabetical order line 515.  'alpine' should come before 'arch'
  ERR: list out of alphabetical order line 530.  'alpine' should come before 'arch'
building yaml dict...
there were errors, please correct the file
```

**Comment by hidmic** [comment]
@Souritra-Garai friendly ping.

**Review by ivanpauno — APPROVED** [review]

**Review by adityapande-1995 — APPROVED** [review]

**Pull request merged**
