### PR TITLE
Fix octomap status_description

### PR DESCRIPTION
**Pull request by ahornung**
Line break breaks the build

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
It looks like the wrapping was not the root of the problem.
The builds seem to have failed because no `debian/lunar/...` branches were created by bloom on the [release repository](https://github.com/ros-gbp/octomap-release).
Did bloom throw any warning when you tried to release?
@ros/ros_team Is this expected behavior to not have these branches created for new releases with the latest version of bloom and ros_buildfarm?

**Comment by tfoote** [comment]
If there's no `debian/*` branches that suggests that the debian generator failed to run during the bloom run.

**Comment by mikaelarguedas** [comment]
what is surprising here is that there is not a single branch for lunar (debian/lunar/PACKAGE_NAME or debian/UBUNTU_DISTRO/PACKAGE_NAME).
@ahornung can you rerun bloom and post here any warnings you encounter?

**Comment by tfoote** [comment]
@mikaelarguedas 

https://github.com/ros-gbp/octomap-release/branches/active
The upstream was created https://github.com/ros-gbp/octomap-release/branches/active

The patches and release branches were created. And the release tags were created: https://github.com/ros-gbp/octomap-release/releases https://github.com/ros-gbp/octomap-release/blob/master/tracks.yaml#L118


But rpm branches were created too: https://github.com/ros-gbp/octomap-release/blob/master/tracks.yaml#L123


But non of the debian targets, neither Ubuntu or Debian proper.

https://github.com/ros-gbp/octomap-release/blob/master/tracks.yaml#L119-L122

The most common reason I've seen for this is that the debian steps fail due to a missing rosdep key. 

It looks like the release https://github.com/ros/rosdistro/pull/14423 came out before the rosdep rules were merged: https://github.com/ros/rosdistro/pull/14424

I tested it locally and it didn't have a problem. I think it just needs a rerun with those keys added.
```
$ bloom-release -t lunar -r lunar octomap
ROS Distro index file associate with commit 'ccf8f18aa2e3a85a470c283ad2b342f31818e77c'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/ccf8f18aa2e3a85a470c283ad2b342f31818e77c/index.yaml'
==> Fetching 'octomap' repository from 'https://github.com/ros-gbp/octomap-release.git'
Cloning into '/tmp/tmpU1xuuK'...
remote: Counting objects: 10528, done.
remote: Total 10528 (delta 0), reused 0 (delta 0), pack-reused 10528
Receiving objects: 100% (10528/10528), 4.36 MiB | 4.03 MiB/s, done.
Resolving deltas: 100% (4090/4090), done.
Checking connectivity... done.
==> Setting release repository remote url to 'git@github.com:ros-gbp/octomap-release.git'
==> git remote set-url origin git@github.com:ros-gbp/octomap-release.git
==> Testing for push permission on release repository
==> git remote -v
origin	git@github.com:ros-gbp/octomap-release.git (fetch)
origin	git@github.com:ros-gbp/octomap-release.git (push)
==> git push --dry-run
Everything up-to-date
==> Releasing 'octomap' using release track 'lunar'
==> git-bloom-release lunar
Processing release track settings for 'lunar'
Checking upstream devel branch for package.xml(s)
Cloning into '/tmp/tmpZs83r0/upstream'...
remote: Counting objects: 10655, done.
remote: Total 10655 (delta 0), reused 0 (delta 0), pack-reused 10655
Receiving objects: 100% (10655/10655), 66.31 MiB | 6.17 MiB/s, done.
Resolving deltas: 100% (7128/7128), done.
Checking connectivity... done.
Looking for packages in 'devel' branch... found 3 packages.
Detected version '1.8.0' from package(s): ['octomap', 'dynamic_edt_3d', 'octovis']

Executing release track 'lunar'
==> bloom-export-upstream /tmp/tmpZs83r0/upstream git --tag v1.8.0 --display-uri https://github.com/OctoMap/octomap.git --name octomap --output-dir /tmp/tmpIzFbZ6
Checking out repository at 'https://github.com/OctoMap/octomap.git' to reference 'v1.8.0'.
Exporting to archive: '/tmp/tmpIzFbZ6/octomap-v1.8.0.tar.gz'
Cloning into '/tmp/tmpqDFLaW'...
warning: --depth is ignored in local clones; use file:// instead.
done.
md5: fa5783957801359ad91ee64e69c3094b

==> git-bloom-import-upstream /tmp/tmpIzFbZ6/octomap-v1.8.0.tar.gz   --release-version 1.8.0 --replace
The latest upstream tag in the release repository is 'upstream/1.8.1'.
Version discrepancy:
The upstream version '1.8.0' isn't newer than upstream version '1.8.1'.

Removing tag: 'upstream/1.8.0'
Importing archive into upstream branch...
Creating tag: 'upstream/1.8.0'
I'm happy.  You should be too.

==> git-bloom-generate -y rosrelease lunar --source upstream -i 1
Releasing packages: ['octomap', 'dynamic_edt_3d', 'octovis']
Releasing package 'octomap' for 'lunar' to: 'release/lunar/octomap'
Releasing package 'dynamic_edt_3d' for 'lunar' to: 'release/lunar/dynamic_edt_3d'
Releasing package 'octovis' for 'lunar' to: 'release/lunar/octovis'

==> git-bloom-generate -y rosdebian --prefix release/lunar lunar -i 1 --os-name ubuntu
Generating source debs for the packages: ['octovis', 'dynamic_edt_3d', 'octomap']
Debian Incremental Version: 1
Debian Distributions: ['xenial', 'yakkety', 'zesty']
Releasing for rosdistro: lunar

Pre-verifying Debian dependency keys...
Running 'rosdep update'...
All keys are OK

Placing debian template files into 'debian/lunar/octovis' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'xenial' debian for package 'octovis' at version '1.8.0-1'
####
Generating debian for xenial...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octovis'
Package 'octovis' has dependencies:
Run Dependencies:
  rosdep key           => xenial key
  catkin               => ['ros-lunar-catkin']
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4     => ['libqglviewer2-qt4']
  libqtgui4            => ['libqtgui4']
  libqt4-opengl        => ['libqt4-opengl']
Build and Build Tool Dependencies:
  rosdep key           => xenial key
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4-dev => ['libqglviewer-dev-qt4']
  libqt4-dev           => ['libqt4-dev']
  libqt4-opengl-dev    => ['libqt4-opengl-dev']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octovis_1.8.0-1_xenial
####
#### Successfully generated 'xenial' debian for package 'octovis' at version '1.8.0-1'
####


####
#### Generating 'yakkety' debian for package 'octovis' at version '1.8.0-1'
####
Generating debian for yakkety...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octovis'
Package 'octovis' has dependencies:
Run Dependencies:
  rosdep key           => yakkety key
  catkin               => ['ros-lunar-catkin']
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4     => ['libqglviewer2-qt4']
  libqtgui4            => ['libqtgui4']
  libqt4-opengl        => ['libqt4-opengl']
Build and Build Tool Dependencies:
  rosdep key           => yakkety key
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4-dev => ['libqglviewer-dev-qt4']
  libqt4-dev           => ['libqt4-dev']
  libqt4-opengl-dev    => ['libqt4-opengl-dev']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octovis_1.8.0-1_yakkety
####
#### Successfully generated 'yakkety' debian for package 'octovis' at version '1.8.0-1'
####


####
#### Generating 'zesty' debian for package 'octovis' at version '1.8.0-1'
####
Generating debian for zesty...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octovis'
Package 'octovis' has dependencies:
Run Dependencies:
  rosdep key           => zesty key
  catkin               => ['ros-lunar-catkin']
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4     => ['libqglviewer2-qt4']
  libqtgui4            => ['libqtgui4']
  libqt4-opengl        => ['libqt4-opengl']
Build and Build Tool Dependencies:
  rosdep key           => zesty key
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4-dev => ['libqglviewer-dev-qt4']
  libqt4-dev           => ['libqt4-dev']
  libqt4-opengl-dev    => ['libqt4-opengl-dev']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octovis_1.8.0-1_zesty
####
#### Successfully generated 'zesty' debian for package 'octovis' at version '1.8.0-1'
####

Placing debian template files into 'debian/lunar/dynamic_edt_3d' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'xenial' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####
Generating debian for xenial...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'dynamic_edt_3d'
Package 'dynamic-edt-3d' has dependencies:
Run Dependencies:
  rosdep key           => xenial key
  octomap              => ['ros-lunar-octomap']
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => xenial key
  octomap              => ['ros-lunar-octomap']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-dynamic-edt-3d_1.8.0-1_xenial
####
#### Successfully generated 'xenial' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####


####
#### Generating 'yakkety' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####
Generating debian for yakkety...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'dynamic_edt_3d'
Package 'dynamic-edt-3d' has dependencies:
Run Dependencies:
  rosdep key           => yakkety key
  octomap              => ['ros-lunar-octomap']
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => yakkety key
  octomap              => ['ros-lunar-octomap']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-dynamic-edt-3d_1.8.0-1_yakkety
####
#### Successfully generated 'yakkety' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####


####
#### Generating 'zesty' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####
Generating debian for zesty...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'dynamic_edt_3d'
Package 'dynamic-edt-3d' has dependencies:
Run Dependencies:
  rosdep key           => zesty key
  octomap              => ['ros-lunar-octomap']
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => zesty key
  octomap              => ['ros-lunar-octomap']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-dynamic-edt-3d_1.8.0-1_zesty
####
#### Successfully generated 'zesty' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####

Placing debian template files into 'debian/lunar/octomap' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'xenial' debian for package 'octomap' at version '1.8.0-1'
####
Generating debian for xenial...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octomap'
Package 'octomap' has dependencies:
Run Dependencies:
  rosdep key           => xenial key
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => xenial key
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octomap_1.8.0-1_xenial
####
#### Successfully generated 'xenial' debian for package 'octomap' at version '1.8.0-1'
####


####
#### Generating 'yakkety' debian for package 'octomap' at version '1.8.0-1'
####
Generating debian for yakkety...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octomap'
Package 'octomap' has dependencies:
Run Dependencies:
  rosdep key           => yakkety key
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => yakkety key
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octomap_1.8.0-1_yakkety
####
#### Successfully generated 'yakkety' debian for package 'octomap' at version '1.8.0-1'
####


####
#### Generating 'zesty' debian for package 'octomap' at version '1.8.0-1'
####
Generating debian for zesty...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octomap'
Package 'octomap' has dependencies:
Run Dependencies:
  rosdep key           => zesty key
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => zesty key
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octomap_1.8.0-1_zesty
####
#### Successfully generated 'zesty' debian for package 'octomap' at version '1.8.0-1'
####


==> git-bloom-generate -y rosdebian --prefix release/lunar lunar -i 1 --os-name debian --os-not-required
Generating source debs for the packages: ['octovis', 'dynamic_edt_3d', 'octomap']
Debian Incremental Version: 1
Debian Distributions: ['stretch']
Releasing for rosdistro: lunar

Pre-verifying Debian dependency keys...
Running 'rosdep update'...
All keys are OK

Placing debian template files into 'debian/lunar/octovis' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'stretch' debian for package 'octovis' at version '1.8.0-1'
####
Generating debian for stretch...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octovis'
Package 'octovis' has dependencies:
Run Dependencies:
  rosdep key           => stretch key
  catkin               => ['ros-lunar-catkin']
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4     => ['libqglviewer-qt4-2']
  libqtgui4            => ['libqtgui4']
  libqt4-opengl        => ['libqt4-opengl']
Build and Build Tool Dependencies:
  rosdep key           => stretch key
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4-dev => ['libqglviewer-qt4-dev']
  libqt4-dev           => ['libqt4-dev']
  libqt4-opengl-dev    => ['libqt4-opengl-dev']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octovis_1.8.0-1_stretch
####
#### Successfully generated 'stretch' debian for package 'octovis' at version '1.8.0-1'
####

Placing debian template files into 'debian/lunar/dynamic_edt_3d' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'stretch' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####
Generating debian for stretch...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'dynamic_edt_3d'
Package 'dynamic-edt-3d' has dependencies:
Run Dependencies:
  rosdep key           => stretch key
  octomap              => ['ros-lunar-octomap']
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => stretch key
  octomap              => ['ros-lunar-octomap']
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-dynamic-edt-3d_1.8.0-1_stretch
####
#### Successfully generated 'stretch' debian for package 'dynamic_edt_3d' at version '1.8.0-1'
####

Placing debian template files into 'debian/lunar/octomap' branch.
==> Placing templates files in the 'debian' folder.

####
#### Generating 'stretch' debian for package 'octomap' at version '1.8.0-1'
####
Generating debian for stretch...
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'octomap'
Package 'octomap' has dependencies:
Run Dependencies:
  rosdep key           => stretch key
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => stretch key
  cmake                => ['cmake']
==> In place processing templates in 'debian' folder.
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/rules.em' -> 'debian/rules'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/gbp.conf.em' -> 'debian/gbp.conf'
Creating tag: debian/ros-lunar-octomap_1.8.0-1_stretch
####
#### Successfully generated 'stretch' debian for package 'octomap' at version '1.8.0-1'
####


==> git-bloom-generate -y rosrpm --prefix release/lunar lunar -i 1
Generating source RPMs for the packages: ['octovis', 'dynamic_edt_3d', 'octomap']
RPM Incremental Version: 1
RPM Distributions: ['26']
Releasing for rosdistro: lunar

Pre-verifying RPM dependency keys...
Running 'rosdep update'...
All keys are OK

Placing RPM template files into 'rpm/lunar/octovis' branch.
==> Placing templates files in the 'rpm' folder.

####
#### Generating '26' RPM for package 'octovis' at version '1.8.0-1'
####
Generating RPM for 26...
Package 'octovis' has dependencies:
Run Dependencies:
  rosdep key           => 26 key
  catkin               => ['ros-lunar-catkin']
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4     => ['libQGLViewer']
  libqtgui4            => ['qt-x11']
  libqt4-opengl        => ['qt']
Build and Build Tool Dependencies:
  rosdep key           => 26 key
  octomap              => ['ros-lunar-octomap']
  libqglviewer-qt4-dev => ['libQGLViewer-devel']
  libqt4-dev           => ['qt-devel']
  libqt4-opengl-dev    => ['qt-devel']
  cmake                => ['cmake']
==> In place processing templates in 'rpm' folder.
Expanding 'rpm/template.spec.em' -> 'rpm/template.spec'
Creating tag: rpm/ros-lunar-octovis-1.8.0-1_26
####
#### Successfully generated '26' RPM for package 'octovis' at version '1.8.0-1'
####

Placing RPM template files into 'rpm/lunar/dynamic_edt_3d' branch.
==> Placing templates files in the 'rpm' folder.

####
#### Generating '26' RPM for package 'dynamic_edt_3d' at version '1.8.0-1'
####
Generating RPM for 26...
Package 'dynamic-edt-3d' has dependencies:
Run Dependencies:
  rosdep key           => 26 key
  octomap              => ['ros-lunar-octomap']
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => 26 key
  octomap              => ['ros-lunar-octomap']
  cmake                => ['cmake']
==> In place processing templates in 'rpm' folder.
Expanding 'rpm/template.spec.em' -> 'rpm/template.spec'
Creating tag: rpm/ros-lunar-dynamic-edt-3d-1.8.0-1_26
####
#### Successfully generated '26' RPM for package 'dynamic_edt_3d' at version '1.8.0-1'
####

Placing RPM template files into 'rpm/lunar/octomap' branch.
==> Placing templates files in the 'rpm' folder.

####
#### Generating '26' RPM for package 'octomap' at version '1.8.0-1'
####
Generating RPM for 26...
Package 'octomap' has dependencies:
Run Dependencies:
  rosdep key           => 26 key
  catkin               => ['ros-lunar-catkin']
Build and Build Tool Dependencies:
  rosdep key           => 26 key
  cmake                => ['cmake']
==> In place processing templates in 'rpm' folder.
Expanding 'rpm/template.spec.em' -> 'rpm/template.spec'
Creating tag: rpm/ros-lunar-octomap-1.8.0-1_26
####
#### Successfully generated '26' RPM for package 'octomap' at version '1.8.0-1'
####





Tip: Check to ensure that the debian tags created have the same version as the upstream version you are releasing.
Everything went as expected, you should check that the new tags match your expectations, and then push to the release repo with:
  git push --all && git push --tags  # You might have to add --force to the second command if you are over-writing existing tags
<== Released 'octomap' using release track 'lunar' successfully
==> git remote -v
origin	git@github.com:ros-gbp/octomap-release.git (fetch)
origin	git@github.com:ros-gbp/octomap-release.git (push)
Releasing complete, push to release repository?
Continue [Y/n]? n
User answered no to continue prompt, aborting.

```

**Comment by mikaelarguedas** [comment]
Yes that was my understanding too that's why I asked for a rerun of bloom (and any warning log if any). Thanks for testing it locally!

**Comment by ahornung** [comment]
Yes, indeed I got errors about missing keys for QGLViewer, but since I 
could skip over those I assumed it's fine to just go ahead, push, and 
create the entries in parallel. I thought the worst that could happen 
would have been a failed octovis build.

I'll re-run bloom as suggested.

**Comment by mikaelarguedas** [comment]
Closing this now that the new release https://github.com/ros/rosdistro/pull/14458 fixed the builds

**Pull request closed without merging**
