### PR TITLE
Fixed issue with alphabetical order. "g" does not come before "-"

### PR DESCRIPTION
**Pull request by allenh1**

### CODE REVIEW

**Comment by tfoote** [comment]
It looks good. Could you squash the commits together and readd the final newline at the bottom of the document?

**Comment by allenh1** [comment]
Ok - I think I did that right. Let me know if I need to fix it still.

**Comment by tfoote** [comment]
The newline is fixed, but the three commits remain. For cleanlyness we prefer to have fixup commits squashed together so they don't end up in the main branch. A quick description of how to squash commits is here: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ or http://davidwalsh.name/squash-commits-git


More complete info here: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by allenh1** [comment]
Welp. Now I've grabbed a couple other commits in the process...

**Comment by tfoote** [comment]
You probably brought in a few too many commits try `rebase -i origin/master`

**Comment by allenh1** [comment]
No dice. :/ how about I just close this and form a new pull request?

**Comment by tfoote** [comment]
Figuring this out will be easier than recreating the diff, and will help you in the future. Good rebasing is very useful. 

Below is all that i needed to run. Make sure your master branch is up to date with the repo. And after the rebase it was just your commit since the other commits are already in the repo. 

```
tfoote@yeti:/tmp/rosdistro$ git checkout -b allenh1-master master
Switched to a new branch 'allenh1-master'
tfoote@yeti:/tmp/rosdistro$ git pull https://github.com/allenh1/rosdistro.git master
From https://github.com/allenh1/rosdistro
 * branch            master     -> FETCH_HEAD

File Edit Options Buffers Tools Help                                                                                                          
Merge branch 'master' of https://github.com/allenh1/rosdistro into allenh1-master

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.


Merge made by the 'recursive' strategy.
 rosdep/base.yaml | 40 +++++++++++++++++++++++++++++++++++++---
 1 file changed, 37 insertions(+), 3 deletions(-)al) -----------------------------------------------------------------------------------------
tfoote@yeti:/tmp/rosdistro$ git rebase origin/master 
First, rewinding head to replay your work on top of it...
Applying: jsk_common: 2.0.1-0 in 'hydro/distribution.yaml' [bloom]
Using index info to reconstruct a base tree...
M	hydro/distribution.yaml
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: jsk_common: 2.0.1-0 in 'jade/distribution.yaml' [bloom]
Using index info to reconstruct a base tree...
M	jade/distribution.yaml
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Updated Gentoo dependencies for Jade.
tfoote@yeti:/tmp/rosdistro$ 
```

**Comment by allenh1** [comment]
Hold on... I think I see it now... Thank you so much. This is an invaluable skill. Glad I have an excuse to learn it this time! Sorry to keep spamming your github account with this... I'll get it soon enough!

**Comment by allenh1** [comment]
YUS. Awesome. Thank you again! This was certainly beneficial, and ultimately successful! Git is a fantastic tool.

**Comment by tfoote** [comment]
It is very powerful and you're close, but it appears that you've collapsed not just your commits, but also several others into your new commit. You can see all of them in the commit message, and your diff includes their releases. 

It looks like what you rebased against was slightly out of date. If you rebase on top of the latest version, all those other changes will go away. 

You probably need to use
```
git remote add upstream git@github.com:ros/rosdistro.git
git fetch upstream
```

Then 
```
git rebase -i upstream/master 
```

And use the keyword `reword` to allow you to reword your commit message

**Comment by allenh1** [comment]
Did I do it?

**Comment by tfoote** [comment]
Looks good. Welcome to rebasing. Powerful but steep on the learning curve.

**Pull request merged**
