### PR TITLE
adding behavior_tree package

### PR DESCRIPTION
**Pull request by miccol**
Hello, 

I would like to add the behavior_tree package. 
Thank you
Michele

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Just an unrelated question: where are the build status badges in your README file coming from?

**Comment by miccol** [comment]
I have manually copied from shield.io after testing them. Is there an automatic way to do that?

**Comment by dirk-thomas** [comment]
If the code is being built on our Jenkins farm you can use the badges from there. Please see the wiki which already makes use of that: http://wiki.ros.org/roscpp (click on the sidebar on "Jenkins jobs")

**Comment by tfoote** [comment]
There's an Embeddable Build Status Icon provided by our jenkins instance for each job. 

It provides documentation for how to embed it in different places such as: http://build.ros.org/view/Jsrc_uT/job/Jsrc_uT__roscpp__ubuntu_trusty__source/badge/

**Comment by miccol** [comment]
Thank you! I will change that!

Michele

**Pull request merged**
