### PR TITLE
Update base.yaml

### PR DESCRIPTION
**Pull request by niyawe**
libestools-dev is a virtual package. Since the package cannot be found in [1] and in [2] it looks like the script parses a file, where the virtual package is missing I changed the name to libestools2.1-dev

[1] http://jenkins.ros.org/job/ros-indigo-robot-face_binarydeb_trusty_amd64/2/console
[2] https://github.com/smd-ros-devel/catkin-rpms/blob/master/scripts/assert_package_dependencies_present.py

### CODE REVIEW

**Comment by dirk-thomas** [comment]
In some Ubuntu distributions the package including the version number is the virtual package. In some it is the other way around. Therefore I don't think that this patch is the right solution.

**Comment by niyawe** [comment]
Ok, what would be the right solution? Different package names for each Ubuntu version?

**Comment by tfoote** [comment]
It is a virtual package in Precise, Trusty, and Vivid, but a real package after that. http://packages.ubuntu.com/search?keywords=libestools-dev

Unfortunately rosdep and our checkers are not able to track virtual packages correctly. You'll need to give the concrete implementation packages for each version.

**Comment by niyawe** [comment]
done

**Comment by tfoote** [comment]
Thanks for the update.

**Pull request merged**
