### PR TITLE
add and fix boost rules

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Based on https://github.com/ros/rosdistro/pull/23620#discussion_r371039051 most fedora rules for libboost-*-dev were wrong.

This PR:
- fix dev boost keys for fedora
- add non-dev boost keys for all existing dev boost keys
- add libboost-atomic and libboost-atomic-dev

## Links:

- Fedora
https://apps.fedoraproject.org/packages/boost-devel
https://apps.fedoraproject.org/packages/boost-atomic
https://apps.fedoraproject.org/packages/boost-chrono
https://apps.fedoraproject.org/packages/boost-date-time
https://apps.fedoraproject.org/packages/boost-filesystem
https://apps.fedoraproject.org/packages/boost-iostreams
https://apps.fedoraproject.org/packages/boost-program-options
https://apps.fedoraproject.org/packages/boost-random
https://apps.fedoraproject.org/packages/boost-system
https://apps.fedoraproject.org/packages/boost-thread

- libboost-atomic:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-atomic1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-atomic1.65.1
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-atomic1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-atomic1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-atomic1.62.0
- libboost-atomic-dev:
  - Ubuntu: https://packages.ubuntu.com/xenial/libboost-atomic-dev
  - Debian: https://packages.debian.org/buster/libboost-atomic-dev
- libboost-chrono:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-chrono1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-chrono1.65.1
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-chrono1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-chrono1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-chrono1.62.0
- libboost-date-time:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-date-time1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-date-time1.65.1
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-date-time1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-date-time1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-date-time1.62.0
- libboost-filesystem:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-filesystem1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-filesystem1.65.1
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-filesystem1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-filesystem1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-filesystem1.62.0
- libboost-iostreams:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-iostreams1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-iostreams1.65.1
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-iostreams1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-iostreams1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-iostreams1.62.0
- libboost-program-options:
  - Ubuntu
    - focal: https://packages.ubuntu.com/focal/libboost-program-options1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-program-options1.67.0
- libboost-random:
  - Ubuntu
    - xenial: https://packages.ubuntu.com/xenial/libboost-random1.58.0
    - focal: https://packages.ubuntu.com/focal/libboost-random1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-random1.67.0
- libboost-system:
  - Ubuntu
    - trusty: https://packages.ubuntu.com/trusty/libboost-system1.55.0
    - xenial: https://packages.ubuntu.com/xenial/libboost-system1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-system1.65.1
    - disco: https://packages.ubuntu.com/disco/libboost-system1.67.0
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-system1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-system1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-system1.62.0
- libboost-thread:
  - Ubuntu
    - trusty: https://packages.ubuntu.com/trusty/libboost-thread1.55.0
    - xenial: https://packages.ubuntu.com/xenial/libboost-thread1.58.0
    - bionic: https://packages.ubuntu.com/bionic/libboost-thread1.65.1
    - disco: https://packages.ubuntu.com/disco/libboost-thread1.67.0
    - eoan/focal: https://packages.ubuntu.com/eoan/libboost-thread1.67.0
  - Debian
    - buster: https://packages.debian.org/buster/libboost-thread1.67.0
    - stretch: https://packages.debian.org/stretch/libboost-thread1.62.0

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Beat me to it. Thanks :+1:

**Comment by tfoote** [comment]
This looks reasonable but it needs a rebase now

**Comment by mikaelarguedas** [comment]
Rebased on top of https://github.com/ros/rosdistro/pull/23622 to avoid conflicting again when #23622 gets in.

**Comment by mikaelarguedas** [comment]
`libboost-regex` links

- Ubuntu
  - xenial: https://packages.ubuntu.com/xenial/libboost-regex1.58.0
  - bionic: https://packages.ubuntu.com/bionic/libboost-regex1.65.1
  - eoan/focal: https://packages.ubuntu.com/eoan/libboost-regex1.67.0
 - Debian
  - buster: https://packages.debian.org/buster/libboost-regex1.67.0
  - stretch: https://packages.debian.org/stretch/libboost-regex1.62.0

**Review by tfoote — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Friendly :bellhop_bell: 

Is there anything holding this back?

**Comment by nuclearsandwich** [comment]
> bellhop_bell
> 
> Is there anything holding this back?

I meant to review this yesterday and got caught up trying to get the other PR merged in cleanly before being pulled away. I'll try to get a second review on this today.

**Comment by rosbuild** [comment]
This pull request has been mentioned on **ROS**. There might be relevant details there:

https://discourse.ros.org/t/new-github-integration-with-ros-discourse/12627/1

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
I for one welcome our new well-scoped dependency overlords.

**Comment by rosbuild** [comment]
This pull request has been mentioned on **ROS**. There might be relevant details there:

https://discourse.ros.org/t/generating-dev-and-runtime-artefacts-from-ros-packages/12448/23

**Comment by gavanderhoorn** [comment]
@mikaelarguedas: any reason you did not include [libboost-math](https://packages.ubuntu.com/bionic/libboost-math1.65-dev)? It's only available on Bionic and later, but there are other keys like that.

**Comment by mikaelarguedas** [comment]
I simply replaced the ones already existing in the rosdep database and didnt add new ones. So my guess is that it wasn't in the database when I made this PR.

Rereading the description it looks like I added libboost-atomic(-dev), it must have been because some ros_core packages depended on it so I needed to add it to update those packages. There are likely multiple boost packages that still dont have a rosdep key

**Comment by ruffsl** [comment]
In addition to `libboost-math(-dev)`, could we add:
* `libboost-timer(-dev)`
* `libboost-serialization(-dev)`

**Pull request merged**
