### PR TITLE
Shadow robot kinetic distro

### PR DESCRIPTION
**Pull request by georgiablanco**
I'd like to add the Shadow Robot repos to be indexed and coumented on ros.org

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Hi @georgiablanco it looks like these repositories were added to Kinetic in #26918 and the commits later applied to this PR are removing the source entries. Is that intended or can this PR be closed?

**Comment by georgiablanco** [comment]
Yes I have removed the source on purpose.

**Comment by nuclearsandwich** [comment]
We are holding Kinetic releases in preparation for a [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2020-10-27/16997). While this is not a release in the interest of keeping the distribution stable during the sync window I'm going to wait to merge this until the sync is out.

**Comment by Blast545** [comment]
Sync is out

**Pull request merged**
