### PR TITLE
Add pyosmium

### PR DESCRIPTION
**Pull request by grecim**
Looking to add [pyosmium](https://osmcode.org/pyosmium/), which enables the creation of OpenStreetMap files from GPS coordinates.

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Following our 
Thanks for the contribution of rosdep keys. Please take a moment to update your PR following our rosdep rule [contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions). You can add changes to the branch you have submitted from or edit the description. When you make the changes please comment back on this PR so that we get a notification that you've updated it.

Please link to the packages and take a look for fedora and gentoo packages.

**Comment by grecim** [comment]
Ready for next review. Thanks.

**Review by tfoote — CHANGES_REQUESTED** [review]
Thanks for submitting this rule but a quick search shows that there's binary packages for it that we should prefer to use instead of the pip installations.

https://packages.debian.org/buster/python-pyosmium
https://packages.ubuntu.com/disco/python-pyosmium

On Fedora I only found a python3 version:
https://apps.fedoraproject.org/packages/python3-osmium

But the python3 version also exists for debian and ubuntu:
https://packages.ubuntu.com/disco/python3-pyosmium
https://packages.debian.org/buster/python3-pyosmium

On the other platforms we can fall back to pip. 

As a side note, we do already have the c++ bindings in the database: https://github.com/ros/rosdistro/pull/9056

**Comment by clalancette** [comment]
There's been no response on this for almost a month, so I'm going to close this out for now.  Feel free to reopen when you have time to fix it up like the previous comment.  Thanks.

**Comment by grecim** [comment]
I am ready to re-open

**Comment by tfoote** [comment]
Follow up in #21608

**Pull request closed without merging**
