### PR TITLE
Feature/python3 bs4

### PR DESCRIPTION
**Pull request by hakuturu583**
This package is based on Python2. (https://github.com/ros/rosdistro/blob/ddaa4b4b257cac3915a0a85f57a14d9fb82f43bf/rosdep/python.yaml#L754)
https://packages.ubuntu.com/ja/bionic/python-beautifulsoup
We want to use beautifulsoup4 in Python3.
So we want to add this package into rosdistro.
https://pypi.org/project/beautifulsoup4/

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
This appears to be packaged for Ubuntu already and we should use that version:

https://packages.ubuntu.com/bionic/python3-bs4

Also Debian https://packages.debian.org/buster/python3-bs4

Please search for other platforms and switch this to use the native packages not pip.

**Comment by hakuturu583** [comment]
Change to the native package.

**Comment by hakuturu583** [comment]
Ubuntu : https://packages.ubuntu.com/bionic/python3-bs4
Debian : https://packages.debian.org/buster/python3-bs4
Arch : https://www.archlinux.org/packages/community/any/python-beautifulsoup4/
Fedora：https://src.fedoraproject.org/rpms/python-beautifulsoup4

**Review by mjcarroll — APPROVED** [review]

**Review by tfoote — APPROVED** [review]
Thanks for the iteration lgtm

**Pull request merged**
