### PR TITLE
rosdep: python-msgpack support for ubuntu xenial

### PR DESCRIPTION
**Pull request by ledmonster**
Add python-msgpack support for ubuntu xenial

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]
Please consider to check and add the package for the Ubuntu distros in between (U, V, W) and also Y.

**Comment by ledmonster** [comment]
@dirk-thomas okay, I'll add aditional distros support.

**Comment by ledmonster** [comment]
@dirk-thomas Add support for ubuntu from U to Y.

**Comment by tfoote** [comment]
Thanks!

**Pull request merged**
