### PR TITLE
Shadow robot melodic distro

### PR DESCRIPTION
**Pull request by georgiablanco**
I'd like to add Shadow Robot repos to be indexed and documented on ros.org

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Hi @georgiablanco it looks like these repositories were added to Kinetic in #26919 and the commits later applied to this PR are removing the source entries. Is that intended or can this PR be closed?

**Comment by georgiablanco** [comment]
Yes I have removed the source on purpose.

**Comment by nuclearsandwich** [comment]
Why remove the source entries and not the doc entries?

**Comment by georgiablanco** [comment]
because I was meant to do [this](http://wiki.ros.org/rosdistro/Tutorials/Indexing Your ROS Repository for Documentation Generation) and so realised source doesn't need to be there.

**Comment by nuclearsandwich** [comment]
Thanks for clarifying.

**Comment by georgiablanco** [comment]
Thank you. May you please do the Kinetic branch also? https://github.com/ros/rosdistro/pull/27190

**Comment by nuclearsandwich** [comment]
Please see https://github.com/ros/rosdistro/pull/27190#issuecomment-718898597 for why that one is still pending.

**Pull request merged**
