### PR TITLE
Add lidar_s_graphs to humble and iron distributions

### PR DESCRIPTION
**Pull request by hridaybavle**
## Package names:

  * [lidar_s_graphs](https://github.com/snt-arg/lidar_s_graphs.git)
  
## Package Upstream Source:

https://github.com/snt-arg/lidar_s_graphs.git

## Purpose of using this:

Repository to generate in real-time situational graphs for robot pose and high-Level map Optimization using 3D LiDAR data. Apart from the main package there also dependencies of `lidar_s_graphs` in the which will be uploaded to `distribution.yaml` in seperate PRs. The scientific paper can be found [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10168233).

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/snt-arg/lidar_s_graphs.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by hridaybavle** [comment]
@clalancette, since all the debs of this lidar_s_graphs are accepted, could you accept this PR as well?

**Comment by clalancette** [comment]
> @clalancette, since all the debs of this lidar_s_graphs are accepted, could you accept this PR as well?

This one still needs to be renamed as well, to `lidar_situational_graph`.

**Comment by hridaybavle** [comment]
okay working on it.

**Comment by hridaybavle** [comment]
@clalancette I have renamed `lidar_s_graphs` to `lidar_situational_graphs`, the PR should be ready to be merged as well. 

Thanks again.

**Comment by sloretz** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-06-07/38086)

**Review by clalancette — APPROVED** [review]

**Pull request merged**
