### PR TITLE
Add simple_desktop_launcher

### PR DESCRIPTION
**Pull request by VictorLamoine**

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
According to the [guidelines](http://wiki.ros.org/ROS/Patterns/Conventions), new packages shouldn't use `ros` in the name.  Also, having `test` in the name is a little confusing (at least to me); the [README](https://gitlab.com/InstitutMaupertuis/ros_desktop_launcher_test) seems to suggest that this package actually installs desktop launchers.

**Comment by VictorLamoine** [comment]
The goal of this package is to demonstrate how to install desktop launcher for a ROS application.
It has no other use than educational / example

`desktop_launcher_example`
`simple_desktop_launcher`

What do you think is best?

**Comment by clalancette** [comment]
I prefer `simple_desktop_launcher`; @tfoote any opinions?

**Comment by VictorLamoine** [comment]
@clalancette I have renamed the package to `simple_desktop_launcher`

**Comment by clalancette** [comment]
> @clalancette I have renamed the package to `simple_desktop_launcher`

Thanks, appreciated.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
