### PR TITLE
Update Heifu-release version

### PR DESCRIPTION
**Pull request by BV-OpenSource**

### CODE REVIEW

**Comment by clalancette** [comment]
Is there a particular reason you didn't use `bloom-release` for this?  It is our preferred form for updates, as it ensures that everything is working.

**Comment by amferreiraBEV** [comment]
> Is there a particular reason you didn't use `bloom-release` for this? It is our preferred form for updates, as it ensures that everything is working.

At the end of the `bloom-release` command it was mentioned to "manually open a pull request".
At the moment I've the OAuth token needed so I believe that from now on it will be with bloom.

**Comment by clalancette** [comment]
> At the end of the `bloom-release` command it was mentioned to "manually open a pull request".
> At the moment I've the OAuth token needed so I believe that from now on it will be with bloom.

Sounds good, thanks for the explanation.

**Comment by amferreiraBEV** [comment]
@clalancette sorry to bother you but to whom can I address for help in Jenkins building errors?

**Pull request merged**
