### PR TITLE
Add key for pip package cppcheck-junit

### PR DESCRIPTION
**Pull request by jlack1987**
Just add a key for the pip package `cppcheck-junit`. Wasn't able to find a debian for it.

### CODE REVIEW

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
The keys need to be in alphabetical order
If creating a key for packages only available via pip, please add the `-pip` suffix. Also we try to add entries for at least ubuntu and debian when adding a new key.

Thanks!

**Comment by jlack1987** [comment]
Lol thought I put it in alphabetical order, turns out "c" comes before "d". Haha ya learn something new everyday. Fixed, thanks!

**Comment by mikaelarguedas** [comment]
haha it happens, unfortunately is also applies to the list of platforms so you will need to put debian before ubuntu

**Review by mikaelarguedas — APPROVED** [review]
lgtm thanks @jlack1987 for the quick iteration!

**Pull request merged**
