### PR TITLE
Added python-flatdict-pip

### PR DESCRIPTION
**Pull request by reinzor**
For flattening dictionaries to work with rosbag_pandas

### CODE REVIEW

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of packaging for debian / ubuntu as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of packaging for debian / ubuntu as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of packaging for debian / ubuntu as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of packaging for debian / ubuntu as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of packaging for debian / ubuntu as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/ 

No sign of debian / ubuntu package as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/ 

No sign of debian / ubuntu package as far as I know

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of a debian / ubuntu package as far as I know.

**Comment by reinzor** [comment]
https://pypi.org/project/flatdict/

No sign of a debian / ubuntu package as far as I know.

**Review by tfoote — APPROVED** [review]

**Comment by reinzor** [comment]
Can this be merged?

**Comment by reinzor** [comment]
Could you give an update on this, or what the timeline is. I am waiting for this ROS package before releasing https://github.com/eurogroep/rosbag_pandas

**Comment by tfoote** [comment]
@reinzor I'm pinging some others to try to get this reviewed. But note that you cannot make a release using a pip entry. Releases require the rosdep rules resolve by the primary package manager. On Ubuntu and Debian that's apt.

**Comment by reinzor** [comment]
> @reinzor I'm pinging some others to try to get this reviewed. But note that you cannot make a release using a pip entry. Releases require the rosdep rules resolve by the primary package manager. On Ubuntu and Debian that's apt.

@tfoote , thanks for the help. Regarding that releases only may depend on apt package: didn't know that. Thanks for the info. How would you suggest I release something depending on pip packages? Including the source in the package? Is there some documentation about release requirements?

**Comment by tfoote** [comment]
You can embed the source into your package. But make sure to keep it off the path to avoid side effecting other packages accidentally. But in general we strongly recommend focusing on knowing what's available in the upstream and developing applications with that in mind. We also pay attention to what we'll want in future releases and push to get things released into debian packages ahead of time too. It's a bit of a pain but at some level we all need to be patient and consistent in the versions of software that we release so they can all go through the QA process.

**Pull request merged**
