### PR TITLE
Update distribution.yaml

### PR DESCRIPTION
**Pull request by ZhuangYanDLUT**
Add IG_exploration and exploration_planning while are used in autonomous environment exploration.
I'd like IG_exploration and exploration_planning to be indexed and documented on ros.org

### CODE REVIEW

**Comment by ZhuangYanDLUT** [comment]
I'd like IG_exploration and exploration_planning to be indexed and documented on ros.org

**Comment by mikaelarguedas** [comment]
this branch has conflicts, can you please rebase it ?

**Comment by mikaelarguedas** [comment]
@ZhuangYanDLUT friendly ping

**Comment by mikaelarguedas** [comment]
@ZhuangYanDLUT I'm closing this due to no response. Feel free to comment here or to open a new pull request once this branch is rebased

**Pull request closed without merging**
