### PR TITLE
Removed ridgeback_robot source.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Comment by tfoote** [comment]
Why are you removing the source entry? That's important for users who want to build from source.

**Comment by tonybaltovski** [comment]
I wanted to get rid of the failing build.

**Comment by tfoote** [comment]
You can just turn off the devel job using  `test_commits: false`  see [rep 143](http://www.ros.org/reps/rep-0143.html) for the syntax documentation.

**Comment by tfoote** [comment]
See #11183 for an example

**Comment by tonybaltovski** [comment]
Will change but isn't the default suppose to be false according to REP143?

**Comment by tfoote** [comment]
It's the default value, however it's overridden at the build file level to default to true. https://github.com/ros-infrastructure/ros_buildfarm_config/blob/production/kinetic/source-build.yaml#L53

**Pull request closed without merging**
