### PR TITLE
qb_hand: 2.2.2-1 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by umbertofontana93**
Increasing version of package(s) in repository `qb_hand` to `2.2.2-1`:

- upstream repository: https://bitbucket.org/qbrobotics/qbhand-ros.git
- release repository: https://bitbucket.org/qbrobotics/qbhand-ros-release.git
- distro file: `noetic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## qb_hand

- No changes

## qb_hand_control

- No changes

## qb_hand_description

- No changes

## qb_hand_hardware_interface

- No changes

### CODE REVIEW

**Review by audrow — APPROVED** [review]

**Comment by ivanpauno** [comment]
@umbertofontana93 Could you resolve conflicts?

**Comment by sloretz** [comment]
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-09-06/)

**Comment by tfoote** [comment]
This also conflicts with #30601 I recommend rebasing it on top of #30603 so we can merge that one and then this one as I suspect they will conflict too.

**Review by tfoote — CHANGES_REQUESTED** [review]
in this PR you're replacing qb_move with qb_hand. You need to insert the new release, not overwrite the other existing releases.

**Comment by umbertofontana93** [comment]
I have opened another PR #30766. You can close this one

**Pull request closed without merging**
