### PR TITLE
Add mola_test_datasets for indexing

### PR DESCRIPTION
**Pull request by jlblancoc**
# Please Add This Package to be indexed in the rosdistro.

humble, iron, rolling

# The source is here:

https://github.com/MOLAorg/mola_test_datasets

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [X] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by Yadunund — APPROVED** [review]

**Comment by Yadunund** [comment]
Will defer to @tfoote and @adityapande-1995 for final approval since it's a new package.

**Comment by tfoote** [comment]
The name looks ok with the prefix. However I notice the readme says "Each dataset file holds the license of their original authors. Refer to each subdirectory." But the package.xml only says BSD. And I didn't find license files in the subdirectories.

**Comment by jlblancoc** [comment]
@tfoote Please, take a [look at the repo now](https://github.com/MOLAorg/mola_test_datasets) and let me know if it's clearer via the `*/README.md` files, or if I should reflect this somehow in the package.xml too. Thanks.

**Comment by tfoote** [comment]
There should be multiple license lines in the package.xml to provide a complete picture of the licenses included in the package so that if someone is auditing packages on their system the package.xml will give them the quick summary. 

And the Readme is good for readability and discovery. I'd recommend a link to the upstream projects. 

And please place a LICENSE file in each of the directories copied from the upstream repository as the short names are only categories and the actual license text is what is enforceable. 

You can reference those files from each license tag in the xml.

**Comment by jlblancoc** [comment]
@tfoote Ok, it makes sense. It's now done upstream via [this commit](https://github.com/MOLAorg/mola_test_datasets/commit/504b249c566b134ecea28d22e778bf285f75cd20).

**Review by tfoote — APPROVED** [review]
Thanks for the extra followups. I know that it can feel like a pain, but these things are important to make sure we keep clear.

**Comment by jlblancoc** [comment]
I know, no problem! I'm used to similar issues with `debian/copyright` in other packages :-) Thanks for the quick follow up.

**Comment by tfoote** [comment]
Yeah, we actually generate those for the debian packages from the package.xml

**Pull request merged**
