### PR TITLE
Add autossh

### PR DESCRIPTION
**Pull request by erelson**
Didn't find any cases of different package name via google.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Can you please provide the links of the ones that are added in this PR ?

**Comment by erelson** [comment]
@mikaelarguedas Haven't done the link searching before. I'm assuming I just need links indicating that packages exist; some of these links seem better than others, but they all seem official?:

- Debian: https://packages.debian.org/search?keywords=autossh
- Fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/autossh/
- freebsd: http://www.freebsdsoftware.org/security/autossh.html
- gentoo: https://packages.gentoo.org/packages/net-misc/autossh
- macports: https://github.com/macports/macports-ports/tree/master/net/autossh/files
- opensuse: https://software.opensuse.org/download.html?project=security&package=autossh
- Rhel: https://rpmfind.net/linux/rpm2html/search.php?query=autossh
- ubuntu: https://launchpad.net/ubuntu/+source/autossh

**Comment by mikaelarguedas** [comment]
Thanks that list is exactly what I was looking for!

> I'm assuming I just need links indicating that packages exist

Yeah basically know that the package manager can install them :+1: 
e.g. for debian/ubuntu  packages.debian.org and packages.ubuntu.com

In the case of gentoo you will need to add the category: `[autossh]` => `[net-misc/autossh]`

**Comment by erelson** [comment]
Fixed up the gentoo one

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @erelson for iterating

**Pull request merged**
