### PR TITLE
Add libpcl-dev, libpcl-all-dev for Focal

### PR DESCRIPTION
**Pull request by rotu**
all packages: https://packages.ubuntu.com/search?suite=focal&section=all&arch=any&keywords=libpcl-&searchon=names

### CODE REVIEW

**Comment by cottsay** [comment]
From the [`CONTRIBUTING.md`](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions):
> For convenience in reviewing, please comment in the PR with links to the web listings of packages such as on http://packages.ubuntu.com

**Comment by cottsay** [comment]
Here is a direct, unambiguous link to the package backing this new rule: https://packages.ubuntu.com/focal/libpcl-dev

If I'm not mistaken, the missing rule in ros-infrastructure/rosdep#747 is for the `libpcl-all` key, not `libpcl-all-dev`.

**Comment by rotu** [comment]
you're right and I intended to add both.

**Review by cottsay — APPROVED** [review]
All of the packages in the list appear to exist in Focal, and there don't appear to be any new subpackages in PCL 1.10 that should be added.

**Comment by cottsay** [comment]
@rotu - this change looks fine, but you need to fix CI for us to merge it.

**Comment by rotu** [comment]
Oops! CI fixed

**Review by clalancette — APPROVED** [review]

**Pull request merged**
