### PR TITLE
Add Turtle Nest for indexing

### PR DESCRIPTION
**Pull request by Jannkar**
# Please Add Turtle Nest to be indexed in the rosdistro.

humble, iron, jazzy, rolling

# The source is here:

https://github.com/Jannkar/turtle_nest

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/Jannkar/turtle_nest/blob/main/LICENSE
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): https://opensource.org/license/apache-2-0
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/Jannkar/turtle_nest
- [x] Source repository contains ROS packages - yes, though the organization is a bit different than we are used to.  There are 4 top-level directories, but only one of them contains a ROS package (turtle_nest)
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - The package name doesn't exactly explain what it does, but I also don't think it violates REP-144.  @alsora what do you think?

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
@Jannkar Due to changes unrelated to your PR, this needs a rebase to pass CI.  Thanks in advance!

**Comment by alsora** [comment]
> Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - The package name doesn't exactly explain what it does, but I also don't think it violates REP-144. @alsora what do you think?

I agree with your assesment.
I think we have a lot of packages that use a "codename" as package name, which is not descriptive at all of what the package does.
Prohibiting that, would cause a proliferation of packages with either very similar names or very long names.

**Review by alsora — APPROVED** [review]

**Comment by Jannkar** [comment]
Thank you! I've now rebased.

I was also thinking about the package structure, as I noticed that usually the repo seems to be either a single package or set of packages. I chose this structure, since I wanted to avoid including for example docker stuff and images into the package itself. Is it fine like this?

**Comment by mikeferguson** [comment]
> I think we have a lot of packages that use a "codename" as package name, which is not descriptive at all of what the package does (unless you know the project).

To be fair, ROS is not really an "operating system". Further, most of the core packages aren't really all that "robot" specific either...

**Pull request merged**
