### PR TITLE
add python-zmq for latest ubuntu distros

### PR DESCRIPTION
**Pull request by fmessmer**
https://packages.ubuntu.com/search?keywords=python-zmq

or should I use the default notation?
`    '*': [python-zmq]`

### CODE REVIEW

**Comment by tfoote** [comment]
It would be great to switch to use the wildcard notation. When trusty is no longer supported we can then just collapse it to the default rule since the package is unchanging.

**Comment by fmessmer** [comment]
using wildcard now

**Comment by fmessmer** [comment]
this is blocking us quite a bit atm...could this please be reviewed/merged?...thanks

**Review by tfoote — APPROVED** [review]
Thanks for iterating. I also removed the now redundant rules. It looks good to me.

**Review by floweisshardt — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
