### PR TITLE
fetch_gazebo: 0.9.0-0 in 'melodic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by moriarty**
Increasing version of package(s) in repository `fetch_gazebo` to `0.9.0-0`:

- upstream repository: https://github.com/fetchrobotics/fetch_gazebo.git
- release repository: https://github.com/fetchrobotics-gbp/fetch_gazebo-release.git
- distro file: `melodic/distribution.yaml`
- bloom version: `0.7.2`
- previous version for package: `null`

## fetch_gazebo

```
* Improved wheel frictions (#59 <https://github.com/fetchrobotics/fetch_gazebo/issues/59>)
* fetch_gazebo: add casters to fetch.gazebo.xacro (#49)
  
  This adds 4 casters to the gazebo model, and updates the physics params.
  This should fix #31 and fix #35
  This is related to #37
* [package.xml] adds: license(BSD), author, maintainers (#45)
  
  [package.xml] update maintainers
  
  [fetchit_challenge] adds license(BSD), author, maintainers
  
  [fetchit_challenge] add <url> tags to package.xml
* [CMake/Catkin] fetch_gazebo install headers (#43)
  
  catkin_make_isolated --install would fail because we were not installing the header files
  This fixes #42
* [CMake][package] Clean CMake warnings and REP-140 (#29)
  
  This cleans up some, but misses one warning- might be coming from gazebo itself.
  Also moved to package.xml format 2
* Merge pull request #25 from stfuchs/fix/melodic-rosdep
  
  change rosdep from gazebo7 to gazebo9
* Merge pull request #24 from mikeferguson/gazebo9
  
  fixes for gazebo9 (melodic)
* updates for gazebo7
* Contributors: Alex Moriarty, Michael Ferguson, Miguel Angel Rodríguez, Russell Toris, Steffen Fuchs
```

## fetch_gazebo_demo

```
* Improved pick place frictions (#59)
  
  Added higher frictions to avoid the base movements when moving the arm, and also added a simple pick and place environment for fast testing
  
  Added a script that can be used to test basic movement with fetch arm and gripper and also test that the friction is enough that movement of the arm wont affect it
  
  [gazebo_demo] Install script and depends
* [package.xml] adds: license(BSD), author, maintainers (#45)
  
  [package.xml] update maintainers
  
  [fetchit_challenge] adds license(BSD), author, maintainers
  
  [fetchit_challenge] add <url> tags to package.xml
* Merge pull request #32 from RDaneelOlivav/gazebo9
  
  FetchIt Challenge Package addition and minor melodic Moveit Fix
* Added correction suggested in pick and place demo script and new tables
* Corrected Bug for new Melodic MoveIt Version
* Contributors: Alex Moriarty, Miguel Angel Rodríguez
```

## fetch_simulation

```
* [fetch_simulation] fix filename & CMakeLists.txt
  
  cherry-pick 730051a64df815ed61b6d3fb012fb5a225ae2e2e
* [fetch_simulation] new meta-package (#52)
  
  A meta-package makes installing things easier and they're used with
  wiki.ros.org and index.ros.org to automatically group and link things.
* Contributors: Alexander Moriarty
```

## fetchit_challenge

```
* [FetchIt!] Don't find_package an exec_depend
* [package.xml] sync versions to 0.8.0
* [fetchit] catkin depends and installation (#58)
  
  The models, scripts and launch files were not installed. Fixes #57
* [FetchIt!] fix the stl collision scales (#60)
  
  Added rescaled stls with corrected origins that generated issue that seems they were no collisions but in fact they were decentered and huge.
  This fixes #56
* [FetchIt!] Model updates for new largeGear (#51)
  
  [FetchIt!] STL updates for new largeGear
  
  This fixes #50 in part, the stl files
  
  These changes correspond to fetchrobotics/fetchit#2
  
  Added updated dae versions with rescaling to correct dimensions and same colours as previous versions
* [package.xml] adds: license(BSD), author, maintainers (#45)
  
  [package.xml] update maintainers
  
  [fetchit_challenge] adds license(BSD), author, maintainers
  
  [fetchit_challenge] add <url> tags to package.xml
* Merge pull request #38 from RDaneelOlivav/gazebo9
  
  Invisible table and gear Fix, creation of simpler simulation environment, creation of different lighting conditions launches
* Merge pull request #32 from RDaneelOlivav/gazebo9
  
  FetchIt Challenge Package addition and minor melodic Moveit Fix
* Added fetchit Challenge package files
* Contributors: Alexander Moriarty, Miguel Angel Rodríguez
```

### CODE REVIEW

**Review by sloretz — APPROVED** [review]

**Comment by sloretz** [comment]
Holding for [melodic sync](https://discourse.ros.org/t/preparing-for-melodic-sync-2019-03-25/8454)

**Comment by DanielTakeshi** [comment]
Hello! I am wondering if the "sync" means we will be able to install gazebo? We are having some problems installing the robot, as outlined here: https://github.com/fetchrobotics/fetch_gazebo/issues/77

**Comment by moriarty** [comment]
Holding for sync, means it was approved but too near to the “sync”.

When package updates are merged into rosdep, they’re available in shadow-fixed, until the next sync.

This gives developers, maintainers and users who want to help test the bleeding edge time to find and fix bugs. Once there is a “sync” they packages from shadow-fixed become available, they are “synced” to the regular ROS repos.

Packages are not merged just before a sync- because then there would be the potential to break something... so they’re approved but “held until the after the sync”  and after the sync they are merged into rosdep, and available to test from shadow-fixed.

So, this PR, was too close to the last Melodic sync to be merged and tested. It has since been merged and is now available on ROS shadow-fixed. 

When there is another sync, it will become available in the main repos.

Syncs generally happen every 2 weeks, sometimes longer.

**Comment by tfoote** [comment]
@DanielTakeshi  That's a good summary from @moriarty 
 You can find more info at: http://wiki.ros.org/ShadowRepository

**Pull request merged**
