### PR TITLE
dev-util/eclipse-sdk-bin was removed from gentoo

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
https://github.com/ros/rosdistro/issues/15082 for reference

**Comment by mikaelarguedas** [comment]
@Alessandro-Barbieri please provide reference/link of package removal along the PR that removes them

**Comment by Alessandro-Barbieri** [comment]
Don't know, in gentoo database there is no more

**Comment by allenh1** [comment]
@mikaelarguedas I can't find a URL for it either, but I can confirm that it was removed some time ago.

**Comment by mikaelarguedas** [comment]
sounds good thanks both of you for confirming

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
