### PR TITLE
applied pep8 rules

### PR DESCRIPTION
**Pull request by alexanderLinear**
applied style for most of locations reported by this line:

`find . -name '*.py' -not -path '*/.*' -exec pep8 {} --max-line-length 160 --ignore E701 \;`

### CODE REVIEW

**Comment by alexanderLinear** [comment]
@tfoote - can you take a look here?

**Comment by AlexanderStohr** [comment]
hmm - the tooling proposed to merge towards ros:master but the checker seems to choke because there is no ros:master.
galactic might be the default on ros: - but of course there are also e.g. humble or rolling.
:-/

**Comment by emersonknapp** [comment]
Is there any proposal here to add in an enforcer for this choice of formatting style? Doing a pass on the code is all well and good (if one agrees with the choice of formatter, which I have no opinion on in this case) but unless a linter is plugged in  to review PRs moving forward then it won't stick - and if it's not enforced then philosophically I lean against  changing the existing code even if it is a functional no-op.

**Comment by AlexanderStohr** [comment]
> **Validate rosdistro / rosdistro / rosdep checks (3.8) (pull_request) ** Failing after 12m

just a short blink here - not sure if that is "good" already or if this is relevant here... but there are checks:

"Validate rosdistro / rosdistro / rosdep checks (3.8) (pull_request) Failing after 12m"

**Comment by emersonknapp** [comment]
> PEP8 is the base "standard" 

That's fine. It's not what I was trying to comment on. I'm saying - "if you want to enforce a code formatting standard on this repository, then add automated tooling that enforces it". Pytest is being run on the repo in the PR checker, so maybe a pytest that checks pep8 formatting for the repo? Or if that has issues then at least a separate Github Action?

**Comment by tfoote** [comment]
It is useful to conform with the standard. Though there's overhead to general refactors in terms of maintainability. So I agree with Emerson's suggestion that to take this effort we should also add the linter such as flake8 to the unit tests. 

Picking one off the top of my head rosdep has an example: https://github.com/ros-infrastructure/rosdep/blob/master/test/test_flake8.py

**Comment by sloretz** [comment]
Thanks for the PR!

It looks like it's been a little while, and there's now a merge conflict. I'll close this for now, but we can reopen once there's a unit test to make sure the style sticks.

**Pull request closed without merging**
