### PR TITLE
add cognitao_ros for Kinetic

### PR DESCRIPTION
**Pull request by cogniteam**
Adding CogniTAO ROS git repos

### CODE REVIEW

**Review by cogniteam — COMMENTED** [review]
missed tag

**Review by cogniteam — COMMENTED** [review]
Develop branch in cognitao_ros

**Comment by dirk-thomas** [comment]
Please update your package manifests to contain a valid maintainer name and email as well as license.

**Comment by YakirHuri** [comment]
Hello,
I updated on project cognitao_ros 
and also on project cognitao_ros2 the license and the email
(in all package.xml files),
Regards,
Yakir Huri (cogniteam)

**Comment by dirk-thomas** [comment]
(Leaving it up to @tfoote when to merge.)

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
Holding for Kinetic [sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-12-11/11907).

**Pull request merged**
