### PR TITLE
add kinetic:eyantra_drone

### PR DESCRIPTION
**Pull request by simmubhangu**
Add eyantra_drone to kinetic index

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
The package.xml files declare the license to be BSD, but the LICENSE file appears to be the only license in the repository and it contains the GPL. 

Please resolve this discrepancy to be listed.

**Comment by simmubhangu** [comment]
I have changes the license on git to BSD-2

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
Holding for kinetic [sync](https://discourse.ros.org/t/preparing-kinetic-sync-2019-07-08/9818)

**Comment by tfoote** [comment]
Please note that standard practice for BSD licenses is to put the full license into the top of every source file in comments.

**Pull request merged**
