### PR TITLE
Define which sources are valid for rosdep keys

### PR DESCRIPTION
**Pull request by tfoote**

### CODE REVIEW

**Comment by tfoote** [comment]
@cottsay @allenh1 @russkel could you take a few moments to fill in the requirements for Fedora, Gentoo, and Alpine as amendments to this PR?

**Comment by allenh1** [comment]
@tfoote I am ready to push but don't have write access here, actually. I can email you a patch to `git am` into your branch or PR it into yours.

Let me know your preference.

**Comment by tfoote** [comment]
A PR into this branch would be great.

**Review by allenh1 — APPROVED** [review]
lgtm

**Review by clalancette — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
I have added an Archlinux entry. The link to the AUR installer issue in rosdep may be more information than needed.

**Comment by russkel** [comment]
Pedantic: I believe it's referred to as Arch Linux

**Comment by nuclearsandwich** [comment]
> Pedantic: I believe it's referred to as Arch Linux

I swear they change it every few years just to mess with me.

**Comment by tfoote** [comment]
Thanks for all the updates. This looks like a better state than we had before. More followups are welcome too if we need to iterate.

**Pull request merged**
