### PR TITLE
add lark-parser for debian via pip

### PR DESCRIPTION
**Pull request by christianrauch**
Add pip package `lark-parser` (https://pypi.org/project/lark-parser/) for Debian Stretch.

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
This rule is specifically for python3. We don't have a good way of capturing that in the pip rules and it looks like we haven't forced that wrt to other rules. 

But I can't find any debian package lark-parser and it should be made sure that it's a python3 package too which from the name doesn't look likely.

**Comment by christianrauch** [comment]
Yes, it's a python3 package.
I am not sure how I can force the python3 version via the rosdep file. It's up to the version of pip which python version of the package is installed. But since ROS2 defaults to python3 (and ROS1 to python2), the corresponding python version should be used to install pip packages.

**Comment by tfoote** [comment]
I agree that the pip rule is functional. But the debian rule is incorrect as that package is both the wrong python version and doesn't exist for either version.

**Comment by nuclearsandwich** [comment]
With https://github.com/ros/rosdistro/pull/22234 merged I would propose that we close this PR.

**Comment by christianrauch** [comment]
Is `python3-lark-parser` now a Debian package that has been manually added to the ROS repo for stretch and buster?

In that case, the `pip3` installation of the package is not required and this PR can be closed.

**Comment by nuclearsandwich** [comment]
> Is `python3-lark-parser` now a Debian package that has been manually added to the ROS repo for stretch and buster?

Yes. It's both the ROS and ROS 2 repositories and their respective testing repos for Ubuntu Bionic and Debian Stretch and Buster. For future distributions I'm going to try and get the packages submitted upstream.

**Pull request closed without merging**
