### PR TITLE
Update sparsehash os

### PR DESCRIPTION
**Pull request by DangitBen**
## Package name:

sparsehash

## Package Upstream Source:

https://github.com/sparsehash/sparsehash

## Purpose of using this:

The Google SparseHash project contains several C++ template hash-map implementations in use at Google, with different performance characteristics, including an implementation that optimizes for space and one that optimizes for speed.

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/sid/libsparsehash-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://packages.ubuntu.com/search?keywords=sparsehash
- More already in use, that this PR _does not_ change.

### CODE REVIEW

**Comment by cottsay** [comment]
Could we please update this rule to use a wildcard in the OS version? The package name appears to be somewhat stable upstream now.

https://www.ros.org/reps/rep-0111.html#wildcard-os-version

**Comment by DangitBen** [comment]
> Could we please update this rule to use a wildcard in the OS version? The package name appears to be somewhat stable upstream now.
> 
> https://www.ros.org/reps/rep-0111.html#wildcard-os-version

@cottsay that seems useful. Something like this?

```
ubuntu:
    '*': [libsparsehash-dev]
    precise: [sparsehash]
    saucy: [sparsehash]
    trusty: [sparsehash]
    utopic: [sparsehash]
```

**Comment by tfoote** [comment]
@DangitBen Yes that's what he was proposing. However looking at that list those are all completely EOL platforms so we could actually even simplify further without the need for the wildcard or any version specific tags. 

`ubuntu: [libsparsehash-dev]`

Would be adequate just like the debian one.

**Comment by DangitBen** [comment]
@tfoote Even better. Thanks!

**Review by tfoote — APPROVED** [review]
thanks for the iteration!

**Comment by DangitBen** [comment]
Confirmed this works following [this page's](http://docs.ros.org/en/independent/api/rosdep/html/contributing_rules.html) guide.

```bash
bandrew@TARS:~ $ rosdep resolve --os=ubuntu:focal sparsehash
#apt
libsparsehash-dev
```

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
