### PR TITLE
Mark Foxy as end-of-life.

### PR DESCRIPTION
**Pull request by clalancette**

### CODE REVIEW

**Review by adityapande-1995 — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
Hold for final rosboss (@quarkytale) approval

**Review by quarkytale — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
For future EOL PRs I would recommend disabling build farm jobs before merging this change. `ros_buildfarm` uses the rosdistro index to identify active ROS distributions and so foxy devel jobs have been failing to run since this change was merged.

**Comment by nuclearsandwich** [comment]
## Foxy build farm wind-down

- [x] Stop merging all foxy-related ros/rosdistro PRs
- [x] Tag the last commit of ros2/ros_buildfarm_config which includes the foxy config and push the tag: https://github.com/ros2/ros_buildfarm_config/releases/tag/foxy-20230626-config
- [ ] Delete foxy jobs from ros2/ros_buildfarm_config: https://github.com/ros2/ros_buildfarm_config/pull/275
- [ ] Disable jobs using the method described in https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/ongoing_operations.rst (but with batching)
- [x] This is when I'd recommend a PR like this one be merged: https://github.com/ros/rosdistro/pull/36211
- [ ] Update distro in https://github.com/ros-infrastructure/rosindex/blob/ros2/_config.yml#L87-L115
- [ ] After a few weeks, assuming that no one has asked to resurrect foxy for a fixup sync, the jobs can be deleted using a modified copy of the disabling script.

**Comment by quarkytale** [comment]
Thanks for the super helpful checklist!

**Pull request merged**
