### PR TITLE
added avaliable ubuntu bionic packages

### PR DESCRIPTION
**Pull request by jorritsmit**
These packages are available in the bionic repository

### CODE REVIEW

**Review by tfoote — DISMISSED** [review]
Please either add Y Z A as well as B.

Most of these look like they'd make sense to switch to 
```
'*': [package_name]
'lucid':
  pip:
    packages: [pip_package_name]
```

For a more compact and maintainable version.

**Comment by jorritsmit** [comment]
i can do both, what do you prefer?

**Comment by tfoote** [comment]
Using the * syntax for the current and expected future versions would be great. Listing the older versions explicitly as blank.

**Review by mikaelarguedas — COMMENTED** [review]
changes looks good to me except the wildcard use for the `python-requests` rules

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @jorritsmit for iterating!

I'll leave it up to @tfoote to provide 2nd review and merge

**Review by tfoote — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
Rebased and resolved conflicts now that https://github.com/ros/rosdistro/pull/18767 has been merged

**Review by mikaelarguedas — APPROVED** [review]

**Pull request merged**
