### PR TITLE
Add graph_datasets to rosdistro

### PR DESCRIPTION
**Pull request by hridaybavle**
## Package names:

  * [graph_datasets](https://github.com/snt-arg/graph_datasets.git)
  
## Package Upstream Source:

https://github.com/snt-arg/graph_datasets.git

## Purpose of using this:

Structured indoors synthetic dataset in the form of graphs as a tool for [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git). 

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/snt-arg/graph_datasets.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): GPLv3
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/snt-arg/graph_datasets
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - Unfortunately this name is far too generic; this could be about many different concepts in robotics or even computer science.  I'm going to suggest you rename this package to `situational_graph_datasets`, or `snt_situational_graph_datasets`.

Besides that, the source repository is missing a `setup.cfg` file, and the `setup.py` file has a bunch of TODOs in it.

**Comment by hridaybavle** [comment]
Hello @clalancette, I have done the renaming of the repos as suggested by you previously. They now start with a prefix `situational`. Could you confirm this is okay so can I make commit to the other PRs as well. Thanks. 

Also this source repo now has the `setup.py` and `setup.cfg`.

**Review by mjcarroll — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): GPLv3
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/snt-arg/situational_graphs_datasets
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

I'm going to approve this, but I will suggest that you update https://github.com/snt-arg/situational_graphs_datasets/blob/develop/setup.py to include the license and the maintainer.

**Comment by clalancette** [comment]
Note that this needs to be rebased now because we merged some of the other packages.  Once that is done, we can get this in, thanks!

**Pull request merged**
