### PR TITLE
Revert "Pin version of PyYAML to fix rosdistro checks."

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Reverts ros/rosdistro#18283 to allow testing of an updated change https://github.com/ros/rosdistro/pull/18290.

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
For some reason there's a handful of empty revert commits for PRs made since this change. I don't actually follow why they're there. While they don't change history or repository contents they aren't accurate and I'd like to filter them out before merging.

**Comment by dirk-thomas** [comment]
What is the status of this?

**Comment by nuclearsandwich** [comment]
Updated to remove the spurious commits.

**Review by mikaelarguedas — APPROVED** [review]
Lgtm

**Pull request merged**
