### PR TITLE
update vtk dependencies

### PR DESCRIPTION
**Pull request by spuetz**
Since pcl on noetic runs also with vtk7 we should change the default here to vtk7

### CODE REVIEW

**Comment by mabelzhang** [comment]
I might not be the best person to review this, since I don't have enough context about PCL or VTK, but to push this along, I see that libvtk7* [exists](https://packages.ubuntu.com/search?keywords=libvtk7&searchon=names&suite=all&section=all) for bionic, but is that staying at 6 because PCL on Melodic runs on vtk6?

@jacobperron is there anything else that needs to be done when the default is changed? I'm not seeing extra things to be done as far as the REVIEW_GUIDELINES and CONTRIBUTING guides go.

**Comment by spuetz** [comment]
> but is that staying at 6 because PCL on Melodic runs on vtk6?

Yes, that's the reason. VTK6 and VTK7 can not be installed at the same time.

**Comment by mabelzhang** [comment]
To second reviewer: I'm ready to approve if there's nothing else in the process I have to be aware of.

**Review by jacobperron — DISMISSED** [review]
I'm not sure if we've documented the process for this situation.

It's possible this change could break other users depending `libvtk6`, but given that pcl is depending on `libvtk7`, making this change makes sense to me.

Pinging @clalancette and @tfoote for guidance.
In general, how do we handle version bumps to dependencies? I can help document this case in our review guidelines.

**Review by mabelzhang — APPROVED** [review]
Approving to unblock, but HOLD pending question above.

**Review by jacobperron — COMMENTED** [review]
After further considering, we shouldn't change the version of the key in Focal since it will break existing users depending on this.

IIUC, keeping the key as vtk6 in Focal shouldn't affect pcl, since it is already transitively installing vtk7. It appears vtk6 and vtk7 are side-by-side installable; though I have no idea about linking against both.

**Comment by spuetz** [comment]
Like it is now, it breaks installations. vtk6 and vtk7 are not side by side installable due to the vtk-java installation. E.g. installing lvr2 and pcl worked in melodic. Now in noetic it does not.

**Comment by jacobperron** [comment]
> Like it is now, it breaks installations. vtk6 and vtk7 are not side by side installable due to the vtk-java installation. E.g. installing lvr2 and pcl worked in melodic. Now in noetic it does not.

I'm misunderstanding something. I can successfully install both `lvr2` and `pcl` (and `pcl_ros`) on Noetic:

```
sudo apt install ros-noetic-lvr2 libpcl-dev ros-noetic-pcl-ros
```

However, it's true that we can't install `libvtk6-java` since [it is not available on focal](https://packages.ubuntu.com/search?keywords=libvtk6-java). We should certainly update the rule for `libvtk-java` for focal (as done in this PR).

For the other rosdep keys, I think we shouldn't make the change to vtk7. If a key for vtk7 is desired, we could consider adding a new key (e.g. `libvtk7`).

Does that makes sense?

**Review by tfoote — CHANGES_REQUESTED** [review]
I've confirmed that as of [focal libpcl-dev](https://packages.ubuntu.com/focal/libpcl-dev) is depending on libvtk7-dev 

For bionic [it's only on vtk6](https://packages.ubuntu.com/bionic/libpcl-dev)


Everything appears to have switched to vtk7

```
root@dedfe2e0f5b0:/# apt-rdepends -r libvtk7-dev | grep -v "Depends:" | wc -l
Reading package lists... Done
Building dependency tree       
Reading state information... Done
75
root@dedfe2e0f5b0:/# apt-rdepends -r libvtk6-dev | grep -v "Depends:" | wc -l
Reading package lists... Done
Building dependency tree       
Reading state information... Done
4
```

Upon review lvr2 appears to be approximately the only packages using vtk6 because it's using this rule directly.

```
root@dedfe2e0f5b0:/# apt-rdepends -r libvtk6-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvtk6-dev
  Reverse Depends: libvtk6-qt-dev (= 6.3.0+dfsg2-5build2)
  Reverse Depends: ros-noetic-lvr2 (20.11.2-1focal.20201204.140039)
libvtk6-qt-dev
  Reverse Depends: ros-noetic-lvr2 (20.11.2-1focal.20201204.140039)
ros-noetic-lvr2
  Reverse Depends: ros-noetic-lvr2-dbgsym (= 20.11.2-1focal.20201204.140039)
ros-noetic-lvr2-dbgsym
```

Most other things are getting vtk7 indirectly. 
```
root@dedfe2e0f5b0:/# apt-rdepends -r libvtk7-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvtk7-dev
  Reverse Depends: libcamitk-dev (4.1.2-4build1)
  Reverse Depends: libpcl-dev (1.10.0+dfsg-5ubuntu1)
  Reverse Depends: libsight-dev (19.0.0-5ubuntu4)
  Reverse Depends: libvtk7-qt-dev (= 7.1.1+dfsg2-2ubuntu1)
libcamitk-dev
libpcl-dev
  Reverse Depends: libpcl-conversions-dev (0.2.1-6build1)
  Reverse Depends: ros-noetic-cob-map-accessibility-analysis (0.6.11-1focal.20201022.171901)
  Reverse Depends: ros-noetic-ifm3d-core (0.18.0-5focal.20201017.020358)
  Reverse Depends: ros-noetic-pcl-conversions (1.7.2-1focal.20201017.015926)
  Reverse Depends: ros-noetic-pcl-ros (1.7.2-1focal.20201017.021046)
  Reverse Depends: ros-noetic-rtabmap (0.20.0-3focal.20201017.020606)
libpcl-conversions-dev
ros-noetic-cob-map-accessibility-analysis
  Reverse Depends: ros-noetic-cob-map-accessibility-analysis-dbgsym (= 0.6.11-1focal.20201022.171901)
  Reverse Depends: ros-noetic-cob-navigation (0.6.11-1focal.20201207.160458)
ros-noetic-cob-map-accessibility-analysis-dbgsym
ros-noetic-cob-navigation
ros-noetic-ifm3d-core
  Reverse Depends: ros-noetic-ifm3d (0.6.2-3focal.20201017.024034)
ros-noetic-ifm3d
  Reverse Depends: ros-noetic-ifm3d-dbgsym (= 0.6.2-3focal.20201017.024034)
ros-noetic-ifm3d-dbgsym
ros-noetic-pcl-conversions
  Reverse Depends: ros-noetic-cob-image-flip (0.6.17-1focal.20201017.024012)
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-map-organizer (0.10.4-1focal.20201113.174636)
  Reverse Depends: ros-noetic-nonpersistent-voxel-layer (1.2.3-2focal.20201102.232857)
  Reverse Depends: ros-noetic-obj-to-pointcloud (0.10.4-1focal.20201113.174647)
  Reverse Depends: ros-noetic-octomap-server (0.6.5-1focal.20201017.023939)
  Reverse Depends: ros-noetic-pcl-ros (1.7.2-1focal.20201017.021046)
  Reverse Depends: ros-noetic-perception-pcl (1.7.2-1focal.20201017.024327)
  Reverse Depends: ros-noetic-rtabmap-ros (0.20.0-3focal.20201117.014722)
  Reverse Depends: ros-noetic-safety-limiter (0.10.4-1focal.20201207.153347)
  Reverse Depends: ros-noetic-sick-scan (1.7.8-1focal.20201207.153307)
ros-noetic-cob-image-flip
  Reverse Depends: ros-noetic-cob-image-flip-dbgsym (= 0.6.17-1focal.20201017.024012)
  Reverse Depends: ros-noetic-cob-perception-common (0.6.17-1focal.20201017.025254)
ros-noetic-cob-image-flip-dbgsym
ros-noetic-cob-perception-common
ros-noetic-jsk-pcl-ros
  Reverse Depends: ros-noetic-jsk-pcl-ros-dbgsym (= 1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-recognition (1.2.15-1focal.20201207.190545)
ros-noetic-jsk-pcl-ros-dbgsym
ros-noetic-jsk-recognition
ros-noetic-jsk-pcl-ros-utils
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils-dbgsym (= 1.2.15-1focal.20201207.164151)
ros-noetic-jsk-pcl-ros-utils-dbgsym
ros-noetic-map-organizer
  Reverse Depends: ros-noetic-map-organizer-dbgsym (= 0.10.4-1focal.20201113.174636)
  Reverse Depends: ros-noetic-neonavigation (0.10.4-1focal.20201207.155814)
ros-noetic-map-organizer-dbgsym
ros-noetic-neonavigation
ros-noetic-nonpersistent-voxel-layer
  Reverse Depends: ros-noetic-nonpersistent-voxel-layer-dbgsym (= 1.2.3-2focal.20201102.232857)
ros-noetic-nonpersistent-voxel-layer-dbgsym
ros-noetic-obj-to-pointcloud
  Reverse Depends: ros-noetic-neonavigation (0.10.4-1focal.20201207.155814)
  Reverse Depends: ros-noetic-obj-to-pointcloud-dbgsym (= 0.10.4-1focal.20201113.174647)
ros-noetic-obj-to-pointcloud-dbgsym
ros-noetic-octomap-server
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-octomap-mapping (0.6.5-1focal.20201017.030156)
  Reverse Depends: ros-noetic-octomap-server-dbgsym (= 0.6.5-1focal.20201017.023939)
ros-noetic-octomap-mapping
ros-noetic-octomap-server-dbgsym
ros-noetic-pcl-ros
  Reverse Depends: ros-noetic-cob-image-flip (0.6.17-1focal.20201017.024012)
  Reverse Depends: ros-noetic-cob-map-accessibility-analysis (0.6.11-1focal.20201022.171901)
  Reverse Depends: ros-noetic-cob-object-detection-visualizer (0.6.17-1focal.20201017.024032)
  Reverse Depends: ros-noetic-ifm3d (0.6.2-3focal.20201017.024034)
  Reverse Depends: ros-noetic-image-view2 (2.2.11-2focal.20201017.024039)
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-jsk-perception (1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-jsk-recognition-utils (1.2.15-1focal.20201207.155239)
  Reverse Depends: ros-noetic-mcl-3dl (0.5.1-1focal.20201207.153348)
  Reverse Depends: ros-noetic-multi-object-tracking-lidar (1.0.3-1focal.20201017.024047)
  Reverse Depends: ros-noetic-nonpersistent-voxel-layer (1.2.3-2focal.20201102.232857)
  Reverse Depends: ros-noetic-octomap-server (0.6.5-1focal.20201017.023939)
  Reverse Depends: ros-noetic-pcl-ros-dbgsym (= 1.7.2-1focal.20201017.021046)
  Reverse Depends: ros-noetic-perception-pcl (1.7.2-1focal.20201017.024327)
  Reverse Depends: ros-noetic-robot-self-filter (0.1.32-1focal.20201017.024102)
  Reverse Depends: ros-noetic-rtabmap-ros (0.20.0-3focal.20201117.014722)
  Reverse Depends: ros-noetic-safety-limiter (0.10.4-1focal.20201207.153347)
  Reverse Depends: ros-noetic-sick-scan (1.7.8-1focal.20201207.153307)
  Reverse Depends: ros-noetic-toposens-pointcloud (2.1.0-1focal.20201110.162124)
  Reverse Depends: ros-noetic-velodyne-pcl (1.6.1-1focal.20201110.155227)
ros-noetic-cob-object-detection-visualizer
  Reverse Depends: ros-noetic-cob-object-detection-visualizer-dbgsym (= 0.6.17-1focal.20201017.024032)
  Reverse Depends: ros-noetic-cob-perception-common (0.6.17-1focal.20201017.025254)
ros-noetic-cob-object-detection-visualizer-dbgsym
ros-noetic-image-view2
  Reverse Depends: ros-noetic-image-view2-dbgsym (= 2.2.11-2focal.20201017.024039)
  Reverse Depends: ros-noetic-jsk-common (2.2.11-2focal.20201207.160317)
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-jsk-perception (1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-jsk-rqt-plugins (2.1.7-4focal.20201027.054624)
ros-noetic-image-view2-dbgsym
ros-noetic-jsk-common
ros-noetic-jsk-perception
  Reverse Depends: ros-noetic-jsk-perception-dbgsym (= 1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-jsk-recognition (1.2.15-1focal.20201207.190545)
ros-noetic-jsk-perception-dbgsym
ros-noetic-jsk-rqt-plugins
  Reverse Depends: ros-noetic-jsk-visualization (2.1.7-4focal.20201207.172355)
ros-noetic-jsk-visualization
ros-noetic-jsk-recognition-utils
  Reverse Depends: ros-noetic-imagesift (1.2.15-1focal.20201207.161335)
  Reverse Depends: ros-noetic-jsk-interactive-marker (2.1.7-4focal.20201207.164202)
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-jsk-perception (1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-jsk-recognition (1.2.15-1focal.20201207.190545)
  Reverse Depends: ros-noetic-jsk-recognition-utils-dbgsym (= 1.2.15-1focal.20201207.155239)
  Reverse Depends: ros-noetic-jsk-rviz-plugins (2.1.7-4focal.20201207.161323)
ros-noetic-imagesift
  Reverse Depends: ros-noetic-imagesift-dbgsym (= 1.2.15-1focal.20201207.161335)
  Reverse Depends: ros-noetic-jsk-perception (1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-jsk-recognition (1.2.15-1focal.20201207.190545)
ros-noetic-imagesift-dbgsym
ros-noetic-jsk-interactive-marker
  Reverse Depends: ros-noetic-jsk-interactive (2.1.7-4focal.20201207.170143)
  Reverse Depends: ros-noetic-jsk-interactive-marker-dbgsym (= 2.1.7-4focal.20201207.164202)
  Reverse Depends: ros-noetic-jsk-interactive-test (2.1.7-4focal.20201207.171233)
  Reverse Depends: ros-noetic-jsk-visualization (2.1.7-4focal.20201207.172355)
ros-noetic-jsk-interactive
  Reverse Depends: ros-noetic-jsk-interactive-test (2.1.7-4focal.20201207.171233)
  Reverse Depends: ros-noetic-jsk-visualization (2.1.7-4focal.20201207.172355)
ros-noetic-jsk-interactive-test
  Reverse Depends: ros-noetic-jsk-visualization (2.1.7-4focal.20201207.172355)
ros-noetic-jsk-interactive-marker-dbgsym
ros-noetic-jsk-recognition-utils-dbgsym
ros-noetic-jsk-rviz-plugins
  Reverse Depends: ros-noetic-jsk-interactive-marker (2.1.7-4focal.20201207.164202)
  Reverse Depends: ros-noetic-jsk-rviz-plugins-dbgsym (= 2.1.7-4focal.20201207.161323)
  Reverse Depends: ros-noetic-jsk-visualization (2.1.7-4focal.20201207.172355)
ros-noetic-jsk-rviz-plugins-dbgsym
ros-noetic-mcl-3dl
  Reverse Depends: ros-noetic-mcl-3dl-dbgsym (= 0.5.1-1focal.20201207.153348)
ros-noetic-mcl-3dl-dbgsym
ros-noetic-multi-object-tracking-lidar
  Reverse Depends: ros-noetic-multi-object-tracking-lidar-dbgsym (= 1.0.3-1focal.20201017.024047)
ros-noetic-multi-object-tracking-lidar-dbgsym
ros-noetic-pcl-ros-dbgsym
ros-noetic-perception-pcl
  Reverse Depends: ros-noetic-perception (1.5.0-1focal.20201017.024725)
ros-noetic-perception
  Reverse Depends: ros-noetic-desktop-full (1.5.0-1focal.20201207.161434)
ros-noetic-desktop-full
ros-noetic-robot-self-filter
  Reverse Depends: ros-noetic-jsk-pcl-ros (1.2.15-1focal.20201207.172248)
  Reverse Depends: ros-noetic-jsk-pcl-ros-utils (1.2.15-1focal.20201207.164151)
  Reverse Depends: ros-noetic-jsk-perception (1.2.15-1focal.20201207.162537)
  Reverse Depends: ros-noetic-robot-self-filter-dbgsym (= 0.1.32-1focal.20201017.024102)
ros-noetic-robot-self-filter-dbgsym
ros-noetic-rtabmap-ros
  Reverse Depends: ros-noetic-rtabmap-ros-dbgsym (= 0.20.0-3focal.20201117.014722)
ros-noetic-rtabmap-ros-dbgsym
ros-noetic-safety-limiter
  Reverse Depends: ros-noetic-neonavigation (0.10.4-1focal.20201207.155814)
  Reverse Depends: ros-noetic-neonavigation-launch (0.10.4-1focal.20201207.155040)
  Reverse Depends: ros-noetic-safety-limiter-dbgsym (= 0.10.4-1focal.20201207.153347)
ros-noetic-neonavigation-launch
  Reverse Depends: ros-noetic-neonavigation (0.10.4-1focal.20201207.155814)
ros-noetic-safety-limiter-dbgsym
ros-noetic-sick-scan
  Reverse Depends: ros-noetic-sick-scan-dbgsym (= 1.7.8-1focal.20201207.153307)
ros-noetic-sick-scan-dbgsym
ros-noetic-toposens-pointcloud
  Reverse Depends: ros-noetic-toposens (2.1.0-1focal.20201117.021130)
  Reverse Depends: ros-noetic-toposens-bringup (2.1.0-1focal.20201117.020632)
  Reverse Depends: ros-noetic-toposens-pointcloud-dbgsym (= 2.1.0-1focal.20201110.162124)
ros-noetic-toposens
ros-noetic-toposens-bringup
  Reverse Depends: ros-noetic-toposens (2.1.0-1focal.20201117.021130)
ros-noetic-toposens-pointcloud-dbgsym
ros-noetic-velodyne-pcl
ros-noetic-rtabmap
  Reverse Depends: ros-noetic-rtabmap-dbgsym (= 0.20.0-3focal.20201017.020606)
  Reverse Depends: ros-noetic-rtabmap-ros (0.20.0-3focal.20201117.014722)
ros-noetic-rtabmap-dbgsym
libsight-dev
libvtk7-qt-dev
  Reverse Depends: libcamitk-dev (4.1.2-4build1)
  Reverse Depends: libpcl-dev (1.10.0+dfsg-5ubuntu1)
  Reverse Depends: libsight-dev (19.0.0-5ubuntu4)
```

So although I usually wouldn't want to switch a rule after it being out, I think in this case we should. 

While I was looking I confirmed that as of [buster libpcl-dev](https://packages.debian.org/buster/libpcl-dev) is also using vtk7 so we should switch that rule too to maintain consistency.

**Comment by spuetz** [comment]
@tfoote Thank you for reviewing this PR and all bundled information. What is the change you are requesting here? I can't read it between the lines.

**Comment by sloretz** [comment]
> @tfoote Thank you for reviewing this PR and all bundled information. What is the change you are requesting here? I can't read it between the lines.

@spuetz I think @tfoote is requesting the `libvtk*` rosdep rules for Debian Buster to be changed to `libvtk7-dev` instead of `libvtk6-dev` to match the change in Ubuntu Focal.

https://github.com/ros/rosdistro/blob/0ed124c2d547c16ffab4d0fa52c992ad6dddb67f/rosdep/base.yaml#L4500-L4506
https://github.com/ros/rosdistro/blob/0ed124c2d547c16ffab4d0fa52c992ad6dddb67f/rosdep/base.yaml#L4531-L4537
https://github.com/ros/rosdistro/blob/0ed124c2d547c16ffab4d0fa52c992ad6dddb67f/rosdep/base.yaml#L4559-L4565

**Comment by jacobperron** [comment]
@spuetz Friendly ping. Can you update the rules for `buster` as well? Thanks!

**Review by jacobperron — APPROVED** [review]

**Review by tfoote — APPROVED** [review]

**Pull request merged**
