### PR TITLE
remove libx52pro

### PR DESCRIPTION
**Pull request by tfoote**
following up #10331

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I only tried `libx52pro0` but I was able to install it just fine on my Trusty machine. Therefore I don't think it should be removed.

**Comment by tfoote** [comment]
I think it has a missing dependency needed for configuring. It cannot install on a clean system. See below: 

Since the package cannot be reliably installed I would consider it worse than not being listed. We do not list packages which are not installable because they don't exist. Similarly we should not list a package which is not installable because it's potentially missing dependencies. Even worse is that it presents itself as installable but is not actually. 

We could do the effort to find and add to this rule the missing dependency. I don't think that knowingly having a rule in our database which is known to be a problem is helpful. (And it's not just an known problem that noone will see, it's seen when doing CI for a package with this dependency. As such if we leave the rule in place others may add it and more jobs will start to fail possibly including debbuild jobs. And if it's a runtime only dependency we could also get the problem that we could build one or our debs which would then become uninstallable. 

Here's the output of a clean ubuntu instance:
```
$ docker run -ti ubuntu:trusty
root@327484363c03:/# apt-get update && apt-get install libx52pro0
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Hit http://archive.ubuntu.com trusty Release.gpg                
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [325 kB]
Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [5222 B]
Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [189 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [889 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.5 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [438 kB]
Get:9 http://archive.ubuntu.com trusty-security/main Sources [132 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3920 B]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [37.9 kB]
Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [522 kB]
Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [160 kB]
Hit http://archive.ubuntu.com trusty Release
Get:15 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:16 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:17 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:18 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:19 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.5 MB in 4s (4670 kB/s)                         
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libx52pro0
0 upgraded, 1 newly installed, 0 to remove and 32 not upgraded.
Need to get 12.5 kB of archives.
After this operation, 82.9 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe libx52pro0 amd64 0.1.1-2.1 [12.5 kB]
Fetched 12.5 kB in 0s (0 B/s)           
Selecting previously unselected package libx52pro0.
(Reading database ... 11542 files and directories currently installed.)
Preparing to unpack .../libx52pro0_0.1.1-2.1_amd64.deb ...
Unpacking libx52pro0 (0.1.1-2.1) ...
Setting up libx52pro0 (0.1.1-2.1) ...
dpkg: error processing package libx52pro0 (--configure):
 subprocess installed post-installation script returned error exit status 2
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dirk-thomas** [comment]
If it doesn't work on a clean system you might be able to add an additional package to the list to make it work.

Anyway -1 to merge this as-is.

**Comment by tfoote** [comment]
The original submitter of [this rule](https://github.com/ros/rosdistro/commit/770d10ac60fa27f2eb1aff34cbba9669584533ed) @cyborg-x1 is onboard with the change as indicated in the other ticket. 

Other @ros/rosdistro-maintainers thoughts?

**Comment by cyborg-x1** [comment]
Yes, I will role back the package to have the sources of the library inside again, so it also builds on other systems, where this library is not available at all, I will see if I can do that this week, was busy with getting out an alpha in another project of mine (Yocto Linux with ROS for Lego Mindstorms EV3 Brick - https://github.com/Hacks4ROS/h4r_ev3_ctrl/ - released yesterday ...) I will also have to update my Email, it's wrong in the package file, that's why I did not get a notice in first place ... Sorry for the inconvenience...

**Comment by cyborg-x1** [comment]
Actually I probably fixed this on the weekend, I just need to test it and release it again.

**Pull request merged**
