### PR TITLE
Add ndt_omp to rosdistro

### PR DESCRIPTION
**Pull request by hridaybavle**
## Package names:

  * [ndt_omp](https://github.com/koide3/ndt_omp.git)
  
## Package Upstream Source:

https://github.com/koide3/ndt_omp.git

## Purpose of using this:

Multi-threaded and SSE friendly NDT registration algorithm. Required as as dependency in the scan matching based odometry and loop closure modules of [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git).

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/koide3/ndt_omp.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

You can copy-paste the below into your review comment when reviewing a new package addition into rosdistro.

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/koide3/ndt_omp/blob/0852c95360d1b0d29745e7eae7a57c0950de695b/LICENSE
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): BSD 2-clause
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/koide3/ndt_omp
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions: I'm not sure that this is the case.  `ndt_omp` is kind of hard to understand, and doesn't really tell us what it does (thus I think it might violate [Global Guidelines bullet 4](https://www.ros.org/reps/rep-0144.html#global-guidelines).

Besides the naming concern, I also have some additional questions:
1.  There haven't been any commits to the project in 2 years.  Is this project still active?
2.  What is the relationship between you (@hridaybavle) and the upstream (which seems to be run by @koide3)?

**Comment by hridaybavle** [comment]
Hello @clalancette,

Thank you for the concern. Regarding the naming of the package as the name suggests `ndt_omp` does a normal distribution transforms based registration mostly using 3D LiDAR measurements. The name `omp` is for OpenMultiProcessing for faster scan matching. Our primary repo [lidar_s_graphs](https://github.com/snt-arg/lidar_s_graphs/) depends on `ndt_omp` registration for providing odometry based on scan_matching. And the relationship with `lidar_s_graphs` and `ndt_omp` is that it `lidar_s_graphs`  is based on [hdl_graph_slam](https://github.com/koide3/hdl_graph_slam) a fork of @koide3. 

I could also create a fork of `ndt_omp` if required and rename it to something such as `ndt_omp_registration` or `ndt_omp_scan_matching`

**Comment by clalancette** [comment]
In general, this looks OK, but I want to make sure that @koide3 is OK with this release.  As long as that happens, we can merge this in.

**Comment by koide3** [comment]
This and https://github.com/ros/rosdistro/pull/40807 are both fine with me. Thanks @hridaybavle and @clalancette for handling them.

**Comment by hridaybavle** [comment]
Thank you @koide3 for confirmation. @clalancette the CI on `ndt_omp` and `fast_gicp` failing because of some libraries of `libpcl-all` are not found in ubuntu noble. What could be done to fix this?

**Comment by clalancette** [comment]
> Thank you @koide3 for confirmation. @clalancette the CI on `ndt_omp` and `fast_gicp` failing because of some libraries of `libpcl-all` are not found in ubuntu noble. What could be done to fix this?

Just rebase the PRs, that should fix it.

**Comment by hridaybavle** [comment]
@clalancette both (fast_gicp)[https://github.com/ros/rosdistro/pull/40807] and this one have been rebased with master.

**Pull request merged**
