### PR TITLE
New Version of popf 0.0.11-1

### PR DESCRIPTION
**Pull request by fmrico**
Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>

Hi

This new release tries to fix the building of popf. The last version did not include the dependencies to build the source.

This version is 0.0.11-1 and the last one is 0.0.3-1. I am still not an expert with bloom, and the automated script increased the minor every time I tried to fix it. I hope that 0.0.11-1 will be ok. 

There is also a PR #23347 to fix the name of the package.

Best

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
With the repository rename lines 1102 and 1103 can be removed because if there's no package listed, it's assumed to be the same name as the repository. This is failing CI as in needs to be the canonical representation which is as simple as possible.

**Comment by tfoote** [comment]
Higher version numbers are fine for us. If you get into semantic versioning you may want to control things. I don't know what automated script you're using. But catkin_prepare_release by default bumps the patch number. 

Though I'm surprised to see 0.0.5 in the source: https://github.com/fmrico/popf/blob/eloquent-devel/package.xml but 0.0.11 in the release repository. 

What process are you following? It's unexpected to have versions in the release repository higher than the source repository.  Oh, now I find it in your ros2 branch: https://github.com/fmrico/popf/blob/ros2/package.xml however your rosdistro content references the eloquent-devel branch.

You also appear not to have the 0.3 releases in your release repository anymore. Was that intentional?

**Comment by fmrico** [comment]
Dear @tfoote 

I have removed the unnecessary lines.

I have also updated the brach `eloquent-devel` with the commits in the `ros2` branch at [https://github.com/fmrico/popf](https://github.com/fmrico/popf). Sorry for the inconsistency. Now both are in 0.0.11, consistent with changelog and package.xml. It is also consistent with https://github.com/fmrico/popf-release. The `master` branch will maintain the original work of the author, independent from ROS2.

About the 0.3 releases in your release repository, it was not intentional. As I commented, this is my first release, and trying to fix the errors, I made a mistake and I removed https://github.com/fmrico/popf-release.git, and I lost that release. I am not an expert in bloom yet, and some parts of the procedure were still dark for me.

I will maintain this package as a dependency for an imminent first release of [PlanSys2](https://github.com/IntelligentRoboticsLabs/ros2_planning_system).

Thanks. Best
Francisco.

**Review by clalancette — APPROVED** [review]
This looks OK to me now, but I'll let @tfoote re-review and merge it.

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
Ok, yeah there's often a learning curve for making releases and unfortunately there's not easy way to practice offline. We try to ask a bunch of questions to make sure that we can be as helpful as possible in the reviews. Sometimes we have to ferret out invalid assumptions. It looks like you've gotten most of the way through now though.

**Pull request merged**
