### PR TITLE
add exiv2 to base.yaml

### PR DESCRIPTION
**Pull request by hakuturu583**
add exiv2 to rosdep.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
please provide links to the package for each platforms as well as a description of the package.
You can find more information on how to contribute rosdep rules in the [CONTRIBUTING.md file](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)

**Comment by hakuturu583** [comment]
Thanks. These are package URLs.
[python-pyexiv2](https://packages.ubuntu.com/bionic/python-pyexiv2)

**Comment by mikaelarguedas** [comment]
To know why travis fails you can click on "Details" and access the travis logs.

It says `AssertionError: see folded block 'block2' above for details`
And if you click on "block2" it says:
`ERR: list out of alphabetical order line 1109.  'python-expiringdict' should come before 'python-pyexiv2'`

So this mean that you didnt insert the key in alphabetical order

---

Previous comment still applies:
Please provide:
- links and entries for at least debian and ubuntu and if possible feodra and gentoo
- description of the package and what use case you want to use it for

**Comment by hakuturu583** [comment]
@mikaelarguedas Thanks, I update package order.
This is the package infomation.

ubuntu:[python-pyexiv2](https://packages.ubuntu.com/bionic/python-pyexiv2)
debian:[python-pyexiv2](https://packages.debian.org/sid/python-pyexiv2)

This package is a python binging of exiv2.
I want to use this package in order to add exif infomation to image from gazebo simulator.

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by hakuturu583** [comment]
@mikaelarguedas Thanks!!

**Pull request merged**
