### PR TITLE
rosdep: added dependencies for openembedded:

### PR DESCRIPTION
**Pull request by DasRoteSkelett**
Added dependencies for openembedded for

* alsa-oss: https://layers.openembedded.org/layerindex/recipe/1161/
 * clang-native: https://layers.openembedded.org/layerindex/recipe/31565/
 * file: https://layers.openembedded.org/layerindex/recipe/4681/
 * fmt: https://layers.openembedded.org/layerindex/recipe/104406/
 * jq: https://layers.openembedded.org/layerindex/recipe/27305/
 * abseil-cpp: https://layers.openembedded.org/layerindex/recipe/120200/
 * lttng-ust-dev: https://layers.openembedded.org/layerindex/recipe/6147/
 * opencv-imgproc-dev: https://layers.openembedded.org/layerindex/recipe/39865/
 * python3-pybind11: https://layers.openembedded.org/layerindex/recipe/56447/
 * uncrustify: meta-ros via pull request https://github.com/ros/meta-ros/pull/1031
 * python3-dbus: https://layers.openembedded.org/layerindex/recipe/51342/
 * python3-whichcraft: meta-ros via pull request https://github.com/ros/meta-ros/pull/1031

Signed-off-by: Matthias Schoepfer <m.schoepfer@rethinkrobotics.com>

### CODE REVIEW

**Comment by methylDragon** [comment]
Could you add links to the packages :o

**Comment by DasRoteSkelett** [comment]
What links? These are not new packages, I just added missing package names for openembedded :thinking:

**Comment by DasRoteSkelett** [comment]
Thanks @methylDragon for the suggestions, I changed the commit message to match similar commits to added packages to openembedded. About the nosetest: I have no clue what this error is about, I double checked formatting, also a yaml checker did not find any issues... Any hint on what went wrong here is appreciated.

**Comment by DasRoteSkelett** [comment]
nvm I *think* I got it figured out. At least `nosetests`  run fine on my pc. Keeping my fingers crossed :crossed_fingers:

**Review by wjwwood — APPROVED** [review]
lgtm, but I don't know how to double check the keys for openembedded. Needs a second review.

**Review by ivanpauno — APPROVED** [review]
LGTM

**Pull request merged**
