### PR TITLE
Add ensenso_driver to the index for kinetic and lunar

### PR DESCRIPTION
**Pull request by saierd**

### CODE REVIEW

**Comment by tfoote** [comment]
Travis CI flagged this as abuse. We've had some trouble with that before. Can you log into travis-ci with your github account so they have your account cross referenced.. When we contact support that's what they usually ask us to do. Please comment back here and we can retrigger. If that doesn't work we'll need to contact support at travis-ci.

image

**Comment by saierd** [comment]
I just did that. Also gave it permissions for the organization the pull request comes from, so they know that as well. I hope it works now.

**Comment by mikaelarguedas** [comment]
closing and reopening to see if travis issue resolved

**Comment by mikaelarguedas** [comment]
looks like the request went through :tada: , travis job in progress

**Pull request merged**
