### PR TITLE
added libhidapi-dev and liblapacke

### PR DESCRIPTION
**Pull request by wzli**
https://packages.ubuntu.com/xenial/liblapacke-dev
https://packages.ubuntu.com/xenial/libhidapi-dev

needed to compile:
https://github.com/cnlohr/libsurvive

### CODE REVIEW

**Review by mikaelarguedas — DISMISSED** [review]
new rosdep keys need to cover all targeted platforms (at least all active Ubuntu and Debian distributions. Fedora and Gentoo appreciated) please see [Contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions) for more details about contributing rosdep rules

**Comment by wzli** [comment]
added a few more
https://packages.debian.org/stretch/libhidapi-dev
https://packages.debian.org/stretch/lapacke-dev
https://packages.gentoo.org/packages/dev-libs/hidapi

couldn't find fedora and gentoo ones for lapacke

**Comment by wzli** [comment]
bump

**Comment by dirk-thomas** [comment]
> https://packages.debian.org/stretch/lapacke-dev

Shows "No such package"?

**Comment by wzli** [comment]
It's actually https://packages.debian.org/stretch/liblapacke
Only the comment was wrong tho

**Review by dirk-thomas — APPROVED** [review]
LGTM

A second person will review & merge soon.

**Review by mikaelarguedas — APPROVED** [review]

**Pull request merged**
