### PR TITLE
Switch to upstream homebrew rosdeps for UUID and yaml-cpp

### PR DESCRIPTION
**Pull request by mikepurvis**
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ossp-uuid.rb

https://github.com/Homebrew/homebrew-core/blob/master/Formula/yaml-cpp.rb

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm, thanks @mikepurvis

**Comment by wjwwood** [comment]
(waiting on other ROS distro maintainers to +1 before merging)

**Comment by mikepurvis** [comment]
FYI @hawesie @ahundt @spmaniato

**Comment by ahundt** [comment]
useful, thanks!

**Pull request merged**
