### PR TITLE
[rosdep] Add python-graphviz

### PR DESCRIPTION
**Pull request by evenator**
Adds the PyPi graphviz package (https://pypi.python.org/pypi/graphviz)

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Since this is pip only please use the `-pip` extension convention for the key.

**Comment by dirk-thomas** [comment]
Is the existing rosdep key `python-pygraphviz` not sufficient for your use case?

**Comment by mikaelarguedas** [comment]
Gentoo doesn't support pip. But has an official package for it: https://packages.gentoo.org/packages/dev-python/graphviz.

I see that there is a `python-pygraphviz` in Ubuntu and Debian, is this similar to what you're looking for ?

Also it looks like newer Ubuntu and Debian will have a python package called python-graphviz but it's only a source package for now:
Ubuntu
```
 python-graphviz | 0.5.2-1        | zesty/universe  | source
 python-graphviz | 0.5.2-1ubuntu1 | artful/universe | source
 python-graphviz | 0.5.2-1ubuntu1 | bionic/universe | source
```
Debian:
```
python-graphviz | 0.5.2-1       | testing    | source
python-graphviz | 0.5.2-1       | unstable   | source
```

**Comment by evenator** [comment]
> Since this is pip only please use the -pip extension convention for the key.

Yeah, I can do that.

> Is the existing rosdep key python-pygraphviz not sufficient for your use case?

pygraphviz is a different package.

> Gentoo doesn't support pip. But has an official package for it: https://packages.gentoo.org/packages/dev-python/graphviz.

I'll update accordingly.

> Also it looks like newer Ubuntu and Debian will have a python package called python-graphviz but it's only a source package for now:

Good to know. It's too bad there's no binary package yet.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @evenator for iterating

**Review by tfoote — APPROVED** [review]

**Pull request merged**
