### PR TITLE
Update source and doc branches for Crystal.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Created `crystal` branches and updated the release repository crystal track for the following repositories.

https://github.com/ament/ament_cmake/tree/crystal
https://github.com/ament/ament_index/tree/crystal
https://github.com/ament/ament_lint/tree/crystal
https://github.com/ament/ament_package/tree/crystal
https://github.com/ament/googletest/tree/crystal
https://github.com/ament/uncrustify_vendor/tree/crystal
https://github.com/osrf/osrf_testing_tools_cpp/tree/crystal
https://github.com/ros2/ament_cmake_ros/tree/crystal
https://github.com/ros2/common_interfaces/tree/crystal
https://github.com/ros2/console_bridge_vendor/tree/crystal
https://github.com/ros2/depthimage_to_laserscan/tree/crystal
https://github.com/ros2/example_interfaces/tree/crystal
https://github.com/ros2/examples/tree/crystal
https://github.com/ros2/geometry2/tree/crystal
https://github.com/ros2/joystick_drivers/tree/crystal
https://github.com/ros2/kdl_parser/tree/crystal
https://github.com/ros2/launch/tree/crystal
https://github.com/ros2/libyaml_vendor/tree/crystal
https://github.com/ros2/message_filters/tree/crystal
https://github.com/ros2/orocos_kinematics_dynamics/tree/crystal
https://github.com/ros2/pcl_conversions/tree/crystal
https://github.com/ros2/poco_vendor/tree/crystal
https://github.com/ros2/rcl_interfaces/tree/crystal
https://github.com/ros2/rcl_logging/tree/crystal
https://github.com/ros2/rcutils/tree/crystal
https://github.com/ros2/robot_state_publisher/tree/crystal
https://github.com/ros2/ros1_bridge/tree/crystal
https://github.com/ros2/ros2cli/tree/crystal
https://github.com/ros2/rosidl_dds/tree/crystal
https://github.com/ros2/rosidl_defaults/tree/crystal
https://github.com/ros2/rosidl/tree/crystal
https://github.com/ros2/rosidl_python/tree/crystal
https://github.com/ros2/rosidl_typesupport_connext/tree/crystal
https://github.com/ros2/rosidl_typesupport_fastrtps/tree/crystal
https://github.com/ros2/rosidl_typesupport/tree/crystal
https://github.com/ros2/ros_workspace/tree/crystal
https://github.com/ros2/sros2/tree/crystal
https://github.com/ros2/teleop_twist_joy/tree/crystal
https://github.com/ros2/teleop_twist_keyboard/tree/crystal
https://github.com/ros2/tinydir_vendor/tree/crystal
https://github.com/ros2/tinyxml2_vendor/tree/crystal
https://github.com/ros2/tinyxml_vendor/tree/crystal
https://github.com/ros2/tlsf/tree/crystal
https://github.com/ros2/unique_identifier_msgs/tree/crystal
https://github.com/ros2/urdfdom/tree/crystal
https://github.com/ros2/urdf/tree/crystal
https://github.com/ros2/variants/tree/crystal
https://github.com/ros2/yaml_cpp_vendor/tree/crystal
https://github.com/ros/class_loader/tree/crystal
https://github.com/ros/pluginlib/tree/crystal
https://github.com/ros/resource_retriever/tree/crystal
https://github.com/ros/urdfdom_headers/tree/crystal

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Shouldn't the branches for `Fast-CDR` and `Fast-RTPS` also be locked?

**Comment by nuclearsandwich** [comment]
I was under the impression that the version entries for source jobs [need to be branches](https://github.com/ros/rosdistro/pull/20286). The release tracks are pinned to specific versions for new releases. Without forking or inducing upstream to create crystal branches I don't believe we can change those entries.

**Comment by dirk-thomas** [comment]
If we use the master branch `rosinstall_generator` will serve code which likely won't build in the future.

The branch restrictions comes from the devel jobs. For doc jobs that is not the case and for these repos we have disables the devel jobs anyway.

So I think it should use the tag.

**Review by dirk-thomas — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
I didn't think that would work. @dirk-thomas how do you want to proceed. If we merge as-is every PR will fail CI.

**Comment by dirk-thomas** [comment]
My assumption is that this is supposed to work. I would suggest to update the test to accept the case where the version is a tag if the devel job is disabled. I don't see an alternative to that approach - if anyone has an idea please feel free to propose it.

**Comment by tfoote** [comment]
I added an explaination of the reason for the restriction in #20286 and improved checks in #20287 We could add logic to #20287 to allow tags and commits if the CI is disabled.

**Comment by nuclearsandwich** [comment]
Rebased onto current master to incorporate #20287.

**Pull request merged**
