### PR TITLE
add Kompass package to rosdistro

### PR DESCRIPTION
**Pull request by mkabtoul**
# Please add kompass to be indexed in the rosdistro

## Package name:

`kompass`

## Package Upstream Source:

https://github.com/automatika-robotics/kompass.git

## Purpose of using this:

`kompass` is a framework for building robust event-driven navigation stacks using an intuitive Python API

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by sloretz** [comment]
[Iron Irwini is already in its final sync hold](https://discourse.ros.org/t/preparing-for-final-iron-irwini-patch-release-and-sync-2024-11-18/)

**Comment by mkabtoul** [comment]
Package removed from Iron @sloretz

**Comment by mjcarroll** [comment]
[Holding for Jazzy sync](https://discourse.ros.org/t/preparing-for-jazzy-sync-2024-11-21/40682)

**Comment by nuclearsandwich** [comment]
New package review:

- [ ] At least one of the following must be present
  - [ ] Top level license file: https://github.com/automatika-robotics/kompass/blob/main/LICENSE
  - [ ] Per package license files
- [ ] License is [OSI-approved](https://opensource.org/licenses): MIT
- [ ] License correctly listed in package.xmls
  - [ ] kompass: https://github.com/automatika-robotics/kompass/blob/main/kompass/package.xml#L8
  - [ ] kompass_interfaces: https://github.com/automatika-robotics/kompass/blob/main/kompass_interfaces/package.xml#L8
- [ ] Public source repo: https://github.com/automatika-robotics/kompass/tree/main/
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] kompass
  - [ ] kompass_interfaces

**Comment by nuclearsandwich** [comment]
@mkabtoul the check is failing due to a separate change that has been fixed on `master` can you please sync this PR so that CI checks can pass before merging?

**Review by nuclearsandwich — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
