### PR TITLE
Rosjava kinetic deps

### PR DESCRIPTION
**Pull request by airballking**

### CODE REVIEW

**Comment by airballking** [comment]
Tested on my local machine, following these instructions: http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html

**Review by tfoote — APPROVED** [review]
lgtm

**Comment by dirk-thomas** [comment]
The entries for non-LTS versions are missing. Since Kinetic is e.g. targeting Xenial as well as Wily I think all missing ones should be filled in as well.

**Comment by airballking** [comment]
No problem, done.

**Comment by tfoote** [comment]
There were still a few missing intermediate ones. I added a commit that collapses the rules into a non-version specific fule. The only different entry was for lucid which is 1.5 years past it's 5 year server-only EOL. Now the rules won't need to be updated regularly as the names appear to be stable.

**Comment by airballking** [comment]
Even better. Did not occur to me to do this. Thanks @tfoote

**Pull request merged**
