### PR TITLE
Added python-lzf package to python.yaml

### PR DESCRIPTION
**Pull request by atomoclast**

### CODE REVIEW

**Review by mikaelarguedas — DISMISSED** [review]
@atomoclast please add the suffix `-pip` to the key when adding packages that are only available through pip. Can you also add a rule for the other platforms (at least debian)
Thanks!

**Comment by atomoclast** [comment]
I updated the key name. In regards to adding the debian, I don't have a machine to test that one nor can I find the proper name via a quick cursory search. I added lzf so I can move forward with a project I'm working on and I don't have the bandwidth to confirm another distro. Sorry.

**Comment by mikaelarguedas** [comment]
thanks for iterating on this.

pip is available on debian as well as ubuntu. So adding debian means adding a debian entry with the same content:
```
debian:
   pip:
     packages: [python-lzf]
```

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Comment by jlack1987** [comment]
@mikaelarguedas i'm looking and I don't see a debian package for `python-lzf`

**Comment by mikaelarguedas** [comment]
@jlack1987 the package is installed through pip given that it doesn't exist in the [Debian](https://packages.debian.org/search?keywords=python-lzf&searchon=names&suite=all&section=all) or [Ubuntu](https://packages.ubuntu.com/search?keywords=python-lzf&searchon=names&suite=all&section=all) repositories.

On debian stretch:
```
root@15a30716c890:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
root@15a30716c890:~# pip install python-lzf
Collecting python-lzf
  Using cached python-lzf-0.2.4.tar.gz
Building wheels for collected packages: python-lzf
  Running setup.py bdist_wheel for python-lzf ... done
  Stored in directory: /root/.cache/pip/wheels/21/17/f3/fa184bcecd38e47d6bd1b9936c8c7486d9557ea1a3390b25f0
Successfully built python-lzf
Installing collected packages: python-lzf
Successfully installed python-lzf-0.2.4
```

Does that answer your question ?

**Comment by jlack1987** [comment]
Bah I read the file wrong, my bad

**Pull request merged**
