### PR TITLE
Adding auction_methods_stack to documentation index for kinetic

### PR DESCRIPTION
**Pull request by joaoquintas**
I'd like auction_methods_stack to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@joaoquintas I think that travis is failing because you are missing a `.git` at the end of your repository url

**Comment by joaoquintas** [comment]
@mikaelarguedas , thank you so much for the help. It seem it passed

**Comment by joaoquintas** [comment]
@mikaelarguedas , thank you so much. It was the missing .git that was indeed causing the problem

**Comment by mikaelarguedas** [comment]
looks good, thanks.
Note: the documentation is running every 3 days so you may have to wait a bit before this shows up on the ros wiki

**Pull request merged**
