### PR TITLE
remove segbot_apps and segbot_simulator from Indigo distribution

### PR DESCRIPTION
**Pull request by jack-oquin**

### CODE REVIEW

**Comment by jack-oquin** [comment]
Is there a problem with this? 

We merged the packages from those two repositories into https://github.com/utexas-bwi/segbot

**Comment by dirk-thomas** [comment]
Please see the announce on the ros-release mailing list: http://lists.ros.org/pipermail/ros-release/2015-August/004661.html

**Comment by jack-oquin** [comment]
It's not critical, but I would like to get a few things into the release pipeline before leaving on vacation next week.

Is it OK to release again, now?

**Comment by dirk-thomas** [comment]
Yes, that's why we have merge all pending PR just minutes ago.

**Comment by jack-oquin** [comment]
OK. 

I'd seen Tully's message about new Indigo packages and assumed it was open for business again.

**Pull request merged**
