### PR TITLE
Adding new repository for indexing: aerostack

### PR DESCRIPTION
**Pull request by martin-molina**

### CODE REVIEW

**Comment by clalancette** [comment]
This doesn't really look like something we want to index.  It is a repository with a bunch of shell scripts that points elsewhere.  It doesn't really even have documentation to speak of, other than the README.md at the top level.  If you'd like to have aerostack indexed, then I'd suggest starting with the source packages and work your way towards the metapackage.

I'm going to close this for now, but feel free to comment or re-open if you disagree.

**Comment by martin-molina** [comment]
Yes, we made a mistake with the URL. The correct URL is: https://github.com/Vision4UAV/Aerostack.
Please, let me know if you can correct the URL or we have to generate a new pull request.

**Comment by clalancette** [comment]
> The correct URL is: https://github.com/Vision4UAV/Aerostack.
> Please, let me know if you can correct the URL or we have to generate a new pull request.

You'll want to generate a new pull request for a different repository.

However, looking at https://github.com/Vision4UAV/Aerostack, it looks like the repository itself doesn't have any packages.  They seem to be all in git submodules.  I'm not sure if our documentation generator can properly do `git submodule` stuff.  So feel free to open another PR to test it out, but we may not be able to accommodate it either.

**Comment by tfoote** [comment]
Besides the fact that we haven't fully tested all our toolchain on submodules. 

Please don't submit a meta repository like this, but do the actual upstream repositories. It's much more useful for our tools to expose people to the actual content and not a layer of indirection. The history of this repository is not useful: https://github.com/Vision4UAV/Aerostack/commits/master as it's just a malleable index with not consistency or tracking of what's actually changed.

```
Text improvement

@martin-molina
martin-molina committed 2 days ago
  
Just a link to the wiki

@martin-molina
martin-molina committed 2 days ago
  
Commits on Jul 30, 2019
Added new project

@rodelgo7al
rodelgo7al committed 10 days ago
 
Commits on Jul 26, 2019
Code improvements

@rodelgo7al
rodelgo7al committed 14 days ago
 
Commits on Jul 25, 2019
minor bugs

@rodelgo7al
rodelgo7al committed 15 days ago
 
Update LICENSE

@rodelgo7al
rodelgo7al committed 15 days ago
  
Merge branch 'master' into v3-sirocco

@rodelgo7al
rodelgo7al committed 15 days ago
 
edited gitsubmodules

@rodelgo7al
rodelgo7al committed 15 days ago
 
edited gitsubmodules

@rodelgo7al
rodelgo7al committed 15 days ago
 
v3-sirocco

@rodelgo7al
rodelgo7al committed 15 days ago
 
Added new submodule to a project

@rodelgo7al
rodelgo7al committed 15 days ago
 
added submodule to a project

@rodelgo7al
rodelgo7al committed 15 days ago
```

Also with a quick browse through your submodules you have things that are already indexed in your submodules which you should not be submitting for indexing such as the hokuyo driver: https://github.com/Vision4UAV/Aerostack/blob/e0286e3392867c35bcc33c8e9ab71c8787dae5af/.gitmodules#L404-L407

rotors_simuator
https://github.com/Vision4UAV/Aerostack/blob/e0286e3392867c35bcc33c8e9ab71c8787dae5af/.gitmodules#L402

bebop_autonomy
https://github.com/Vision4UAV/Aerostack/blob/e0286e3392867c35bcc33c8e9ab71c8787dae5af/.gitmodules#L31

**Pull request closed without merging**
