### PR TITLE
Added new package to jderobot_drones

### PR DESCRIPTION
**Pull request by pariaspe**
Version 1.2.0-1 includes rqt_ground_robot_teleop package.

### CODE REVIEW

**Comment by clalancette** [comment]
This looks OK, but is there a particular reason you didn't use bloom for this release?  It should have picked up the new package.

**Comment by pariaspe** [comment]
I did (`bloom-release jderobot_drones --rosdistro melodic`), but idk why the automated pull request did not work. Sorry for the inconvenience

**Comment by clalancette** [comment]
> I did (`bloom-release jderobot_drones --rosdistro melodic`), but idk why the automated pull request did not work. Sorry for the inconvenience

No worries.  I'll still go ahead and merge, just wondering :).

**Comment by pariaspe** [comment]
> > I did (`bloom-release jderobot_drones --rosdistro melodic`), but idk why the automated pull request did not work. Sorry for the inconvenience
> 
> No worries. I'll still go ahead and merge, just wondering :).

Thanks! :)

**Pull request merged**
