### PR TITLE
add rosdep key for npm

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by mikeferguson** [comment]
Is it possible to get this merged? It's currently blocking further progress on what I'm working on.

**Comment by dirk-thomas** [comment]
We updated our policy to require two +1s for rosdep keys. Therefore @tfoote didn't merge it right away.

**Comment by mikeferguson** [comment]
OK -- was that change in policy advertised anywhere?

**Comment by dirk-thomas** [comment]
Not yet, we only made that change last week. I am sure @tfoote will do it soonish.

**Pull request merged**
