### PR TITLE
Add python-cbor package

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Comment by tfoote** [comment]
I see this for debian and ubuntu, could you link to the fedora and gentoo packages?

https://packages.debian.org/search?keywords=python-cbor
https://packages.ubuntu.com/search?keywords=python-cbor

**Comment by mvollrath** [comment]
Fedora:
https://copr.fedorainfracloud.org/coprs/hvenev/experiments/package/python-cbor/
(I must admit I have no idea if this will install)

Gentoo:
https://packages.gentoo.org/packages/dev-python/cbor

**Review by tfoote — CHANGES_REQUESTED** [review]
> Fedora:
https://copr.fedorainfracloud.org/coprs/hvenev/experiments/package/python-cbor/
(I must admit I have no idea if this will install)
Yeah that's what I found too. copr is the equivalent of ubuntu ppas so we shouldn't include that entry as a rule as it won't be installable by default.

**Comment by mvollrath** [comment]
Don't intend to use this anymore.

**Review by dirk-thomas — APPROVED** [review]

**Comment by mvollrath** [comment]
@tfoote I've excluded the uninstallable Fedora package.

**Comment by dirk-thomas** [comment]
@ros/ros_team Needs a second review and merge.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
