### PR TITLE
Adding rosaic to documentation index for noetic

### PR DESCRIPTION
**Pull request by septentrio-users**

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Reviewing the package quickly it doesn't appear to meet our guidelines of not using ros in the name: https://www.ros.org/reps/rep-0144.html And I can't even understand what aic is after skimming through the overview docs which suggests it's less useful in the descriptive department. To that end I'd like to request that you rename this before indexing it and spreading it wider. After that happens it's much harder to rename things.

**Comment by hidmic** [comment]
@septentrio-users friendly ping

**Comment by septentrio-users** [comment]
Thank you for pointing out that "ros" cannot be included in the repo name. After renaming to "septentrio_gnss_driver" I have made a new pull request. Cheers

**Comment by clalancette** [comment]
With #26976 merged, I'm going to close this out.  Thanks for iterating.

**Comment by tfoote** [comment]
Thanks for updating. That's a much clearer name!

**Pull request closed without merging**
