### PR TITLE
Adding new repository for indexing: atracsys_fusion_tracker

### PR DESCRIPTION
**Pull request by ghost**
# Please Add This Package to be indexed in the rosdistro.

Kinetic

# The source is here: 

https://github.com/cerberos79/atracsys_fusionTrack.git

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by cottsay** [comment]
@cerberos79, it looks like there are merge conflicts. Would you mind resolving them?

**Comment by tfoote** [comment]
We are preparing for the final kinetic sync. All releases should be prepared by April 20th and we will have a long soak time until April 26th. Please make sure to test from the [testing repository](http://wiki.ros.org/TestingRepository) to make sure that there's no regressions after this is released. You can get more info from [this thread on ROS Discourse](https://discourse.ros.org/t/preparing-for-final-kinetic-sync/19805)

Because of the pending EOL status of Kinetic I might suggest that you target a newer platform. The kinetic rosdistro will be frozen after the above sync.

**Review by tfoote — CHANGES_REQUESTED** [review]
official change requested due to merge conflict.

**Comment by cottsay** [comment]
Hi @cerberos79. There are still merge conflicts that will prevent testing and merging this change, but I spotted another issue.

The `release:` portion of this change is referring to the content repository, when it should refer to a "release" repository. You'll notice that other entries in this file use a separate repository for this purpose.

Please take a look at this page, which describes how to release your package: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

For now, I recommend dropping the `release:` part and merge only the `source:` part, until you've properly prepared the package as described on the wiki.

**Comment by clalancette** [comment]
Given where we are with the final Kinetic sync, and the fact that this still has conflicts, I'm going to close this out.  If you'd like this package to be indexed, I'll suggest opening a PR against Melodic or Noetic, which still have a few years of support left.

**Pull request closed without merging**
