### PR TITLE
Add rb1_base_sim package manually into melodic

### PR DESCRIPTION
**Pull request by David-rn**
Opening a PR manually after `bloom-release` in order to add the rb1_base_sim package into the rosdisto

### CODE REVIEW

**Comment by wjwwood** [comment]
@David-rn can you explain why you didn't allow `bloom-release` to open the pull request? This is preferred for us because it helps ensure there were no mistakes in the new entry.

**Comment by dredonieto** [comment]
Hi! I'll show you a picture from it: 

Screenshot from 2020-09-22 22-06-57

When it arrives at this point it shows the changes but it won't continue, and I do not know why fails trying to open a PR. So, what I did is check where are the changes and add them manually. What should I do? In every release I did, it shows that message.

**Comment by wjwwood** [comment]
@David-rn can you locate the log in `~/.bloom_logs`? That will tell me what the source of the error is.

**Comment by dredonieto** [comment]
Sure! I attach the whole file:

[bloom-release_2020-09-22_22.02.40.571164.log](https://github.com/ros/rosdistro/files/5266110/bloom-release_2020-09-22_22.02.40.571164.log)

To sum up, after reading the file, the error appears at the end: 

```
[debug] Checking out to debian/melodic/stretch/robotnik_sensors
[debug] /tmp/tmpnyKJZb:$ git checkout "debian/melodic/stretch/robotnik_sensors"
[debug] Checking out to release/melodic/robotnik_sensors
[debug] /tmp/tmpnyKJZb:$ git checkout "release/melodic/robotnik_sensors"
[debug] Checking out to debian/melodic/stretch/robotnik_sensors
[debug] /tmp/tmpnyKJZb:$ git checkout "debian/melodic/stretch/robotnik_sensors"
[info] ==> Checking on GitHub for a fork to make the pull request from...
[warning] Could not find a fork of ros/rosdistro on the dredo@robotnik.es GitHub account.
[warning] Would you like to create one now?
[debug] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1120, in perform_release
    track, repository, distro, interactive, override_release_repository_url
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 704, in open_pull_request
    "Using this fork to make a pull request from: {head_org}/{head_repo}".format(**locals())))
  File "/usr/lib/python2.7/dist-packages/bloom/logging.py", line 356, in fmt
    msg = t.substitute(_ansi) + ansi('reset')
  File "/usr/lib/python2.7/string.py", line 176, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python2.7/string.py", line 166, in convert
    val = mapping[named]
KeyError: u'robotnik'

[error] Failed to open pull request: KeyError - u'robotnik'
[error] SYS.EXIT
```

**Comment by clalancette** [comment]
I'm going to go ahead and merge this, as the change itself looks OK.  It would be good to file a bug here against https://github.com/ros-infrastructure/bloom , since that looks like something that bloom should handle.

**Comment by clalancette** [comment]
And reverting, since the release repository isn't setup properly.  Bloom really does need to work here; one thing I'll suggest is trying it with Python 3 instead of Python 2.

**Comment by wjwwood** [comment]
@dredonieto it could be a Python2/3 issue since the key is unicode and the string being formatted is not, but I thought we'd addressed all of those cases. So you could try a Python3 install of bloom. But please feel free to open an issue on the bloom repository with this output too:

https://github.com/ros-infrastructure/bloom/issues/new

**Comment by dredonieto** [comment]
@wjwwood Okay, I'll try that and see how it goes and I'll open a new issue as well. Thanks!

**Comment by dredonieto** [comment]
I've tried what you said, but it happened again, so I've opened a new issue as you suggested as see what we can do.

**Pull request merged**
