### PR TITLE
rosbag2: 0.15.6-1 in 'humble/distribution.yaml' [bloom]

### LINKED ISSUE #1365: New release for Humble?
## Description

I am trying to use rosbag2 in Humble, but this issue: https://github.com/ros2/rosbag2/pull/1225 makes it very annoying to use as my console is either filled with messages from the binary version, or I need to build rosbag2 from source.

## Related Issues

https://github.com/ros2/rosbag2/issues/1139

## Completion Criteria

Release rosbag2 0.15.6 or so for Humble. As far as I can see, a few extra small issues have been fixed, but I don't think it's anything major?

### PR DESCRIPTION
**Pull request by MichaelOrlov**
Increasing version of package(s) in repository `rosbag2` to `0.15.6-1`:

- upstream repository: https://github.com/ros2/rosbag2.git
- release repository: https://github.com/ros2-gbp/rosbag2-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.11.2`
- previous version for package: `0.15.5-1`
- Closes https://github.com/ros2/rosbag2/issues/1365

## mcap_vendor

- No changes

## ros2bag

- No changes

## rosbag2

- No changes

## rosbag2_compression

```
* Deconstruct compression classloader factory in correct order with classes loaded (#1362 <https://github.com/ros2/rosbag2/issues/1362>)
* Fx memory issue when multiple writers with message compression_mode required (#1331 <https://github.com/ros2/rosbag2/issues/1331>)
  - Deep copy message when sequential compression writer is writing
  Co-authored-by: zeal <mailto:ziyaolin.zeal@gmail.com>
* Contributors: Emerson Knapp, zeal-up
```

## rosbag2_compression_zstd

- No changes

## rosbag2_cpp

```
* Added close to writer (#1363 <https://github.com/ros2/rosbag2/issues/1363>)
  Co-authored-by: Bernat <mailto:bernat.gaston@movvo.eu>
* Contributors: Bernat
```

## rosbag2_interfaces

- No changes

## rosbag2_performance_benchmarking

- No changes

## rosbag2_py

- No changes

## rosbag2_storage

- No changes

## rosbag2_storage_default_plugins

- No changes

## rosbag2_storage_mcap

- No changes

## rosbag2_storage_mcap_testdata

- No changes

## rosbag2_test_common

```
* Add extra checks in execute_and_wait_until_completion(..) (#1346 <https://github.com/ros2/rosbag2/issues/1346>) (#1357 <https://github.com/ros2/rosbag2/issues/1357>)
  - Add check if process was terminated by the signal or really exited
  (cherry picked from commit 1215440903c61e0bcbefcf8779b58c86fe31daa6)
  Co-authored-by: Michael Orlov <mailto:michael.orlov@apex.ai>
* Contributors: Michael Orlov
```

## rosbag2_tests

- No changes

## rosbag2_transport

```
* [Humble] Bugfix for parameters not passing to recorder's node from child component (backport #1360 <https://github.com/ros2/rosbag2/issues/1360>) (#1368 <https://github.com/ros2/rosbag2/issues/1368>)
  * Bugfix for parameters not passing to recorder's node from child component (#1360 <https://github.com/ros2/rosbag2/issues/1360>)
  * Update recorder.cpp
  * Regression test
  * Fix test for composable recorder with parameter override option
  ---------
  Co-authored-by: Michael Orlov <mailto:michael.orlov@apex.ai>
  (cherry picked from commit 13f51510342e9f06327ae1146820780baee06c4a)
  ---------
  Co-authored-by: Patrick Roncagliolo <mailto:ronca.pat@gmail.com>
  Co-authored-by: Michael Orlov <mailto:michael.orlov@apex.ai>
* Fix memory issue when multiple writers with message compression_mode required (#1331 <https://github.com/ros2/rosbag2/issues/1331>)
  - Deep copy message when sequential compression writer is writing
  Co-authored-by: zeal <mailto:ziyaolin.zeal@gmail.com>
* Print "Hidden topics are not recorded" only once. (#1225 <https://github.com/ros2/rosbag2/issues/1225>) (#1323 <https://github.com/ros2/rosbag2/issues/1323>)
  (cherry picked from commit a640adaeeee3bbffaa6cd73cde3f3e8781f12e89)
  Co-authored-by: rshanor <mailto:rickshanor@gmail.com>
* Contributors: zeal-up, Michael Orlov, Patrick Roncagliolo, rshanor
```

## shared_queues_vendor

- No changes

## sqlite3_vendor

- No changes

## zstd_vendor

- No changes

### CODE REVIEW

**Comment by emersonknapp** [comment]
> We should wait to merge this until we are ready for a patch release. @audrow FYI.

Not sure what this means - there's no sync hold on Humble right now, is there?

**Comment by clalancette** [comment]
> Not sure what this means - there's no sync hold on Humble right now, is there?

No, but because this is a core package (i.e. in https://github.com/ros2/ros2/blob/humble/ros2.repos), we probably shouldn't release it without a patch release.

The basic reason is that if we do this, then when building from source, or when using the Debian package, it will have fixes listed above.  But you use the binary tarball (from https://github.com/ros2/ros2/releases/tag/release-humble-20230502), then it will *not* have these fixes.  It's a pretty inconsistent experience for users, particularly on Windows where there aren't a lot of good deployment options.

That said, if we think these fixes are urgent enough we can merge it without a patch release.  I'll leave that to figure out between you and @audrow.

**Comment by MichaelOrlov** [comment]
@clalancette @audrow In this case when is going to be the next patch-release for Humble?

**Comment by emersonknapp** [comment]
> but because this is a core package we probably shouldn't release it without a patch release

1. Is a patch release created at the same time as each apt sync?)? If so - then it seems like the debian package and tarball release won't actually be out of sync since you'd have to use `ros-testing` to get the inconsistent version and that's already a conscious choice to get out-of-release artifacts.
1. Is there a tag or board that is used to bundle things up for the patch releases?
1. If we do save it for later, and we then end up making another bloom release before the next Humble patch release, will that cause problems? Do we need to remember to come in and close this PR before doing the followup bloom?

**Comment by clalancette** [comment]
> * Is a patch release created at the same time as each apt sync? If so - then it seems like the debian package and tarball release wouldn't be out of sync -- you'd have to use `ros-testing` apt repo to get the inconsistent deb and that's already a conscious choice to get out-of-release artifacts.

No, they are separate things.  When we do a "normal" sync, we are more-or-less just syncing apt/rpm packages out.  Doing a patch release is a bunch more work.

> * Is there a tag or board that is used to bundle things up for the patch releases?

Yes: https://github.com/orgs/ros2/projects/51

> * If we do save it for later, and we then end up making another bloom release before the next Humble patch release, will that cause problems? Do we need to remember to come in and close this PR before doing the followup bloom?

No, it won't cause a problem.  It would be best to close this one out if/when another patch release is made, but there won't be any problem if we forget.

**Comment by emersonknapp** [comment]
Well, I'd personally like to merge it and that way just make sure bugfixes go out in the next sync, much nicer incremental experience. I do see the argument for the consistency of experience, but I personally feel like I'm weighing fixes higher

**Comment by MichaelOrlov** [comment]
I don't have a very strong opinion about when to release changes but agree with @emersonknapp in regard to the 
> I personally feel like I'm weighing fixes higher

At least users who are waiting for these fixes will be able to get them early.

**Comment by haudren-woven** [comment]
As a user waiting for these fixes to go in via binary packages (apt), I'd be glad if this can be merged in sooner rather than later. But I don't really understand the consequences of making a patch release...

**Comment by clalancette** [comment]
I'll put it on the agenda to discuss next week with the full team (including @audrow).

**Comment by audrow** [comment]
We can go ahead and merge these in. I'll make a mini patch next week.

**Comment by audrow** [comment]
Here's the patch: https://github.com/ros2/ros2/releases/tag/release-humble-20230614

**Comment by MichaelOrlov** [comment]
Thank you @audrow

**Pull request merged**
