### PR TITLE
Adding new libraries for Ubuntu (fixed)

### PR DESCRIPTION
**Pull request by jonyal**
New libraries:
- libjaxp1.3-java
- libjsoncpp0
- speex
- tap-plugins
- libbison-dev
- libboost-random (libboost-random-dev, libboost-random1.X)
- libttspico (libttspico-dev, libttspico-data, libttspico-utils, libttspico0)
- bluez-hcidump
- acpitool

### CODE REVIEW

**Comment by vrabaud** [comment]
http://packages.ubuntu.com/wily/acpitool
http://packages.ubuntu.com/wily/bluez-hcidump
http://packages.ubuntu.com/wily/libbison-dev
http://packages.ubuntu.com/precise/libboost-random1.46-dev
http://packages.ubuntu.com/trusty/libboost-random1.54.0
http://packages.ubuntu.com/precise/libboost-random-dev
http://packages.ubuntu.com/precise/libjaxp1.3-java
http://packages.ubuntu.com/precise/speex
http://packages.ubuntu.com/wily/tap-plugins

Concerning libjsoncpp0, maybe rename it to libjsoncpp ? Because in Xenial it becomes: http://packages.ubuntu.com/fr/xenial/libjsoncpp1

**Comment by wjwwood** [comment]
+1 to renaming it to `libjsoncpp` since it is a new key and the deb name changes in xenial and because there's already the `libjsoncpp-dev` key.

**Comment by JonatanAlcocer** [comment]
Done. I have modified the libjsoncpp0 lib name to libjsoncpp, and considering both (lbjsoncpp0 & libjsoncpp1) for each ubuntu package

**Comment by vrabaud** [comment]
@JonatanAlcocer , Wily is missing for libjsoncpp

**Comment by JonatanAlcocer** [comment]
Ok, added for wily

**Comment by JonatanAlcocer** [comment]
Done, libjsoncpp added for wili (libjsoncpp0v5)

**Comment by wjwwood** [comment]
http://packages.ubuntu.com/fr/wily/libjsoncpp0v5

Lgtm, thanks for iterating with us.

**Pull request merged**
