### PR TITLE
reintegrate Ardent, Bouncy and Crystal from ros2/rosdistro

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to ros2/rosdistro#492.

Contains all commits from ros2/rosdistro which affect the three ROS 2 distros (using `git-splits`). Each commit message was rewritten to prepend "ros2/rosdistro" to each referenced ticket number (using `git filter-branch --msg-filter ...`). A manual commit at the end adds the three distros to the index files.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
> Each commit message was rewritten to prepend "ros2/rosdistro" to each referenced ticket number

Was that successful? Most commits seem to show something like `ros2#491`. Should that be `ros2/rosdistro#491`?

**Comment by dirk-thomas** [comment]
> Most commits seem to show something like ros2#491. Should that be ros2/rosdistro#491?

Yes, you might want to look at the plain commit message. GitHub is reformatting the link text since it is a forked repo. The links should work though.

**Comment by nuclearsandwich** [comment]
> A manual commit at the end adds the three distros to the index files.

I don't see this commit on this PR. Has it been added already?

**Comment by dirk-thomas** [comment]
Thanks for pointing it out. Looks like that one was sitting only in my local working copy. Pushed in 8cc1b58f7f31ef76b4fea0735862a99af9f189ff.

**Comment by nuclearsandwich** [comment]
Before we do the merge I'm going to take this branch to my fork and perform a dry-run release against the merged rosdistro.

**Review by nuclearsandwich — APPROVED** [review]
I was able to use this branch on my fork to mock re-release random_numbers for melodic and class_loader for crystal with pull requests.

**Pull request merged**
