### PR TITLE
Adding new repository for indexing: phm_tools

### PR DESCRIPTION
**Pull request by HakanGENCTURK**

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
I took a quick look and it appears that all your packages have TODO declared as the license. [Like this](https://github.com/inomuh/phm_tools/blob/65a862ea5b1ce53a1aeedf805585790ff7772b63/phm_tools/package.xml#L9). And no other license files. Please choose a license and apply it to your repositories. https://choosealicense.com/

Our recommended license is Apache-2.0 https://choosealicense.com/licenses/apache-2.0/

**Comment by HakanGENCTURK** [comment]
I made all require

**Comment by HakanGENCTURK** [comment]
I made all required changes. I added Apache 2.0 license into my package.

**Comment by tfoote** [comment]
Great, thanks for the updates. In the future you can leave this open and just comment back here when the change request has been resolved and I can update my review.

**Pull request closed without merging**
