### PR TITLE
add rosdep key for libgif-dev

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by mikeferguson** [comment]
Rebased on top of master (I didn't update my fork initially)

**Comment by tfoote** [comment]
Could you add debian [`libgif-dev`](https://packages.debian.org/sid/libgif-dev) and fedora [`libgif-devel`](https://www.rpmfind.net/linux/rpm2html/search.php?query=giflib-devel) too?

**Comment by mikeferguson** [comment]
Added

**Comment by tfoote** [comment]
We turned on GitHub protection for this branch and it will warn if there are any commits out of date, you probably were well out of date if you hadn't updated but now It's likely still mergeable, we just have to use our admin status to override the warning. Since it's unreasonable to expect people to rebase every 5 minutes.

**Pull request merged**
