### PR TITLE
Update python.yaml

### PR DESCRIPTION
**Pull request by PhilippSchmaelzle**
TensorFlow Serving API support would be appreciated :) 
https://pypi.org/project/tensorflow-serving-api/

Please add the following dependency to the rosdep database.

## Package name:

tensorflow-serving-api

## Package Upstream Source:

https://github.com/tensorflow/serving

## Purpose of using this:

This dependency enables the usage of the TensorFlow Serving API which helps to deploy NNs easy into production. In my case, I can easily run NNs in an enclosed Docker and do inference. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - not available
- Ubuntu: https://packages.ubuntu.com/
   - not available
- Fedora: https://src.fedoraproject.org/browse/projects/
  - not available

### CODE REVIEW

**Review by cottsay — CHANGES_REQUESTED** [review]
Everything checks out, but it would be appreciated if you added rules for some of the other supported platforms. Matching those listed for `python-tensorflow-pip` (above the new rule) seems appropriate.

**Comment by PhilippSchmaelzle** [comment]
Thx for the initial review.
I added the other rules, matching previous tensorflow packages.

**Review by cottsay — APPROVED** [review]
> I added the other rules, matching previous tensorflow packages

Thanks!

**Comment by belorenz** [comment]
Could you please merge this @cottsay? Thanks in advance!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
