### PR TITLE
rosdep: Add libgeographic-dev for Zesty

### PR DESCRIPTION
**Pull request by vooon**
Required for releasing mavros for Lunar.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@vooon can you please add ubuntu artful as well?
The debian rule should be updated as well:
 - only wheezy has [libgeographiclib-dev](https://packages.debian.org/search?keywords=libgeographiclib-dev&searchon=names&suite=all&section=all)
 - jessie, stretch and buster have [libgeographic-dev](https://packages.debian.org/search?keywords=libgeographic-dev&searchon=names&suite=all&section=all)

**Comment by vooon** [comment]
@mikaelarguedas done.

**Review by mikaelarguedas — APPROVED** [review]
thanks!

**Comment by mikaelarguedas** [comment]
Note for reviewer: should be "squash and merge"d

**Comment by mikaelarguedas** [comment]
retriggering travis...

**Pull request merged**
