### PR TITLE
adding ira_laser_tools

### PR DESCRIPTION
**Pull request by pietrocolombo**
I'd like ira_laser_tools to be indexed and documented on ros.org

### CODE REVIEW

**Comment by tfoote** [comment]
This is failing CI because it's out of alphabetical order.

**Comment by mikaelarguedas** [comment]
please create a separate PR for the rosdep key addition providing the information listed in the [rosdep rule contribution guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions)

**Comment by pietrocolombo** [comment]
okay I do it, thanks

**Comment by mikaelarguedas** [comment]
@pietrocolombo sorry for the delay on this. This is now conflicting, can you please rebase this branch for it to be merged? thanks!

**Comment by tfoote** [comment]
Same as: https://github.com/ros/rosdistro/pull/18533#issuecomment-411901933

**Comment by pietrocolombo** [comment]
I rebase this branch now you can merge
thanks!

**Comment by mikaelarguedas** [comment]
Github doesnt allow to reopen a PR if the branch has been force-pushed. Can you please open a new PR with this change?

**Pull request closed without merging**
