### PR TITLE
Revert ros_industrial_cmake_boilerplate release and dependent packages (melodic)

### PR DESCRIPTION
**Pull request by asherikov**
Reverted commits:

commit e84a79ab34ba871f0bef538a4f8df9a6deedfa0f
    ros_industrial_cmake_boilerplate: 0.2.13-1 in 'melodic/distribution.yaml' [bloom] (#31362)

commit 2c43065abb5d8180878e128e4fdc37dc11781379
    ros_industrial_cmake_boilerplate: 0.2.14-1 in 'melodic/distribution.yaml' [bloom] (#31379)

commit 84592d3af098c6eb85cd65d9a3ec9b6e52125d22
    opw_kinematics: 0.4.4-1 in 'melodic/distribution.yaml' [bloom] (#31368)

Reason: overrides default `gtest` package and introduces version conflict that breaks linking

Example:
```
CMakeFiles/rosconsole-assertion_test.dir/test/assertion_test.cpp.o: In function `RosAssert_assert_Test::TestBody()':
assertion_test.cpp:(.text+0x84b): undefined reference to `testing::internal::DeathTest::Create(char const*, testing::Matcher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allo
CMakeFiles/rosconsole-assertion_test.dir/test/assertion_test.cpp.o: In function `RosAssert_breakpoint_Test::TestBody()':
assertion_test.cpp:(.text+0xbc3): undefined reference to `testing::internal::DeathTest::Create(char const*, testing::Matcher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allo
CMakeFiles/rosconsole-assertion_test.dir/test/assertion_test.cpp.o: In function `RosAssert_assertWithMessage_Test::TestBody()':
assertion_test.cpp:(.text+0xf3b): undefined reference to `testing::internal::DeathTest::Create(char const*, testing::Matcher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allo
collect2: error: ld returned 1 exit status
CMakeFiles/rosconsole-assertion_test.dir/build.make:109: recipe for target '/home/asherikov/ros_catkin_ws/devel_isolated/rosconsole/lib/rosconsole/rosconsole-assertion_test' failed
make[3]: *** [/home/asherikov/ros_catkin_ws/devel_isolated/rosconsole/lib/rosconsole/rosconsole-assertion_test] Error 1
CMakeFiles/Makefile2:171: recipe for target 'CMakeFiles/rosconsole-assertion_test.dir/all' failed
```

Reproduce with (Ubuntu 18)
```
mkdir ~/ros_catkin_ws
cd ~/ros_catkin_ws
rosinstall_generator rosconsole --rosdistro melodic --deps --tar > test.rosinstall                       
mkdir src
vcs import src < test.rosinstall                
./src/catkin/bin/catkin_make_isolated --install --catkin-make-args run_tests        
```

Validate the source of the problem with
```
rm -Rf build_isolated/ devel_isolated/ install_isolated/ 
rm -Rf src/ros_industrial_cmake_boilerplate/
./src/catkin/bin/catkin_make_isolated --install --catkin-make-args run_tests
```

Reported to maintainer -> https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/issues/57, but no reaction so far.

### CODE REVIEW

**Review by mabelzhang — COMMENTED** [review]
I think this is fine as these packages haven't been synced to main.
But maybe we should wait till the maintainer knows about this and respond either here or the ticket linked above? Maybe they can release a new version to fix things.
Melodic is not in sync yet so we have a bit of time. (@clalancette FYI)

**Comment by clalancette** [comment]
> I think this is fine as these packages haven't been synced to main.

Yes, if we decide to do this, it should be OK.

> But maybe we should wait till the maintainer knows about this and respond either here or the ticket linked above?

Yeah, let's wait a bit more on it (it has only been 4 days).  @Levi-Armstrong ping on this one.

**Comment by asherikov** [comment]
Well, I didnt find this by accident, it actually broke some of my CI jobs.
Sure, it can wait, but I would prefer it to be fixed first and then rereleased.

Also, I am much more concerned with overriding of the default package than the linking problem: essentially, this injects a dependency on a custom `gtest` package into pretty much all other packages. The contribution guide is not very precise regarding this -> https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#releasing-third-party-system-packages-into-a-ros-distribution, but it looks like it requires using a different package name: "Install side by side with the system one, with a different name".

**Comment by Levi-Armstrong** [comment]
I forgot to ignore the gtest package from the release process. This PR #31403 should address the issue.

**Comment by asherikov** [comment]
Ok, thanks a lot. I'll close this MR when the fix is merged.

**Comment by audrow** [comment]
Closed in favor of https://github.com/ros/rosdistro/pull/31403.

**Pull request closed without merging**
