### PR TITLE
added libalglib-dev

### PR DESCRIPTION
**Pull request by betwo**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Please add [debian](https://packages.debian.org/search?keywords=libalglib-dev&searchon=names&suite=all&section=all) and [fedora](https://admin.fedoraproject.org/pkgdb/package/rpms/alglib/) entries as well.
Thanks!

**Comment by mikaelarguedas** [comment]
can you use the suffix `-devel` for the fedora entry so that they all use the development version of the package ? (like in libann-dev below) thanks

**Comment by betwo** [comment]
Oh, sorry.

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks for the quick iteration

**Pull request merged**
