### PR TITLE
Adding clober to documentation index for distro

### PR DESCRIPTION
**Pull request by clobot-git**
I'd like my repository to be indexed and documented on ros.org

### CODE REVIEW

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
It does not appear that your release repository has been used to create a bloom release yet. I would recommend that you remove the `release` sections entirely. When you create a [release with Bloom ](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) the pull request that bloom creates will add a complete release section.

**Comment by clobot-git** [comment]
I remove the `release` sections entirely.

**Review by mabelzhang — COMMENTED** [review]
Could you update the `<license>` tags of all the packages to match the license? `clober_bringup`, `clober_serial` still say TODO.

**Comment by clobot-git** [comment]
I update the `<license>` tags of all the packages. Please check our packages.

**Review by ivanpauno — APPROVED** [review]

**Pull request merged**
