### PR TITLE
Added openocd key

### PR DESCRIPTION
**Pull request by pablogs9**
Added OpenOCD key for micro-ROS project

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please link to the upstream packages for contributed rosdep rules: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by pablogs9** [comment]
- https://packages.ubuntu.com/eoan/openocd
- https://packages.debian.org/buster/openocd
- https://src.fedoraproject.org/rpms/openocd
- https://packages.gentoo.org/packages/dev-embedded/openocd

**Review by tfoote — APPROVED** [review]

**Comment by pablogs9** [comment]
How can I get this PR merged?

**Comment by iluetkeb** [comment]
This has been approved 5 days ago, and all checks pass. Did you forget it? ;-)

**Comment by tfoote** [comment]
rosdep rules need two reviewers: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
