### PR TITLE
Adding report_card to documentation index for indigo

### PR DESCRIPTION
**Pull request by So-Cool**
I'd like report_card to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by tfoote** [comment]
There is no indigo-devel branch on that repo, only master. You should either change the PR to reference master or create an indigo-devel branch for your indigo development.

**Comment by So-Cool** [comment]
Thanks for the tip; it seems to work now.

**Comment by tfoote** [comment]
Great, could you squash the commits into one before we merge?

**Comment by So-Cool** [comment]
Done. Is it OK right now?

**Comment by tfoote** [comment]
Thanks. That looks good, it will merge fine. Note for next time, fetch the latest master before you rebase. This repo moves quickly and you actually rebased another already merged branch inside yours. Git's merging will figure it out this time.

**Pull request merged**
