### PR TITLE
extrinsic_calibrator: in 'humble/distribution.yaml'

### PR DESCRIPTION
**Pull request by pep248**
# Please Add This Package to be indexed in the rosdistro.

`humble`

# The source is here:

[extrinsic_calibrator](https://github.com/Ikerlan-KER/extrinsic_calibrator.git) 

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by marcoag** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-11-04/40374)

**Comment by pep248** [comment]
> [Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-11-04/40374)

Do we have to do anything?
I don't see that we are mentioned anywhere in [99 packages ](http://repo.ros2.org/status_page/ros_humble_default.html?q=SYNC).

**Comment by marcoag** [comment]
> > [Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-11-04/40374)
> 
> Do we have to do anything? I don't see that we are mentioned anywhere in [99 packages ](http://repo.ros2.org/status_page/ros_humble_default.html?q=SYNC).

No you don't have to do anything, just wait. There's a hold for humble packages PRs to rosdistro. You can find more info in the link I posted.

**Comment by marcoag** [comment]
@pep248 Actually I just noticed the repo file license shows up Affero GPL 3: https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/humble/license.md while the packages seem to declare GPL 3: 
- https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/667b9204b6e536c203bf8a44a9721b5fdbadab83/extrinsic_calibrator/package.xml#L8
- https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/667b9204b6e536c203bf8a44a9721b5fdbadab83/extrinsic_calibrator_core/package.xml#L8
- https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/667b9204b6e536c203bf8a44a9721b5fdbadab83/extrinsic_calibrator_examples/package.xml#L9

I believe this are slightly different licenses, can we get this in sync?

**Comment by pep248** [comment]
@audrow!
No please! put again the held for sync, please.
I have fixed the issues

**Review by sloretz — APPROVED** [review]
- [X] At least one of the following must be present
  - [x] Top level license file: 
  - [ ] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - I think so, but I'll let one more reviewer take a look at the name `extrinsic_calibrator`.

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>extrinsic_calibrator</name>
  <name>extrinsic_calibrator_core</name>
  <name>extrinsic_calibrator_examples</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
./extrinsic_calibrator/package.xml:  <license>AGPL-3.0-only</license>
./extrinsic_calibrator_core/package.xml:  <license>AGPL-3.0-only</license>
./extrinsic_calibrator_examples/package.xml:  <license>AGPL-3.0-only</license>
```
</details>

**Pull request merged**
