### PR TITLE
aubo_robot: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by liuxinwust**
Increasing version of package(s) in repository `aubo_robot` to `0.1.1-0`:
- upstream repository: https://github.com/auboliuxin/aubo_robot.git
- release repository: https://github.com/auboliuxin/aubo_robot-release.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.22`
- previous version for package: `null`
## aubo_control

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_description

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_driver

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_gazebo

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_i5_moveit_config

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_kinematics

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_msgs

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_robot

```
* update CHANGELOG.rst
* Contributors: robot
```
## aubo_trajectory

```
* update CHANGELOG.rst
* Contributors: robot
```

### CODE REVIEW

**Comment by auboliuxin** [comment]
I bloom release success, but  no  Documentation Status  on page  http://wiki.ros.org/aubo_robot.  how to solve?
 Thanks

**Comment by tfoote** [comment]
I just merged your pull request #12762 it will take up to 3 days for documentation to be generated. 

Unfortunately that PR was redundant with this PR so you'll need to rebase this PR on top of that one since it's conflicting.  I'm reverting that so this should merge cleanly.

**Comment by auboliuxin** [comment]
"Unfortunately that PR was redundant with this PR so you'll need to rebase this PR on top of that one since it's conflicting. I'm reverting that so this should merge cleanly. " --------Sorry,I'm not undersatand. Can i pull request a new version successfully next time?

**Comment by tfoote** [comment]
Yes, you can make a pull request for a new release now that this one has been merged. The problem was that your two pull requests inserted data in the same area so they were in conflict since they were both outstanding. Now that your pull request has been merged you can make a new PR to modify it for a new release. The problem is if you make two parallel pull requests for the same package they cannot both be merged without modification.

**Comment by auboliuxin** [comment]
OK,if I should  rebase the  PR #12763 next time?

**Comment by auboliuxin** [comment]
I do the bloom release(PR #12763), should i need do PR like #12765? just only need do bloom release?

**Comment by auboliuxin** [comment]
I'm a green hand for so sorry!  I do the bloom release(PR #12763), should i need both do PR like #12765? just do bloom release next time?

**Comment by auboliuxin** [comment]
I should follow Tutorials/Indexing Your ROS Repository for Documentation Generation.
 OR
bloom/Tutorials/ReleaseCatkinPackage?

**Comment by tfoote** [comment]
The tutorial about how to add to the documentation index is only necessary if you are not going to be releasing with bloom immediately. Most people do it in two stages, first they get it indexed, then later release it with bloom. If you have not submitted it to be indexed for doc or source bloom does both the release and prompts to add the documentation and source entries. In the future you only need to do a bloom release, and the only delta will be the version number.

**Pull request merged**
