### PR TITLE
added darwin_gazebo, darwin_control, darwin_description

### PR DESCRIPTION
**Pull request by ghost**
Added packages for simulating DarwinOP robot

### CODE REVIEW

**Comment by vrabaud** [comment]
ouh yeah ! thx !

**Comment by HumaRobotics** [comment]
You"re more than welcome Vincent !

**Comment by vrabaud** [comment]
I know many persons were looking for that. Maybe an announcement on ROS users would be welcome

**Comment by HumaRobotics** [comment]
Coming up, I was waiting for the index to update but I'm not sure how long it takes.

**Comment by HumaRobotics** [comment]
Hmm I'm getting a Jenkins error on darwin_control, even though it's almost empty, and the error seems to be that indigo could not be installed. Any hint?

http://jenkins.ros.org/job/doc-indigo-darwin_control/1/

The relevant part I guess:

Executing command 'apt-get install ros-indigo-ros ros-indigo-genmsg --yes'
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-indigo-ros : Depends: ros-indigo-mk but it is not going to be installed
                  Depends: ros-indigo-rosbuild but it is not going to be installed
                  Depends: ros-indigo-roslib but it is not going to be installed
                  Depends: ros-indigo-rosunit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
/!\  Failed to execute command '['apt-get', 'install', 'ros-indigo-ros', 'ros-indigo-genmsg', '--yes']' with return code 100
Traceback (most recent call last):
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 221, in <module>
    main()
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 119, in main
    doit(args.rosdistro, args.repo, workspace, docspace, args.platform, args.arch, args.no_chroot, args.skip_garbage, args.force)
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/doc", line 184, in doit
    call("apt-get install ros-%s-ros ros-%s-genmsg --yes" % (install_distro, install_distro))
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/common.py", line 148, in call
    return call_with_list(command.split(' '), envir=envir, verbose=verbose, return_output=return_output)
  File "/home/rosbuild/hudson/workspace/doc-indigo-darwin_control/jenkins_scripts/common.py", line 142, in call_with_list
    raise BuildException(msg)
common.BuildException

**Comment by vrabaud** [comment]
that was a buildfarm hickup sorry, a new build was triggered and it passed. You should receive an email soon.

**Comment by HumaRobotics** [comment]
worked fine
thanks!

**Comment by HumaRobotics** [comment]
Apparently the hickup is back: (on darwin_control)

The following packages have unmet dependencies:
 ros-indigo-ros : Depends: ros-indigo-mk but it is not going to be installed
                  Depends: ros-indigo-rosbuild but it is not going to be installed
                  Depends: ros-indigo-roslib but it is not going to be installed
                  Depends: ros-indigo-rosunit but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
/!\  Failed to execute command '['apt-get', 'install', 'ros-indigo-ros', 'ros-indigo-genmsg', '--yes']' with return code 100
Traceback (most recent call last):

**Pull request merged**
