### PR TITLE
Add rocky_tf_monitor in noetic/distribution.yaml

### PR DESCRIPTION
**Pull request by rkoyama1623**
# Please Add This Package to be indexed in the rosdistro.

tf_monitor

# The source is here:

https://github.com/rkoyama1623/tf_monitor.git

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/rkoyama1623/tf_monitor/blob/main/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): MIT
- [x] License correctly listed in package.xmls
  - [x] tf_monitor: https://github.com/rkoyama1623/tf_monitor/blob/main/package.xml
- [x] Public source repo: https://github.com/rkoyama1623/tf_monitor/tree/main/
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] tf_monitor


@audrow I could a second opinion on this package name before approving the name.
The name is accurate but I'm not sure if it counts as too general.

**Comment by clalancette** [comment]
I think the package name here could be confusing, because we already have a `tf2_monitor` command available from geometry2: https://github.com/ros2/geometry2/blob/rolling/tf2_ros/src/tf2_monitor.cpp .  I know that is for ROS 2, but I still think this could be confusing.

How about `rkoyama_tf_monitor` instead?

**Comment by sloretz** [comment]
[Holding for Noetic sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2023-11-09/)

**Comment by rkoyama1623** [comment]
@nuclearsandwich, @clalancette, Thank you for your considerations and naming suggestion.
rkoyama is my personal name:laughing:. I'd like to use a little more generic name.
I named this ros package rocky_tf_monitor, since this tool is used to inspect rocky tf topics, and rocky is a bit like my name.

**Comment by clalancette** [comment]
> I named this ros package rocky_tf_monitor, since this tool is used to inspect rocky tf topics, and rocky is a bit like my name.

That sounds good to me.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
