### PR TITLE
add 'apriltag_msgs' and 'apriltag_ros' to 'humble' and 'rolling'

### PR DESCRIPTION
**Pull request by christianrauch**
# Please Add This Package to be indexed in the rosdistro.

`humble` and `rolling`

# The source is here:

- https://github.com/christianrauch/apriltag_msgs
- https://github.com/christianrauch/apriltag_ros

# Checks
 - [x] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by christianrauch** [comment]
See also the PR for the release repos: https://github.com/ros2-gbp/ros2-gbp-github-org/issues/109.

**Comment by christianrauch** [comment]
@quarkytale Is this still held for a distro sync? Would it make sense to split this PR in order to get one of the distros merged before the other?

**Comment by quarkytale** [comment]
Hi @christianrauch, its not held for sync anymore. Could you update the release repos to ros2-gbp ones since that PR is now merged? 
But I see the release repos to be empty, is this supposed to merged first in that case?

**Comment by christianrauch** [comment]
> But I see the release repos to be empty, is this supposed to merged first in that case?

That was my understanding from the [release documentation](https://docs.ros.org/en/humble/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository):
> If your repository is new to the ROS community, you should first open a pull request on [ros/rosdistro](https://github.com/ros/rosdistro) adding a source entry for your repository. [...] Once your package name has been approved and merged, fill in the [Add New Release Repositories issue](https://github.com/ros2-gbp/ros2-gbp-github-org/issues/new?assignees=&labels=&template=new_release_repository.md&title=Add+new+release+repositories) issue template if you don’t have a release repo for your project yet.

There it says that the package name should be approved first by merging the `source` entry. I send both requests in parallel to speed up the process, but my understanding is that new packages should not have entries other than `source` populated initially. I probably then have to send another PR that is generated by `bloom-release` and will contain the release repo etc.

Is my understanding correct or should I generate a single PR that contains the full entry, including the `source` and `release` entries?

**Review by quarkytale — APPROVED** [review]
Lgtm based on attached thread and documentation. Please proceed with the `bloom-release`!

**Pull request merged**
