### PR TITLE
Add rosdep rule for libnotify

### PR DESCRIPTION
**Pull request by dornhege**

### CODE REVIEW

**Comment by tfoote** [comment]
Could you switch to use the more compact notation. And while you're at it add debian and fedora. 

debian: [libnotify-dev]
fedora: [libnotify-devel]
ubuntu: [libnotify-dev]


http://packages.ubuntu.com/trusty/libnotify-dev
https://packages.debian.org/jessie/libnotify-dev
https://apps.fedoraproject.org/packages/libnotify-devel

**Comment by dornhege** [comment]
Done and done, although only tested on ubuntu.

**Comment by tfoote** [comment]
+1

Yeah, we try to add the cross platform mostly based on documentation. Hopefully one day we'll have time to put together a verification script that will check in in the pull request.

**Comment by tfoote** [comment]
@wjwwood @jacquelinekay @vrabaud can you review? This looks like it got lost in the other pending pull requests

**Comment by wjwwood** [comment]
lgtm

**Pull request merged**
