### PR TITLE
rosdep: adding dependencies for openembedded

### PR DESCRIPTION
**Pull request by ghost**
Added dependencies for openembedded for the following packages:

 * cargo: https://layers.openembedded.org/layerindex/recipe/189290/
 * hdf5: https://layers.openembedded.org/layerindex/recipe/96029/
 * lttng-tools: https://layers.openembedded.org/layerindex/recipe/6146/
 * paho-mqtt-c: https://layers.openembedded.org/layerindex/recipe/69135/
 * paho-mqtt-cpp: https://layers.openembedded.org/layerindex/recipe/231014/
 * libqt5-quick,libqt5-qml: https://layers.openembedded.org/layerindex/recipe/4754/
 * libqt5-svg: https://layers.openembedded.org/layerindex/recipe/4783/
 * libyaml: https://layers.openembedded.org/layerindex/recipe/40236/
 * ode: https://github.com/RethinkRobotics-opensource/meta-ros/blob/nanbield/meta-ros-common/recipes-ode/ode/ode_0.16.4.1.bb
 * socat: https://layers.openembedded.org/layerindex/recipe/5109/
 * sqlite3: https://layers.openembedded.org/layerindex/recipe/45261/
 * wayland: https://layers.openembedded.org/layerindex/recipe/5057/

Python:

 * black: https://layers.openembedded.org/layerindex/recipe/396801/
 * python-construct: https://layers.openembedded.org/layerindex/recipe/354026/
 * python3-fiona: https://layers.openembedded.org/layerindex/recipe/396802/
 * python3-flake8-builtins: https://layers.openembedded.org/layerindex/recipe/354018/
 * python3-flake8-comprehensions: https://layers.openembedded.org/layerindex/recipe/354019/
 * python3-flake8-docstrings: https://layers.openembedded.org/layerindex/recipe/354020/
 * python3-flake8-import-order: https://layers.openembedded.org/layerindex/recipe/354021/
 * python3-flake8-quotes: https://layers.openembedded.org/layerindex/recipe/354022/
 * python3-git: https://layers.openembedded.org/layerindex/recipe/51298/
 * python3-img2pdf: https://layers.openembedded.org/layerindex/recipe/396797/
 * python3-jinja2: https://layers.openembedded.org/layerindex/recipe/148975/
 * python3-jsonschema: https://layers.openembedded.org/layerindex/recipe/240199/
 * python3-natsort: https://layers.openembedded.org/layerindex/recipe/133075/
 * python3-ntplib: https://layers.openembedded.org/layerindex/recipe/68086/
 * python3-protobuf: https://layers.openembedded.org/layerindex/recipe/72577/
 * python3-pytest-timeout: https://layers.openembedded.org/layerindex/recipe/120209/
 * python3-rtree: https://layers.openembedded.org/layerindex/recipe/396805/
 * python3-shapely: https://layers.openembedded.org/layerindex/recipe/396806/
 * python3-typeguard: https://layers.openembedded.org/layerindex/recipe/120600/
 * python3-unidiff: https://layers.openembedded.org/layerindex/recipe/68092/
 * python3-uvloop: https://layers.openembedded.org/layerindex/recipe/396808/
 * python3-vcstool: https://layers.openembedded.org/layerindex/recipe/396799/

Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database.

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
  - REQUIRED
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE
- rhel: https://rhel.pkgs.org/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by mjcarroll** [comment]
@RethinkMatze all changes seem reasonable, but in the long term, would it make sense to add verifications to our current CI process to check against openembedded?

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
There are a set of rosdep checks that are implemented for various platforms here: https://github.com/ros/rosdistro/tree/master/test/rosdep_repo_check

These checks allow us to automatically verify that the keys are valid for a particular rosdep and platform.

This is by no means a blocker on this PR, just a thought for something to consider.

**Comment by mjcarroll** [comment]
Or, as it seems, we can nerd-snipe @cottsay

**Comment by cottsay** [comment]
> Or, as it seems, we can nerd-snipe cottsay

Guilty.

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
