### PR TITLE
Add python-face-alignment-pip

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
This will be required in a package that we plan to release soon.

### CODE REVIEW

**Comment by tfoote** [comment]
Releases cannot use pip rules, they require native package manager rules. Will this still be useful?

**Comment by Tobias-Fischer** [comment]
Yes it'd still be useful. Would be great if we can add it.

**Review by tfoote — CHANGES_REQUESTED** [review]
Ok, then pleas fix your indentation to be consistent with the rest of the file. The tests are failing due to incorrect indententation.

Also please provide links to the package and double check your submission against the CONTRIBUTING guidelines: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md

**Comment by Tobias-Fischer** [comment]
Sorry for that. Indentation fixed.
Link: https://pypi.org/project/face-alignment/

Thanks

**Review by cottsay — APPROVED** [review]

**Review by tfoote — APPROVED** [review]

**Pull request merged**
