### PR TITLE
qb_device: 2.0.0-0 in 'lunar/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by qbrobotics-AT**
Increasing version of package(s) in repository `qb_device` to `2.0.0-0`:

- upstream repository: https://bitbucket.org/qbrobotics/qbdevice-ros.git
- release repository: https://bitbucket.org/qbrobotics/qbdevice-ros-release.git
- distro file: `lunar/distribution.yaml`
- bloom version: `0.6.4`
- previous version for package: `null`

## qb_device

- No changes

## qb_device_bringup

```
* Refactor launch files
* Fix minors
* Add a blocking setCommands method
* Fix until ros_comm#889 is fixed
* Refactor launch files and fix controllers spawner
```

## qb_device_control

```
* Update doxygen documentation
* Refactor launch files
* Add method to temporarily change PID parameters
* Add asynchronous requests for sporadic get/set
* Add a unique control node
* Fix minors
* Fix thread spinning
* Add basic trajectory builder methods
* Refactor yaml waypoint trajectory parsing
* Refactor Actions to match given hardware interfaces
* Switch to CombinedRobotHW
* Fix minors
* Fix waypoints parsing source
* Add a control loop frequency publisher
* Refactor launch files and fix controllers spawner
* Fix destructor calls on ROS shutdown
* Fix minors
```

## qb_device_description

```
* Refactor launch files
* Refactor launch files and fix controllers spawner
```

## qb_device_driver

```
* Move sleep at low level (next to API)
* Add method to temporarily change PID parameters
* Fix doxygen documentation
* Fix communication errors with asynchronous reads
* Refactor node registration
* Add method to get currents and positions together
* Fix minors
* Fix repetitions reliablity check
* Add a blocking setCommands method
* Fix destructor calls on ROS shutdown
* Fix minors
* Fix unexpected fault with std::unordered_set
* Add parallelization with several USB connected
* Let the user decide whether to read/write or not
* Add an alert if maximum repetitions is set to zero
* Refactor node registration
* Add a real isConnected method
* Refactor device scan method with repetitions
* Retrieve control and input mode device settings
* Implement repetitions also for getMeasurements
* Add repetitions while reading from serial
* Move error checks in ROS service callbacks
```

## qb_device_hardware_interface

```
* Add device configuration to the state topic info
* Fix recovery on service server fault
* Refactor node registration
* Fix accidental repetitions with namespace prefix
* Refactor initialization by extending the base init
* Add method to get currents and positions together
* Fix repetitions reliablity check
* Add a blocking setCommands method
* Refactor launch files and fix controllers spawner
* Fix minors
* Let the user decide whether to read/write or not
* Refactor node registration
* Add repetitions while reading from serial
```

## qb_device_msgs

```
* Add device configuration to the state topic info
* Add repetitions while reading from serial
```

## qb_device_srvs

```
* Add method to temporarily change PID parameters
* Refactor node registration
* Add method to get currents and positions together
* Add a blocking setCommands method
* Let the user decide whether to read/write or not
* Refactor node registration
* Add repetitions while reading from serial
```

## qb_device_utils

```
* Add SIGINT and shutdown RPC handlers
```

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@qbrobotics-AT It looks like something didn't got well when blooming this. There isn't any of the branches or tags that are usually created by bloom ( for lunar or melodic, only he branches for the kinetic release have been created)

**Comment by qbrobotics-AT** [comment]
@mikaelarguedas I had a circular dependency problem which caused `rosdep update` to fail when releasing the package with bloom.
I'm going to patch this and I'll wait to rebase the other pull requests until this is fixed.
I'm sorry for all this mess.

**Comment by qbrobotics-AT** [comment]
@mikaelarguedas However, since I think the other pull requests have the same problem too, how can I proceed to fix it properly?
The patch only affects the `qb_device` package which will become 2.0.1, but `qb_move` and `qb_hand` are ok since they depend on it.

**Comment by mikaelarguedas** [comment]
From what it looks like on the `qb_move` release repo, bloom failed there as well as there is no `debian/lunar/XX` branches.
If only `qb_device` requires a package.xml / source change, you can:
- release `qb_device` 2.0.1
- rerun bloom on the other packages that don't require a change (so no need to rerun catkin_prepare_release, just running bloom should be enough).

This will create new pull requests referring to the new versions so you can close the pending ones freely.

Tip: as it's likely that these new PRs will all touch the same part of the `distribution.yaml`, they will conflict as soon as I merge one of them, so I encourage you to bloom them one at a time so that I have the time to merge them before you bloom the next one

**Comment by qbrobotics-AT** [comment]
Thank you very much and sorry again.

**Pull request merged**
