### PR TITLE
Adding additional rosdep rules for Python packages

### PR DESCRIPTION
**Pull request by mirzashah**
apt: ```python-fixtures, python-testscenarios, python-testtools, python-levenshtein```
pip: ```annoy, google-cloud-vision, progressbar2, fuzzywuzzy```

All have been tested locally.

### CODE REVIEW

**Comment by wjwwood** [comment]
CI is failing.

**Comment by mirzashah** [comment]
@wjwwood hey, I'm struggling a bit with the error message in CI (pasted below) -- would you please give me some guidance on how to interpret this message, thanks much appreciated

```
======================================================================
FAIL: test.rosdep_formatting_test.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ros/rosdistro/test/rosdep_formatting_test.py", line 24, in test
    assert check_rosdep(fname), fold.get_message()
AssertionError: see folded block 'block1' for details
```

**Comment by mirzashah** [comment]
trailing spaces ... found it with rosdep_formatting_test.py

**Comment by wjwwood** [comment]
Please add at least Debian and optionally Fedora entries to the ones that currently have Ubuntu. Otherwise they cannot be used when releasing a package.

**Comment by mirzashah** [comment]
I googled to make sure all the package names were correct for fedora and debian. Everything is the same except on Fedora, it's ```python-Levenshtein``` instead of ```python-levenshtein```

**Review by wjwwood — APPROVED** [review]
lgtm, it needs two reviews before merging

**Pull request merged**
