### PR TITLE
Add packages for ROS2 kuka drivers

### PR DESCRIPTION
**Pull request by Svastits**
# Please Add This Package to be indexed in the rosdistro.
rosdistro: humble
package names:
- `kuka_drivers`
- `kuka_external_control_sdk`
- `kuka_robot_descriptions`

These packages add real-time capable drivers for different KUKA robots, including hardware interfaces of the `ros2_control` framework, robot models and KUKA-specific controllers.

Package dependencies: `kuka_drivers` depends on `kuka_external_control_sdk` and `kuka_robot_descriptions`. Aside of these depencencies, all of them build on humble.

What is the process in this case? I would like to create a ROS2 release from all packages. Should I at first only include `kuka_external_control_sdk` in this PR, do the relesase and then add the other packages one by one?

# The source is here:
- https://github.com/kroshu/kuka_drivers
- https://github.com/kroshu/kuka-external-control-sdk
- https://github.com/kroshu/kuka_robot_descriptions

# Checks
 - [X] All packages have a declared license in the package.xml
 - [X] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by sloretz** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-04-18/37216)

**Review by sloretz — CHANGES_REQUESTED** [review]
Couple points of feedback: 

*  event_broadcaster and control_mode_handler seem to me like they don't meet the guideline `Package names should be specific enough to identify what the package does`. Would you be willing to rename them to `kuka_event_broadcaster` and `kuka_control_mode_handler`?
 * Please add a LICENSE file to `kuka_external_control_sdk`

---

- [ ] At least one of the following must be present
  - [ ] Top level license file: 
  - [ ] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>kuka_lbr_iiwa_moveit_config</name>
  <name>kuka_robot_descriptions</name>
  <name>kuka_kr_moveit_config</name>
  <name>kuka_mock_hardware_interface</name>
  <name>kuka_lbr_iisy_moveit_config</name>
  <name>kuka_fortec_support</name>
  <name>kuka_cybertech_support</name>
  <name>kuka_quantec_support</name>
  <name>kuka_agilus_support</name>
  <name>kuka_lbr_iiwa_support</name>
  <name>kuka_lbr_iisy_support</name>
  <name>kuka_iontec_support</name>
  <name>kuka_resources</name>
  <name>kuka_external_control_sdk</name>
  <name>kuka_external_control_sdk_examples</name>
  <name>kuka_driver_interfaces</name>
  <name>kuka_iiqka_eac_driver</name>
  <name>kuka_drivers</name>
  <name>kuka_sunrise_fri_driver</name>
  <name>iiqka_moveit_example</name>
  <name>kuka_kss_rsi_driver</name>
  <name>kuka_drivers_core</name>
  <name>fri_state_broadcaster</name>
  <name>fri_configuration_controller</name>
  <name>event_broadcaster</name>
  <name>kuka_controllers</name>
  <name>joint_group_impedance_controller</name>
  <name>control_mode_handler</name>
  <name>kuka_rsi_simulator</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
./kuka_robot_descriptions/kuka_lbr_iiwa_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_robot_descriptions/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_kr_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_mock_hardware_interface/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iisy_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_fortec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_cybertech_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_quantec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_agilus_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iiwa_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iisy_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_iontec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_resources/package.xml:  <license>Apache-2.0</license>
./kuka-external-control-sdk/kuka_external_control_sdk/package.xml:  <license>Apache-2.0</license>
./kuka-external-control-sdk/kuka_external_control_sdk_examples/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_driver_interfaces/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_iiqka_eac_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_drivers/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_sunrise_fri_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/examples/iiqka_moveit_example/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_kss_rsi_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_drivers_core/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/fri_state_broadcaster/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/fri_configuration_controller/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/event_broadcaster/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/kuka_controllers/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/joint_group_impedance_controller/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/control_mode_handler/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_rsi_simulator/package.xml:  <license>Apache-2.0</license>
```
</details>

**Comment by sloretz** [comment]
> Package dependencies: kuka_drivers depends on kuka_external_control_sdk and kuka_robot_descriptions. Aside of these depencencies, all of them build on humble.
> 
> What is the process in this case? I would like to create a ROS2 release from all packages. Should I at first only include kuka_external_control_sdk in this PR, do the relesase and then add the other packages one by one?

This PR is a good first step. Doing one PR per repo is slightly easier to review. I think the next step after this is merged will be to `bloom-release` the repositories one at a time starting with kuka_external_control_sdk.

**Comment by Svastits** [comment]
Thanks @sloretz for the feedback :)

I have fixed the package names in [this PR](https://github.com/kroshu/kuka_drivers/pull/160)
In the kuka-external-control-sdk repo, I have a [top-level license file](https://github.com/kroshu/kuka-external-control-sdk/blob/master/LICENSE.txt), should I move it to be inside the `kuka_external_control_sdk` package, as that is the only package to be added to rosdistro?

**Comment by sloretz** [comment]
> In the kuka-external-control-sdk repo, I have a [top-level license file](https://github.com/kroshu/kuka-external-control-sdk/blob/master/LICENSE.txt), should I move it to be inside the kuka_external_control_sdk package, as that is the only package to be added to rosdistro?

No need to move it. Having a top level license file is fine, even if the repo only contains one ROS package.

**Review by sloretz — APPROVED** [review]
- [X] At least one of the following must be present
  - [X] Top level license file: 
  - [ ] Per package license files
- [X] License is [OSI-approved](https://opensource.org/licenses):
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>kuka_lbr_iiwa_moveit_config</name>
  <name>kuka_robot_descriptions</name>
  <name>kuka_kr_moveit_config</name>
  <name>kuka_mock_hardware_interface</name>
  <name>kuka_lbr_iisy_moveit_config</name>
  <name>kuka_fortec_support</name>
  <name>kuka_cybertech_support</name>
  <name>kuka_quantec_support</name>
  <name>kuka_agilus_support</name>
  <name>kuka_lbr_iiwa_support</name>
  <name>kuka_lbr_iisy_support</name>
  <name>kuka_iontec_support</name>
  <name>kuka_resources</name>
  <name>kuka_external_control_sdk</name>
  <name>kuka_external_control_sdk_examples</name>
  <name>kuka_driver_interfaces</name>
  <name>kuka_iiqka_eac_driver</name>
  <name>kuka_drivers</name>
  <name>kuka_sunrise_fri_driver</name>
  <name>iiqka_moveit_example</name>
  <name>kuka_kss_rsi_driver</name>
  <name>kuka_drivers_core</name>
  <name>fri_state_broadcaster</name>
  <name>fri_configuration_controller</name>
  <name>kuka_controllers</name>
  <name>kuka_control_mode_handler</name>
  <name>joint_group_impedance_controller</name>
  <name>kuka_event_broadcaster</name>
  <name>kuka_rsi_simulator</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
./kuka_robot_descriptions/kuka_lbr_iiwa_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_robot_descriptions/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_kr_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_mock_hardware_interface/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iisy_moveit_config/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_fortec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_cybertech_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_quantec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_agilus_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iiwa_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_lbr_iisy_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_iontec_support/package.xml:  <license>Apache-2.0</license>
./kuka_robot_descriptions/kuka_resources/package.xml:  <license>Apache-2.0</license>
./kuka-external-control-sdk/kuka_external_control_sdk/package.xml:  <license>Apache-2.0</license>
./kuka-external-control-sdk/kuka_external_control_sdk_examples/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_driver_interfaces/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_iiqka_eac_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_drivers/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_sunrise_fri_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/examples/iiqka_moveit_example/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_kss_rsi_driver/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_drivers_core/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/fri_state_broadcaster/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/fri_configuration_controller/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/kuka_controllers/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/kuka_control_mode_handler/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/joint_group_impedance_controller/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/controllers/kuka_event_broadcaster/package.xml:  <license>Apache-2.0</license>
./kuka_drivers/kuka_rsi_simulator/package.xml:  <license>Apache-2.0</license>
```
</details>

**Pull request merged**
