### PR TITLE
Added libqt5-websockets-dev

### PR DESCRIPTION
**Pull request by facontidavide**

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
can you add `dev-qt/qtwebsockets` for gentoo? https://packages.gentoo.org/packages/dev-qt/qtwebsockets

other links for the second reviewer:
https://packages.ubuntu.com/search?keywords=libqt5websockets5-dev
https://packages.debian.org/search?keywords=libqt5websockets5-dev
https://fedora.pkgs.org/31/fedora-updates-x86_64/qt5-qtwebsockets-5.13.2-1.fc31.x86_64.rpm.html
https://www.archlinux.org/packages/extra/x86_64/qt5-websockets/

**Comment by ivanpauno** [comment]
alpha order (see tests logs)

```
ERR: list out of alphabetical order line 3837.  'libqt5-websockets-dev' should come before 'libqt5multimedia5-plugins'
```

**Comment by facontidavide** [comment]
should be fixed now

**Comment by ivanpauno** [comment]
> 2020-10-13T14:19:08.1485933Z   ERR: trailing space line 3822

**Review by clalancette — APPROVED** [review]

**Pull request merged**
