### PR TITLE
Added xdot package to Kinetic distribution.yaml

### PR DESCRIPTION
**Pull request by yotabits**
v 2.0.1-0

### CODE REVIEW

**Comment by clalancette** [comment]
@yotabits So the "old" release of xdot in Indigo was released from https://github.com/jbohren/xdot-release.git (with the sources at https://github.com/jbohren/xdot.git).  How does this package relate to that one?

**Review by tfoote — CHANGES_REQUESTED** [review]
There's also an xdot system package that this looks like it might collide with: https://packages.ubuntu.com/xenial/xdot Maybe a rodep rule would be a better solution?

**Comment by yotabits** [comment]
Sorry I forget to make those basic checks, I was in hurry unfortunately...

**Comment by yotabits** [comment]
Sorry I forget to make those basic checks, I was in hurry unfortunately...

**Pull request closed without merging**
