### PR TITLE
clober: 1.0.4-2 in 'noetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by clobot-git**
Please add the following dependency to the rosdep database.

## Package name:

TODO

## Package Upstream Source:

TODO link to source repository

## Purpose of using this:

TODO Replace. This dependency is being used for this reason. This is why I think it's valuable to be added to the rosdep database. 

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - REQUIRED
- Ubuntu: https://packages.ubuntu.com/
   - REQUIRED
- Fedora: https://src.fedoraproject.org/browse/projects/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here: 

http://sourcecode_url

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
@clobot-git I'm a bit confused here. Why is the description that of a `rosdep` contribution? The commit name suggests this was released through `bloom`. Did some release automation go awry?

**Comment by clobot-git** [comment]
I didn't know that this description is `rosdep` contribution. I just tried to new release about my packages through `bloom`. When released through `bloom`, this description was generated automatically. Perhaps it was caused by `rosdep` error related to `clober_msgs` when I release using `bloom`.

`clober` pkg has a dependency to `clober_msgs`, but `clober_msgs` has not yet been released.

**Comment by hidmic** [comment]
> Perhaps it was caused by `rosdep` error related to `clober_msgs` when I release using bloom.

Well, I don't know if that caused the unusual PR description, but releasing a package with missing dependencies is not a good idea to begin with.

**Comment by clobot-git** [comment]
I understand. To solve this problem, I will release the `clober_msgs` package.
After that, I will release this `clober` package and open the new PR.

Thank you.

**Pull request closed without merging**
