### PR TITLE
ipython for bionic

### PR DESCRIPTION
**Pull request by floweisshardt**
adding ipython for bionic: https://packages.ubuntu.com/bionic/ipython

### CODE REVIEW

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
I think we can elide this to a plain `ubuntu: [ipython]` key and avoid specifying each distro. We wouldn't be able to do so if there were any currently supported distros that ipython is missing from or named differently.

**Review by tfoote — APPROVED** [review]
+1 for collapsing it, then lgtm

**Comment by floweisshardt** [comment]
collapsed all ubuntu entries as requested in https://github.com/ros/rosdistro/pull/21791/commits/3c2321fa7dd6fcab60225e29cd2b508471737079

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Thank you!

**Comment by floweisshardt** [comment]
anything else I should modify before merging?

**Pull request merged**
