### PR TITLE
Adding forte_rc_robot to documentation index for distro

### PR DESCRIPTION
**Pull request by aaraujo11**
Please, i'd like forte_rc_robot to be indexed and documented on ros.org.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The release repo is empty atm. You need to run bloom to populate it or remove the release version for now.

**Comment by aaraujo11** [comment]
Hi @dirk-thomas , can you please check if everthing is ok now, i have populate the release repo.

**Comment by dirk-thomas** [comment]
The release repo doesn't contain a version 1.0.1-0. You need to update the version number in this PR.

**Comment by dirk-thomas** [comment]
Please comment on the ticket after committing to the branch. Otherwise nobody gets an email notification.

Looks good now - merging...

**Comment by tfoote** [comment]
This repo does not have any debian branches/tags generated by bloom for the various ubuntu distros: https://github.com/ingeniarius-ltd/forte_rc_robot-release

It's causing the sourcedebs to all fail to checkout those branches. http://54.183.26.131:8080/job/Isrc_uT__forte_rc_robot__ubuntu_trusty__source/

**Pull request merged**
