### PR TITLE
add jade to eol distro list

### PR DESCRIPTION
**Pull request by mikaelarguedas**
to avoid doing it manually https://github.com/ros/rosdistro/pull/15886

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
Food for thoughts: I remember that this information is also stored by the roswiki, known by the ros_buildfarm somehow and likely other places. Would it make sense to consolidate this information in a single human-readable and machine-consumable file ? Maybe an amendment to the index file to define the status of a distro ?

**Comment by mikaelarguedas** [comment]
I'm going to merge this but feel free to comment here post-merge

**Comment by tfoote** [comment]
It would be good to have generally, but we do need to keep things like the wiki from loading remote resources pre-render so sometimes the caching/duplication is important.

**Comment by mikaelarguedas** [comment]
Thanks for the feedback, do you guys think it belongs in the index file ? or that we should specify this somewhere else ?
(slightly related we had the same interrogation when generating dockerfiles for all supported ros distributions and were wondering if it would make sense to have a way to know all active ROSDistros/OSDistros/Architectures supported without having to parse rosdistro + ros_buildfarm_config + custom logic for EOL ROS distros)

**Pull request merged**
