### PR TITLE
add arm g++ cross compiler

### PR DESCRIPTION
**Pull request by hakuturu583**
add arm64/armhf g++ cross compiler.
I want to make cross-compiler package for embeded computers.

### CODE REVIEW

**Comment by hakuturu583** [comment]
list of packages.

## g++-cross-aarch64  
### ubuntu : g++-aarch64-linux-gnu
https://launchpad.net/ubuntu/trusty/amd64/g++-aarch64-linux-gnu/4:4.8.2-1
### debian : g++-aarch64-linux-gnu
https://packages.debian.org/stretch/devel/g++-aarch64-linux-gnu

## g++-cross-armhf
### ubuntu : g++-arm-linux-gnueabihf
https://packages.ubuntu.com/cosmic/g++-arm-linux-gnueabihf
### debian : g++-arm-linux-gnueabihf
https://packages.debian.org/stretch/g++-arm-linux-gnueabihf

**Review by tfoote — CHANGES_REQUESTED** [review]
Adding these keys is fine. But there's a few updates needed. I've commented inline below.

Ubuntu package for reference https://packages.ubuntu.com/en/bionic/g++-aarch64-linux-gnu instead of launchpad link

**Comment by tfoote** [comment]
@hakuturu583  Is this something that you'd still like to see. A few fixups and this would be good to land, otherwise we'll close this for lack of follow up soon.

**Comment by tfoote** [comment]
Closing due to no follow up. This can be reopened if someone wants to circle back.

**Pull request closed without merging**
