### PR TITLE
Add python progressbar entry

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Not in alphabetical order.

**Comment by vrabaud** [comment]
osx needs to be before ubuntu (very unexplicit erro from Travis btw @dirk-thomas )

**Comment by wkentaro** [comment]
I see. I changed it.

**Comment by vrabaud** [comment]
thx !

**Comment by dirk-thomas** [comment]
I have updated the unit test to explicitly mention "list out of alphabetical order": 4cb872cdfcc38d59cab291db40c274c8c33d6699

**Comment by wkentaro** [comment]
thanks.

2015年4月27日月曜日、Dirk Thomas<notifications@github.com>さんは書きました:

> I have updated the unit test to explicitly mention "list out of
> alphabetical order": 4cb872c
> <https://github.com/ros/rosdistro/commit/4cb872cdfcc38d59cab291db40c274c8c33d6699>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros/rosdistro/pull/8116#issuecomment-96409817>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Pull request merged**
