### PR TITLE
Added pocketsphinx to base.yaml

### PR DESCRIPTION
**Pull request by beatrizleon**
It is available after xenial:
http://packages.ubuntu.com/search?keywords=pocketsphinx+&searchon=sourcenames

https://admin.fedoraproject.org/pkgdb/package/rpms/pocketsphinx/

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The link you posted lists it as being available for Precise and Trusty too. And the non-LTS distros in between likely also contain the package.

**Comment by beatrizleon** [comment]
It didn't exits as such `pocketsphinx`. I get `Unable to locate package pocketsphinx` in trusty. I think it was needed to install it from sources:
https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L8516
which is no longer available in kinetic/distribution.yaml

**Comment by dirk-thomas** [comment]
Which part of the package are you interested in? The shared libraries? They are available as http://packages.ubuntu.com/trusty/libsphinxbase1

**Comment by beatrizleon** [comment]
We have a package on xenial-kinetic that `<build_depend>pocketsphinx</build_depend>` and rosdep is not able to find it: `Cannot locate rosdep definition for [pocketsphinx]`

**Comment by beatrizleon** [comment]
Yes, exactly. That is why we are doing the PR

**Comment by dirk-thomas** [comment]
Ok, but you won't be able to release you package afterwards for Kinetic. Kinetic targets Xenial as well as Wily and there is no mapping for Wily. Therefore I suggest to add mapping for additional Ubuntu distros. The key can map to a different package name for older Ubuntu distros if necessary.

**Comment by beatrizleon** [comment]
Like this?

**Review by dirk-thomas — APPROVED** [review]
LGTM

**Comment by beatrizleon** [comment]
Thanks!

**Comment by k-okada** [comment]
@beatrizleon , @dirk-thomas we used package with `  <run_depend>pocketsphinx</run_depend>
` https://github.com/tork-a/ros_seminar/blob/master/ros_seminar_navigation/my_navigation/package.xml#L20, which is inted to install `ros-indigo-pocketsphinx`, but since we add `pocketsphinx` entry to base.yaml, we can not install `pocketsphinx` with `rosdep install` any more

can we rename this  to `libsphinxbase` ?

**Comment by tfoote** [comment]
@k-okada please submit a PR to do that. They shouldn't have a conflicting name if they have different content.

**Pull request merged**
