### PR TITLE
remove ros2_ouster_drivers entry from rolling in preparation for replacing with the official ouster_ros package.

### PR DESCRIPTION
**Pull request by Samahu**
Please remove the following dependency to the rosdep database.

## Package name:

ros2_ouster_drivers

## Package Upstream Source:

https://github.com/ros-drivers/ros2_ouster_drivers

## Purpose of using this:

Remove **ros2_ouster_drivers** entry from **rolling** in preparation for replacing with the official **ouster_ros** packages.

Distro packaging links:

## Comments to reviewers
I will have a followup pull request to add an entry to the rolling distribution list once this has been removed since bloom wouldn't allow me to create a pull request due to package name conflict for `ouster_msgs`.

I have already prepared the rolling release: https://github.com/ros2-gbp/ouster-ros-release

Should I manually add **ouster-ros** entry in this pull request? Let me know please...

### CODE REVIEW

**Comment by Samahu** [comment]
The followup PR would be same as https://github.com/ros/rosdistro/pull/38390 but targeting **rolling**

**Comment by emersonknapp** [comment]
I'm not sure what the ramifications might be of moving a single package from one release entry to another... maybe it'll be fine?   @nuclearsandwich I could use some more expert input on what might happen here.

**Comment by Samahu** [comment]
@emersonknapp or @nuclearsandwich how could we move this forward?

**Comment by clalancette** [comment]
I think removing the older package first will be the best; then you can do the normal `bloom-release` process.  Before we do that, though, this needs to come out of draft and I would like explicit confirmation from @SteveMacenski that this is the right path forward.

**Comment by Samahu** [comment]
I did put it in Draft mode for now as we are trying to make a decision between converging the official `ouster-ros` with `ros2_ouster_driver` package and move it into **ros-drivers** org, or keep the two packages totally separate (i.e. `ouster-ros` to totally replace `ros2_ouster_driver` entry within `rosdistro` starting with rolling/iron) . and yes I am in talks with @SteveMacenski about this move. We should reach the decision within this week.

**Comment by SteveMacenski** [comment]
> I'm not sure what the ramifications might be of moving a single package from one release entry to another... maybe it'll be fine? 

At the very least, breaking all existing users since those messages I assume aren't exactly identical. 

> this needs to come out of draft and I would like explicit confirmation from @SteveMacenski that this is the right path forward.

I don't agree with this action until the comment below is resolved. I don't know why @Samahu is rushing this process, we should pause and not make any more moves until you have clarity from your management.  

> we are trying to make a decision between converging the official ouster-ros with ros2_ouster_driver package and move it into ros-drivers org, or keep the two packages totally separate

**Comment by Samahu** [comment]
@SteveMacenski I don't think I am rushing this process, I created this MR over a week ago when I found about the name conflict with 'ouster-msgs' and that bloom-release blocked it. I put this MR in Draft mode on Friday in order to take time to research the subject a bit more and discuss with management about which path they would prefer. Although I play a role in the decision but it is definitely not entirely up to me and I need to act in the interest of Ouster and what suits the company better short and long term.

With regard to message breaking changing, this would only affect the rolling distro and as far as I know developers on rolling do expect some breaking changes to happen while on this distro.

**Comment by sloretz** [comment]
Holding for an upcoming [Rolling sync](https://discourse.ros.org/t/preparing-for-rolling-sync-2023-09-27/33770)

**Comment by Samahu** [comment]
@SteveMacenski We have discussed this internally and for the time being **Ouster** would like to keep **ouster-ros** driver fully under **ouster-lidar** organization.

**Comment by Samahu** [comment]
@SteveMacenski still waiting for your approve.. why is this taking so long?

**Comment by SteveMacenski** [comment]
OK, in that case, you will need to rename your package. The following are already used names and I will likely re-release under them for Iron since we're not merging into the `ros-drivers` repository. If its going to continue to live on, it should be available for users under the binary format as it has been historically. Think of them now as community-supported drivers. This is not the direction I wanted to go, I wanted to remove them and replace with your company-supported version, but if they're just hanging around, then status quo should continue for those that rely on it.

So no, I think this PR should be closed and I can sync up with an Iron release of these packages after ROSCon

```
      - ouster_msgs
      - ros2_ouster
```

**Comment by Samahu** [comment]
> OK, in that case, you will need to rename your package. The following are already used names and I will likely re-release under them for Iron since we're not merging into the `ros-drivers` repository. If its going to continue to live on, it should be available for users under the binary format as it has been historically. Think of them now as community-supported drivers. This is not the direction I wanted to go, I wanted to remove them and replace with your company-supported version, but if they're just hanging around, then status quo should continue for those that rely on it.
> 
> So no, I think this PR should be closed and I can sync up with an Iron release of these packages after ROSCon
> 
> ```
>       - ouster_msgs
>       - ros2_ouster
> ```

I don't know where to start, I am really dismayed by your response. What kind of direction you wanted? I mean previously you asked me to clarify the decision if Ouster wants to merge the source code with your driver? I had discussed this thoroughly with the management here at Ouster, the decision was clearly irrevocably to not merge the official driver with _ros2_ouster_ros_ repo for an array of reasons. One of the reasons we decided to not merge with ros2_ouster_ros repo is to avoid the the headache that you mentioned going forward and have one source of reference for the driver that our users can refer. We don't prevent anyone from re-using whole or part of our code to create their own implementation but at the same time we'd like to retain the official implementation fully under ouster-lidar organization. At the request of many of our users we worked on providing a binary release of the official driver through ROS distribution, which has been done for Iron release and the same should happen for ros-rolling. 

Now that the company has clarified its position you decided to regress on your part and hold off approving this PR? Why did you ask me to check with the management about our decision when you had no intention of supporting the decision of the company?

The rolling distro is for development, users who are consuming your implementation on galactic, foxy, humble wouldn't be affected by this change. Users who wish to retain access to the binaries published to these previous distros, I am not planning to submit a PR to change them.

In the last e-mail you sent me you mentioned that you have been supporting Ouster the entire time but now I am reading your response and I am not sure how this fits? How does disallowing our company from providing binary distribution of the official driver through ROS but at the same time allowing others to take over and publish a binary distribution for the driver with a package name that includes the name of the company, how does help serve Ouster users and how does this not going to continue be a source of headache for us and for our users?

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/who-has-the-first-right-to-publish-binary-package-using-the-companys-name/34200/4

**Comment by peci1** [comment]
The discourse thread led me here. I see it is a pretty complicated issue to resolve. What about naming the manufacturer driver packages `ouster_official_*`? That would resolve all naming conflicts and users would right away know they are using the official driver.

**Comment by Samahu** [comment]
> But the depreciation of this work was under the explicit agreement that your new work would be replacing this driver. Since that is no longer happening, this software is going to remain because its not being overwritten anymore.

What is this explicit agreement exactly? In a way this PR is in fact replacing the _ros2_ouster_driver_.. but I don't remember personally that I agreed (or Ouster) to having to move or merge **ouster-ros** code into _ros2_ouster_driver_. It is very problematic on multiple fronts for us to do so.

**Comment by Samahu** [comment]
> s `ouster_official_*`? That would resolve all naming conflicts and users would right away know they are using the official driver.

Thanks Martin but is this a common pattern? I searched ros index and didn't find a single package that uses the word  _official_.. into the name. **ouster_msgs** seems the the most fitting given that Ouster originally (before I joined them) named the main package as **ouster_ros**.

Still reviewing the community opinion about this and I am hoping we can get past this soon.

**Comment by gbiggs** [comment]
My understanding of the problem is that it is only the `ouster_msgs` package that conflicts. I'd like to encourage both sides to find a way to use the same messages for their respective drivers. This would improve the user experience by allowing the user to choose which driver implementation meets their needs without needing to make changes to the rest of their system.

**Comment by iliabaranov** [comment]
> I suppose one option is to sunset the existing driver, but I will need to put out a call for that and wait for responses from users that the new driver is sufficient for their needs before I pull the rug from under them. That may take several months but I can start the inquiry after ROSCon.

Yes please! It's likely folks have the older driver baked into things, suddenly pulling it would impact folks, including us.

**Comment by Samahu** [comment]
Thanks all for your valuable feedback, sorry for being slow on this matter but I have on a PTO this past time. I am waiting for a confirmation on the path the company wants to take before moving forward but we should conclude this PR soon.

**Comment by Samahu** [comment]
After discussing this matter with Ouster management we decided to rename "ouster_msgs" package part of the official driver to "ouster_sensor_msgs" to avoid this conflict. As such I am closing this PR and will open another one soon after the name change is applied.

**Pull request closed without merging**
