### PR TITLE
add libsimde-dev into base yaml

### PR DESCRIPTION
**Pull request by wep21**
Please add the following dependency to the rosdep database.

## Package name:

simde

## Package Upstream Source:

https://github.com/simd-everywhere/simde

## Purpose of using this:

libsimde-dev is used for https://github.com/Simple-Robotics/proxsuite

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/sid/libsimde-dev
- Ubuntu: https://packages.ubuntu.com/
   - https://launchpad.net/ubuntu/+source/simde
- Fedora: https://packages.fedoraproject.org/
  - IF AVAILABLE
- Arch: https://www.archlinux.org/packages/
  - IF AVAILABLE
- Gentoo: https://packages.gentoo.org/
  - IF AVAILABLE
- macOS: https://formulae.brew.sh/
  - IF AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - IF AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL
- openSUSE: https://software.opensuse.org/package/
  - IF AVAILABLE

# Please Add This Package to be indexed in the rosdistro.

ROSDISTRO NAME

# The source is here:

http://sourcecode_url

# Checks
 - [ ] All packages have a declared license in the package.xml
 - [ ] This repository has a LICENSE file
 - [ ] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by jcarpent** [comment]
@wep21 Thanks for adding simde to ROS. Why did you choose `libsimde-dev` and not simply `simde`?

**Comment by wep21** [comment]
@jcarpent I don't have any reason to choose `libsimde-dev`. If `simde` is preferable, I will change the name of key.

**Comment by wep21** [comment]
I changed key name to `simde`.

**Review by emersonknapp — APPROVED** [review]

**Comment by jcarpent** [comment]
Is there any timeline for merging this PR?

**Comment by emersonknapp** [comment]
We need two approvers for new rosdistro keys. @mjcarroll is also looking this week

**Review by mjcarroll — APPROVED** [review]

**Comment by wxmerkt** [comment]
Since this package is not available on Focal, would it be an option to vendor it for those distributions?

**Comment by emersonknapp** [comment]
You could always vendor any package in your own workspace - and if you see a wider need for it then there isn't anything specifically blocking you from bloom-releasing that vendor-wrap package. I feel like a much better way would be to try and get the package into Focal ubuntu repos, but I understand that you don't have complete control over that

**Pull request merged**
