### PR TITLE
mycroft_ros index

### PR DESCRIPTION
**Pull request by injones**

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
@injones There's no license specified in the package.xml; can you add in `Apache 2` there?  Thanks.

**Comment by injones** [comment]
@clalancette Apologies, I have since updated the package.xml as such

**Review by clalancette — APPROVED** [review]
Thanks for the update, looks good now.

**Comment by clalancette** [comment]
Holding for kinetic [sync](https://discourse.ros.org/t/preparing-kinetic-sync-2019-07-08/9818)

**Pull request merged**
