### PR TITLE
add rosdep key python-qt5-bindings

### PR DESCRIPTION
**Pull request by dirk-thomas**
Waiting for availability of a custom `PySide2` package.

### CODE REVIEW

**Comment by wjwwood** [comment]
The keys in there look good to me.

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
We need the following packages as well as their dependencies (as added in the second commit):
* `python-pyside2`
* `libpyside2-dev`
* `shiboken2`
* `libshiboken2-dev`

We can get prerelease packages from the following PPA: https://code.launchpad.net/~thopiekar/+archive/ubuntu/pyside-git

@tfoote Can you please import the necessary packages into our repos. I assume we will just not add the PySide2 dependencies for other platforms then?

**Comment by tfoote** [comment]
@dirk-thomas what are the packages we need. Can you propose a config file to be added here https://github.com/ros-infrastructure/reprepro-updater/tree/master/config with the appropriate regex?

For the other platforms do we gracefully degrade if pyside is not installed?

**Comment by dirk-thomas** [comment]
We need the four packages listed in my previous comment. I don't know what you commonly use to determine all recursive dependencies of such packages or if that is a manual process?

**Comment by tfoote** [comment]
Please submit a PR with your best guess for the config and with the justification for why to add them. The git history on that repos is currently our best database of what's been imported and why.

Usually the recursive dependencies are available in the upstream repos and we don't need to explicitly import them. That would only happen if that PPA depended on another PPA.

**Comment by dirk-thomas** [comment]
ros-infrastructure/reprepro-updater#28

**Comment by dirk-thomas** [comment]
The packages have been imported from the PPA. I also added Wily and Xenial entries for two more Python packages. If there are no further comments I will go ahead and merge this.

**Pull request merged**
