### PR TITLE
Do not run test_commits for MoveIt!

### PR DESCRIPTION
**Pull request by davetcoleman**

### CODE REVIEW

**Comment by sloretz** [comment]
Output from failing test, looks like it wants alphabetical order?
```
If this fails you can run 'rosdistro_reformat index.yaml' to help cleanup.
'rosdistro_reformat' shows the diff between the current files and their expected formatting.
--- file:///home/travis/build/ros/rosdistro/indigo/distribution.yaml
+++ loaded-and-saved
@@ -7485,2 +7485,3 @@
     source:
+      test_commits: false
       type: git
@@ -7488,3 +7489,2 @@
       version: indigo-devel
-      test_commits: false
     status: developed
--- file:///home/travis/build/ros/rosdistro/kinetic/distribution.yaml
+++ loaded-and-saved
@@ -6012,2 +6012,3 @@
     source:
+      test_commits: false
       type: git
@@ -6015,3 +6016,2 @@
       version: kinetic-devel
-      test_commits: false
     status: developed
--- file:///home/travis/build/ros/rosdistro/lunar/distribution.yaml
+++ loaded-and-saved
@@ -2276,2 +2276,3 @@
     source:
+      test_commits: false
       type: git
@@ -2279,3 +2280,2 @@
       version: kinetic-devel
-      test_commits: false
     status: developed
--- file:///home/travis/build/ros/rosdistro/melodic/distribution.yaml
+++ loaded-and-saved
@@ -2291,2 +2291,3 @@
     source:
+      test_commits: false
       type: git
@@ -2294,3 +2295,2 @@
       version: melodic-devel
-      test_commits: false
     status: developed
```

**Comment by davetcoleman** [comment]
Done.

Also heads up @130s

**Review by rhaschke — APPROVED** [review]

**Review by sloretz — APPROVED** [review]

**Comment by tfoote** [comment]
We just upgraded the hardware we provision on the buildfarm. Can we hold off a few days to see if it resolves things? I've seen Indigo Kinetic and Lunar pass with the new hardware. 

http://build.ros.org/view/Idev/job/Idev__moveit__ubuntu_trusty_amd64/
http://build.ros.org/job/Kdev__moveit__ubuntu_xenial_amd64/
http://build.ros.org/view/Ldev/job/Ldev__moveit__ubuntu_xenial_amd64/

Melodic is in process. It crashed a few times due to a new type of job that was running concurrent job running the machine OOM

http://build.ros.org/job/Mdev__moveit__ubuntu_bionic_amd64/

**Comment by rhaschke** [comment]
I would be definitely happy to keep the full dev jobs, as they typically reveal missing package dependencies, which Travis doesn't spot, because we manually pull-in everything...

**Comment by tfoote** [comment]
All recent tests have passed so I'm going to close this and keep the tests enabled.

**Pull request closed without merging**
