### PR TITLE
Add Qt 5 Concurrent module

### PR DESCRIPTION
**Pull request by pjreed**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@pjreed can you please provide the links of these packages for the platforms added in this PR ? Thanks

**Review by wjwwood — APPROVED** [review]
- Debian:
  - https://packages.debian.org/jessie/libs/libqt5concurrent5
- Ubuntu:
  - https://packages.ubuntu.com/trusty/libqt5concurrent5
  - https://packages.ubuntu.com/xenial/libqt5concurrent5
  - https://packages.ubuntu.com/zesty/libqt5concurrent5
  - https://packages.ubuntu.com/artful/libqt5concurrent5

Those are all the currently supported (and not EOL) platforms I think.

**Comment by mikaelarguedas** [comment]
For debian looks like stretch and buster have it as well:
https://packages.debian.org/stretch/libqt5concurrent5
https://packages.debian.org/buster/libqt5concurrent5

I didnt look for the other platforms though

**Comment by pjreed** [comment]
Sure.  Other than the Debian & Ubuntu packages already listed:

Arch: https://www.archlinux.org/packages/extra/x86_64/qt5-base/
Fedora: https://apps.fedoraproject.org/packages/qt5-qtbase
Gentoo: https://packages.gentoo.org/packages/dev-qt/qtconcurrent
openSUSE: https://software.opensuse.org/package/libQt5Concurrent5
Slackware: https://slackbuilds.org/repository/14.2/libraries/qt5/

**Review by mikaelarguedas — APPROVED** [review]
thanks @pjreed for the links, lgtm

**Pull request merged**
