### PR TITLE
Added python-aiohttp and python-aiohttp-cors to the rosdep database

### PR DESCRIPTION
**Pull request by stevegolton**
Please add the following dependencies to the rosdep database.

## Package name:
- python3-aiohttp
- python3-aiohttp-cors

## Package Upstream Source:
- https://github.com/aio-libs/aiohttp
- https://github.com/aio-libs/aiohttp-cors

## Purpose of using this:
aiohttp is an increasingly popular library for building HTTP clients and servers using Python3's asyncio library. The aiohttp-cors middleware is useful for development as it means the web page and HTTP server don't have to be hosted from the same origin in order for browsers to load resources, which is a common state of affairs when developing robots!

Distro packaging links:

## Links to Distribution Packages

- Debian: https://packages.debian.org/
  - https://packages.debian.org/buster/python3-aiohttp
  - https://packages.debian.org/buster/python3-aiohttp-cors
- Ubuntu: https://packages.ubuntu.com/
  - https://packages.ubuntu.com/focal/python3-aiohttp
  - https://packages.ubuntu.com/focal/python3-aiohttp-cors
- Fedora: https://src.fedoraproject.org/browse/projects/
  - https://src.fedoraproject.org/rpms/python-aiohttp
  - https://src.fedoraproject.org/rpms/python-aiohttp-cors
- Arch: https://www.archlinux.org/packages/
  - https://archlinux.org/packages/community/x86_64/python-aiohttp/
  - https://archlinux.org/packages/community/any/python-aiohttp-cors/
- Gentoo: https://packages.gentoo.org/
  - https://packages.gentoo.org/packages/dev-python/aiohttp
  - https://packages.gentoo.org/packages/dev-python/aiohttp-cors
- macOS: https://formulae.brew.sh/
  - NOT AVAILABLE
- Alpine: https://pkgs.alpinelinux.org/packages
  - NOT AVAILABLE
- NixOS/nixpkgs: https://search.nixos.org/packages
  - OPTIONAL

### CODE REVIEW

**Review by hidmic — APPROVED** [review]

**Comment by clalancette** [comment]
It looks like this is going to need some fixes based on our automated checks.  Once those are fixed, I'm happy to approve.

**Comment by stevegolton** [comment]
@clalancette Thanks for approving! I think the only issue was that I didn't have the distributions in alphabetical order but that should be in order now.

**Comment by clalancette** [comment]
> @hidmic @clalancette Thanks for approving! I think the only issue was that I didn't have the distributions in alphabetical order but that should be in order now.

So it looks like it is more than that; if you flip over to the "Files Changed" tab in GitHub, our automated tests left some comments about what the problems might be.

**Comment by stevegolton** [comment]
Looks like stretch doesn't have the `aiohttp-cors` package. Apologies. I've figured out how to run the nosetests on my local machine now so the latest commit should be good to go.

**Comment by stevegolton** [comment]
> > @hidmic @clalancette Thanks for approving! I think the only issue was that I didn't have the distributions in alphabetical order but that should be in order now.
> 
> So it looks like it is more than that; if you flip over to the "Files Changed" tab in GitHub, our automated tests left some comments about what the problems might be.

Sorry, I just saw this. I think the error should be addressed, but let me fix the warnings too.

**Comment by stevegolton** [comment]
@clalancette I think we should be good to go now!

**Review by clalancette — APPROVED** [review]

**Pull request merged**
