### PR TITLE
Add ds4_driver:0.1.0 to 'kinetic/distribution.yaml'

### PR DESCRIPTION
**Pull request by naoki-mizuno**
- Repository: https://github.com/naoki-mizuno/ds4_ros
- ROS Wiki: http://wiki.ros.org/ds4_ros

### CODE REVIEW

**Review by tfoote — CHANGES_REQUESTED** [review]
Please see the naming rules for packages in [REP 144](https://www.ros.org/reps/rep-0144.html) . In particular we try not to have ros in the ROS package name as it's redundant with being a ros package.

**Comment by naoki-mizuno** [comment]
@tfoote I renamed the package name. If you want the branch name also renamed I'll close this PR and open up another one.

**Comment by tfoote** [comment]
Branch names are up to your development preference. Thanks for renaming it quickly.

**Review by tfoote — APPROVED** [review]

**Comment by naoki-mizuno** [comment]
Thank you for merging!

**Pull request merged**
