### PR TITLE
add baidu speech to document index for disro

### PR DESCRIPTION
**Pull request by DinnerHowe**
i'd like to add my baidu_speech and rplidar_driver_in_python repositories into index and documented on http://wiki.ros.org

### CODE REVIEW

**Comment by vrabaud** [comment]
hydro is eol-ed, you cannot modify the file.

**Comment by vrabaud** [comment]
your release repos are not valid, they lack branches (which contain a package.xml)

**Comment by tfoote** [comment]
Please see the tutorials for bloom about how to release packages: http://wiki.ros.org/bloom There's a specific tutorial for [releasing a package for the first time](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) that should be helpful. Bloom can automatically open the pull-request for you via the github api.

**Comment by DinnerHowe** [comment]
great thx for @vrabaud vrabaud,  i deleted my package from hydro distributuion, and added branches for both.
and thank you very much @tfoote as well, i'm studying this tutorial now. 
you've both been a great help.

**Comment by dirk-thomas** [comment]
Please close obsolete obsolete PRs yourself in the future.

**Pull request closed without merging**
