### PR TITLE
h4r_thermapp_camera: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by cyborg-x1**
Increasing version of package(s) in repository `h4r_thermapp_camera` to `0.0.1-0`:
- upstream repository: https://github.com/Hacks4ROS/h4r_thermapp_camera.git
- release repository: https://github.com/Hacks4ROS-release/h4r_thermapp_camera.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.20`
- previous version for package: `null`
## h4r_thermapp_camera

```
* fix License information
* add install to CMakeLists
* update ReadMe with install information
* add udev file
* change thermapp.launch
* Merge branch 'develop'
* fix submodule for ThermAppCam project
* Initial commit
* add author tag
* fix dynamic reconfigure
* change #define for header file
* change package name to h4r
  add default values to dynamic_reconfigure
  tidy up package.xml
* integrate reading camera
* rename namespace,
  add first functions
  make it compile with ThermAppCam files
* delete old thermapp code
* delete class for own code
* add new thermapp code to library and to node in CMakeLists
* create include for catkin for not breaking up with origin of the thermapp code
* update ThermAppCam
* add ThermAppCam from PidBip (Alexander G)
* last of my own tries to get protocol working
* removed prints
* stable image but slow
* fix filename of perspective in launchfile
* reformat launchfile code
* add current code to main node to have easier testing
* add current code to bulk class
* create rqt perspective with image view and launchfile
* add Code from test application
* add function for opening usb device
  add function for closing
  add function for requesting image (unfinished)
* add libusb to CMakeLists
* add class for usb bulk transfer
* add thermapp_camera_node
  -add boost thread bind
  -add dynamic reconfigure
  -add CameraPublisher
  -add cv bridge
* Add maintainer and description to package.xml
* initial commit, create ros package
* initial commit, create ros package
* Contributors: Christian Holl
```

### CODE REVIEW

**Comment by vrabaud** [comment]
@tfoote , the error seems to come from the version (though it's there). The REP says it should work if it's a tag though.

**Comment by cyborg-x1** [comment]
Maybe it expects version or something infront of the tagname, currently the tag name is just the version number "0.0.1"

**Comment by tfoote** [comment]
It's not valid to have a tag for the version of the source checkout. It needs to be a branch, as we're going to run continuous integration. (this is a work around for https://issues.jenkins-ci.org/browse/JENKINS-23299 )

**Comment by cyborg-x1** [comment]
I added the branch 0.0.1

**Comment by vrabaud** [comment]
@tfoote , http://www.ros.org/reps/rep-0141.html#distribution-file states that: "version: For git and hg this is the tag, branch or hash to be checked out. " Bug in the REP then ?

**Comment by tfoote** [comment]
The upstream bug is marked as fixed. Hopefully once we deploy the new buildfarm we can support tags again.

**Comment by cyborg-x1** [comment]
@tfoote  Ehm, just one not the branch 0.0.1 created a problem with catkin_generate_changelog.

catkin_generate_changelog
Found packages: h4r_thermapp_camera
Querying all tags and commit information...
ERROR: Could not fetch commit message:
fatal: Invalid object name 'warning'.

deleting the branch locally fixed this problem

**Comment by dirk-thomas** [comment]
You should not name your branch and tag the same since `checkout 0.0.1` become ambiguous.

**Pull request merged**
