### PR TITLE
Added libgeotiff to Base file for Ubuntu

### PR DESCRIPTION
**Pull request by Axel13fr**
Added libgeotiff for ubuntu

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Can you please rename the key to have the `-dev` suffix as the runtime version is also available (libgeotiff2)?
Please add the other platforms as well:
Debian: https://packages.debian.org/jessie/libgeotiff-dev
Fedora: https://koji.fedoraproject.org/koji/packageinfo?packageID=4815
Gentoo: https://packages.gentoo.org/packages/sci-libs/libgeotiff
Ubuntu: https://packages.ubuntu.com/trusty/libgeotiff-dev

**Comment by Axel13fr** [comment]
Sure, done. I added as well Arch. I wasn't able to run/test it on each distrib though, I only used the package infos for platforms other than Ubuntu.

**Comment by mikaelarguedas** [comment]
Thanks for the quick fix.
For gentoo you will need to add the category as well: `[sci-libs/libgeotiff]`

Link for book keeping:
Arch: https://www.archlinux.org/packages/community/x86_64/libgeotiff/

**Review by mikaelarguedas — APPROVED** [review]
lgtm, thanks @Axel13fr

**Pull request merged**
