### PR TITLE
Add python-rx-pip package to python.yaml

### PR DESCRIPTION
**Pull request by jorgenfb**
Provide RxPy as a pip package to ROS. This package provides reactive extensions to python. (RxPy)[https://github.com/ReactiveX/RxPY] is _a library for composing asynchronous and event-based programs using observable collections and LINQ-style query operators in Python_.

### CODE REVIEW

**Comment by tfoote** [comment]
This looks reasonable. It's failing CI because the keys are out of alphabetical order. And note that you will not be able to add dependencies on this from a released package because pip is not a native dependency for the package managers on any system.

**Comment by tfoote** [comment]
@jorgenfb do you want to update this to pass CI so we can accept it?

**Comment by jorgenfb** [comment]
Updated! Thank you!

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
