### PR TITLE
kinematics_interface: 0.0.1-1 in 'humble/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by bmagyar**
Increasing version of package(s) in repository `kinematics_interface` to `0.0.1-1`:

- upstream repository: https://github.com/ros-controls/kinematics_interface.git
- release repository: https://github.com/ros-controls/kinematics_interface-release.git
- distro file: `humble/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

## kinematics_interface

```
* Make formatting of comments unified and nice. (#11 <https://github.com/ros-controls/kinematics_interface/issues/11>)
* Enable interface to use Eigen per default (#6 <https://github.com/ros-controls/kinematics_interface/issues/6>)
* Add CI setup to the repository. (#8 <https://github.com/ros-controls/kinematics_interface/issues/8>)
* Update CMakeFiles, correct deps and formatting. (#10 <https://github.com/ros-controls/kinematics_interface/issues/10>)
* add pre-commit to repo (#7 <https://github.com/ros-controls/kinematics_interface/issues/7>)
* Fix more indentations and alphabetize
* Update dependencies and maintainers
* Kinematics interface with KDL implementation
* change directory name and use header only interface
* changed plugin name to kinematics_interface_kdl/KDLKinematics
* add calculate_jacobian as new interface method
* added argument to specify which link the Jacobian is calculated with respect to
* made interface stateless, changed method name, fixed small bugs
* updated README and cleaned up code
* added KDL plugin for kinematics interface
* Contributors: Paul Gesel, Andy Zelenak, Bence Magyar, Denis Štogl
```

## kinematics_interface_kdl

```
* Enable interface to use Eigen per default (#6 <https://github.com/ros-controls/kinematics_interface/issues/6>)
* Add CI setup to the repository. (#8 <https://github.com/ros-controls/kinematics_interface/issues/8>)
* Remove duplicate of Eigen dependency.
* Update CMakeFiles, correct deps and formatting. (#10 <https://github.com/ros-controls/kinematics_interface/issues/10>)
* add pre-commit to repo (#7 <https://github.com/ros-controls/kinematics_interface/issues/7>)
  add pre-commit
* Fix failing KDL test (#5 <https://github.com/ros-controls/kinematics_interface/issues/5>)
  * add verification for all inputs
  * add underscore to end_effector
  * add test to ensure inverse then forward calculation is approximately unit
* Fix more indentations and alphabetize
* Update dependencies and maintainers
* Kinematics interface with KDL implementation
* change directory name and use header only interface
* Contributors: Paul Gesel, Andy Zelenak, Bence Magyar, Denis Štogl
```

### CODE REVIEW

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
Before we merge this release (and the corresponding one for Rolling) let's move the release repository into ros2-gbp.

Does adding it to [the control](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/control.tf) team make sense or should we add a new team?

**Comment by audrow** [comment]
@bmagyar, also, would you add a license file to the repository?

**Comment by bmagyar** [comment]
@nuclearsandwich yes it'd be great. I added you to the release repo as admin, you can transfer it over any time. Also... for future I'd love to be able to add things to the control group over at ros2-gbp. Is it possible to give me rights to do that without being an admin for the whole of ros2-gbp?

**Comment by nuclearsandwich** [comment]
> for future I'd love to be able to add things to the control group over at ros2-gbp. Is it possible to give me rights to do that without being an admin for the whole of ros2-gbp?

We have the [ros2-gbp-github-org](https://github.com/ros2-gbp/ros2-gbp-github-org) repository for managing that entire organization. Adding things to the control team via PR should be fairly straightforward although someone from the core team will still need to review and deploy the proposed changes. We generally prefer not to transfer repositories and instead to either create new release repositories for packages that have never been released or mirror existing repositories (which we recommend archiving so that they are not pushed to inadvertently) to the ros2-gbp org. Redirects for repositories are not always guaranteed and can later become a security issue so we prefer not to rely on them.

**Pull request closed without merging**
