### PR TITLE
Add rosbag2_to_video to rolling index

### PR DESCRIPTION
**Pull request by bjsowa**
# Please Add This Package to be indexed in the rosdistro.

rosbag2_to_video

# The source is here:

https://github.com/fictionlab/rosbag2_to_video

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): https://opensource.org/license/apache-2-0
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/fictionlab/rosbag2_to_video, but this is a fork of the upstream
- [x] Source repository contains ROS packages
- [x] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

I have two issues that prevent me from approving this:
1.  The version number is 0.0.0, which, while technically allowed, isn't great.  I'd like to see that bumped to some number that isn't 0.
2. We've only given the real upstream 2 weeks to respond to a request for release.  I'll suggest we wait a bit longer before deciding to make the fork official.

**Comment by bjsowa** [comment]
> 1. The version number is 0.0.0, which, while technically allowed, isn't great.  I'd like to see that bumped to some number that isn't 0.

Fixed

> 2. We've only given the real upstream 2 weeks to respond to a request for release.  I'll suggest we wait a bit longer before deciding to make the fork official.

What would be the appropriate time to consider the fork official?

**Comment by bjsowa** [comment]
bump

**Comment by bjsowa** [comment]
@clalancette Could you reconsider it now?

**Comment by bjsowa** [comment]
@clalancette friendly ping

**Comment by methylDragon** [comment]
fyi @ivanpauno

**Review by Yadunund — APPROVED** [review]
Sufficient time has elapsed waiting for the original maintainer to respond so we are good to make this fork official.

**Pull request merged**
