### PR TITLE
Add triangle key

### PR DESCRIPTION
**Pull request by JulianKu**
pip Triangle package (https://pypi.org/project/triangle/)

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
Please follow the pip rules in https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#pip-1 .  In particular, make sure the key is prefixed with `python-` and/or `python3-`.

**Review by clalancette — APPROVED** [review]
Thanks for iterating.

**Review by tfoote — CHANGES_REQUESTED** [review]
This is described as "Python binding to the triangle library". Do we need a dependency on the triangle library?

I see a triangle package already in ubuntu? https://packages.ubuntu.com/xenial/triangle-bin how will this play with that? It looks like this has a copy of that implementation actually inside that, which might lead to masking or otherwise interfering with the native package if installed as well?

**Comment by JulianKu** [comment]
> This is described as "Python binding to the triangle library". Do we need a dependency on the triangle library?

The triangle package offers an easy way to triangulate in Python between a set of vertices that could, for instance, represent a map. Triangulated maps can then be used by Path Planning algorithms, for example. This is why I definitely see a good use for this dependency.

> I see a triangle package already in ubuntu? https://packages.ubuntu.com/xenial/triangle-bin how will this play with that? It looks like this has a copy of that implementation actually inside that, which might lead to masking or otherwise interfering with the native package if installed as well?

From what I saw, the Python package is self-contained (when installed via pip, the package becomes just some Python wrappers + the compiled Cython file).
Having the pip package installed alongside the ubuntu package does not cause any issues on my computer for either of them.

**Comment by JulianKu** [comment]
Are there any updates? Is there something else I can do?

**Comment by sloretz** [comment]
> I see a triangle package already in ubuntu? https://packages.ubuntu.com/xenial/triangle-bin how will this play with that? It looks like this has a copy of that implementation actually inside that, which might lead to masking or otherwise interfering with the native package if installed as well?

It looks like it won't interfere with the debian package so long as it doesn't install a `showme`, `triangle` or `tricall` executable. https://packages.ubuntu.com/xenial/amd64/triangle-bin/filelist . It doesn't look like the pip package installs any executables at all: https://github.com/drufat/triangle/blob/master/setup.py

**Review by sloretz — APPROVED** [review]

**Review by tfoote — APPROVED** [review]
If this won't interfere than we can add it.

**Pull request merged**
