### PR TITLE
Added Gentoo dependencies for kinetic

### PR DESCRIPTION
**Pull request by allenh1**
This adds necessary build dependencies for ROS kinetic on Gentoo.

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm, needs one other maintainer to +1/merge it.

**Comment by allenh1** [comment]
Thank you! By the way, the Gentoo kinetic install is very close. Just have a little bit of Gazebo patching left.

**Comment by tfoote** [comment]
That's great. I look forward to seeing it here: http://wiki.ros.org/kinetic/Installation You could add it even if it's not complete and maybe you could get some help @wjwwood has done that working on osx support.

**Comment by allenh1** [comment]
The site says it's an immutable page... I thought I was white listed? User is HunterAllen.

**Comment by tfoote** [comment]
`Hunter.Allen` was whitelisted. I've fixed it re: https://github.com/ros-infrastructure/roswiki/issues/139

**Comment by allenh1** [comment]
Thanks

**Pull request merged**
