### PR TITLE
 Add a new package, unitree_ros, to rosdep database #39767 

### PR DESCRIPTION
**Pull request by PedroS235**
Please add the following dependency to the rosdep database.

## Package name:

unitree_ros

## Package Upstream Source:

https://github.com/snt-arg/unitree_ros

## Purpose of using this:

This is a ROS package that is used to control the Unitree Go1 robot via ROS topics, as well as receiving data from the robot. This package can be useful for people who want to use the robot without needing to develop a driver/wrapper to use their robot. It can be especially useful for researchers, that want to test their development on the real hardware.

Distro packaging links:

## Links to Distribution Packages

I did not really understand what I should be doing here. Is this required? Sorry for this, it is my first time.

ROSDISTRO NAME: Foxy

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

(PS: Apologies if there is something missing.)

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
- [X] At least one of the following must be present
  - [ ] Top level license file: 
  - [x] Per package license files
- [ ] License is [OSI-approved](https://opensource.org/licenses):
   - not quite, but based on MIT https://github.com/snt-arg/unitree_ros/blob/541727bba5ef0cd78d3a3c05a5ff59d11f0242be/LICENSE#L2
- [X] License correctly listed in package.xmls
- [X] Public source repo:
- [X] Source repository contains ROS packages
- [X] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions

<details><summary>Package name details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<name>" "{}" ";"
  <name>unitree_ros</name>
```
</details>

<details><summary>License details</summary>

```console
$ find . -name "package.xml" -exec grep --color=auto -e "<license[^>]*>" "{}" "+"
  <license>SnT Academic License</license>
```
</details>

**Comment by sloretz** [comment]
@clalancette mind taking a look at the license?

**Comment by clalancette** [comment]
> @clalancette mind taking a look at the license?

Yes, thanks for the ping.

Unfortunately, we cannot take packages that don't use an OSI-approved license.  The basic problem is that we are engineers, not lawyers, and so we cannot determine whether we have the right to distribute the contents.  If you can rework your package to use MIT, BSD, or Apache-2.0 license, then we can consider it.

**Comment by PedroS235** [comment]
Hello both, thank you for reviewing the PR. 

That was already one concern I had. I will try to see if I can change to one of the more common ones.
The main reason why we have that Licence is due to University rules. Nevertheless, I will see if I can change. 

If possible, could this stay on hold until I have permission to update the Licence?

**Comment by clalancette** [comment]
> If possible, could this stay on hold until I have permission to update the Licence?

Yes, that's fine.  I'm going to set this to "Draft" and "changes-requested" until it can be fixed.

**Comment by PedroS235** [comment]
Hello @clalancette 

I have managed to update the license to GPL. The repo is now updated.

**Comment by clalancette** [comment]
https://github.com/snt-arg/unitree_ros/blob/246abc53357ad8965758d2d0c20016f39ac8493a/package.xml#L8 needs to be updated to reflect the new license.

**Comment by PedroS235** [comment]
> https://github.com/snt-arg/unitree_ros/blob/246abc53357ad8965758d2d0c20016f39ac8493a/package.xml#L8 needs to be updated to reflect the new license.

Sorry for that, its fixed now!

**Comment by PedroS235** [comment]
Hey @clalancette,
Is there anything else that I need to do?

**Review by clalancette — APPROVED** [review]
This looks good now.  Both `humble` and `iron` are in sync holds right now, so I'm going to wait to merge it in until they get out of the hold.

**Pull request merged**
