### PR TITLE
Adding ros2_benchmark to index for Humble

### PR DESCRIPTION
**Pull request by jaiveersinghNV**
# Please Add This Package to be indexed in the rosdistro.

Humble

# The source is here:

https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark

# Checks
 - [x] All packages have a declared license in the package.xml
 - [x] This repository has a LICENSE file
 - [x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
New package review:

- [x] At least one of the following must be present
  - [x] Top level license file: https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/blob/main/LICENSE
  - [ ] Per package license files
- [x] License is [OSI-approved](https://opensource.org/licenses): Apache-2.0
- [x] License correctly listed in package.xmls
  - [x] ros2_benchmark: https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/blob/main/ros2_benchmark
/package.xml#L28
  - [x] ros2_benchmark_interfaces: https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/blob/main/ros2_benchmark_interfaces/package.xml#L28
- [x] Public source repo: https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark/tree/main/
- [ ] Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
  - [ ] ros2_benchmark
  - [ ] ros2_benchmark_interfaces

**Comment by jaiveersinghNV** [comment]
> * [ ]  Source repository contains ROS packages and each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions
>   
>   * [ ]  ros2_benchmark
>   * [ ]  ros2_benchmark_interfaces

Hi @nuclearsandwich , is there anything else you need from us to complete this review? We'd like to get this package in for the next Humble sync, if possible. Thanks!

**Comment by nuclearsandwich** [comment]
@jaiveersinghNV these packages don't currently conform to our expected naming requirements as described in [REP-144](https://www.ros.org/reps/rep-0144.html). Specifically

> A package name should not contain ros as it is redundant. Exceptions include core packages and ROS bindings of an upstream library (e.g. moveit_ros)

Additionally, `benchmark` alone is too generic. Updating the package name to increase precision in terms of what kinds of benchmarks can be collected or how would go a long way towards improving the situation here. If absolutely necessary, the package could be named something like `nvidia_graph_benchmark` which would at least namespace it, although descriptive package names are strongly preferred.

**Comment by nuclearsandwich** [comment]
Naming review is currently blocking this package.

Humble is also currently being [held for sync](https://discourse.ros.org/t/preparing-for-humble-sync-2023-05-30/31622) so, once approved, this change cannot be merged until the hold is released.

**Comment by nuclearsandwich** [comment]
> Thank you for your feedback. I appreciate your concerns about the namespacing issue. How about a prefix of `r2b_` (ie, naming the package `r2b_benchmark`)?

I have no objection with `r2b_benchmark`, it seems derived from `ROS 2 benchmark` but such derivations don't conflict with either the Trademark or naming policies to the best of my knowledge. I'd like one of the other reviewers on rosdistro duty this week to 👍🏼 as well before approving (as I do whenever I raise a possible naming conflict).

**Comment by emersonknapp** [comment]
:+1: At least `rb2` kind of sounds like a unique-ish project name. I approve this as a reviewer on duty this week. It does remind me of a past job, we serial-numbered the robots with `rb`, so `rb2` was the second bot built and was a no-so-pretty prototype with panels missing and wires hanging out :grin: - but that's irrelevant to this conversation.

Thanks @jaiveersinghNV for engaging in the conversation about this, we appreciate the effort. Naming is difficult, but I think this is a reasonable compromise.

**Comment by nuclearsandwich** [comment]
@jaiveersinghNV to close this one out could you please update the PR data once the packages have been renamed. If it's easier to open a separate PR you're welcome to do so but please link this one for context.

**Comment by mjcarroll** [comment]
Humble is held for sync https://discourse.ros.org/t/preparing-for-humble-sync-2023-06-29/32110

**Review by audrow — APPROVED** [review]

**Review by audrow — COMMENTED** [review]
On second thought, I'll wait until the suggested naming changes are made.

**Pull request closed without merging**
