### PR TITLE
add qttools5-dev to the rosdistro base.yaml file

### PR DESCRIPTION
**Pull request by SamLyuubc**
Currently for ubuntu 18.04, to use Qt LinguistTools to build catkin package we have dependency of qttools5-dev which is not currently included in the  `rosdep/base.yaml` file. This pull request add qttools5-dev to the file so rosdep can install such package. 

- Ubuntu Package link: https://packages.ubuntu.com/disco/qttools5-dev

- Debian Package link: https://packages.debian.org/buster/qttools5-dev

Could not find an equivalent package in Fedora distro.

### CODE REVIEW

**Review by nuclearsandwich — CHANGES_REQUESTED** [review]
Please address the alphabetical order issue raised on CI (https://travis-ci.org/ros/rosdistro/jobs/572408510#L438) and update the pull request description to include links to the packages in the Ubuntu package index as described in our [contribution guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules).

It would also be a big help if you could add rules for our other supported platforms, at least debian and fedora.

**Comment by SamLyuubc** [comment]
> Please address the alphabetical order issue raised on CI (https://travis-ci.org/ros/rosdistro/jobs/572408510#L438) and update the pull request description to include links to the packages in the Ubuntu package index as described in our [contribution guide](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#guidelines-for-rosdep-rules).
> 
> It would also be a big help if you could add rules for our other supported platforms, at least debian and fedora.

Hey Steven,
I have made the change and squash the commits. The links to debian and ubuntu are updated. However, I could not find one corresponding package for Fedora distro. Let me know if I can help more.

**Review by nuclearsandwich — APPROVED** [review]
Thanks for iterating.

**Comment by nuclearsandwich** [comment]
>  I could not find one corresponding package for Fedora distro. Let me know if I can help more.

There isn't one that's obvious to me either. @cottsay will know better than me but this gets a :heavy_check_mark: from me with or without the Fedora package.

**Review by cottsay — APPROVED** [review]
I added the Fedora package, which is the same that provides for `qttools5-dev-tools`:
https://apps.fedoraproject.org/packages/qt5-qttools-devel

**Pull request merged**
