### PR TITLE
Allow removal of *_python3 keys when EOL

### PR DESCRIPTION
**Pull request by sloretz**
Discussion:

https://github.com/ros/rosdistro/pull/25120#discussion_r432116597
https://github.com/ros/rosdistro/pull/25120#discussion_r441699931
https://github.com/ros/rosdistro/pull/25482#discussion_r441103028

### CODE REVIEW

**Comment by 130s** [comment]
+1 this helps contributors like me, and it aligns with @tfoote's comment https://github.com/ros/rosdistro/pull/25120#discussion_r432116597

**Review by nuclearsandwich — APPROVED** [review]

**Comment by clalancette** [comment]
I'll say that I am all for this, but I have gotten complaints from some users when I've attempted to do this.  Their point being that while the distribution may be EOL, the robot they have may still be running the EOL distribution.

This can clearly get crazy (I don't think we should keep `precise_python3` keys around, for instance), but if we take this stance we'll definitely get some disappointed users.

**Comment by nuclearsandwich** [comment]
>  Their point being that while the distribution may be EOL, the robot they have may still be running the EOL distribution.

There may be situations I'm unfamiliar with, but my first recommendation to anyone having rosdep diffficulties with a platform that is no longer supported would be to use rosdep sources which is frozen in a state which meets their needs.

**Review by tfoote — APPROVED** [review]
Yeah, if we can provide best practices such as leveraging a snapshot/hashed value or tag then we don't need to worry about keeping far backwards compatibility. It might make sense to have an official <distro>-eol tag which demarcates the end of support, and then we'd prune after that.

**Pull request merged**
