### PR TITLE
Add python-geocoder-pip

### PR DESCRIPTION
**Pull request by Timple**

### CODE REVIEW

**Comment by cottsay** [comment]
From the Travis build:
```
ERR: list out of alphabetical order line 1434.  'python-gTTS-pip' should come before 'python-geocoder-pip'
```

**Comment by tfoote** [comment]
Looking at this there's a more popular geocoding python package geopy https://pypi.org/project/geopy/
vs https://pypi.org/project/geocoder/

It's also available as a debian package on [debian](https://packages.debian.org/buster/python-geopy) and [ubuntu](https://packages.ubuntu.com/xenial/python-geopy) which would make this rosdep key much more useful  . (It could be used in binary releases) 

There are definitely differences https://webgeodatavore.com/python-geocoders-clients-comparison.html but the geopy looks to have better coverage on programmatic APIs and platforms supported.

**Comment by tfoote** [comment]
Yeah, the capitals come first in python's alphabetical sort.
`  ERR: list out of alphabetical order line 1453.  'python-gcloud-pip' should come before 'python-geocoder-pip'`
It needs to go down a few more.

In general we prefer to not end up with extra unused entries. They lead to extra maintenance as well as bit rot if no one is actively using them which makes people trying to use new keys experience worse. So if you can use the already packaged one we'd prefer to just add that one.

**Comment by tfoote** [comment]
@Timple any feedback on whether geopy will work? Without more feedback we'll plan to close this due to inactivity soon.

**Comment by Timple** [comment]
I haven't gotten around to implement this. Wasn't a drop-in replacement in the quick investigation I did.

But the provide the same functionality, so I assume it can be done. If you don't like the pip dependency in the rosdep, you are free to close this.

**Comment by tfoote** [comment]
If it's not a drop in replacement we can add this, just know that it won't be releasable.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
