### PR TITLE
magni_robot 0.1.0 kinetic release

### PR DESCRIPTION
**Pull request by jim-v**
Manually releasing magni_robot 0.1.0 (initial release)
Contains:

- magni_bringup
- magni_demos
- magni_description
- magni_nav
- magni_teleop

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
For releases  we recommend using bloom (also applies for first time release, please see [this tutorial](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)).

**Comment by rohbotics** [comment]
Hey @mikaelarguedas, I was working with @jim-v on this one. 

In the process we didn't do the bloom OAuth stuff correctly, so we just manually created a PR based on the patch file that bloom put in /tmp.

Is there a way to run just the PR part of bloom-release? The rest of the process was done with bloom already.

**Comment by mikaelarguedas** [comment]
You can rerun bloom-release with `-p` if you want to only do the PR part.

I wanted to be sure @jim-v knew the tool to ease the release process in the future, and make sure that the absence of source entry was on purpose. No major objection to merge this as is.

**Comment by rohbotics** [comment]
Ok, go for merging as is, we will do it more correctly next time. :smiley:

**Comment by mikaelarguedas** [comment]
Sounds good

**Pull request merged**
