### PR TITLE
cob_simulation: 0.6.8-0 in 'kinetic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by ipa-rmb**
Increasing version of package(s) in repository `cob_simulation` to `0.6.8-0`:

- upstream repository: https://github.com/ipa320/cob_simulation.git
- release repository: https://github.com/ipa320/cob_simulation-release.git
- distro file: `kinetic/distribution.yaml`
- bloom version: `0.5.26`
- previous version for package: `null`

## cob_bringup_sim

```
* refactored the code and added retreating model while on circular motion
* provision for re-spawning the person object to the start, due to presence of obstacle
* use xacro --inorder
* allow single letter option for move_object
* rospy.sleep exception handling
* wait for models and cleanup
* launch argument world_name
* use exported robotlist and envlist
* manually fix changelog
* debug functionality
* continue motion if object is far away enough
* metavars for parser options
* introduce stop_objects list and stop_distance
* remove throttled
* add missing robots to robotlist
* added stopping of objects
* Contributors: fmw-ss, hannes, ipa-fxm
```

## cob_gazebo

```
* remove cob_controller_configuration_gazebo
* use exported robotlist and envlist
* use cob_bringup robot.xml in simulation
* manually fix changelog
* Empty launch file changed and empty urdf created
* wait parameter removed. it was not working when launching a empty world
* Contributors: Bruno Brito, ipa-fxm
```

## cob_gazebo_objects

```
* add station_charger
* correct marker radius
* add reflector_marker_round
* make reflector marker static
* use exported robotlist and envlist
* use latest xacro syntax
* manually fix changelog
* Contributors: ipa-fxm
```

## cob_gazebo_worlds

```
* rename IZS-carpark-top to izs-carpark-top
* add simulation for izs-carpark-top to cob_gazebo_worlds
* remove kitchen unit
* fix ipa-production-plant
* use xacro --inorder
* use xml suffix for non-standalone launch files
* rospy.sleep exception handling
* launch argument world_name
* use exported robotlist and envlist
* use latest xacro syntax
* handle ROSTimeMovedBackwardsException
* manually fix changelog
* add test for empty.urdf.xacro
* remove throttled
* simplify launch files
* conflict between empty launch files and other scenarios solved
* Empty launch file changed and empty urdf created
* Contributors: Bruno Brito, Jannik Abbenseth, ipa-fxm
```

## cob_simulation

```
* manually fix changelog
* Contributors: ipa-fxm
```

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@ipa-rmb this branch has conflicts that need to be resolved

**Comment by ipa-rmb** [comment]
Thanks for notifying - I resolved the conflict. And many thanks for the extremely fast merge responses today!

**Comment by mikaelarguedas** [comment]
You are welcome,
I think that something went wrong in the conflict resolution, `cob_simulation` has been removed instead of `cob_robot` resulting in this PR being empty

**Comment by ipa-rmb** [comment]
Totally right. I missed the addition when merging...

**Comment by mikaelarguedas** [comment]
all good :-1:

**Comment by mikaelarguedas** [comment]
oops sneaky github emoji, I meant :+1: obviously!

**Pull request merged**
