### PR TITLE
Python 3 compatible syntax

### PR DESCRIPTION
**Pull request by dirk-thomas**
Redo of #17110 since the original author closed the PR.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Letting someone else review and merge.

**Review by mikaelarguedas — APPROVED** [review]
lgtm
as the version of unidiff we need to avoid https://github.com/ros/rosdistro/issues/6637 (0.5.1) is way older than the one in pip or the one shipped in ubuntu (0.5.4)

**Comment by dirk-thomas** [comment]
The `unidiff` version should not be relevant anymore since the diff string is being decoded in our code now: https://github.com/ros/rosdistro/pull/18374/files#diff-393d31931da612bbb9e5da3580a789b9R236

**Comment by tfoote** [comment]
The python3 builds are failing new PRs such as:  #18376 #18377  https://travis-ci.org/ros/rosdistro/jobs/400700171

**Pull request merged**
