### PR TITLE
add move_base_sequence to index (noetic)

### PR DESCRIPTION
**Pull request by MarkNaeem**

### CODE REVIEW

**Comment by MarkNaeem** [comment]
I have tried everything and I cannot get anything helpful from the error in 
Validate rosdistro / Nosetests (3.8) (pull_request)

**Comment by tfoote** [comment]
The underlying error is `2021-02-23T20:27:02.5785515Z rosdistro: DEBUG: Skipped "git_manifest_provider()": Unable to fetch package.xml: Could not clone repository "https://github.com/MarkNaeem/move_base_sequence-release.git" at reference "release/noetic/move_base_sequence/0.0.1-2"`

This is erroring because you are trying to release 0.0.1-2 for noetic but you have bloomed 0.0.1-1 for noetic in your release repository: https://github.com/MarkNaeem/move_base_sequence-release/commit/8e25e936fcebba745bc96987527c7375b6607d60

You have 0.0.1-2 in Melodic https://github.com/MarkNaeem/move_base_sequence-release/commit/aaa88ad525ed54900eb890089a09d613202633bf

This is why it's highly recommended to setup bloom to make the pull requests for you instead of doing it manually.

**Comment by MarkNaeem** [comment]
Thanks. used Bloom and opened another pull request.

**Comment by tfoote** [comment]
note that if you've already run boom successfully but haven't opened the pr it has a `--pull-request-only` option to avoid rerunning the release.

**Pull request closed without merging**
