### PR TITLE
Added novatel_oem7_driver to noetic.

### PR DESCRIPTION
**Pull request by novatel-applications-engineering**

### CODE REVIEW

**Review by hidmic — CHANGES_REQUESTED** [review]
@novatel-applications-engineering did you `bloom-release` this package? It's a missing a release repository. It also differs from other releases of this repository to older distributions.

**Comment by hidmic** [comment]
@novatel-applications-engineering friendly ping

**Comment by novatel-applications-engineering** [comment]
We did not bloom-release this package to 'noetic' yet.  
Just adding a package to rosdistro per http://wiki.ros.org/ROS/ReleasingAPackage, so that we can run the 'pre-release' tests.

**Review by hidmic — APPROVED** [review]
I see. Thanks for the clarification.

**Pull request merged**
