### PR TITLE
Add graph_wrapper to rosdistro

### PR DESCRIPTION
**Pull request by hridaybavle**
## Package names:

  * [graph_wrapper](https://github.com/snt-arg/graph_wrapper.git)
  
## Package Upstream Source:

https://github.com/snt-arg/graph_wrapper.git

## Purpose of using this:

Graph wrapper for Networkx library as a tool for [lidar_s_graphs](https://github.com/snt-arg/s_graphs_msgs.git).

PR related to `lidar_s_graphs` ---> https://github.com/ros/rosdistro/pull/40800

# Please Add This Package to be indexed in the rosdistro.

Iron and Humble

# The source is here:

https://github.com/snt-arg/graph_wrapper.git

# Checks
 - [ x] All packages have a declared license in the package.xml
 - [ x] This repository has a LICENSE file
 - [ x] This package is expected to build on the submitted rosdistro

### CODE REVIEW

**Comment by clalancette** [comment]
### New package review checklist

- [x] At least one of the following must be present
  - [x] Top level license file:
  - [ ] Per package license files:
- [x] License is [OSI-approved](https://opensource.org/licenses): GPLv3
- [x] License correctly listed in package.xmls
- [x] Public source repo: https://github.com/snt-arg/graph_wrapper
- [x] Source repository contains ROS packages
- [ ] Each package meets [REP-144](https://www.ros.org/reps/rep-0144.html) naming conventions - Unfortunately, `graph_wrapper` is far too generic.  It doesn't really describe what it does, and it could mean many things.  I'm going to suggest you rename this package to something like `situational_graph_wrapper` or `snt_situational_graph_wrapper`, which will make it much clearer.

Besides the above, the sources seem to be missing a `setup.cfg` file (which will be required to make this package work), and the setup.py has a bunch of TODO comments in it.

**Comment by clalancette** [comment]
> @clalancette I am looking into the renaming of the repos with my team and will come back with the relevant changes soon.

Thank you!

**Review by clalancette — APPROVED** [review]
This now looks good, though I suggest that you update https://github.com/snt-arg/situational_graphs_wrapper/blob/develop/setup.py to have a maintainer and license.

**Comment by hridaybavle** [comment]
Rebased with master :)

**Comment by clalancette** [comment]
And this one needs to be rebased as well.

**Comment by hridaybavle** [comment]
@clalancette done!

**Comment by sloretz** [comment]
[Holding for Humble sync](https://discourse.ros.org/t/preparing-for-humble-sync-2024-06-07/38086)

**Pull request merged**
