### PR TITLE
Add python3-usb rosdep entry

### PR DESCRIPTION
**Pull request by jonbinney**
Needed to release fadecandy_ros onto neotic: https://github.com/ros/rosdistro/pull/25171

### CODE REVIEW

**Comment by clalancette** [comment]
Can you please provide links to the package databases?  Also, is this package available in Fedora or Gentoo?

**Comment by jonbinney** [comment]
@clalancette It's in ubuntu universe for bionic: https://packages.ubuntu.com/bionic/python3-usb and focal: https://packages.ubuntu.com/focal/python3-usb

Here's the package on debian buster: https://packages.debian.org/buster/python3-usb

I don't know how it is packaged for gentoo or fedora. Currently they package names for python-usb for those distros in rosdep are "pyusb" and "dev-python/pyusb". I could try to extrapolate but i have no experience with fedora or gentoo package systems; they may be handling python3 packages differently than ubuntu/debian. So I left those fields blank - someone with fedora/gentoo experience could fill them in later.

**Comment by jonbinney** [comment]
@clalancette are the gentoo and fedora keys required before merging this?

**Review by tfoote — APPROVED** [review]
Fedora and Gentoo are not required but we try to fill them in if it's obvious.


@cottsay @allenh1  FYI

**Comment by allenh1** [comment]
@tfoote the Gentoo package is `dev-python/pyusb`.

@jonbinney I would be very grateful if you would add the key!

**Comment by jonbinney** [comment]
@allenh1 "dev-python/pyusb" is the python2 version of the library, right? Does gentoo use the same names for python2 and python3 versions?

**Comment by allenh1** [comment]
Yes, same name for both.

**Comment by jonbinney** [comment]
Thanks @allenh1 ; I've added the entry for gentoo.

**Review by tfoote — APPROVED** [review]

**Review by clalancette — APPROVED** [review]

**Pull request merged**
