### PR TITLE
ublox_dgnss: 0.2.0-1 in 'galactic/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by hortovanyi**
Increasing version of package(s) in repository `ublox_dgnss` to `0.2.0-1`:

- upstream repository: https://github.com/aussierobots/ublox_dgnss
- release repository: https://github.com/aussierobots/ublox_dgnss-release.git
- distro file: `galactic/distribution.yaml`
- bloom version: `0.10.7`
- previous version for package: `null`

### CODE REVIEW

**Comment by ahcorde** [comment]
there is another PR for this same package and distribution. can we colse this one https://github.com/ros/rosdistro/pull/30151 ?

**Comment by hortovanyi** [comment]
Yes - had to re-bloom

**Review by sloretz — APPROVED** [review]

**Comment by hortovanyi** [comment]
getting build failed in Jenkins emails. Not sure what the problem is or what I'm supposed to do? first time publishing a package

**Comment by sloretz** [comment]
@hortovanyi I replied at https://github.com/aussierobots/ublox_dgnss/issues/1

**Pull request merged**
