### PR TITLE
Adding multipoint_navigation_receiver to documentation index for distro

### PR DESCRIPTION
**Pull request by SuperAruba**
One  multipoint navigation receiver for  move_base

### CODE REVIEW

**Comment by SuperAruba** [comment]
I also have a multipoint navigation sender based on Unity

**Comment by SuperAruba** [comment]
I don't know why it failed.I study commit on 2.1 at http://wiki.ros.org/ja/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation.

**Comment by nuclearsandwich** [comment]
@SuperAruba your package currently lacks a license. It would probably be a good idea to set one before adding it to the ROS distribution.

**Comment by SuperAruba** [comment]
Oh,my bad.Thank you



---Original---

**Comment by SuperAruba** [comment]
Now,I have added a license,Thank you!



---Original---

**Comment by clalancette** [comment]
> Now,I have added a license,Thank you!

Please also add the license to the [package.xml](https://github.com/SuperAruba/multipoint_navigation_receiver/blob/master/package.xml#L16).  While you are modifying it, I'll also suggest putting a maintainer name and email address.

**Comment by SuperAruba** [comment]
Now,I have commited wiki page at "package.xml"

**Comment by SuperAruba** [comment]
@clalancette 
Hi,I want to know when my package will appear in ROS list

**Comment by SuperAruba** [comment]
@clalancette 
Hi,I want know How to write Package Summary section in ros.wiki.org.

**Comment by SuperAruba** [comment]
@clalancette 
Why my package not in rospackage list?

**Comment by SuperAruba** [comment]
And how to appear Package Links

**Comment by clalancette** [comment]
> Why my package not in rospackage list?

It takes time to do (usually overnight after the PR is merged).  At the moment the buildfarm is actually really busy, so it may take a couple of days to show up.

As for the rest of your questions, please consider searching https://wiki.ros.org and https://answers.ros.org.  If you can't find the answers there, please post questions to https://answers.ros.org.  That way it is searchable and people can find it in the future.

**Comment by SuperAruba** [comment]
Thank you very much



---Original---

**Pull request merged**
