### PR TITLE
add python3-selenium key

### PR DESCRIPTION
**Pull request by knorth55**
debian: https://packages.debian.org/buster/python3-selenium
fedora: https://src.fedoraproject.org/rpms/python-selenium
ubuntu: https://packages.ubuntu.com/bionic/python3-selenium

### CODE REVIEW

**Comment by knorth55** [comment]
Can anyone please review this PR?

**Review by mjcarroll — COMMENTED** [review]
Can you go ahead and add keys for:

* Gentoo: https://packages.gentoo.org/packages/dev-python/selenium
* Arch: `python-selenium`

Is this also available via pip for MacOS?

**Comment by knorth55** [comment]
Thanks, I update to add arch, gentoo and osx keys.

**Review by tfoote — APPROVED** [review]

**Comment by knorth55** [comment]
Kindly ping...

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
